!MNH_LIC Copyright 1995-2023 CNRS, Meteo-France and Universite Paul Sabatier
!MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
!MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt
!MNH_LIC for details. version 1.
!-----------------------------------------------------------------
! Modifications:
!  P. Wautelet 14/04/2023: initialize ZZ_LSFACT and ZZ_LVFACT
!-----------------------------------------------------------------
MODULE MODE_ICE4_BUDGETS
IMPLICIT NONE
CONTAINS
SUBROUTINE ICE4_BUDGETS(D, PARAMI, BUCONF, KRR, &
                        PLVFACT, PLSFACT, PRHODJ, PEXNREF, &
                        PRVHENI, PBUDGETS, &
                        TBUDGETS, KBUDGETS)
!
!*       0.    DECLARATIONS
!              ------------
!
USE YOMHOOK , ONLY : LHOOK, DR_HOOK, JPHOOK

USE MODD_DIMPHYEX,   ONLY: DIMPHYEX_t
USE MODD_BUDGET,     ONLY: TBUDGETDATA_PTR, TBUDGETCONF_t, NBUDGET_TH, NBUDGET_RV, NBUDGET_RC, &
                           NBUDGET_RI, NBUDGET_RR, NBUDGET_RS, NBUDGET_RG, NBUDGET_RH
USE MODD_PARAM_ICE_n,  ONLY: PARAM_ICE_t
!
USE MODD_FIELDS_ADDRESS, ONLY: IBUNUM, IBUNUM_EXTRA, IRCACCR, IRCAUTR, IRCBERI, IRCDRYG, IRCDRYH, &
                               IRCHONI, IRCMLTSR, IRCRIMSG, IRCRIMSS, IRCWETG, IRCWETH, IRDRYHG, &
                               IRGDRYH, IRGMLTR, IRGWETH, IRHMLTR, IRIAGGS, IRIAUTS, IRICFRR, &
                               IRICFRRG, IRIDRYG, IRIDRYH, IRIMLTC_MR, IRIWETG, IRIWETH, &
                               IRRACCSG, IRRACCSS, IRRCFRIG, IRRDRYG, IRRDRYH, IRREVAV, IRRHONG_MR, &
                               IRRWETG, IRRWETH, IRSACCRG, IRSDRYG, IRSDRYH, IRSMLTG, IRSRIMCG, &
                               IRSWETG, IRSWETH, IRVDEPG, IRVDEPS, IRVHENI_MR, IRWETGH
! index number for prognostic (theta and mixing ratios) and budgets
!
!
IMPLICIT NONE
!
!*       0.1   Declarations of dummy arguments :
!
!
!
TYPE(DIMPHYEX_t),                            INTENT(IN)    :: D
TYPE(PARAM_ICE_t),                           INTENT(IN)    :: PARAMI
TYPE(TBUDGETCONF_t),                         INTENT(IN)    :: BUCONF
INTEGER,                                     INTENT(IN)    :: KRR
REAL, DIMENSION(D%NIJT, D%NKT),              INTENT(IN)    :: PLVFACT
REAL, DIMENSION(D%NIJT, D%NKT),              INTENT(IN)    :: PLSFACT
REAL, DIMENSION(D%NIJT, D%NKT),              INTENT(IN)    :: PRHODJ
REAL, DIMENSION(D%NIJT, D%NKT),              INTENT(IN)    :: PEXNREF
REAL, DIMENSION(D%NIJT, D%NKT),              INTENT(IN)    :: PRVHENI
REAL, DIMENSION(D%NIJT, D%NKT, IBUNUM-IBUNUM_EXTRA), INTENT(IN)    :: PBUDGETS
TYPE(TBUDGETDATA_PTR), DIMENSION(KBUDGETS),      INTENT(INOUT) :: TBUDGETS
INTEGER,                                     INTENT(IN)    :: KBUDGETS
!
!
!*       0.2   Declarations of local variables :
!
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
!
INTEGER :: JIJ, JK
INTEGER :: IKTB, IKTE, IKB, IIJB, IIJE
REAL,    DIMENSION(D%NIJT, D%NKT) :: ZW1 ! work array
REAL, DIMENSION(D%NIJT, D%NKT) :: ZZ_DIFF, ZZ_LVFACT, ZZ_LSFACT
REAL, DIMENSION(D%NIJT, D%NKT) :: ZWKBUD
!
!-------------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('ICE4_BUDGETS', 0, ZHOOK_HANDLE)
!
IKTB=D%NKTB
IKTE=D%NKTE
IKB=D%NKB
IIJB=D%NIJB
IIJE=D%NIJE
!
IF (BUCONF%LBUDGET_TH) THEN
  ZZ_DIFF(:,:)   = 0.
  ZZ_LSFACT(:,:) = 0.
  ZZ_LVFACT(:,:) = 0.
  DO JK = IKTB, IKTE
    DO JIJ = IIJB, IIJE
      ZZ_LVFACT(JIJ, JK) = PLVFACT(JIJ, JK) / PEXNREF(JIJ, JK)
      ZZ_LSFACT(JIJ, JK) = PLSFACT(JIJ, JK) / PEXNREF(JIJ, JK)
      ZZ_DIFF(JIJ, JK) = ZZ_LSFACT(JIJ, JK) - ZZ_LVFACT(JIJ, JK)
    ENDDO
  ENDDO
END IF

ZW1(:,:) = 0.
DO JK = IKTB, IKTE
  DO JIJ = IIJB, IIJE
    ZW1(JIJ, JK) = PBUDGETS(JIJ, JK, IRVHENI_MR) + PRVHENI(JIJ, JK)
  ENDDO
ENDDO
IF (BUCONF%LBUDGET_TH) ZWKBUD(:,:) = ZW1(:, :)*ZZ_LSFACT(:, :)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_TH) CALL TBUDGETS(NBUDGET_TH)%PTR%ADD_PHY(D, 'HIN',  ZWKBUD)
IF (BUCONF%LBUDGET_RV) ZWKBUD(:,:) = -ZW1(:, :)                *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RV) CALL TBUDGETS(NBUDGET_RV)%PTR%ADD_PHY(D, 'HIN',  ZWKBUD)
IF (BUCONF%LBUDGET_RI) ZWKBUD(:,:) = ZW1(:, :)                *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RI) CALL TBUDGETS(NBUDGET_RI)%PTR%ADD_PHY(D, 'HIN',  ZWKBUD)

IF (BUCONF%LBUDGET_TH) ZWKBUD(:,:) = PBUDGETS(:, :, IRCHONI)*ZZ_DIFF(:, :)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_TH) CALL TBUDGETS(NBUDGET_TH)%PTR%ADD_PHY(D, 'HON',  ZWKBUD)
IF (BUCONF%LBUDGET_RC) ZWKBUD(:,:) = -PBUDGETS(:, :, IRCHONI)              *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RC) CALL TBUDGETS(NBUDGET_RC)%PTR%ADD_PHY(D, 'HON',  ZWKBUD)
IF (BUCONF%LBUDGET_RI) ZWKBUD(:,:) = PBUDGETS(:, :, IRCHONI)              *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RI) CALL TBUDGETS(NBUDGET_RI)%PTR%ADD_PHY(D, 'HON',  ZWKBUD)

IF (BUCONF%LBUDGET_TH) ZWKBUD(:,:) = PBUDGETS(:, :, IRRHONG_MR)*ZZ_DIFF(:, :)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_TH) CALL TBUDGETS(NBUDGET_TH)%PTR%ADD_PHY(D, 'SFR',  ZWKBUD)
IF (BUCONF%LBUDGET_RR) ZWKBUD(:,:) = -PBUDGETS(:, :, IRRHONG_MR)              *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RR) CALL TBUDGETS(NBUDGET_RR)%PTR%ADD_PHY(D, 'SFR',  ZWKBUD)
IF (BUCONF%LBUDGET_RG) ZWKBUD(:,:) = PBUDGETS(:, :, IRRHONG_MR)              *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RG) CALL TBUDGETS(NBUDGET_RG)%PTR%ADD_PHY(D, 'SFR',  ZWKBUD)

IF (BUCONF%LBUDGET_TH) ZWKBUD(:,:) = PBUDGETS(:, :, IRVDEPS)*ZZ_LSFACT(:, :)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_TH) CALL TBUDGETS(NBUDGET_TH)%PTR%ADD_PHY(D, 'DEPS',  ZWKBUD)
IF (BUCONF%LBUDGET_RV) ZWKBUD(:,:) = -PBUDGETS(:, :, IRVDEPS)                *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RV) CALL TBUDGETS(NBUDGET_RV)%PTR%ADD_PHY(D, 'DEPS',  ZWKBUD)
IF (BUCONF%LBUDGET_RS) ZWKBUD(:,:) = PBUDGETS(:, :, IRVDEPS)                *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RS) CALL TBUDGETS(NBUDGET_RS)%PTR%ADD_PHY(D, 'DEPS',  ZWKBUD)

IF (BUCONF%LBUDGET_RI) ZWKBUD(:,:) = -PBUDGETS(:, :, IRIAGGS)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RI) CALL TBUDGETS(NBUDGET_RI)%PTR%ADD_PHY(D, 'AGGS',  ZWKBUD)
IF (BUCONF%LBUDGET_RS) ZWKBUD(:,:) = PBUDGETS(:, :, IRIAGGS)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RS) CALL TBUDGETS(NBUDGET_RS)%PTR%ADD_PHY(D, 'AGGS',  ZWKBUD)

IF (BUCONF%LBUDGET_RI) ZWKBUD(:,:) = -PBUDGETS(:, :, IRIAUTS)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RI) CALL TBUDGETS(NBUDGET_RI)%PTR%ADD_PHY(D, 'AUTS',  ZWKBUD)
IF (BUCONF%LBUDGET_RS) ZWKBUD(:,:) = PBUDGETS(:, :, IRIAUTS)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RS) CALL TBUDGETS(NBUDGET_RS)%PTR%ADD_PHY(D, 'AUTS',  ZWKBUD)

IF (BUCONF%LBUDGET_TH) ZWKBUD(:,:) = PBUDGETS(:, :, IRVDEPG)*ZZ_LSFACT(:, :)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_TH) CALL TBUDGETS(NBUDGET_TH)%PTR%ADD_PHY(D, 'DEPG',  ZWKBUD)
IF (BUCONF%LBUDGET_RV) ZWKBUD(:,:) = -PBUDGETS(:, :, IRVDEPG)                *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RV) CALL TBUDGETS(NBUDGET_RV)%PTR%ADD_PHY(D, 'DEPG',  ZWKBUD)
IF (BUCONF%LBUDGET_RG) ZWKBUD(:,:) = PBUDGETS(:, :, IRVDEPG)                *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RG) CALL TBUDGETS(NBUDGET_RG)%PTR%ADD_PHY(D, 'DEPG',  ZWKBUD)

IF(PARAMI%LWARM) THEN
  IF (BUCONF%LBUDGET_RC) ZWKBUD(:,:) = -PBUDGETS(:, :, IRCAUTR)*PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RC) CALL TBUDGETS(NBUDGET_RC)%PTR%ADD_PHY(D, 'AUTO',  ZWKBUD)
  IF (BUCONF%LBUDGET_RR) ZWKBUD(:,:) = PBUDGETS(:, :, IRCAUTR)*PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RR) CALL TBUDGETS(NBUDGET_RR)%PTR%ADD_PHY(D, 'AUTO',  ZWKBUD)

  IF (BUCONF%LBUDGET_RC) ZWKBUD(:,:) = -PBUDGETS(:, :, IRCACCR)*PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RC) CALL TBUDGETS(NBUDGET_RC)%PTR%ADD_PHY(D, 'ACCR',  ZWKBUD)
  IF (BUCONF%LBUDGET_RR) ZWKBUD(:,:) = PBUDGETS(:, :, IRCACCR)*PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RR) CALL TBUDGETS(NBUDGET_RR)%PTR%ADD_PHY(D, 'ACCR',  ZWKBUD)

  IF (BUCONF%LBUDGET_TH) ZWKBUD(:,:) = -PBUDGETS(:, :, IRREVAV)*ZZ_LVFACT(:, :)*PRHODJ(:, :)
  IF (BUCONF%LBUDGET_TH) CALL TBUDGETS(NBUDGET_TH)%PTR%ADD_PHY(D, 'REVA',  ZWKBUD)
  IF (BUCONF%LBUDGET_RV) ZWKBUD(:,:) = PBUDGETS(:, :, IRREVAV)                *PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RV) CALL TBUDGETS(NBUDGET_RV)%PTR%ADD_PHY(D, 'REVA',  ZWKBUD)
  IF (BUCONF%LBUDGET_RR) ZWKBUD(:,:) = -PBUDGETS(:, :, IRREVAV)                *PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RR) CALL TBUDGETS(NBUDGET_RR)%PTR%ADD_PHY(D, 'REVA',  ZWKBUD)
ENDIF

IF (BUCONF%LBUDGET_TH) ZWKBUD(:,:) = (PBUDGETS(:, :, IRCRIMSS)+PBUDGETS(:, :, IRCRIMSG))*ZZ_DIFF(:, :)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_TH) CALL TBUDGETS(NBUDGET_TH)%PTR%ADD_PHY(D, 'RIM',  ZWKBUD)
IF (BUCONF%LBUDGET_RC) ZWKBUD(:,:) = (-PBUDGETS(:, :, IRCRIMSS)-PBUDGETS(:, :, IRCRIMSG))*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RC) CALL TBUDGETS(NBUDGET_RC)%PTR%ADD_PHY(D, 'RIM',  ZWKBUD)
IF (BUCONF%LBUDGET_RS) ZWKBUD(:,:) = (PBUDGETS(:, :, IRCRIMSS)-PBUDGETS(:, :, IRCRIMSG))*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RS) CALL TBUDGETS(NBUDGET_RS)%PTR%ADD_PHY(D, 'RIM',  ZWKBUD)
IF (BUCONF%LBUDGET_RG) ZWKBUD(:,:) = (PBUDGETS(:, :, IRCRIMSG)+PBUDGETS(:, :, IRSRIMCG))*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RG) CALL TBUDGETS(NBUDGET_RG)%PTR%ADD_PHY(D, 'RIM',  ZWKBUD)

IF (BUCONF%LBUDGET_TH) ZWKBUD(:,:) = (PBUDGETS(:, :, IRRACCSS)+PBUDGETS(:, :, IRRACCSG))*ZZ_DIFF(:, :)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_TH) CALL TBUDGETS(NBUDGET_TH)%PTR%ADD_PHY(D, 'ACC',  ZWKBUD)
IF (BUCONF%LBUDGET_RR) ZWKBUD(:,:) = (-PBUDGETS(:, :, IRRACCSS)-PBUDGETS(:, :, IRRACCSG))*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RR) CALL TBUDGETS(NBUDGET_RR)%PTR%ADD_PHY(D, 'ACC',  ZWKBUD)
IF (BUCONF%LBUDGET_RS) ZWKBUD(:,:) = (PBUDGETS(:, :, IRRACCSS)-PBUDGETS(:, :, IRSACCRG))*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RS) CALL TBUDGETS(NBUDGET_RS)%PTR%ADD_PHY(D, 'ACC',  ZWKBUD)
IF (BUCONF%LBUDGET_RG) ZWKBUD(:,:) = (PBUDGETS(:, :, IRRACCSG)+PBUDGETS(:, :, IRSACCRG))*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RG) CALL TBUDGETS(NBUDGET_RG)%PTR%ADD_PHY(D, 'ACC',  ZWKBUD)

IF (BUCONF%LBUDGET_RS) ZWKBUD(:,:) = -PBUDGETS(:, :, IRSMLTG)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RS) CALL TBUDGETS(NBUDGET_RS)%PTR%ADD_PHY(D, 'CMEL',  ZWKBUD)
IF (BUCONF%LBUDGET_RG) ZWKBUD(:,:) = PBUDGETS(:, :, IRSMLTG)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RG) CALL TBUDGETS(NBUDGET_RG)%PTR%ADD_PHY(D, 'CMEL',  ZWKBUD)

IF (BUCONF%LBUDGET_RC) ZWKBUD(:,:) = -PBUDGETS(:, :, IRCMLTSR)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RC) CALL TBUDGETS(NBUDGET_RC)%PTR%ADD_PHY(D, 'CMEL',  ZWKBUD)
IF (BUCONF%LBUDGET_RR) ZWKBUD(:,:) = PBUDGETS(:, :, IRCMLTSR)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RR) CALL TBUDGETS(NBUDGET_RR)%PTR%ADD_PHY(D, 'CMEL',  ZWKBUD)

IF (BUCONF%LBUDGET_TH) ZWKBUD(:,:) = PBUDGETS(:, :, IRRCFRIG)*ZZ_DIFF(:, :)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_TH) CALL TBUDGETS(NBUDGET_TH)%PTR%ADD_PHY(D, 'CFRZ',  ZWKBUD)
IF (BUCONF%LBUDGET_RR) ZWKBUD(:,:) = (-PBUDGETS(:, :, IRRCFRIG)+PBUDGETS(:, :, IRICFRR))*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RR) CALL TBUDGETS(NBUDGET_RR)%PTR%ADD_PHY(D, 'CFRZ',  ZWKBUD)
IF (BUCONF%LBUDGET_RI) ZWKBUD(:,:) = (-PBUDGETS(:, :, IRICFRRG)-PBUDGETS(:, :, IRICFRR))*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RI) CALL TBUDGETS(NBUDGET_RI)%PTR%ADD_PHY(D, 'CFRZ',  ZWKBUD)
IF (BUCONF%LBUDGET_RG) ZWKBUD(:,:) = (PBUDGETS(:, :, IRICFRRG)+PBUDGETS(:, :, IRRCFRIG))*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RG) CALL TBUDGETS(NBUDGET_RG)%PTR%ADD_PHY(D, 'CFRZ',  ZWKBUD)

IF (BUCONF%LBUDGET_TH) ZWKBUD(:,:) = (PBUDGETS(:, :, IRCWETG)+PBUDGETS(:, :, IRRWETG))*ZZ_DIFF(:, :)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_TH) CALL TBUDGETS(NBUDGET_TH)%PTR%ADD_PHY(D, 'WETG',  ZWKBUD)
IF (BUCONF%LBUDGET_RC) ZWKBUD(:,:) = -PBUDGETS(:, :, IRCWETG)    *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RC) CALL TBUDGETS(NBUDGET_RC)%PTR%ADD_PHY(D, 'WETG',  ZWKBUD)
IF (BUCONF%LBUDGET_RR) ZWKBUD(:,:) = -PBUDGETS(:, :, IRRWETG)    *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RR) CALL TBUDGETS(NBUDGET_RR)%PTR%ADD_PHY(D, 'WETG',  ZWKBUD)
IF (BUCONF%LBUDGET_RI) ZWKBUD(:,:) = -PBUDGETS(:, :, IRIWETG)    *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RI) CALL TBUDGETS(NBUDGET_RI)%PTR%ADD_PHY(D, 'WETG',  ZWKBUD)
IF (BUCONF%LBUDGET_RS) ZWKBUD(:,:) = -PBUDGETS(:, :, IRSWETG)    *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RS) CALL TBUDGETS(NBUDGET_RS)%PTR%ADD_PHY(D, 'WETG',  ZWKBUD)
IF (BUCONF%LBUDGET_RG) ZWKBUD(:,:) = (PBUDGETS(:, :, IRCWETG)+PBUDGETS(:, :, IRRWETG)+&
                                                 &PBUDGETS(:, :, IRIWETG)+PBUDGETS(:, :, IRSWETG))*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RG) CALL TBUDGETS(NBUDGET_RG)%PTR%ADD_PHY(D, 'WETG',  ZWKBUD)

IF(KRR==7) THEN
  IF (BUCONF%LBUDGET_RG) ZWKBUD(:,:) = -PBUDGETS(:, :, IRWETGH)*PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RG) CALL TBUDGETS(NBUDGET_RG)%PTR%ADD_PHY(D, 'GHCV',  ZWKBUD)
  IF (BUCONF%LBUDGET_RH) ZWKBUD(:,:) = PBUDGETS(:, :, IRWETGH)*PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RH) CALL TBUDGETS(NBUDGET_RH)%PTR%ADD_PHY(D, 'GHCV',  ZWKBUD)
END IF

IF (BUCONF%LBUDGET_TH) ZWKBUD(:,:) = (PBUDGETS(:, :, IRCDRYG)+PBUDGETS(:, :, IRRDRYG) )*ZZ_DIFF(:, :)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_TH) CALL TBUDGETS(NBUDGET_TH)%PTR%ADD_PHY(D, 'DRYG',  ZWKBUD)
IF (BUCONF%LBUDGET_RC) ZWKBUD(:,:) = -PBUDGETS(:, :, IRCDRYG)     *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RC) CALL TBUDGETS(NBUDGET_RC)%PTR%ADD_PHY(D, 'DRYG',  ZWKBUD)
IF (BUCONF%LBUDGET_RR) ZWKBUD(:,:) = -PBUDGETS(:, :, IRRDRYG)     *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RR) CALL TBUDGETS(NBUDGET_RR)%PTR%ADD_PHY(D, 'DRYG',  ZWKBUD)
IF (BUCONF%LBUDGET_RI) ZWKBUD(:,:) = -PBUDGETS(:, :, IRIDRYG)     *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RI) CALL TBUDGETS(NBUDGET_RI)%PTR%ADD_PHY(D, 'DRYG',  ZWKBUD)
IF (BUCONF%LBUDGET_RS) ZWKBUD(:,:) = -PBUDGETS(:, :, IRSDRYG)     *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RS) CALL TBUDGETS(NBUDGET_RS)%PTR%ADD_PHY(D, 'DRYG',  ZWKBUD)
IF (BUCONF%LBUDGET_RG) ZWKBUD(:,:) = (PBUDGETS(:, :, IRCDRYG)+PBUDGETS(:, :, IRRDRYG)+&
                                                 &PBUDGETS(:, :, IRIDRYG)+PBUDGETS(:, :, IRSDRYG))*PRHODJ(:, :)
IF (BUCONF%LBUDGET_RG) CALL TBUDGETS(NBUDGET_RG)%PTR%ADD_PHY(D, 'DRYG',  ZWKBUD)

IF (BUCONF%LBUDGET_TH) ZWKBUD(:,:) = -PBUDGETS(:, :, IRGMLTR)*ZZ_DIFF(:, :)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_TH) CALL TBUDGETS(NBUDGET_TH)%PTR%ADD_PHY(D, 'GMLT',  ZWKBUD)
IF (BUCONF%LBUDGET_RR) ZWKBUD(:,:) = PBUDGETS(:, :, IRGMLTR)              *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RR) CALL TBUDGETS(NBUDGET_RR)%PTR%ADD_PHY(D, 'GMLT',  ZWKBUD)
IF (BUCONF%LBUDGET_RG) ZWKBUD(:,:) = -PBUDGETS(:, :, IRGMLTR)              *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RG) CALL TBUDGETS(NBUDGET_RG)%PTR%ADD_PHY(D, 'GMLT',  ZWKBUD)

IF(KRR==7) THEN
  IF (BUCONF%LBUDGET_TH) ZWKBUD(:,:) = (PBUDGETS(:, :, IRCWETH)+PBUDGETS(:, :, IRRWETH))*ZZ_DIFF(:, :)*PRHODJ(:, :)
  IF (BUCONF%LBUDGET_TH) CALL TBUDGETS(NBUDGET_TH)%PTR%ADD_PHY(D, 'WETH',  ZWKBUD)
  IF (BUCONF%LBUDGET_RC) ZWKBUD(:,:) = -PBUDGETS(:, :, IRCWETH)    *PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RC) CALL TBUDGETS(NBUDGET_RC)%PTR%ADD_PHY(D, 'WETH',  ZWKBUD)
  IF (BUCONF%LBUDGET_RR) ZWKBUD(:,:) = -PBUDGETS(:, :, IRRWETH)    *PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RR) CALL TBUDGETS(NBUDGET_RR)%PTR%ADD_PHY(D, 'WETH',  ZWKBUD)
  IF (BUCONF%LBUDGET_RI) ZWKBUD(:,:) = -PBUDGETS(:, :, IRIWETH)    *PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RI) CALL TBUDGETS(NBUDGET_RI)%PTR%ADD_PHY(D, 'WETH',  ZWKBUD)
  IF (BUCONF%LBUDGET_RS) ZWKBUD(:,:) = -PBUDGETS(:, :, IRSWETH)    *PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RS) CALL TBUDGETS(NBUDGET_RS)%PTR%ADD_PHY(D, 'WETH',  ZWKBUD)
  IF (BUCONF%LBUDGET_RG) ZWKBUD(:,:) = -PBUDGETS(:, :, IRGWETH)    *PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RG) CALL TBUDGETS(NBUDGET_RG)%PTR%ADD_PHY(D, 'WETH',  ZWKBUD)
  IF (BUCONF%LBUDGET_RH) ZWKBUD(:,:) = (PBUDGETS(:, :, IRCWETH)+PBUDGETS(:, :, IRRWETH)+PBUDGETS(:, :, IRIWETH)+ &
                                                   &PBUDGETS(:, :, IRSWETH)+PBUDGETS(:, :, IRGWETH))*PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RH) CALL TBUDGETS(NBUDGET_RH)%PTR%ADD_PHY(D, 'WETH',  ZWKBUD)

  IF (BUCONF%LBUDGET_TH) ZWKBUD(:,:) = (PBUDGETS(:, :, IRCDRYH)+PBUDGETS(:, :, IRRDRYH))*ZZ_DIFF(:, :)*PRHODJ(:, :)
  IF (BUCONF%LBUDGET_TH) CALL TBUDGETS(NBUDGET_TH)%PTR%ADD_PHY(D, 'DRYH',  ZWKBUD)
  IF (BUCONF%LBUDGET_RC) ZWKBUD(:,:) = -PBUDGETS(:, :, IRCDRYH) *PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RC) CALL TBUDGETS(NBUDGET_RC)%PTR%ADD_PHY(D, 'DRYH',  ZWKBUD)
  IF (BUCONF%LBUDGET_RR) ZWKBUD(:,:) = -PBUDGETS(:, :, IRRDRYH) *PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RR) CALL TBUDGETS(NBUDGET_RR)%PTR%ADD_PHY(D, 'DRYH',  ZWKBUD)
  IF (BUCONF%LBUDGET_RI) ZWKBUD(:,:) = -PBUDGETS(:, :, IRIDRYH) *PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RI) CALL TBUDGETS(NBUDGET_RI)%PTR%ADD_PHY(D, 'DRYH',  ZWKBUD)
  IF (BUCONF%LBUDGET_RS) ZWKBUD(:,:) = -PBUDGETS(:, :, IRSDRYH) *PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RS) CALL TBUDGETS(NBUDGET_RS)%PTR%ADD_PHY(D, 'DRYH',  ZWKBUD)
  IF (BUCONF%LBUDGET_RG) ZWKBUD(:,:) = -PBUDGETS(:, :, IRGDRYH) *PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RG) CALL TBUDGETS(NBUDGET_RG)%PTR%ADD_PHY(D, 'DRYH',  ZWKBUD)
  IF (BUCONF%LBUDGET_RH) ZWKBUD(:,:) = (PBUDGETS(:, :, IRCDRYH)+PBUDGETS(:, :, IRRDRYH)+PBUDGETS(:, :, IRIDRYH)+ &
                                                   &PBUDGETS(:, :, IRSDRYH)+PBUDGETS(:, :, IRGDRYH))*PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RH) CALL TBUDGETS(NBUDGET_RH)%PTR%ADD_PHY(D, 'DRYH',  ZWKBUD)

  IF (BUCONF%LBUDGET_RG) ZWKBUD(:,:) = -PBUDGETS(:, :, IRDRYHG)*PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RG) CALL TBUDGETS(NBUDGET_RG)%PTR%ADD_PHY(D, 'HGCV',  ZWKBUD)
  IF (BUCONF%LBUDGET_RH) ZWKBUD(:,:) = PBUDGETS(:, :, IRDRYHG)*PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RH) CALL TBUDGETS(NBUDGET_RH)%PTR%ADD_PHY(D, 'HGCV',  ZWKBUD)

  IF (BUCONF%LBUDGET_TH) ZWKBUD(:,:) = -PBUDGETS(:, :, IRHMLTR)*ZZ_DIFF(:, :)*PRHODJ(:, :)
  IF (BUCONF%LBUDGET_TH) CALL TBUDGETS(NBUDGET_TH)%PTR%ADD_PHY(D, 'HMLT',  ZWKBUD)
  IF (BUCONF%LBUDGET_RR) ZWKBUD(:,:) = PBUDGETS(:, :, IRHMLTR)              *PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RR) CALL TBUDGETS(NBUDGET_RR)%PTR%ADD_PHY(D, 'HMLT',  ZWKBUD)
  IF (BUCONF%LBUDGET_RH) ZWKBUD(:,:) = -PBUDGETS(:, :, IRHMLTR)              *PRHODJ(:, :)
  IF (BUCONF%LBUDGET_RH) CALL TBUDGETS(NBUDGET_RH)%PTR%ADD_PHY(D, 'HMLT',  ZWKBUD)
ENDIF

IF (BUCONF%LBUDGET_TH) ZWKBUD(:,:) = -PBUDGETS(:, :, IRIMLTC_MR)*ZZ_DIFF(:, :)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_TH) CALL TBUDGETS(NBUDGET_TH)%PTR%ADD_PHY(D, 'IMLT',  ZWKBUD)
IF (BUCONF%LBUDGET_RC) ZWKBUD(:,:) = PBUDGETS(:, :, IRIMLTC_MR)              *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RC) CALL TBUDGETS(NBUDGET_RC)%PTR%ADD_PHY(D, 'IMLT',  ZWKBUD)
IF (BUCONF%LBUDGET_RI) ZWKBUD(:,:) = -PBUDGETS(:, :, IRIMLTC_MR)              *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RI) CALL TBUDGETS(NBUDGET_RI)%PTR%ADD_PHY(D, 'IMLT',  ZWKBUD)

IF (BUCONF%LBUDGET_TH) ZWKBUD(:,:) = PBUDGETS(:, :, IRCBERI)*ZZ_DIFF(:, :)*PRHODJ(:, :)
IF (BUCONF%LBUDGET_TH) CALL TBUDGETS(NBUDGET_TH)%PTR%ADD_PHY(D, 'BERFI',  ZWKBUD)
IF (BUCONF%LBUDGET_RC) ZWKBUD(:,:) = -PBUDGETS(:, :, IRCBERI)              *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RC) CALL TBUDGETS(NBUDGET_RC)%PTR%ADD_PHY(D, 'BERFI',  ZWKBUD)
IF (BUCONF%LBUDGET_RI) ZWKBUD(:,:) = PBUDGETS(:, :, IRCBERI)              *PRHODJ(:, :)
IF (BUCONF%LBUDGET_RI) CALL TBUDGETS(NBUDGET_RI)%PTR%ADD_PHY(D, 'BERFI',  ZWKBUD)
!
IF (LHOOK) CALL DR_HOOK('ICE4_BUDGETS', 1, ZHOOK_HANDLE)
!
END SUBROUTINE ICE4_BUDGETS
!
END MODULE MODE_ICE4_BUDGETS
