!     ######spl
       MODULE MODI_RAIN_ICE_PART1
!      ###########################
!
IMPLICIT NONE
INTERFACE
       SUBROUTINE RAIN_ICE_PART1 ( D, CST, PARAMI, ICEP, ICED, ELECP, ELECD, BUCONF,     &
                                   OELEC, OSEDIM_BEARD, PTHVREFZIKB,                     &
                                   PTSTEP, KRR, PEXN,                                    &
                                   PDZZ, PRHODJ, PRHODREF, PPABST, PCIT, PCLDFR,         &
                                   PICLDFR, PSSIO,                                        &
                                   PHLC_HRC, PHLC_HCF, PHLI_HRI, PHLI_HCF,               &
                                   PTHT, PRT, PTHS, PRS,                                 &
                                   PINPRC, PINPRR, PEVAP3D,                              &
                                   PINPRS, PINPRG, PRAINFR, PSIGS,               &
                                   TBUDGETS, KBUDGETS,                                   &
                                   PQCT, PQRT, PQIT, PQST, PQGT,           &
                                   PQCS, PQRS, PQIS, PQSS, PQGS,           &
                                   PEFIELDW,                              &
                                   PSEA, PTOWN, PCONC3D,                                 &
                                   PINPRH, PFPR, PQHT, PQHS,                             &
                                   PT, PLVFACT, PLSFACT, PWR, PWTH, PZCONC3D, OMICRO,    &
                                   PRVHENI, PZZZZ )
!
USE MODD_BUDGET,         ONLY: TBUDGETDATA_PTR, TBUDGETCONF_t
USE MODD_CST,            ONLY: CST_t
USE MODD_PARAM_ICE_n,      ONLY: PARAM_ICE_t
USE MODD_RAIN_ICE_PARAM_n, ONLY: RAIN_ICE_PARAM_t
USE MODD_RAIN_ICE_DESCR_n, ONLY: RAIN_ICE_DESCR_t
USE MODD_ELEC_DESCR,     ONLY: ELEC_DESCR_t
USE MODD_ELEC_PARAM,     ONLY: ELEC_PARAM_t
USE MODD_DIMPHYEX,       ONLY: DIMPHYEX_t
!
IMPLICIT NONE
!
TYPE(DIMPHYEX_t),         INTENT(IN)    :: D
TYPE(CST_t),              INTENT(IN)    :: CST
TYPE(PARAM_ICE_t),        INTENT(IN)    :: PARAMI
TYPE(RAIN_ICE_PARAM_t),   INTENT(IN)    :: ICEP
TYPE(RAIN_ICE_DESCR_t),   INTENT(IN)    :: ICED
TYPE(ELEC_PARAM_t),       INTENT(IN)    :: ELECP
TYPE(ELEC_DESCR_t),       INTENT(IN)    :: ELECD
TYPE(TBUDGETCONF_t),      INTENT(IN)    :: BUCONF
LOGICAL,                  INTENT(IN)    :: OELEC
LOGICAL,                  INTENT(IN)    :: OSEDIM_BEARD
REAL,                     INTENT(IN)    :: PTHVREFZIKB
REAL,                     INTENT(IN)    :: PTSTEP
INTEGER,                  INTENT(IN)    :: KRR
!
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN)    :: PEXN
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN)    :: PDZZ
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN)    :: PRHODJ
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN)    :: PRHODREF
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN)    :: PPABST
!
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(INOUT) :: PCIT
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN)    :: PCLDFR
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN)    :: PICLDFR
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN)    :: PSSIO
!
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(INOUT) :: PHLC_HRC
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(INOUT) :: PHLC_HCF
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(INOUT) :: PHLI_HRI
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(INOUT) :: PHLI_HCF
!
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN)    :: PTHT
REAL, DIMENSION(D%NIJT,D%NKT,KRR),   INTENT(IN)    :: PRT
!
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(INOUT) :: PTHS
REAL, DIMENSION(D%NIJT,D%NKT,KRR),   INTENT(INOUT) :: PRS
!
REAL, DIMENSION(D%NIJT), INTENT(OUT)       :: PINPRC
REAL, DIMENSION(D%NIJT), INTENT(OUT)       :: PINPRR
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT)     :: PEVAP3D
REAL, DIMENSION(D%NIJT), INTENT(OUT)       :: PINPRS
REAL, DIMENSION(D%NIJT), INTENT(OUT)       :: PINPRG
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(OUT) :: PRAINFR
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN)    :: PSIGS
!
TYPE(TBUDGETDATA_PTR), DIMENSION(KBUDGETS), INTENT(INOUT) :: TBUDGETS
INTEGER, INTENT(IN) :: KBUDGETS
!
! scalar variables for cloud electricity
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQCT
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQRT
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQIT
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQST
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQGT
!
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQCS
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQRS
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQIS
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQSS
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQGS
!
REAL, DIMENSION(MERGE(D%NIJT,0,OSEDIM_BEARD),MERGE(D%NKT,0,OSEDIM_BEARD)), OPTIONAL, INTENT(IN) :: PEFIELDW
!
! optional variables
REAL, DIMENSION(D%NIJT),           OPTIONAL, INTENT(IN)    :: PSEA
REAL, DIMENSION(D%NIJT),           OPTIONAL, INTENT(IN)    :: PTOWN
REAL, DIMENSION(D%NIJT,D%NKT), OPTIONAL,  INTENT(IN)    :: PCONC3D
REAL, DIMENSION(D%NIJT),           OPTIONAL, INTENT(OUT)   :: PINPRH
REAL, DIMENSION(D%NIJT,D%NKT,KRR), OPTIONAL, INTENT(OUT)   :: PFPR
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQHT
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQHS
!
! Bridge variables (from part1 to part2/part3)
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT) :: PT
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT) :: PLVFACT
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT) :: PLSFACT
REAL, DIMENSION(D%NIJT,D%NKT,7), INTENT(OUT) :: PWR
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT) :: PWTH
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT) :: PZCONC3D
LOGICAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT) :: OMICRO
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT) :: PRVHENI
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(OUT) :: PZZZZ
!
END SUBROUTINE RAIN_ICE_PART1
END INTERFACE
END MODULE MODI_RAIN_ICE_PART1
