MODULE MODE_GATHER_ll
IMPLICIT NONE

INTERFACE GATHERALL_FIELD_ll
  MODULE PROCEDURE                               &
       GATHERALL_X1, GATHERALL_X3
END INTERFACE

CONTAINS
SUBROUTINE GATHERALL_X3(HDIR,PSEND,PRECV,KRESP)
CHARACTER(LEN=*),      INTENT(IN) :: HDIR
REAL,DIMENSION(:,:,:), INTENT(IN) :: PSEND
REAL,DIMENSION(:,:,:), INTENT(INOUT):: PRECV
INTEGER,               INTENT(INOUT):: KRESP

CALL ABORT
END SUBROUTINE GATHERALL_X3
!
SUBROUTINE GATHERALL_X1(HDIR,PSEND,PRECV,KRESP)
CHARACTER(LEN=*),  INTENT(IN) :: HDIR
REAL,DIMENSION(:), INTENT(IN) :: PSEND
REAL,DIMENSION(:), INTENT(INOUT):: PRECV
INTEGER,           INTENT(INOUT):: KRESP

CALL ABORT
END SUBROUTINE GATHERALL_X1
!
END MODULE MODE_GATHER_ll
