MODULE MODE_ll
USE MODE_ARGSLIST_ll    
USE MODE_TOOLS
IMPLICIT NONE
CONTAINS
  SUBROUTINE GET_INDICE_ll(KXOR, KYOR, KXEND, KYEND, KSIZE1, KSIZE2)
  USE MODD_PARAMETERS, ONLY : JPHEXT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: KSIZE1, KSIZE2
  INTEGER, INTENT(OUT) :: KXOR, KYOR, KXEND, KYEND
  KXOR=1+JPHEXT
  KYOR=1+JPHEXT
  KXEND=KSIZE1-JPHEXT
  KYEND=KSIZE2-JPHEXT
  END SUBROUTINE GET_INDICE_ll

  SUBROUTINE UPDATE_HALO_ll(TPLIST, KINFO)
  USE MODD_ARGSLIST_ll, ONLY : LIST_ll  
  TYPE(LIST_ll), POINTER :: TPLIST ! pointer to the list of fields to be updated
  INTEGER                :: KINFO  ! return status
  END SUBROUTINE UPDATE_HALO_ll
END MODULE MODE_ll
