MODULE MODE_ll
IMPLICIT NONE
CONTAINS
  SUBROUTINE GET_INDICE_ll(KXOR, KYOR, KXEND, KYEND, KSIZE1, KSIZE2)
  USE MODD_PARAMETERS, ONLY : JPHEXT
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: KSIZE1, KSIZE2
  INTEGER, INTENT(OUT) :: KXOR, KYOR, KXEND, KYEND
  KXOR=1+JPHEXT
  KYOR=1+JPHEXT
  KXEND=KSIZE1-JPHEXT
  KYEND=KSIZE2-JPHEXT
  END SUBROUTINE GET_INDICE_ll
END MODULE MODE_ll
