MODULE MODE_GATHER_ll
IMPLICIT NONE
CONTAINS
SUBROUTINE GATHERALL_FIELD_ll(HDIR,PSEND,PRECV,KRESP)
CHARACTER(LEN=*),      INTENT(IN) :: HDIR
REAL,DIMENSION(:,:,:), INTENT(IN) :: PSEND
REAL,DIMENSION(:,:,:), INTENT(INOUT):: PRECV
INTEGER,               INTENT(INOUT):: KRESP

CALL ABORT
END SUBROUTINE GATHERALL_FIELD_ll
END MODULE MODE_GATHER_ll
