INTERFACE

SUBROUTINE CONVECT_MIXING_FUNCT( D,  &
PMIXC, KMF, PER, PDR )
USE YOMHOOK , ONLY : LHOOK, DR_HOOK
USE MODD_DIMPHYEX, ONLY: DIMPHYEX_T
TYPE(DIMPHYEX_T),      INTENT(IN) :: D
INTEGER,               INTENT(IN) :: KMF
REAL, DIMENSION(D%NIT), INTENT(IN) :: PMIXC
REAL, DIMENSION(D%NIT), INTENT(OUT):: PER
REAL, DIMENSION(D%NIT), INTENT(OUT):: PDR
END SUBROUTINE CONVECT_MIXING_FUNCT

END INTERFACE
