MODULE MODI_SHALLOW_CONVECTION
IMPLICIT NONE

INTERFACE

SUBROUTINE SHALLOW_CONVECTION(CVP_SHAL, CST, D, NSV, CONVPAR, KBDIA, KTDIA, &
KICE, OSETTADJ, PTADJS, PPABST, PZZ, &
PTKECLS, PTT, PRVT, PRCT, PRIT, PWT, &
PTTEN, PRVTEN, PRCTEN, PRITEN,       &
KCLTOP, KCLBAS, PUMF, OCH1CONV, KCH1,&
PCH1, PCH1TEN)
USE PARKIND1, ONLY : JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK
USE MODD_CST, ONLY : CST_T
USE MODD_CONVPAREXT, ONLY : CONVPAREXT
USE MODD_CONVPAR, ONLY: CONVPAR_T
USE MODD_CONVPAR_SHAL, ONLY: CONVPAR_SHAL
USE MODD_DIMPHYEX, ONLY: DIMPHYEX_T
USE MODD_NSV, ONLY: NSV_T
TYPE(CONVPAR_SHAL),           INTENT(IN) :: CVP_SHAL
TYPE(CST_T),                  INTENT(IN) :: CST
TYPE(DIMPHYEX_T),             INTENT(IN) :: D
TYPE(NSV_T),                  INTENT(IN) :: NSV
TYPE(CONVPAR_T),              INTENT(IN) :: CONVPAR
INTEGER,                      INTENT(IN) :: KBDIA
INTEGER,                      INTENT(IN) :: KTDIA
INTEGER,                      INTENT(IN) :: KICE
LOGICAL,                      INTENT(IN) :: OSETTADJ
REAL,                         INTENT(IN) :: PTADJS
REAL, DIMENSION(D%NIT,D%NKT), INTENT(IN) :: PTT
REAL, DIMENSION(D%NIT,D%NKT), INTENT(IN) :: PRVT
REAL, DIMENSION(D%NIT,D%NKT), INTENT(IN) :: PRCT
REAL, DIMENSION(D%NIT,D%NKT), INTENT(IN) :: PRIT
REAL, DIMENSION(D%NIT,D%NKT), INTENT(IN) :: PWT
REAL, DIMENSION(D%NIT,D%NKT), INTENT(IN) :: PPABST
REAL, DIMENSION(D%NIT,D%NKT), INTENT(IN) :: PZZ
REAL, DIMENSION(D%NIT),       INTENT(IN) :: PTKECLS
REAL, DIMENSION(D%NIT,D%NKT), INTENT(INOUT):: PTTEN
REAL, DIMENSION(D%NIT,D%NKT), INTENT(INOUT):: PRVTEN
REAL, DIMENSION(D%NIT,D%NKT), INTENT(INOUT):: PRCTEN
REAL, DIMENSION(D%NIT,D%NKT), INTENT(INOUT):: PRITEN
INTEGER, DIMENSION(D%NIT),    INTENT(INOUT):: KCLTOP
INTEGER, DIMENSION(D%NIT),    INTENT(INOUT):: KCLBAS
REAL, DIMENSION(D%NIT,D%NKT), INTENT(INOUT):: PUMF
LOGICAL,                    INTENT(IN) :: OCH1CONV
INTEGER,                    INTENT(IN) :: KCH1
REAL, DIMENSION(D%NIT,D%NKT,KCH1), INTENT(IN) :: PCH1
REAL, DIMENSION(D%NIT,D%NKT,KCH1), INTENT(INOUT):: PCH1TEN
END SUBROUTINE SHALLOW_CONVECTION

END INTERFACE

END MODULE MODI_SHALLOW_CONVECTION
