MODULE MODI_SHALLOW_CONVECTION_PART2

INTERFACE
SUBROUTINE SHALLOW_CONVECTION_PART2&
&(CVP_SHAL, CVPEXT, CST, D, NSV,   &
CONVPAR, KICE, OSETTADJ, PTADJS, &
PPABST, PZZ, PTT, PRVT, PRCT,    &
PRIT, OCH1CONV, KCH1,  PCH1,     &
PRDOCP, PTHT, PSTHV, PSTHES,     &
ISDPL, ISPBL, ISLCL, PSTHLCL,    &
PSTLCL, PSRVLCL, PSWLCL, PSZLCL, &
PSTHVELCL, GTRIG1, PUMF, PTHC,   &
PRVC, PRCC, PRIC, ICTL, IMINCTL, &
PPCH1TEN)
USE PARKIND1, ONLY : JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK
USE MODD_CONVPAR, ONLY : CONVPAR_T
USE MODD_CONVPAR_SHAL, ONLY : CONVPAR_SHAL
USE MODD_CONVPAREXT, ONLY: CONVPAREXT
USE MODD_CST, ONLY: CST_T
USE MODD_DIMPHYEX, ONLY: DIMPHYEX_T
USE MODD_NSV, ONLY: NSV_T
TYPE(CONVPAR_SHAL),              INTENT(IN)  :: CVP_SHAL
TYPE(CONVPAREXT),                INTENT(IN)  :: CVPEXT
TYPE(CST_T),                     INTENT(IN)  :: CST
TYPE(DIMPHYEX_T),                INTENT(IN)  :: D
TYPE(NSV_T),                     INTENT(IN)  :: NSV
TYPE(CONVPAR_T),                 INTENT(IN)  :: CONVPAR
INTEGER,                         INTENT(IN)  :: KICE
LOGICAL,                         INTENT(IN)  :: OSETTADJ
REAL,                            INTENT(IN)  :: PTADJS
REAL, DIMENSION(D%NIT,D%NKT),    INTENT(IN)  :: PTT
REAL, DIMENSION(D%NIT,D%NKT),    INTENT(IN)  :: PRVT
REAL, DIMENSION(D%NIT,D%NKT),    INTENT(IN)  :: PRCT
REAL, DIMENSION(D%NIT,D%NKT),    INTENT(IN)  :: PRIT
REAL, DIMENSION(D%NIT,D%NKT),    INTENT(IN)  :: PPABST
REAL, DIMENSION(D%NIT,D%NKT),    INTENT(IN)  :: PZZ
LOGICAL,                           INTENT(IN)  :: OCH1CONV
INTEGER,                           INTENT(IN)  :: KCH1
REAL, DIMENSION(D%NIT,D%NKT,KCH1), INTENT(IN)  :: PCH1
REAL,                              INTENT(IN)  :: PRDOCP
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(IN)  :: PTHT, PSTHV, PSTHES
INTEGER, DIMENSION(D%NIT),         INTENT(IN)  :: ISDPL
INTEGER, DIMENSION(D%NIT),         INTENT(IN)  :: ISPBL
INTEGER, DIMENSION(D%NIT),         INTENT(IN)  :: ISLCL
REAL, DIMENSION(D%NIT),            INTENT(IN)  :: PSTHLCL
REAL, DIMENSION(D%NIT),            INTENT(IN)  :: PSTLCL
REAL, DIMENSION(D%NIT),            INTENT(IN)  :: PSRVLCL
REAL, DIMENSION(D%NIT),            INTENT(IN)  :: PSWLCL
REAL, DIMENSION(D%NIT),            INTENT(IN)  :: PSZLCL
REAL, DIMENSION(D%NIT),            INTENT(IN)  :: PSTHVELCL
LOGICAL, DIMENSION(D%NIT),         INTENT(IN)  :: GTRIG1
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(OUT) :: PUMF
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(OUT) :: PTHC
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(OUT) :: PRVC
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(OUT) :: PRCC
REAL, DIMENSION(D%NIT,D%NKT),      INTENT(OUT) :: PRIC
INTEGER, DIMENSION(D%NIT),         INTENT(OUT) :: ICTL
INTEGER, DIMENSION(D%NIT),         INTENT(OUT) :: IMINCTL
REAL, DIMENSION(D%NIT,D%NKT,KCH1), INTENT(OUT) :: PPCH1TEN
END SUBROUTINE SHALLOW_CONVECTION_PART2

END INTERFACE

END MODULE
