SUBROUTINE SHALLOW_CONVECTION_PART2_SELECT (CVP_SHAL, CVPEXT, CST, D, NSV, CONVPAR, KICE&
&, OSETTADJ, PTADJS, PPABST, PZZ, PTT, PRVT, PRCT, PRIT, OCH1CONV, KCH1, PCH1, PRDOCP,&
& PTHT, PSTHV, PSTHES, ISDPL, ISPBL, ISLCL, PSTHLCL, PSTLCL, PSRVLCL, PSWLCL, PSZLCL, PSTHVELCL&
&, GTRIG1, PUMF, PTHC, PRVC, PRCC, PRIC, ICTL, IMINCTL, PPCH1TEN, KIT_)
USE PARKIND1,ONLY:JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK
USE MODD_CONVPAR,ONLY:CONVPAR_T
USE MODD_CONVPAR_SHAL,ONLY:CONVPAR_SHAL
USE MODD_CONVPAREXT,ONLY:CONVPAREXT
USE MODD_CST,ONLY:CST_T
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_NSV,ONLY:NSV_T
USE MODI_SHALLOW_CONVECTION_PART2

IMPLICIT NONE

TYPE(CONVPAR_SHAL) ,INTENT(IN)   :: CVP_SHAL
TYPE(CONVPAREXT)   ,INTENT(IN)   :: CVPEXT
TYPE(CST_T)        ,INTENT(IN)   :: CST
TYPE(DIMPHYEX_T)   ,INTENT(IN)   :: D
TYPE(NSV_T)        ,INTENT(IN)   :: NSV
TYPE(CONVPAR_T)    ,INTENT(IN)   :: CONVPAR
INTEGER            ,INTENT(IN)   :: KICE
LOGICAL            ,INTENT(IN)   :: OSETTADJ
REAL               ,INTENT(IN)   :: PTADJS
REAL               ,INTENT(IN)   :: PPABST(D%NIT,D%NKT)
REAL               ,INTENT(IN)   :: PZZ(D%NIT,D%NKT)
REAL               ,INTENT(IN)   :: PTT(D%NIT,D%NKT)
REAL               ,INTENT(IN)   :: PRVT(D%NIT,D%NKT)
REAL               ,INTENT(IN)   :: PRCT(D%NIT,D%NKT)
REAL               ,INTENT(IN)   :: PRIT(D%NIT,D%NKT)
LOGICAL            ,INTENT(IN)   :: OCH1CONV
INTEGER            ,INTENT(IN)   :: KCH1
REAL               ,INTENT(IN)   :: PCH1(D%NIT,D%NKT,KCH1)
REAL               ,INTENT(IN)   :: PRDOCP
REAL               ,INTENT(IN)   :: PTHT(D%NIT,D%NKT)
REAL               ,INTENT(IN)   :: PSTHV(D%NIT,D%NKT)
REAL               ,INTENT(IN)   :: PSTHES(D%NIT,D%NKT)
INTEGER            ,INTENT(IN)   :: ISDPL(D%NIT)
INTEGER            ,INTENT(IN)   :: ISPBL(D%NIT)
INTEGER            ,INTENT(IN)   :: ISLCL(D%NIT)
REAL               ,INTENT(IN)   :: PSTHLCL(D%NIT)
REAL               ,INTENT(IN)   :: PSTLCL(D%NIT)
REAL               ,INTENT(IN)   :: PSRVLCL(D%NIT)
REAL               ,INTENT(IN)   :: PSWLCL(D%NIT)
REAL               ,INTENT(IN)   :: PSZLCL(D%NIT)
REAL               ,INTENT(IN)   :: PSTHVELCL(D%NIT)
LOGICAL            ,INTENT(IN)   :: GTRIG1(D%NIT)
REAL               ,INTENT(OUT)  :: PUMF(D%NIT,D%NKT)
REAL               ,INTENT(OUT)  :: PTHC(D%NIT,D%NKT)
REAL               ,INTENT(OUT)  :: PRVC(D%NIT,D%NKT)
REAL               ,INTENT(OUT)  :: PRCC(D%NIT,D%NKT)
REAL               ,INTENT(OUT)  :: PRIC(D%NIT,D%NKT)
INTEGER            ,INTENT(OUT)  :: ICTL(D%NIT)
INTEGER            ,INTENT(OUT)  :: IMINCTL(D%NIT)
REAL               ,INTENT(OUT)  :: PPCH1TEN(D%NIT,D%NKT,KCH1)
INTEGER            ,INTENT(IN)   :: KIT_

LOGICAL::GTRIG1_(KIT_)
INTEGER::ICTL_(KIT_)
INTEGER::IMINCTL_(KIT_)
INTEGER::ISDPL_(KIT_)
INTEGER::ISLCL_(KIT_)
INTEGER::ISPBL_(KIT_)
REAL::PCH1_(KIT_, D%NKT, KCH1)
REAL::PPABST_(KIT_, D%NKT)
REAL::PPCH1TEN_(KIT_, D%NKT, KCH1)
REAL::PRCC_(KIT_, D%NKT)
REAL::PRCT_(KIT_, D%NKT)
REAL::PRIC_(KIT_, D%NKT)
REAL::PRIT_(KIT_, D%NKT)
REAL::PRVC_(KIT_, D%NKT)
REAL::PRVT_(KIT_, D%NKT)
REAL::PSRVLCL_(KIT_)
REAL::PSTHES_(KIT_, D%NKT)
REAL::PSTHLCL_(KIT_)
REAL::PSTHV_(KIT_, D%NKT)
REAL::PSTHVELCL_(KIT_)
REAL::PSTLCL_(KIT_)
REAL::PSWLCL_(KIT_)
REAL::PSZLCL_(KIT_)
REAL::PTHC_(KIT_, D%NKT)
REAL::PTHT_(KIT_, D%NKT)
REAL::PTT_(KIT_, D%NKT)
REAL::PUMF_(KIT_, D%NKT)
REAL::PZZ_(KIT_, D%NKT)

INTEGER :: JI
INTEGER :: JI_
INTEGER :: ISORT (KIT_)
TYPE (DIMPHYEX_T) :: D_

D_ = D
D_%NIB = 1
D_%NIE = KIT_
D_%NIT = KIT_

JI_ = 0

DO JI = D%NIB, D%NIE

    IF (GTRIG1 (JI)) THEN
        JI_ = JI_ + 1
        ISORT (JI_) = JI
    ENDIF

ENDDO

DO JI_ = 1, KIT_
    GTRIG1_(JI_) = GTRIG1(ISORT(JI_))
    ISDPL_(JI_) = ISDPL(ISORT(JI_))
    ISLCL_(JI_) = ISLCL(ISORT(JI_))
    ISPBL_(JI_) = ISPBL(ISORT(JI_))
    PCH1_(JI_,:,:) = PCH1(ISORT(JI_),:,:)
    PPABST_(JI_,:) = PPABST(ISORT(JI_),:)
    PRCT_(JI_,:) = PRCT(ISORT(JI_),:)
    PRIT_(JI_,:) = PRIT(ISORT(JI_),:)
    PRVT_(JI_,:) = PRVT(ISORT(JI_),:)
    PSRVLCL_(JI_) = PSRVLCL(ISORT(JI_))
    PSTHES_(JI_,:) = PSTHES(ISORT(JI_),:)
    PSTHLCL_(JI_) = PSTHLCL(ISORT(JI_))
    PSTHV_(JI_,:) = PSTHV(ISORT(JI_),:)
    PSTHVELCL_(JI_) = PSTHVELCL(ISORT(JI_))
    PSTLCL_(JI_) = PSTLCL(ISORT(JI_))
    PSWLCL_(JI_) = PSWLCL(ISORT(JI_))
    PSZLCL_(JI_) = PSZLCL(ISORT(JI_))
    PTHT_(JI_,:) = PTHT(ISORT(JI_),:)
    PTT_(JI_,:) = PTT(ISORT(JI_),:)
    PZZ_(JI_,:) = PZZ(ISORT(JI_),:)
ENDDO

CALL SHALLOW_CONVECTION_PART2 (CVP_SHAL, CVPEXT, CST, D_, NSV, CONVPAR, KICE, OSETTADJ, PTADJS&
&, PPABST_, PZZ_, PTT_, PRVT_, PRCT_, PRIT_, OCH1CONV, KCH1, PCH1_, PRDOCP, PTHT_, PSTHV_&
&, PSTHES_, ISDPL_, ISPBL_, ISLCL_, PSTHLCL_, PSTLCL_, PSRVLCL_, PSWLCL_, PSZLCL_, PSTHVELCL_&
&, GTRIG1_, PUMF_, PTHC_, PRVC_, PRCC_, PRIC_, ICTL_, IMINCTL_, PPCH1TEN_)


DO JI_ = 1, KIT_
    ICTL(ISORT(JI_)) = ICTL_(JI_)
    IMINCTL(ISORT(JI_)) = IMINCTL_(JI_)
    PPCH1TEN(ISORT(JI_),:,:) = PPCH1TEN_(JI_,:,:)
    PRCC(ISORT(JI_),:) = PRCC_(JI_,:)
    PRIC(ISORT(JI_),:) = PRIC_(JI_,:)
    PRVC(ISORT(JI_),:) = PRVC_(JI_,:)
    PTHC(ISORT(JI_),:) = PTHC_(JI_,:)
    PUMF(ISORT(JI_),:) = PUMF_(JI_,:)
ENDDO


ENDSUBROUTINE SHALLOW_CONVECTION_PART2_SELECT

