MODULE GETDATA_RAIN_ICE_OLD_MOD

USE OMP_LIB

INTERFACE REPLICATE
  MODULE PROCEDURE REPLICATE1
  MODULE PROCEDURE REPLICATE2
  MODULE PROCEDURE REPLICATE3
  MODULE PROCEDURE REPLICATE4
  MODULE PROCEDURE REPLICATEL
END INTERFACE

INTERFACE NPROMIZE
  MODULE PROCEDURE NPROMIZE2
  MODULE PROCEDURE NPROMIZE3
  MODULE PROCEDURE NPROMIZE4
  MODULE PROCEDURE NPROMIZE5
  MODULE PROCEDURE NPROMIZEL
END INTERFACE

INTERFACE INTERPOLATE
  MODULE PROCEDURE INTERPOLATE2
  MODULE PROCEDURE INTERPOLATE3
  MODULE PROCEDURE INTERPOLATE4
  MODULE PROCEDURE INTERPOLATE5
  MODULE PROCEDURE INTERPOLATEL
END INTERFACE

INTERFACE SET
  MODULE PROCEDURE SET2
  MODULE PROCEDURE SET3
  MODULE PROCEDURE SET4
END INTERFACE

CONTAINS

SUBROUTINE GETDATA_RAIN_ICE_OLD(NPROMA, NGPBLOCKS, NFLEVG,             &
                                PDZZ_B, PRHODJ_B, PRHODREF_B,        &
                                PEXNREF_B, PPABSM_B,                 &
                                PCIT_B, PCIT_OUT_B,                  &
                                PCLDFR_B,                            &
                                PICLDFR_B, PSSIO_B, PSSIU_B, PIFR_B, &
                                PTHT_B, PRT_B, PTHS_B, PTHS_OUT_B,   &
                                PRS_B, PRS_OUT_B,                    &
                                PSIGS_B, PSEA_B, PTOWN_B,            &
                                ZINPRC_B, ZINPRC_OUT_B,              &
                                PINPRR_B, PINPRR_OUT_B,              &
                                PEVAP_B, PEVAP_OUT_B,                &
                                PINPRS_B, PINPRS_OUT_B,              &
                                PINPRG_B, PINPRG_OUT_B,              &
                                PINPRH_B, PINPRH_OUT_B,              &
                                PICENU_B, PKGN_ACON_B, PKGN_SBGR_B,  &
                                PFPR_B, PFPR_OUT_B, LDVERBOSE)

USE IEEE_ARITHMETIC, ONLY : IEEE_SIGNALING_NAN, IEEE_VALUE

IMPLICIT NONE

INTEGER, PARAMETER :: IFILE = 77

INTEGER      :: KLON
INTEGER      :: KIDIA
INTEGER      :: KLEV
INTEGER      :: KRR

LOGICAL :: LDVERBOSE

REAL, ALLOCATABLE, DIMENSION(:,:,:),   INTENT(OUT) :: PDZZ_B
REAL, ALLOCATABLE, DIMENSION(:,:,:),   INTENT(OUT) :: PRHODJ_B
REAL, ALLOCATABLE, DIMENSION(:,:,:),   INTENT(OUT) :: PRHODREF_B
REAL, ALLOCATABLE, DIMENSION(:,:,:),   INTENT(OUT) :: PEXNREF_B
REAL, ALLOCATABLE, DIMENSION(:,:,:),   INTENT(OUT) :: PPABSM_B
REAL, ALLOCATABLE, DIMENSION(:,:,:),   INTENT(OUT) :: PCIT_B, PCIT_OUT_B
REAL, ALLOCATABLE, DIMENSION(:,:,:),   INTENT(OUT) :: PCLDFR_B
                   
REAL, ALLOCATABLE, DIMENSION(:,:,:),   INTENT(OUT) :: PICLDFR_B
REAL, ALLOCATABLE, DIMENSION(:,:,:),   INTENT(OUT) :: PSSIO_B
REAL, ALLOCATABLE, DIMENSION(:,:,:),   INTENT(OUT) :: PSSIU_B
REAL, ALLOCATABLE, DIMENSION(:,:,:),   INTENT(OUT) :: PIFR_B
                   
REAL, ALLOCATABLE, DIMENSION(:,:,:),   INTENT(OUT) :: PTHT_B
REAL, ALLOCATABLE, DIMENSION(:,:,:,:), INTENT(OUT) :: PRT_B
REAL, ALLOCATABLE, DIMENSION(:,:,:),   INTENT(OUT) :: PTHS_B, PTHS_OUT_B
REAL, ALLOCATABLE, DIMENSION(:,:,:,:), INTENT(OUT) :: PRS_B,  PRS_OUT_B
                   
REAL, ALLOCATABLE, DIMENSION(:,:),     INTENT(OUT) :: ZINPRC_B, ZINPRC_OUT_B
REAL, ALLOCATABLE, DIMENSION(:,:),     INTENT(OUT) :: PINPRR_B, PINPRR_OUT_B
REAL, ALLOCATABLE, DIMENSION(:,:,:),   INTENT(OUT) :: PEVAP_B,  PEVAP_OUT_B
REAL, ALLOCATABLE, DIMENSION(:,:),     INTENT(OUT) :: PINPRS_B, PINPRS_OUT_B
REAL, ALLOCATABLE, DIMENSION(:,:),     INTENT(OUT) :: PINPRG_B, PINPRG_OUT_B
REAL, ALLOCATABLE, DIMENSION(:,:),     INTENT(OUT) :: PINPRH_B, PINPRH_OUT_B

REAL, ALLOCATABLE, DIMENSION(:,:,:),   INTENT(OUT) :: PSIGS_B
REAL, ALLOCATABLE, DIMENSION(:,:),     INTENT(OUT) :: PSEA_B
REAL, ALLOCATABLE, DIMENSION(:,:),     INTENT(OUT) :: PTOWN_B
                   
REAL, ALLOCATABLE, DIMENSION(:,:),     INTENT(OUT) :: PICENU_B
REAL, ALLOCATABLE, DIMENSION(:,:),     INTENT(OUT) :: PKGN_ACON_B
REAL, ALLOCATABLE, DIMENSION(:,:),     INTENT(OUT) :: PKGN_SBGR_B
                   
REAL, ALLOCATABLE, DIMENSION(:,:,:,:), INTENT(OUT) :: PFPR_B, PFPR_OUT_B


REAL, ALLOCATABLE, DIMENSION(:,:,:)   :: PDZZ
REAL, ALLOCATABLE, DIMENSION(:,:,:)   :: PRHODJ
REAL, ALLOCATABLE, DIMENSION(:,:,:)   :: PRHODREF
REAL, ALLOCATABLE, DIMENSION(:,:,:)   :: PEXNREF
REAL, ALLOCATABLE, DIMENSION(:,:,:)   :: PPABSM
REAL, ALLOCATABLE, DIMENSION(:,:,:)   :: PCIT, PCIT_OUT
REAL, ALLOCATABLE, DIMENSION(:,:,:)   :: PCLDFR
                   
REAL, ALLOCATABLE, DIMENSION(:,:,:)   :: PICLDFR
REAL, ALLOCATABLE, DIMENSION(:,:,:)   :: PSSIO
REAL, ALLOCATABLE, DIMENSION(:,:,:)   :: PSSIU
REAL, ALLOCATABLE, DIMENSION(:,:,:)   :: PIFR
                   
REAL, ALLOCATABLE, DIMENSION(:,:,:)   :: PTHT
REAL, ALLOCATABLE, DIMENSION(:,:,:,:) :: PRT
REAL, ALLOCATABLE, DIMENSION(:,:,:)   :: PTHS, PTHS_OUT
REAL, ALLOCATABLE, DIMENSION(:,:,:,:) :: PRS,  PRS_OUT
                   
REAL, ALLOCATABLE, DIMENSION(:,:)     :: ZINPRC, ZINPRC_OUT
REAL, ALLOCATABLE, DIMENSION(:,:)     :: PINPRR, PINPRR_OUT
REAL, ALLOCATABLE, DIMENSION(:,:,:)   :: PEVAP,  PEVAP_OUT
REAL, ALLOCATABLE, DIMENSION(:,:)     :: PINPRS, PINPRS_OUT
REAL, ALLOCATABLE, DIMENSION(:,:)     :: PINPRG, PINPRG_OUT
REAL, ALLOCATABLE, DIMENSION(:,:)     :: PINPRH, PINPRH_OUT

REAL, ALLOCATABLE, DIMENSION(:,:,:)   :: PSIGS
REAL, ALLOCATABLE, DIMENSION(:,:)     :: PSEA
REAL, ALLOCATABLE, DIMENSION(:,:)     :: PTOWN
                   
REAL, ALLOCATABLE, DIMENSION(:,:)     :: PICENU
REAL, ALLOCATABLE, DIMENSION(:,:)     :: PKGN_ACON
REAL, ALLOCATABLE, DIMENSION(:,:)     :: PKGN_SBGR
                   
REAL, ALLOCATABLE, DIMENSION(:,:,:,:) :: PFPR, PFPR_OUT

INTEGER :: NGPTOT, NPROMA, NGPBLOCKS, NFLEVG
INTEGER :: IOFF, IBL
LOGICAL :: LLEXIST
CHARACTER(LEN=32) :: CLFILE
REAL :: ZNAN

KRR=6
NGPTOT = NPROMA * NGPBLOCKS

IBL = 1
WRITE (CLFILE, '("data/",I8.8,".dat")') IBL
OPEN (IFILE, FILE=TRIM (CLFILE), FORM='UNFORMATTED')
READ (IFILE) KLON, KLEV, KRR
CLOSE (IFILE)

IF (NFLEVG < 0) NFLEVG = KLEV

ALLOCATE (PDZZ_B          (NPROMA, NFLEVG, NGPBLOCKS))
ALLOCATE (PRHODJ_B        (NPROMA, NFLEVG, NGPBLOCKS))
ALLOCATE (PRHODREF_B      (NPROMA, NFLEVG, NGPBLOCKS))
ALLOCATE (PEXNREF_B       (NPROMA, NFLEVG, NGPBLOCKS))
ALLOCATE (PPABSM_B        (NPROMA, NFLEVG, NGPBLOCKS))
ALLOCATE (PCIT_B          (NPROMA, NFLEVG, NGPBLOCKS))
ALLOCATE (PCIT_OUT_B      (NPROMA, NFLEVG, NGPBLOCKS))
ALLOCATE (PCLDFR_B        (NPROMA, NFLEVG, NGPBLOCKS))

ALLOCATE (PICLDFR_B       (NPROMA, NFLEVG, NGPBLOCKS))
ALLOCATE (PSSIO_B         (NPROMA, NFLEVG, NGPBLOCKS))
ALLOCATE (PSSIU_B         (NPROMA, NFLEVG, NGPBLOCKS))
ALLOCATE (PIFR_B          (NPROMA, NFLEVG, NGPBLOCKS))

ALLOCATE (PTHT_B          (NPROMA, NFLEVG, NGPBLOCKS))
ALLOCATE (PRT_B           (NPROMA, NFLEVG, KRR, NGPBLOCKS))
ALLOCATE (PTHS_B          (NPROMA, NFLEVG, NGPBLOCKS))
ALLOCATE (PTHS_OUT_B      (NPROMA, NFLEVG, NGPBLOCKS))
ALLOCATE (PRS_B           (NPROMA, NFLEVG, KRR, NGPBLOCKS))
ALLOCATE (PRS_OUT_B       (NPROMA, NFLEVG, KRR, NGPBLOCKS))

ALLOCATE (ZINPRC_B        (NPROMA, NGPBLOCKS))
ALLOCATE (ZINPRC_OUT_B    (NPROMA, NGPBLOCKS))
ALLOCATE (PINPRR_B        (NPROMA, NGPBLOCKS))
ALLOCATE (PINPRR_OUT_B    (NPROMA, NGPBLOCKS))
ALLOCATE (PEVAP_B         (NPROMA, NFLEVG, NGPBLOCKS))
ALLOCATE (PEVAP_OUT_B     (NPROMA, NFLEVG, NGPBLOCKS))
ALLOCATE (PINPRS_B        (NPROMA, NGPBLOCKS))
ALLOCATE (PINPRS_OUT_B    (NPROMA, NGPBLOCKS))
ALLOCATE (PINPRG_B        (NPROMA, NGPBLOCKS))
ALLOCATE (PINPRG_OUT_B    (NPROMA, NGPBLOCKS))

ALLOCATE (PSIGS_B         (NPROMA, NFLEVG, NGPBLOCKS))
ALLOCATE (PSEA_B          (NPROMA, NGPBLOCKS))
ALLOCATE (PTOWN_B         (NPROMA, NGPBLOCKS))

ALLOCATE (PICENU_B        (NPROMA, NGPBLOCKS))
ALLOCATE (PKGN_ACON_B     (NPROMA, NGPBLOCKS))
ALLOCATE (PKGN_SBGR_B     (NPROMA, NGPBLOCKS))

ALLOCATE (PFPR_B          (NPROMA, NFLEVG, KRR, NGPBLOCKS))
ALLOCATE (PFPR_OUT_B      (NPROMA, NFLEVG, KRR, NGPBLOCKS))

IF (KRR .EQ. 7) THEN
  ALLOCATE (PINPRH_B      (NPROMA, NGPBLOCKS))
  ALLOCATE (PINPRH_OUT_B  (NPROMA, NGPBLOCKS))
ENDIF


ZNAN = IEEE_VALUE (ZNAN, IEEE_SIGNALING_NAN)


CALL SET (PDZZ_B)
CALL SET (PRHODJ_B)
CALL SET (PRHODREF_B)
CALL SET (PEXNREF_B)
CALL SET (PPABSM_B)
CALL SET (PCIT_B)
CALL SET (PCIT_OUT_B)
CALL SET (PCLDFR_B)

CALL SET (PICLDFR_B)
CALL SET (PSSIO_B)
CALL SET (PSSIU_B)
CALL SET (PIFR_B)

CALL SET (PTHT_B)
CALL SET (PRT_B)
CALL SET (PTHS_B)
CALL SET (PTHS_OUT_B)
CALL SET (PRS_B)
CALL SET (PRS_OUT_B)

CALL SET (ZINPRC_B)
CALL SET (ZINPRC_OUT_B)
CALL SET (PINPRR_B)
CALL SET (PINPRR_OUT_B)
CALL SET (PEVAP_B)
CALL SET (PEVAP_OUT_B)
CALL SET (PINPRS_B)
CALL SET (PINPRS_OUT_B)
CALL SET (PINPRG_B)
CALL SET (PINPRG_OUT_B)

CALL SET (PSIGS_B)
CALL SET (PSEA_B)
CALL SET (PTOWN_B)

CALL SET (PICENU_B)
CALL SET (PKGN_ACON_B)
CALL SET (PKGN_SBGR_B)

CALL SET (PFPR_B)
CALL SET (PFPR_OUT_B)

IF (KRR .EQ. 7) THEN
  CALL SET(PINPRH_B)
  CALL SET(PINPRH_OUT_B)
ENDIF

IOFF = 0
IBL = 0
LLEXIST = .TRUE.

DO WHILE(LLEXIST)
  IBL = IBL + 1
  WRITE (CLFILE, '("data/",I8.8,".dat")') IBL

  INQUIRE (FILE=TRIM (CLFILE), EXIST=LLEXIST)

  IF (LDVERBOSE) PRINT *, TRIM (CLFILE)

  IF (.NOT. LLEXIST) EXIT

  OPEN (IFILE, FILE=TRIM (CLFILE), FORM='UNFORMATTED')

  READ (IFILE) KLON, KLEV, KRR

  IF (IBL == 1) THEN
    ALLOCATE (PDZZ         (KLON, KLEV, NGPBLOCKS))
    ALLOCATE (PRHODJ       (KLON, KLEV, NGPBLOCKS))
    ALLOCATE (PRHODREF     (KLON, KLEV, NGPBLOCKS))
    ALLOCATE (PEXNREF      (KLON, KLEV, NGPBLOCKS))
    ALLOCATE (PPABSM       (KLON, KLEV, NGPBLOCKS))
    ALLOCATE (PCIT         (KLON, KLEV, NGPBLOCKS))
    ALLOCATE (PCIT_OUT     (KLON, KLEV, NGPBLOCKS))
    ALLOCATE (PCLDFR       (KLON, KLEV, NGPBLOCKS))

    ALLOCATE (PICLDFR      (KLON, KLEV, NGPBLOCKS))
    ALLOCATE (PSSIO        (KLON, KLEV, NGPBLOCKS))
    ALLOCATE (PSSIU        (KLON, KLEV, NGPBLOCKS))
    ALLOCATE (PIFR         (KLON, KLEV, NGPBLOCKS))

    ALLOCATE (PTHT         (KLON, KLEV, NGPBLOCKS))
    ALLOCATE (PRT          (KLON, KLEV, KRR, NGPBLOCKS))
    ALLOCATE (PTHS         (KLON, KLEV, NGPBLOCKS))
    ALLOCATE (PTHS_OUT     (KLON, KLEV, NGPBLOCKS))
    ALLOCATE (PRS          (KLON, KLEV, KRR, NGPBLOCKS))
    ALLOCATE (PRS_OUT      (KLON, KLEV, KRR, NGPBLOCKS))

    ALLOCATE (ZINPRC       (KLON, NGPBLOCKS))
    ALLOCATE (ZINPRC_OUT   (KLON, NGPBLOCKS))
    ALLOCATE (PINPRR       (KLON, NGPBLOCKS))
    ALLOCATE (PINPRR_OUT   (KLON, NGPBLOCKS))
    ALLOCATE (PEVAP        (KLON, KLEV, NGPBLOCKS))
    ALLOCATE (PEVAP_OUT    (KLON, KLEV, NGPBLOCKS))
    ALLOCATE (PINPRS       (KLON, NGPBLOCKS))
    ALLOCATE (PINPRS_OUT   (KLON, NGPBLOCKS))
    ALLOCATE (PINPRG       (KLON, NGPBLOCKS))
    ALLOCATE (PINPRG_OUT   (KLON, NGPBLOCKS))

    ALLOCATE (PSIGS        (KLON, KLEV, NGPBLOCKS))
    ALLOCATE (PSEA         (KLON, NGPBLOCKS))
    ALLOCATE (PTOWN        (KLON, NGPBLOCKS))

    ALLOCATE (PICENU       (KLON, NGPBLOCKS))
    ALLOCATE (PKGN_ACON    (KLON, NGPBLOCKS))
    ALLOCATE (PKGN_SBGR    (KLON, NGPBLOCKS))

    IF (KRR == 7) THEN
      ALLOCATE (PINPRH       (KLON, NGPBLOCKS))
      ALLOCATE (PINPRH_OUT   (KLON, NGPBLOCKS))
    ENDIF

    ALLOCATE (PFPR         (KLON, KLEV, KRR, NGPBLOCKS))
    ALLOCATE (PFPR_OUT     (KLON, KLEV, KRR, NGPBLOCKS))

  ENDIF

  IF (IOFF+KLON > NGPTOT) THEN
    EXIT
  ENDIF

  READ (IFILE) PDZZ         (:, :, IBL)
  READ (IFILE) PRHODJ       (:, :, IBL)
  READ (IFILE) PRHODREF     (:, :, IBL)
  READ (IFILE) PEXNREF      (:, :, IBL)
  READ (IFILE) PPABSM       (:, :, IBL)
  READ (IFILE) PCIT         (:, :, IBL)
  READ (IFILE) PCLDFR       (:, :, IBL)

  READ (IFILE) PICLDFR      (:, :, IBL)
  READ (IFILE) PSSIO        (:, :, IBL)
  READ (IFILE) PSSIU        (:, :, IBL)
  READ (IFILE) PIFR         (:, :, IBL)

  READ (IFILE) PTHT         (:, :, IBL)
  READ (IFILE) PRT          (:, :, :, IBL)
  READ (IFILE) PTHS         (:, :, IBL)
  READ (IFILE) PRS          (:, :, :, IBL)

  READ (IFILE) ZINPRC       (:, IBL)
  READ (IFILE) PINPRR       (:, IBL)
  READ (IFILE) PEVAP        (:, :, IBL)
  READ (IFILE) PINPRS       (:, IBL)
  READ (IFILE) PINPRG       (:, IBL)

  READ (IFILE) PSIGS        (:, :, IBL)
  READ (IFILE) PSEA         (:, IBL)
  READ (IFILE) PTOWN        (:, IBL)

  READ (IFILE) PICENU       (:, IBL)
  READ (IFILE) PKGN_ACON    (:, IBL)
  READ (IFILE) PKGN_SBGR    (:, IBL)

  IF (KRR == 7) THEN
    READ (IFILE) PINPRH     (:, IBL)
  ENDIF

  READ (IFILE) PCIT_OUT     (:, :, IBL)
  READ (IFILE) PTHS_OUT     (:, :, IBL)
  READ (IFILE) PRS_OUT      (:, :, :, IBL)
  READ (IFILE) ZINPRC_OUT   (:, IBL)
  READ (IFILE) PINPRR_OUT   (:, IBL)
  READ (IFILE) PEVAP_OUT    (:, :, IBL)
  READ (IFILE) PINPRS_OUT   (:, IBL)
  READ (IFILE) PINPRG_OUT   (:, IBL)

  READ (IFILE) PFPR_OUT     (:, :, :, IBL)

  IF (KRR == 7) THEN
    READ (IFILE) PINPRH_OUT (:, IBL)
  ENDIF

  CLOSE (IFILE)

  IOFF = IOFF + KLON

ENDDO

IF (NFLEVG /= KLEV) THEN
  CALL INTERPOLATEX (KLON, KLEV, NGPBLOCKS, IBL, NFLEVG, PSIGS)

  CALL INTERPOLATE (NFLEVG, IOFF, PEXNREF    )
  CALL INTERPOLATE (NFLEVG, IOFF, PDZZ       )
  CALL INTERPOLATE (NFLEVG, IOFF, PRHODJ     )
  CALL INTERPOLATE (NFLEVG, IOFF, PRHODREF   )
  CALL INTERPOLATE (NFLEVG, IOFF, PPABSM     )
  CALL INTERPOLATE (NFLEVG, IOFF, PCIT       )
  CALL INTERPOLATE (NFLEVG, IOFF, PCLDFR     )
  CALL INTERPOLATE (NFLEVG, IOFF, PICLDFR    )
  CALL INTERPOLATE (NFLEVG, IOFF, PTHT       )
  CALL INTERPOLATE (NFLEVG, IOFF, PRT        )
  CALL INTERPOLATE (NFLEVG, IOFF, PTHS       )
  CALL INTERPOLATE (NFLEVG, IOFF, PRS        )
  CALL INTERPOLATE (NFLEVG, IOFF, PSIGS      )
!  CALL INTERPOLATE (NFLEVG, IOFF, PSEA       )
  CALL INTERPOLATE (NFLEVG, IOFF, PTOWN      )
  CALL INTERPOLATE (NFLEVG, IOFF, PCIT_OUT   )
  CALL INTERPOLATE (NFLEVG, IOFF, PRS_OUT    )
  CALL INTERPOLATE (NFLEVG, IOFF, ZINPRC_OUT )
  CALL INTERPOLATE (NFLEVG, IOFF, PINPRR_OUT )
  CALL INTERPOLATE (NFLEVG, IOFF, PEVAP_OUT  )
  CALL INTERPOLATE (NFLEVG, IOFF, PINPRS_OUT )
  CALL INTERPOLATE (NFLEVG, IOFF, PINPRG_OUT )
  CALL INTERPOLATE (NFLEVG, IOFF, PFPR_OUT   )

ENDIF

CALL REPLICATE (IOFF, PEXNREF    (:, :, 1))
CALL REPLICATE (IOFF, PDZZ       (:, :, 1))
CALL REPLICATE (IOFF, PRHODJ     (:, :, 1))
CALL REPLICATE (IOFF, PRHODREF   (:, :, 1))
CALL REPLICATE (IOFF, PPABSM     (:, :, 1))
CALL REPLICATE (IOFF, PCIT       (:, :, 1))
CALL REPLICATE (IOFF, PCLDFR     (:, :, 1))
CALL REPLICATE (IOFF, PICLDFR    (:, :, 1))
CALL REPLICATE (IOFF, PTHT       (:, :, 1))
CALL REPLICATE (IOFF, PRT        (:, :, :, 1))
CALL REPLICATE (IOFF, PTHS       (:, :, 1))
CALL REPLICATE (IOFF, PRS        (:, :, :, 1))
CALL REPLICATE (IOFF, PSIGS      (:, :, 1))
CALL REPLICATE (IOFF, PSEA       (:, 1))
CALL REPLICATE (IOFF, PTOWN      (:, 1))
CALL REPLICATE (IOFF, PCIT_OUT   (:, :, 1))
CALL REPLICATE (IOFF, PRS_OUT    (:, :, :, 1))
CALL REPLICATE (IOFF, ZINPRC_OUT (:, 1))
CALL REPLICATE (IOFF, PINPRR_OUT (:, 1))
CALL REPLICATE (IOFF, PEVAP_OUT  (:, :, 1))
CALL REPLICATE (IOFF, PINPRS_OUT (:, 1))
CALL REPLICATE (IOFF, PINPRG_OUT (:, 1))
CALL REPLICATE (IOFF, PFPR_OUT   (:, :, :, 1))


CALL NPROMIZE (NPROMA, PEXNREF,    PEXNREF_B)
CALL NPROMIZE (NPROMA, PDZZ,       PDZZ_B)
CALL NPROMIZE (NPROMA, PRHODJ,     PRHODJ_B)
CALL NPROMIZE (NPROMA, PRHODREF,   PRHODREF_B)
CALL NPROMIZE (NPROMA, PPABSM,     PPABSM_B)
CALL NPROMIZE (NPROMA, PCIT,       PCIT_B)
CALL NPROMIZE (NPROMA, PCLDFR,     PCLDFR_B)
CALL NPROMIZE (NPROMA, PICLDFR,    PICLDFR_B)
CALL NPROMIZE (NPROMA, PTHT,       PTHT_B)
CALL NPROMIZE (NPROMA, PRT,        PRT_B)
CALL NPROMIZE (NPROMA, PTHS,       PTHS_B)
CALL NPROMIZE (NPROMA, PRS,        PRS_B)
CALL NPROMIZE (NPROMA, PSIGS,      PSIGS_B)
CALL NPROMIZE (NPROMA, PSEA,       PSEA_B)
CALL NPROMIZE (NPROMA, PTOWN,      PTOWN_B)
CALL NPROMIZE (NPROMA, PCIT_OUT,   PCIT_OUT_B)
CALL NPROMIZE (NPROMA, PRS_OUT,    PRS_OUT_B)
CALL NPROMIZE (NPROMA, ZINPRC_OUT, ZINPRC_OUT_B)
CALL NPROMIZE (NPROMA, PINPRR_OUT, PINPRR_OUT_B)
CALL NPROMIZE (NPROMA, PEVAP_OUT,  PEVAP_OUT_B)
CALL NPROMIZE (NPROMA, PINPRS_OUT, PINPRS_OUT_B)
CALL NPROMIZE (NPROMA, PINPRG_OUT, PINPRG_OUT_B)
CALL NPROMIZE (NPROMA, PFPR_OUT,   PFPR_OUT_B)


END SUBROUTINE

SUBROUTINE REPLICATE1 (KOFF, P)

INTEGER :: KOFF
REAL    :: P (:)

INTEGER :: I, J

DO I = KOFF+1, SIZE (P, 1)
  J = 1 + MODULO (I - 1, KOFF)
  P (I) = P (J)
ENDDO

END SUBROUTINE

SUBROUTINE REPLICATE2 (KOFF, P)

INTEGER :: KOFF
REAL    :: P (:,:)

INTEGER :: I, J

DO I = KOFF+1, SIZE (P, 1)
  J = 1 + MODULO (I - 1, KOFF)
  P (I, :) = P (J, :)
ENDDO

END SUBROUTINE

SUBROUTINE REPLICATE3 (KOFF, P)

INTEGER :: KOFF
REAL    :: P (:,:,:)

INTEGER :: I, J

DO I = KOFF+1, SIZE (P, 1)
  J = 1 + MODULO (I - 1, KOFF)
  P (I, :, :) = P (J, :, :)
ENDDO

END SUBROUTINE

SUBROUTINE REPLICATE4 (KOFF, P)

INTEGER :: KOFF
REAL    :: P (:,:,:,:)

INTEGER :: I, J

DO I = KOFF+1, SIZE (P, 1)
  J = 1 + MODULO (I - 1, KOFF)
  P (I, :, :, :) = P (J, :, :, :)
ENDDO

END SUBROUTINE

SUBROUTINE REPLICATEL (KOFF, L)

INTEGER :: KOFF
LOGICAL :: L(:,:)

INTEGER :: I, J

DO I = KOFF+1, SIZE (L, 1)
  J = 1 + MODULO (I - 1, KOFF)
  L (I, :) = L (J, :)
ENDDO

END SUBROUTINE

SUBROUTINE NPROMIZE2 (KPROMA, PI, PO)

INTEGER :: KPROMA
REAL, INTENT (IN)  :: PI (:,:)
REAL, INTENT (OUT) :: PO (:,:)

INTEGER :: I, J, IGPBLK, IGPTOT, IGP, JLON, JIDIA, JFDIA

IF (SIZE (PI, 2) /= 1) STOP 1

IGPTOT = SIZE (PI, 1)
IGPBLK = 1 + (IGPTOT-1) / KPROMA

DO IGP = 1, IGPTOT, KPROMA
  IBL = 1 + (IGP - 1) / KPROMA
  JIDIA = 1
  JFDIA = MIN (KPROMA, IGPTOT - (IBL - 1) * KPROMA)

  DO JLON = JIDIA, JFDIA
    PO (JLON, IBL) = PI (IGP + (JLON - 1), 1)
  ENDDO

  DO JLON = JFDIA+1, KPROMA
    PO (JLON, IBL) = PO (JFDIA, IBL)
  ENDDO

ENDDO

END SUBROUTINE

SUBROUTINE NPROMIZE3 (KPROMA, PI, PO)

INTEGER :: KPROMA
REAL, INTENT (IN)  :: PI (:,:,:)
REAL, INTENT (OUT) :: PO (:,:,:)

INTEGER :: I, J, IGPBLK, IGPTOT, IGP, JLON, JIDIA, JFDIA

IF (SIZE (PI, 3) /= 1) STOP 1

IGPTOT = SIZE (PI, 1)
IGPBLK = 1 + (IGPTOT-1) / KPROMA

DO IGP = 1, IGPTOT, KPROMA
  IBL = 1 + (IGP - 1) / KPROMA
  JIDIA = 1
  JFDIA = MIN (KPROMA, IGPTOT - (IBL - 1) * KPROMA)

  DO JLON = JIDIA, JFDIA
    PO (JLON, :, IBL) = PI (IGP + (JLON - 1), :, 1)
  ENDDO

  DO JLON = JFDIA+1, KPROMA
    PO (JLON, :, IBL) = PO (JFDIA, :, IBL)
  ENDDO

ENDDO

END SUBROUTINE

SUBROUTINE NPROMIZE4 (KPROMA, PI, PO)

INTEGER :: KPROMA
REAL, INTENT (IN)  :: PI (:,:,:,:)
REAL, INTENT (OUT) :: PO (:,:,:,:)

INTEGER :: I, J, IGPBLK, IGPTOT, IGP, JLON, JIDIA, JFDIA

IF (SIZE (PI, 4) /= 1) STOP 1

IGPTOT = SIZE (PI, 1)
IGPBLK = 1 + (IGPTOT-1) / KPROMA

DO IGP = 1, IGPTOT, KPROMA
  IBL = 1 + (IGP - 1) / KPROMA
  JIDIA = 1
  JFDIA = MIN (KPROMA, IGPTOT - (IBL - 1) * KPROMA)

  DO JLON = JIDIA, JFDIA
    PO (JLON, :, :, IBL) = PI (IGP + (JLON - 1), :, :, 1)
  ENDDO

  DO JLON = JFDIA+1, KPROMA
    PO (JLON, :, :, IBL) = PO (JFDIA, :, :, IBL)
  ENDDO

ENDDO

END SUBROUTINE

SUBROUTINE NPROMIZE5 (KPROMA, PI, PO)

INTEGER :: KPROMA
REAL, INTENT (IN)  :: PI (:,:,:,:,:)
REAL, INTENT (OUT) :: PO (:,:,:,:,:)

INTEGER :: I, J, IGPBLK, IGPTOT, IGP, JLON, JIDIA, JFDIA

IF (SIZE (PI, 5) /= 1) STOP 1

IGPTOT = SIZE (PI, 1)
IGPBLK = 1 + (IGPTOT-1) / KPROMA

DO IGP = 1, IGPTOT, KPROMA
  IBL = 1 + (IGP - 1) / KPROMA
  JIDIA = 1
  JFDIA = MIN (KPROMA, IGPTOT - (IBL - 1) * KPROMA)

  DO JLON = JIDIA, JFDIA
    PO (JLON, :, :, :, IBL) = PI (IGP + (JLON - 1), :, :, :, 1)
  ENDDO

  DO JLON = JFDIA+1, KPROMA
    PO (JLON, :, :, :, IBL) = PI (JFDIA, :, :, :, IBL)
  ENDDO

ENDDO

END SUBROUTINE

SUBROUTINE NPROMIZEL (KPROMA, LI, LO)

INTEGER :: KPROMA
LOGICAL, INTENT(IN)  :: LI(:,:,:)
LOGICAL, INTENT(OUT) :: LO(:,:,:)

INTEGER :: I, J, IGPBLK, IGPTOT, IGP, JLON, JIDIA, JFDIA

IF (SIZE (LI, 3) /= 1) STOP 1

IGPTOT = SIZE (LI, 1)
IGPBLK = 1 + (IGPTOT-1) / KPROMA

DO IGP = 1, IGPTOT, KPROMA
  IBL = 1 + (IGP - 1) / KPROMA
  JIDIA = 1
  JFDIA = MIN (KPROMA, IGPTOT - (IBL - 1) * KPROMA)

  DO JLON = JIDIA, JFDIA
    LO(JLON, :, IBL) = LI(IGP + (JLON - 1), :, 1)
  ENDDO

  DO JLON = JFDIA+1, KPROMA
    LO(JLON, :, IBL) = LI(JFDIA, :, IBL)
  ENDDO

ENDDO

END SUBROUTINE

SUBROUTINE INTERPOLATEX (KLON, KLEV, KBLOCKS, IBLOCKS, KFLEVG, P)

IMPLICIT NONE

INTEGER, INTENT(IN) :: KLON, KLEV, KBLOCKS, IBLOCKS, KFLEVG

REAL, ALLOCATABLE, DIMENSION(:, :, :) :: P
REAL, DIMENSION(KLON, KLEV, KBLOCKS) :: Z

INTEGER :: I, J, K

INTEGER :: ILEV1A, ILEV1B
REAL :: ZWA, ZWB, ZLEV

Z = P

DEALLOCATE (P)

ALLOCATE (P(KLON, KFLEVG, KBLOCKS))

DO I = 1, KFLEVG
  ZLEV = 1. + REAL(I-1)*REAL(KLEV-1)/REAL(KFLEVG-1)
  ILEV1B = MIN (CEILING (ZLEV), KLEV)
  ILEV1A = MAX (FLOOR   (ZLEV),    1)

  IF (ILEV1A == ILEV1B) THEN
    ZWA = 1.
    ZWB = 0.
  ELSE
    ZWA = REAL(ILEV1B) - ZLEV
    ZWB = ZLEV - REAL(ILEV1A)
  ENDIF

  DO J = 1, IBLOCKS
    P(:, I, J) = ZWA * Z(:, I, J) + ZWB * Z(:, I, J)
  ENDDO
ENDDO

END SUBROUTINE

SUBROUTINE INTERPOLATE2 (KFLEVG, KOFF, P)

INTEGER :: KFLEVG, KOFF
REAL, ALLOCATABLE :: P (:,:)
REAL :: Z (LBOUND (P, 1):UBOUND (P, 1), &
         & LBOUND (P, 2):UBOUND (P, 2))
INTEGER :: ILEV1A, ILEV1B, ILEV2, NLEV1, NLEV2
REAL :: ZWA, ZWB, ZLEV1, ZLEV2

Z = P

NLEV1 = SIZE (P, 2)
NLEV2 = KFLEVG

DEALLOCATE (P)

ALLOCATE (P (LBOUND (Z, 1):UBOUND (Z, 1), &
           & KFLEVG))

DO ILEV2 = 1, NLEV2
  ZLEV2 = REAL (ILEV2 - 1) / REAL (NLEV2 -1)
  ZLEV1 = 1. + ZLEV2 * REAL (NLEV1 - 1)
  ILEV1B = MIN (CEILING (ZLEV1), NLEV1)
  ILEV1A = MAX (FLOOR   (ZLEV1),     1)

  IF (ILEV1A == ILEV1B) THEN
    ZWA = 1.
    ZWB = 0.
  ELSE
    ZWA = REAL (ILEV1B) - ZLEV1
    ZWB = ZLEV1 - REAL (ILEV1A)
  ENDIF

  P(1:KOFF, ILEV2) = ZWA * Z(1:KOFF, ILEV1A) + ZWB * Z(1:KOFF, ILEV1B)
ENDDO

END SUBROUTINE

SUBROUTINE INTERPOLATE3 (KFLEVG, KOFF, P)

INTEGER :: KFLEVG, KOFF
REAL, ALLOCATABLE :: P (:,:,:)
REAL :: Z (LBOUND (P, 1):UBOUND (P, 1), &
         & LBOUND (P, 2):UBOUND (P, 2), &
         & LBOUND (P, 3):UBOUND (P, 3))
INTEGER :: ILEV1A, ILEV1B, ILEV2, NLEV1, NLEV2
REAL :: ZWA, ZWB, ZLEV1, ZLEV2

Z = P

NLEV1 = SIZE (P, 2)
NLEV2 = KFLEVG

DEALLOCATE (P)

ALLOCATE (P (LBOUND (Z, 1):UBOUND (Z, 1), &
           & KFLEVG, &
           & LBOUND (Z, 3):UBOUND (Z, 3)))

DO ILEV2 = 1, NLEV2
  ZLEV2 = REAL (ILEV2 - 1) / REAL (NLEV2 -1)
  ZLEV1 = 1. + ZLEV2 * REAL (NLEV1 - 1)
  ILEV1B = MIN (CEILING (ZLEV1), NLEV1)
  ILEV1A = MAX (FLOOR   (ZLEV1),     1)

  IF (ILEV1A == ILEV1B) THEN
    ZWA = 1.
    ZWB = 0.
  ELSE
    ZWA = REAL (ILEV1B) - ZLEV1
    ZWB = ZLEV1 - REAL (ILEV1A)
  ENDIF

  P(1:KOFF, ILEV2, :) = ZWA * Z(1:KOFF, ILEV1A, :) + ZWB * Z(1:KOFF, ILEV1B, :)
ENDDO

END SUBROUTINE

SUBROUTINE INTERPOLATE4 (KFLEVG, KOFF, P)

INTEGER :: KFLEVG, KOFF
REAL, ALLOCATABLE :: P (:,:,:,:)
REAL :: Z (LBOUND (P, 1):UBOUND (P, 1), &
         & LBOUND (P, 2):UBOUND (P, 2), &
         & LBOUND (P, 3):UBOUND (P, 3), &
         & LBOUND (P, 4):UBOUND (P, 4))
INTEGER :: ILEV1A, ILEV1B, ILEV2, NLEV1, NLEV2
REAL :: ZWA, ZWB, ZLEV1, ZLEV2

Z = P

NLEV1 = SIZE (P, 3)
NLEV2 = KFLEVG

DEALLOCATE (P)

ALLOCATE (P (LBOUND (Z, 1):UBOUND (Z, 1), &
           & LBOUND (Z, 2):UBOUND (Z, 2), &
           & KFLEVG, &
           & LBOUND (Z, 4):UBOUND (Z, 4)))

DO ILEV2 = 1, NLEV2
  ZLEV2 = REAL (ILEV2 - 1) / REAL (NLEV2 -1)
  ZLEV1 = 1. + ZLEV2 * REAL (NLEV1 - 1)
  ILEV1B = MIN (CEILING (ZLEV1), NLEV1)
  ILEV1A = MAX (FLOOR   (ZLEV1),     1)

  IF (ILEV1A == ILEV1B) THEN
    ZWA = 1.
    ZWB = 0.
  ELSE
    ZWA = REAL (ILEV1B) - ZLEV1
    ZWB = ZLEV1 - REAL (ILEV1A)
  ENDIF

  P (1:KOFF, :, ILEV2, :) = ZWA * Z (1:KOFF, :, ILEV1A, :) + ZWB * Z (1:KOFF, :, ILEV1B, :)
ENDDO

END SUBROUTINE

SUBROUTINE INTERPOLATE5 (KFLEVG, KOFF, P)

INTEGER :: KFLEVG, KOFF
REAL, ALLOCATABLE :: P (:,:,:,:,:)
REAL :: Z (LBOUND (P, 1):UBOUND (P, 1), &
         & LBOUND (P, 2):UBOUND (P, 2), &
         & LBOUND (P, 3):UBOUND (P, 3), &
         & LBOUND (P, 4):UBOUND (P, 4), &
         & LBOUND (P, 5):UBOUND (P, 5))
INTEGER :: ILEV1A, ILEV1B, ILEV2, NLEV1, NLEV2
REAL :: ZWA, ZWB, ZLEV1, ZLEV2

Z = P

NLEV1 = SIZE (P, 3)
NLEV2 = KFLEVG

DEALLOCATE (P)

ALLOCATE (P (LBOUND (Z, 1):UBOUND (Z, 1), &
           & LBOUND (Z, 2):UBOUND (Z, 2), &
           & KFLEVG, &
           & LBOUND (Z, 4):UBOUND (Z, 4), &
           & LBOUND (Z, 5):UBOUND (Z, 5)))

DO ILEV2 = 1, NLEV2
  ZLEV2 = REAL (ILEV2 - 1) / REAL (NLEV2 -1)
  ZLEV1 = 1. + ZLEV2 * REAL (NLEV1 - 1)
  ILEV1B = MIN (CEILING (ZLEV1), NLEV1)
  ILEV1A = MAX (FLOOR   (ZLEV1),     1)

  IF (ILEV1A == ILEV1B) THEN
    ZWA = 1.
    ZWB = 0.
  ELSE
    ZWA = REAL (ILEV1B) - ZLEV1
    ZWB = ZLEV1 - REAL (ILEV1A)
  ENDIF

  P (1:KOFF, :, ILEV2, :, :) = ZWA * Z (1:KOFF, :, ILEV1A, :, :) + ZWB * Z (1:KOFF, :, ILEV1B, :, :)
ENDDO

END SUBROUTINE

SUBROUTINE INTERPOLATEL (KFLEVG, KOFF, L)

INTEGER :: KFLEVG, KOFF
LOGICAL, ALLOCATABLE :: L(:,:,:)
LOGICAL :: Z (LBOUND (L, 1):UBOUND (L, 1), &
              LBOUND (L, 2):UBOUND (L, 2), &
              LBOUND (L, 3):UBOUND (L, 3))
INTEGER :: ILEV1A, ILEV1B, ILEV2, NLEV1, NLEV2
REAL :: ZWA, ZWB, ZLEV1, ZLEV2

Z = L

NLEV1 = SIZE (L, 3)
NLEV2 = KFLEVG

DEALLOCATE (L)

ALLOCATE (L (LBOUND (Z, 1):UBOUND (Z, 1), &
           & KFLEVG, &
           & LBOUND (Z, 3):UBOUND (Z, 3)))

DO ILEV2 = 1, NLEV2
  ZLEV2 = REAL (ILEV2 - 1) / REAL (NLEV2 -1)
  ZLEV1 = 1. + ZLEV2 * REAL (NLEV1 - 1)
  ILEV1B = MIN (CEILING (ZLEV1), NLEV1)
  ILEV1A = MAX (FLOOR   (ZLEV1),     1)

  IF (ILEV1A == ILEV1B) THEN
    ZWA = 1.
    ZWB = 0.
  ELSE
    ZWA = REAL (ILEV1B) - ZLEV1
    ZWB = ZLEV1 - REAL (ILEV1A)
  ENDIF

  L(1:KOFF, ILEV2, :) = ZWA * MERGE(1., 0., Z(1:KOFF, ILEV1A, :)) + ZWB * MERGE(1., 0., Z (1:KOFF, ILEV1B, :)) >= 0.5
ENDDO

END SUBROUTINE


SUBROUTINE SET2(P)

  REAL :: P (:,:)
  INTEGER :: IBL, IGPBLKS
  INTEGER :: NTID, ITID, JBLK1, JBLK2

  IGPBLKS = SIZE (P, 2)

!$OMP PARALLEL PRIVATE (ITID, JBLK1, JBLK2, NTID)
  NTID = OMP_GET_MAX_THREADS ()
  ITID = OMP_GET_THREAD_NUM ()
  JBLK1 = 1 +  (IGPBLKS * (ITID+0)) / NTID
  JBLK2 =      (IGPBLKS * (ITID+1)) / NTID

  DO IBL = JBLK1, JBLK2
    P (:,IBL) = ZNAN
  ENDDO
!$OMP END PARALLEL

END SUBROUTINE

SUBROUTINE SET3 (P)

  REAL :: P (:,:,:)
  INTEGER :: IBL, IGPBLKS
  INTEGER :: NTID, ITID, JBLK1, JBLK2
  
  IGPBLKS = SIZE (P, 3)
  
!$OMP PARALLEL PRIVATE (ITID, JBLK1, JBLK2, NTID)
  NTID = OMP_GET_MAX_THREADS ()
  ITID = OMP_GET_THREAD_NUM ()
  JBLK1 = 1 +  (IGPBLKS * (ITID+0)) / NTID
  JBLK2 =      (IGPBLKS * (ITID+1)) / NTID
  
  DO IBL = JBLK1, JBLK2
    P (:,:,IBL) = ZNAN
  ENDDO
!$OMP END PARALLEL

END SUBROUTINE

SUBROUTINE SET4 (P)

  REAL :: P (:,:,:,:)
  INTEGER :: IBL, IGPBLKS
  INTEGER :: NTID, ITID, JBLK1, JBLK2

  IGPBLKS = SIZE (P, 4)

!$OMP PARALLEL PRIVATE (ITID, JBLK1, JBLK2, NTID)
  NTID = OMP_GET_MAX_THREADS ()
  ITID = OMP_GET_THREAD_NUM ()
  JBLK1 = 1 +  (IGPBLKS * (ITID+0)) / NTID
  JBLK2 =      (IGPBLKS * (ITID+1)) / NTID

  DO IBL = JBLK1, JBLK2
    P (:,:,:,IBL) = ZNAN
  ENDDO
!$OMP END PARALLEL

END SUBROUTINE

END  MODULE
