!     ######spl
        MODULE MODI_INI_CMFSHALL
!       #####################
!
INTERFACE
!
SUBROUTINE INI_CMFSHALL(PALP_PERT,PABUO,PBENTR,PBDETR,PCMF,PENTR_MF,PCRAD_MF,PENTR_DRY,&
 &          PDETR_DRY,PDETR_LUP,PKCF_MF,PKRC_MF,PTAUSIGMF,PPRES_UV,PFRAC_UP_MAX,&
 &          PALPHA_MF,PSIGMA_MF,PA1,PB,PC,PBETA1,PR,PLAMBDA)
!
REAL,   INTENT(IN)   :: PALP_PERT
REAL,   INTENT(IN)   :: PABUO
REAL,   INTENT(IN)   :: PBENTR
REAL,   INTENT(IN)   :: PBDETR
REAL,   INTENT(IN)   :: PCMF
REAL,   INTENT(IN)   :: PENTR_MF
REAL,   INTENT(IN)   :: PCRAD_MF
REAL,   INTENT(IN)   :: PENTR_DRY
REAL,   INTENT(IN)   :: PDETR_DRY
REAL,   INTENT(IN)   :: PDETR_LUP
REAL,   INTENT(IN)   :: PKCF_MF
REAL,   INTENT(IN)   :: PKRC_MF
REAL,   INTENT(IN)   :: PTAUSIGMF
REAL,   INTENT(IN)   :: PPRES_UV
REAL,   INTENT(IN)   :: PFRAC_UP_MAX
REAL,   INTENT(IN)   :: PALPHA_MF
REAL,   INTENT(IN)   :: PSIGMA_MF
REAL,   INTENT(IN)   :: PA1
REAL,   INTENT(IN)   :: PB
REAL,   INTENT(IN)   :: PC
REAL,   INTENT(IN)   :: PBETA1   
REAL,   INTENT(IN)   :: PR   
REAL,   INTENT(IN)   :: PLAMBDA   

END SUBROUTINE INI_CMFSHALL

END INTERFACE
!
END MODULE MODI_INI_CMFSHALL
