!     ######spl
      MODULE MODI_COMPUTE_FRAC_ICE1D
!     ############################## 

INTERFACE 
!
    SUBROUTINE COMPUTE_FRAC_ICE1D(HFRAC_ICE,PFRAC_ICE,PT)
!
CHARACTER*1       , INTENT(IN)    :: HFRAC_ICE
REAL, DIMENSION(:), INTENT(IN)    :: PT
REAL, DIMENSION(:), INTENT(INOUT) :: PFRAC_ICE
!
   END SUBROUTINE COMPUTE_FRAC_ICE1D
END INTERFACE
END MODULE MODI_COMPUTE_FRAC_ICE1D
