!     ######spl
      MODULE MODI_COMPUTE_FRAC_ICE3D  
!     ############################## 

INTERFACE 
!
    SUBROUTINE COMPUTE_FRAC_ICE3D(HFRAC_ICE,PFRAC_ICE,PT)
!
CHARACTER*1           , INTENT(IN) :: HFRAC_ICE
REAL, DIMENSION(:,:,:), INTENT(IN) :: PT
REAL, DIMENSION(:,:,:), INTENT(INOUT) :: PFRAC_ICE                                             
!
   END SUBROUTINE COMPUTE_FRAC_ICE3D
END INTERFACE
END MODULE MODI_COMPUTE_FRAC_ICE3D
