MODULE MODE_INI_TIWMX
IMPLICIT NONE
CONTAINS
SUBROUTINE INI_TIWMX
! Include function definitions
  USE MODE_TIWMX_FUN, ONLY : ESATW,DESDTW,ESATI,DESDTI,AA2,AA2W,AM3,AF3,BB3,BB3W,REDIN
! Only the tables, _NOT_ the functions!
  USE MODD_TIWMX, ONLY : TIWMX, XNDEGR, NSTART, NSTOP
  USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK
  IMPLICIT NONE

  INTEGER :: JK
  REAL :: ZTEMP

  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('INI_TIWMX',0,ZHOOK_HANDLE)

  DO JK=NSTART,NSTOP
     ZTEMP = REAL(JK)/XNDEGR

     TIWMX%ESTABW(JK) = ESATW(ZTEMP)
     TIWMX%DESTABW(JK) = DESDTW(ZTEMP)

     TIWMX%ESTABI(JK) = ESATI(ZTEMP)
     TIWMX%DESTABI(JK) = DESDTI(ZTEMP)

!    Functions for ice crystals or water droplets:
     TIWMX%A2TAB(JK) = AA2(ZTEMP)
     TIWMX%A2WTAB(JK) = AA2W(ZTEMP)
     TIWMX%AM3TAB(JK) = AM3(ZTEMP)
     TIWMX%AF3TAB(JK) = AF3(ZTEMP)
     TIWMX%BB3TAB(JK) = BB3(ZTEMP)
     TIWMX%BB3WTAB(JK) = BB3W(ZTEMP)
     TIWMX%REDINTAB(JK) = REDIN(ZTEMP)

     IF (ZTEMP.GT.273.15) THEN
!       Avoid ice calculation above freezing level:
        TIWMX%ESTABI(JK) = ESATW(ZTEMP)
        TIWMX%DESTABI(JK) = DESDTW(ZTEMP)

!       Functions for ice crystal growth:  
        TIWMX%A2TAB(JK) = AA2(ZTEMP)
        TIWMX%A2WTAB(JK) = AA2W(ZTEMP)
        TIWMX%AM3TAB(JK) = 0.
        TIWMX%AF3TAB(JK) = 0.
        TIWMX%BB3TAB(JK) = BB3(ZTEMP)
        TIWMX%BB3WTAB(JK) = BB3W(ZTEMP)
     ENDIF
  END DO

  IF (LHOOK) CALL DR_HOOK('INI_TIWMX',1,ZHOOK_HANDLE)

END SUBROUTINE INI_TIWMX
END MODULE MODE_INI_TIWMX
