!@no_insert_drhook
!     ######spl
      MODULE MODE_TIWMX
!     ###############
!
!!****  *MODE_TIWMX* - 
!!
!!    PURPOSE
!!    -------
!       The purpose of this  ...
!
!!
!!    REFERENCE
!!    ---------
!!      Book2 of documentation of Meso-NH (ha ha)
!!          
!!    AUTHOR
!!    ------
!!      K. I. Ivarsson   *SMHI*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    20/11/14  
!-------------------------------------------------------------------------------
!
!*       0.   DECLARATIONS
!             ------------
!
USE MODD_TIWMX, ONLY: XNDEGR
IMPLICIT NONE

CONTAINS

  REAL FUNCTION ESATW(ICEP, TT)
    USE MODD_RAIN_ICE_PARAM_n, ONLY: RAIN_ICE_PARAM_t
    TYPE(RAIN_ICE_PARAM_t),   INTENT(IN)    :: ICEP
    REAL,INTENT(IN) :: TT 
    ESATW = ICEP%TIWMX%ESTABW(NINT(XNDEGR*TT))
  END FUNCTION ESATW

  REAL FUNCTION DESDTW(ICEP, TT)
    USE MODD_RAIN_ICE_PARAM_n, ONLY: RAIN_ICE_PARAM_t
    TYPE(RAIN_ICE_PARAM_t),   INTENT(IN)    :: ICEP
    REAL,INTENT(IN) :: TT 
    DESDTW = ICEP%TIWMX%DESTABW(NINT(XNDEGR*TT))
  END FUNCTION

  REAL FUNCTION ESATI(ICEP, TT)
    USE MODD_RAIN_ICE_PARAM_n, ONLY: RAIN_ICE_PARAM_t
    TYPE(RAIN_ICE_PARAM_t),   INTENT(IN)    :: ICEP
    REAL,INTENT(IN) :: TT 
    ESATI = ICEP%TIWMX%ESTABI(NINT(XNDEGR*TT))
  END FUNCTION

  REAL FUNCTION DESDTI(ICEP, TT)
    USE MODD_RAIN_ICE_PARAM_n, ONLY: RAIN_ICE_PARAM_t
    TYPE(RAIN_ICE_PARAM_t),   INTENT(IN)    :: ICEP
    REAL,INTENT(IN) :: TT 
    DESDTI = ICEP%TIWMX%DESTABI(NINT(XNDEGR*TT))
  END FUNCTION

! Water droplet function:
  REAL FUNCTION AA2W(ICEP, TT)
    USE MODD_RAIN_ICE_PARAM_n, ONLY: RAIN_ICE_PARAM_t
    TYPE(RAIN_ICE_PARAM_t),   INTENT(IN)    :: ICEP
    REAL,INTENT(IN) :: TT 
    AA2W = ICEP%TIWMX%A2WTAB(NINT(XNDEGR*TT))
  END FUNCTION

! Ice crystal function
  REAL FUNCTION AA2(ICEP, TT)
    USE MODD_RAIN_ICE_PARAM_n, ONLY: RAIN_ICE_PARAM_t
    TYPE(RAIN_ICE_PARAM_t),   INTENT(IN)    :: ICEP
    REAL,INTENT(IN) :: TT 
    AA2 = ICEP%TIWMX%A2TAB(NINT(XNDEGR*TT))
  END FUNCTION

! Meyers IN concentration function:
  REAL FUNCTION AM3(ICEP, TT)
    USE MODD_RAIN_ICE_PARAM_n, ONLY: RAIN_ICE_PARAM_t
    TYPE(RAIN_ICE_PARAM_t),   INTENT(IN)    :: ICEP
    REAL,INTENT(IN) :: TT 
    AM3 = ICEP%TIWMX%AM3TAB(NINT(XNDEGR*TT))
  END FUNCTION

! Fletchers IN concentration function:
  REAL FUNCTION AF3(ICEP, TT)
    USE MODD_RAIN_ICE_PARAM_n, ONLY: RAIN_ICE_PARAM_t
    TYPE(RAIN_ICE_PARAM_t),   INTENT(IN)    :: ICEP
    REAL,INTENT(IN) :: TT 
    AF3 = ICEP%TIWMX%AF3TAB(NINT(XNDEGR*TT))
  END FUNCTION

! Ice crystal function
  REAL FUNCTION BB3(ICEP, TT)
    USE MODD_RAIN_ICE_PARAM_n, ONLY: RAIN_ICE_PARAM_t
    TYPE(RAIN_ICE_PARAM_t),   INTENT(IN)    :: ICEP
    REAL,INTENT(IN) :: TT 
    BB3 = ICEP%TIWMX%BB3TAB(NINT(XNDEGR*TT))
  END FUNCTION

! Water droplet function:
  REAL FUNCTION BB3W(ICEP, TT)
    USE MODD_RAIN_ICE_PARAM_n, ONLY: RAIN_ICE_PARAM_t
    TYPE(RAIN_ICE_PARAM_t),   INTENT(IN)    :: ICEP
    REAL,INTENT(IN) :: TT 
    BB3W = ICEP%TIWMX%BB3WTAB(NINT(XNDEGR*TT))
  END FUNCTION

! Function for IN concentration reduction between 0 and -25 C:
  REAL FUNCTION REDIN(ICEP, TT)
    USE MODD_RAIN_ICE_PARAM_n, ONLY: RAIN_ICE_PARAM_t
    TYPE(RAIN_ICE_PARAM_t),   INTENT(IN)    :: ICEP
    REAL,INTENT(IN) :: TT 
    REDIN = ICEP%TIWMX%REDINTAB(NINT(XNDEGR*TT))
  END FUNCTION
END MODULE MODE_TIWMX
