MODULE MODI_MINPACK
!Automatically generated by PyForTool
IMPLICIT NONE
INTERFACE
subroutine chkder ( m, n, x, fvec, fjac, ldfjac, xp, fvecp, mode, err )

IMPLICIT NONE
integer ( kind = 4 ) :: LDFJAC
integer ( kind = 4 ) :: M
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(m) :: ERR
real ( kind = 8 ), DIMENSION(ldfjac, n) :: FJAC
real ( kind = 8 ), DIMENSION(m) :: FVEC
real ( kind = 8 ), DIMENSION(m) :: FVECP
integer ( kind = 4 ) :: MODE
real ( kind = 8 ), DIMENSION(n) :: X
real ( kind = 8 ), DIMENSION(n) :: XP
end
subroutine dogleg ( n, r, lr, diag, qtb, delta, x )

IMPLICIT NONE
integer ( kind = 4 ) :: LR
integer ( kind = 4 ) :: N
real ( kind = 8 ) :: DELTA
real ( kind = 8 ), DIMENSION(n) :: DIAG
real ( kind = 8 ), DIMENSION(n) :: QTB
real ( kind = 8 ), DIMENSION(lr) :: R
real ( kind = 8 ), DIMENSION(n) :: X
end
function enorm ( n, x )

IMPLICIT NONE
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(n) :: X
real ( kind = 8 ) :: ENORM
end
function enorm2 ( n, x )

IMPLICIT NONE
integer ( kind = 4 ) :: N
real ( kind = 8 ) :: ENORM2
real ( kind = 8 ), DIMENSION(n) :: X
end
subroutine fdjac1 ( fcn, n, x, fvec, fjac, ldfjac, iflag, ml, mu, epsfcn )

IMPLICIT NONE
integer ( kind = 4 ) :: LDFJAC
integer ( kind = 4 ) :: N
real ( kind = 8 ) :: EPSFCN
real ( kind = 8 ), DIMENSION(ldfjac, n) :: FJAC
real ( kind = 8 ), DIMENSION(n) :: FVEC
integer ( kind = 4 ) :: IFLAG
integer ( kind = 4 ) :: ML
integer ( kind = 4 ) :: MU
real ( kind = 8 ), DIMENSION(n) :: X
external fcn
  end
subroutine fdjac2 ( fcn, m, n, x, fvec, fjac, ldfjac, iflag, epsfcn )

IMPLICIT NONE
integer ( kind = 4 ) :: LDFJAC
integer ( kind = 4 ) :: M
integer ( kind = 4 ) :: N
real ( kind = 8 ) :: EPSFCN
real ( kind = 8 ), DIMENSION(ldfjac, n) :: FJAC
real ( kind = 8 ), DIMENSION(m) :: FVEC
integer ( kind = 4 ) :: IFLAG
real ( kind = 8 ), DIMENSION(n) :: X
external fcn
  end
subroutine hybrd ( fcn, n, x, fvec, xtol, maxfev, ml, mu, epsfcn, diag, mode, &
  factor, nprint, info, nfev, fjac, ldfjac, r, lr, qtf )

IMPLICIT NONE
integer ( kind = 4 ) :: LDFJAC
integer ( kind = 4 ) :: LR
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(n) :: DIAG
real ( kind = 8 ) :: EPSFCN
real ( kind = 8 ) :: FACTOR
real ( kind = 8 ), DIMENSION(ldfjac, n) :: FJAC
real ( kind = 8 ), DIMENSION(n) :: FVEC
integer ( kind = 4 ) :: INFO
integer ( kind = 4 ) :: MAXFEV
integer ( kind = 4 ) :: ML
integer ( kind = 4 ) :: MODE
integer ( kind = 4 ) :: MU
integer ( kind = 4 ) :: NFEV
integer ( kind = 4 ) :: NPRINT
real ( kind = 8 ), DIMENSION(n) :: QTF
real ( kind = 8 ), DIMENSION(lr) :: R
real ( kind = 8 ), DIMENSION(n) :: X
real ( kind = 8 ) :: XTOL
external fcn
  end
subroutine hybrd1 ( fcn, n, x, fvec, tol, info )

IMPLICIT NONE
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(n) :: FVEC
integer ( kind = 4 ) :: INFO
real ( kind = 8 ) :: TOL
real ( kind = 8 ), DIMENSION(n) :: X
external fcn
  end
subroutine hybrj ( fcn, n, x, fvec, fjac, ldfjac, xtol, maxfev, diag, mode, &
  factor, nprint, info, nfev, njev, r, lr, qtf )

IMPLICIT NONE
integer ( kind = 4 ) :: LDFJAC
integer ( kind = 4 ) :: LR
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(n) :: DIAG
real ( kind = 8 ) :: FACTOR
real ( kind = 8 ), DIMENSION(ldfjac, n) :: FJAC
real ( kind = 8 ), DIMENSION(n) :: FVEC
integer ( kind = 4 ) :: INFO
integer ( kind = 4 ) :: MAXFEV
integer ( kind = 4 ) :: MODE
integer ( kind = 4 ) :: NFEV
integer ( kind = 4 ) :: NJEV
integer ( kind = 4 ) :: NPRINT
real ( kind = 8 ), DIMENSION(n) :: QTF
real ( kind = 8 ), DIMENSION(lr) :: R
real ( kind = 8 ), DIMENSION(n) :: X
real ( kind = 8 ) :: XTOL
external fcn
  end
subroutine hybrj1 ( fcn, n, x, fvec, fjac, ldfjac, tol, info )

IMPLICIT NONE
integer ( kind = 4 ) :: LDFJAC
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(ldfjac, n) :: FJAC
real ( kind = 8 ), DIMENSION(n) :: FVEC
integer ( kind = 4 ) :: INFO
real ( kind = 8 ) :: TOL
real ( kind = 8 ), DIMENSION(n) :: X
external fcn
  end
subroutine lmder ( fcn, m, n, x, fvec, fjac, ldfjac, ftol, xtol, gtol, maxfev, &
  diag, mode, factor, nprint, info, nfev, njev, ipvt, qtf )

IMPLICIT NONE
integer ( kind = 4 ) :: LDFJAC
integer ( kind = 4 ) :: M
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(n) :: DIAG
real ( kind = 8 ) :: FACTOR
real ( kind = 8 ), DIMENSION(ldfjac, n) :: FJAC
real ( kind = 8 ) :: FTOL
real ( kind = 8 ), DIMENSION(m) :: FVEC
real ( kind = 8 ) :: GTOL
integer ( kind = 4 ) :: INFO
integer ( kind = 4 ), DIMENSION(n) :: IPVT
integer ( kind = 4 ) :: MAXFEV
integer ( kind = 4 ) :: MODE
integer ( kind = 4 ) :: NFEV
integer ( kind = 4 ) :: NJEV
integer ( kind = 4 ) :: NPRINT
real ( kind = 8 ), DIMENSION(n) :: QTF
real ( kind = 8 ), DIMENSION(n) :: X
real ( kind = 8 ) :: XTOL
external fcn
  end
subroutine lmder1 ( fcn, m, n, x, fvec, fjac, ldfjac, tol, info )

IMPLICIT NONE
integer ( kind = 4 ) :: LDFJAC
integer ( kind = 4 ) :: M
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(ldfjac, n) :: FJAC
real ( kind = 8 ), DIMENSION(m) :: FVEC
integer ( kind = 4 ) :: INFO
real ( kind = 8 ) :: TOL
real ( kind = 8 ), DIMENSION(n) :: X
external fcn
  end
subroutine lmdif ( fcn, m, n, x, fvec, ftol, xtol, gtol, maxfev, epsfcn, &
  diag, mode, factor, nprint, info, nfev, fjac, ldfjac, ipvt, qtf )

IMPLICIT NONE
integer ( kind = 4 ) :: LDFJAC
integer ( kind = 4 ) :: M
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(n) :: DIAG
real ( kind = 8 ) :: EPSFCN
real ( kind = 8 ) :: FACTOR
real ( kind = 8 ), DIMENSION(ldfjac, n) :: FJAC
real ( kind = 8 ) :: FTOL
real ( kind = 8 ), DIMENSION(m) :: FVEC
real ( kind = 8 ) :: GTOL
integer ( kind = 4 ) :: INFO
integer ( kind = 4 ), DIMENSION(n) :: IPVT
integer ( kind = 4 ) :: MAXFEV
integer ( kind = 4 ) :: MODE
integer ( kind = 4 ) :: NFEV
integer ( kind = 4 ) :: NPRINT
real ( kind = 8 ), DIMENSION(n) :: QTF
real ( kind = 8 ), DIMENSION(n) :: X
real ( kind = 8 ) :: XTOL
external fcn
  end
subroutine lmdif1 ( fcn, m, n, x, fvec, tol, info )

IMPLICIT NONE
integer ( kind = 4 ) :: M
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(m) :: FVEC
integer ( kind = 4 ) :: INFO
real ( kind = 8 ) :: TOL
real ( kind = 8 ), DIMENSION(n) :: X
external fcn
  end
subroutine lmpar ( n, r, ldr, ipvt, diag, qtb, delta, par, x, sdiag )

IMPLICIT NONE
integer ( kind = 4 ) :: LDR
integer ( kind = 4 ) :: N
real ( kind = 8 ) :: DELTA
real ( kind = 8 ), DIMENSION(n) :: DIAG
integer ( kind = 4 ), DIMENSION(n) :: IPVT
real ( kind = 8 ) :: PAR
real ( kind = 8 ), DIMENSION(n) :: QTB
real ( kind = 8 ), DIMENSION(ldr, n) :: R
real ( kind = 8 ), DIMENSION(n) :: SDIAG
real ( kind = 8 ), DIMENSION(n) :: X
end
subroutine lmstr ( fcn, m, n, x, fvec, fjac, ldfjac, ftol, xtol, gtol, maxfev, &
  diag, mode, factor, nprint, info, nfev, njev, ipvt, qtf )

IMPLICIT NONE
integer ( kind = 4 ) :: LDFJAC
integer ( kind = 4 ) :: M
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(n) :: DIAG
real ( kind = 8 ) :: FACTOR
real ( kind = 8 ), DIMENSION(ldfjac, n) :: FJAC
real ( kind = 8 ) :: FTOL
real ( kind = 8 ), DIMENSION(m) :: FVEC
real ( kind = 8 ) :: GTOL
integer ( kind = 4 ) :: INFO
integer ( kind = 4 ), DIMENSION(n) :: IPVT
integer ( kind = 4 ) :: MAXFEV
integer ( kind = 4 ) :: MODE
integer ( kind = 4 ) :: NFEV
integer ( kind = 4 ) :: NJEV
integer ( kind = 4 ) :: NPRINT
real ( kind = 8 ), DIMENSION(n) :: QTF
real ( kind = 8 ), DIMENSION(n) :: X
real ( kind = 8 ) :: XTOL
external fcn
  end
subroutine lmstr1 ( fcn, m, n, x, fvec, fjac, ldfjac, tol, info )

IMPLICIT NONE
integer ( kind = 4 ) :: LDFJAC
integer ( kind = 4 ) :: M
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(ldfjac, n) :: FJAC
real ( kind = 8 ), DIMENSION(m) :: FVEC
integer ( kind = 4 ) :: INFO
real ( kind = 8 ) :: TOL
real ( kind = 8 ), DIMENSION(n) :: X
external fcn
  end
subroutine qform ( m, n, q, ldq )

IMPLICIT NONE
integer ( kind = 4 ) :: LDQ
integer ( kind = 4 ) :: M
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(ldq, m) :: Q
end
subroutine qrfac ( m, n, a, lda, pivot, ipvt, lipvt, rdiag, acnorm )

IMPLICIT NONE
integer ( kind = 4 ) :: LDA
integer ( kind = 4 ) :: LIPVT
integer ( kind = 4 ) :: M
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(lda, n) :: A
real ( kind = 8 ), DIMENSION(n) :: ACNORM
integer ( kind = 4 ), DIMENSION(lipvt) :: IPVT
logical :: PIVOT
real ( kind = 8 ), DIMENSION(n) :: RDIAG
end
subroutine qrsolv ( n, r, ldr, ipvt, diag, qtb, x, sdiag )

IMPLICIT NONE
integer ( kind = 4 ) :: LDR
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(n) :: DIAG
integer ( kind = 4 ), DIMENSION(n) :: IPVT
real ( kind = 8 ), DIMENSION(n) :: QTB
real ( kind = 8 ), DIMENSION(ldr, n) :: R
real ( kind = 8 ), DIMENSION(n) :: SDIAG
real ( kind = 8 ), DIMENSION(n) :: X
end
subroutine r1mpyq ( m, n, a, lda, v, w )

IMPLICIT NONE
integer ( kind = 4 ) :: LDA
integer ( kind = 4 ) :: M
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(lda, n) :: A
real ( kind = 8 ), DIMENSION(n) :: V
real ( kind = 8 ), DIMENSION(n) :: W
end
subroutine r1updt ( m, n, s, ls, u, v, w, sing )

IMPLICIT NONE
integer ( kind = 4 ) :: LS
integer ( kind = 4 ) :: M
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(ls) :: S
logical :: SING
real ( kind = 8 ), DIMENSION(m) :: U
real ( kind = 8 ), DIMENSION(n) :: V
real ( kind = 8 ), DIMENSION(m) :: W
end
subroutine r8vec_print ( n, a, title )

IMPLICIT NONE
integer ( kind = 4 ) :: N
real ( kind = 8 ), DIMENSION(n) :: A
character ( len = * ) :: TITLE
end
subroutine rwupdt ( n, r, ldr, w, b, alpha, c, s )

IMPLICIT NONE
integer ( kind = 4 ) :: LDR
integer ( kind = 4 ) :: N
real ( kind = 8 ) :: ALPHA
real ( kind = 8 ), DIMENSION(n) :: B
real ( kind = 8 ), DIMENSION(n) :: C
real ( kind = 8 ), DIMENSION(ldr, n) :: R
real ( kind = 8 ), DIMENSION(n) :: S
real ( kind = 8 ), DIMENSION(n) :: W
end
subroutine timestamp ( )

IMPLICIT NONE
end
END INTERFACE
END MODULE
