!     ######spl
       MODULE MODI_RAIN_ICE_PART3
!      ###########################
!
IMPLICIT NONE
INTERFACE
       SUBROUTINE RAIN_ICE_PART3 ( D, CST, PARAMI, ICEP, ICED, ELECP, ELECD, BUCONF,     &
                                   OELEC, OSEDIM_BEARD, PTHVREFZIKB,                     &
                                   PTSTEP, KRR,                                    &
                                   PDZZ, PRHODJ, PRHODREF, PEXNREF, PPABST, PCIT, &
                                   PTHT, PRT, PTHS, PRS,                                 &
                                   PINPRC, PINPRR,                              &
                                   PINPRS, PINPRG, PINDEP, PRAINFR,               &
                                   TBUDGETS, KBUDGETS,                                   &
                                   PQPIT, PQCT, PQRT, PQIT, PQST, PQGT, PQNIT,           &
                                   PQPIS, PQCS, PQRS, PQIS, PQSS, PQGS, PQNIS,           &
                                   PEFIELDW,                              &
                                   PSEA, PTOWN,                                 &
                                   PINPRH, PFPR, PQHT, PQHS,                             &
                                   PT, PLVFACT, PLSFACT, PWR, PWTH, PCONC3D, PRVHENI,   &
                                   ZBUDGETS )
!
USE MODD_BUDGET,         ONLY: TBUDGETDATA_PTR, TBUDGETCONF_t
USE MODD_CST,            ONLY: CST_t
USE MODD_PARAM_ICE_n,      ONLY: PARAM_ICE_t
USE MODD_RAIN_ICE_PARAM_n, ONLY: RAIN_ICE_PARAM_t
USE MODD_RAIN_ICE_DESCR_n, ONLY: RAIN_ICE_DESCR_t
USE MODD_ELEC_DESCR,     ONLY: ELEC_DESCR_t
USE MODD_ELEC_PARAM,     ONLY: ELEC_PARAM_t
USE MODD_DIMPHYEX,       ONLY: DIMPHYEX_t
USE MODD_FIELDS_ADDRESS, ONLY: IBUNUM, IBUNUM_EXTRA
!
IMPLICIT NONE
!
TYPE(DIMPHYEX_t),         INTENT(IN)    :: D
TYPE(CST_t),              INTENT(IN)    :: CST
TYPE(PARAM_ICE_t),        INTENT(IN)    :: PARAMI
TYPE(RAIN_ICE_PARAM_t),   INTENT(IN)    :: ICEP
TYPE(RAIN_ICE_DESCR_t),   INTENT(IN)    :: ICED
TYPE(ELEC_PARAM_t),       INTENT(IN)    :: ELECP
TYPE(ELEC_DESCR_t),       INTENT(IN)    :: ELECD
TYPE(TBUDGETCONF_t),      INTENT(IN)    :: BUCONF
LOGICAL,                  INTENT(IN)    :: OELEC
LOGICAL,                  INTENT(IN)    :: OSEDIM_BEARD
REAL,                     INTENT(IN)    :: PTHVREFZIKB
REAL,                     INTENT(IN)    :: PTSTEP
INTEGER,                  INTENT(IN)    :: KRR
!
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN)    :: PDZZ
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN)    :: PRHODJ
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN)    :: PRHODREF
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN)    :: PEXNREF
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN)    :: PPABST
!
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(INOUT) :: PCIT
!
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(IN)    :: PTHT
REAL, DIMENSION(D%NIJT,D%NKT,KRR),   INTENT(IN)    :: PRT
!
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(INOUT) :: PTHS
REAL, DIMENSION(D%NIJT,D%NKT,KRR),   INTENT(INOUT) :: PRS
!
REAL, DIMENSION(D%NIJT), INTENT(INOUT)       :: PINPRC
REAL, DIMENSION(D%NIJT), INTENT(INOUT)       :: PINPRR
REAL, DIMENSION(D%NIJT), INTENT(INOUT)       :: PINPRS
REAL, DIMENSION(D%NIJT), INTENT(INOUT)       :: PINPRG
REAL, DIMENSION(D%NIJT), INTENT(INOUT) :: PINDEP
REAL, DIMENSION(D%NIJT,D%NKT),   INTENT(INOUT) :: PRAINFR
!
TYPE(TBUDGETDATA_PTR), DIMENSION(KBUDGETS), INTENT(INOUT) :: TBUDGETS
INTEGER, INTENT(IN) :: KBUDGETS
!
! scalar variables for cloud electricity
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(IN)    :: PQPIT
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQCT
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQRT
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQIT
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQST
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQGT
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(IN)    :: PQNIT
!
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQPIS
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQCS
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQRS
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQIS
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQSS
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQGS
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQNIS
!
REAL, DIMENSION(MERGE(D%NIJT,0,OSEDIM_BEARD),MERGE(D%NKT,0,OSEDIM_BEARD)), OPTIONAL, INTENT(IN) :: PEFIELDW
!
! optional variables
REAL, DIMENSION(D%NIJT),           OPTIONAL, INTENT(IN)    :: PSEA
REAL, DIMENSION(D%NIJT),           OPTIONAL, INTENT(IN)    :: PTOWN
REAL, DIMENSION(D%NIJT),           OPTIONAL, INTENT(INOUT)   :: PINPRH
REAL, DIMENSION(D%NIJT,D%NKT,KRR), OPTIONAL, INTENT(INOUT)   :: PFPR
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQHT
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC),MERGE(D%NKT,0,OELEC)), OPTIONAL, INTENT(INOUT) :: PQHS
!
! Bridge variables from part1/part2
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PT
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) :: PLVFACT
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) :: PLSFACT
REAL, DIMENSION(D%NIJT,D%NKT,7), INTENT(INOUT) :: PWR
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(INOUT) :: PWTH
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PCONC3D
REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN) :: PRVHENI
!
! Budget array (from part2)
REAL, DIMENSION(MERGE(D%NIJT,0,OELEC .OR. BUCONF%LBU_ENABLE), &
                MERGE(D%NKT,0,OELEC .OR. BUCONF%LBU_ENABLE), &
                MERGE(IBUNUM-IBUNUM_EXTRA,0,OELEC .OR. BUCONF%LBU_ENABLE)), &
           INTENT(INOUT) :: ZBUDGETS
!
END SUBROUTINE RAIN_ICE_PART3
END INTERFACE
END MODULE MODI_RAIN_ICE_PART3
