MODULE MODD_MISC
USE MODD_IO,         ONLY: TFILEDATA
USE MODD_LES,        ONLY: TLES_t
USE MODD_BUDGET,     ONLY: NBUDGET_RH, TBUDGETDATA, TBUDGETCONF_t
IMPLICIT NONE
TYPE MISC_t
  INTEGER :: KSV_LGBEG = 0
  INTEGER :: KSV_LGEND = 0
  LOGICAL :: ONOMIXLG=.FALSE.
  INTEGER :: KGRADIENTSLEO =0
  INTEGER :: KGRADIENTSGOG =0
  CHARACTER(LEN=4),DIMENSION(2) :: HLBCX=(/'CYCL','CYCL'/)
  CHARACTER(LEN=4),DIMENSION(2) :: HLBCY=(/'CYCL','CYCL'/)
  INTEGER :: KHALO=1
  LOGICAL :: O2D=.FALSE.
  LOGICAL :: OFLAT=.FALSE.
  LOGICAL :: OCOUPLES=.FALSE.
  LOGICAL :: OBLOWSNOW=.FALSE.
  LOGICAL :: COMPUTE_SRC=.TRUE.
  LOGICAL :: OOCEAN=.FALSE.
  LOGICAL :: ODEEPOC=.FALSE.
  REAL    :: PRSNOW=1.0
  INTEGER :: KSV_LIMA_NR=0
  INTEGER :: KSV_LIMA_NS=0
  INTEGER :: KSV_LIMA_NG=0
  INTEGER :: KSV_LIMA_NH=0
  LOGICAL :: OIBM=.FALSE.
  LOGICAL :: OFLYER=.FALSE.
  LOGICAL :: ODIAG_IN_RUN=.FALSE.
  TYPE(TFILEDATA)    :: ZTFILE
  TYPE(TLES_t)       :: TLES
  CHARACTER(LEN=6)   :: CPROGRAM
  CHARACTER(LEN=4)   :: CELEC='NONE'         !< Name of the electricity scheme
  LOGICAL                        :: OELEC=.FALSE.        !< Lightning prognostic scheme
  LOGICAL            :: OSEDIM_BEARD=.FALSE. !< Switch for effect of electrical forces on sedim.
  CHARACTER(LEN=4)   ::CMICRO
  CHARACTER(LEN=4)   ::CSCONV
  CHARACTER(LEN=4)   ::CTURB
  TYPE(TBUDGETDATA), DIMENSION(NBUDGET_RH) :: YLBUDGET
  INTEGER :: NBUDGET = NBUDGET_RH
  TYPE(TBUDGETCONF_t) :: TBUCONF
END TYPE MISC_t
END MODULE MODD_MISC
