MODULE MODD_IO
USE MODD_PARAMETERS, ONLY: NFILENAMELGTMAX
!
IMPLICIT NONE
!
INTEGER, PARAMETER :: NVERB_NO=0, NVERB_FATAL=1, NVERB_ERROR=2, NVERB_WARNING=3, NVERB_INFO=4, NVERB_DEBUG=5
INTEGER, PARAMETER :: N_ABORT_LEVEL = NVERB_ERROR
!
!Structure describing the characteristics of a file
TYPE TFILEDATA
  LOGICAL           :: LOPENED = .FALSE.   !Is the file opened
  INTEGER :: NLU = -1 ! logical unit number
END TYPE TFILEDATA
ENDMODULE MODD_IO
