MODULE MODE_MPPDB
IMPLICIT NONE
REAL                             :: PRECISION = 1e-8 * 0.0
CONTAINS  
SUBROUTINE MPPDB_CHECK3DM(MESSAGE,PRECISION &
                           ,PTAB1,PTAB2,PTAB3,PTAB4,PTAB5,PTAB6,PTAB7,PTAB8,PTAB9,PTAB10 &
                           ,PTAB11,PTAB12,PTAB13,PTAB14,PTAB15,PTAB16,PTAB17,PTAB18,PTAB19,PTAB20 &
                           )

IMPLICIT NONE

CHARACTER(lEN=*), INTENT(IN)                     :: MESSAGE
REAL, INTENT(IN)                                 :: PRECISION
REAL, DIMENSION(:,:,:), INTENT(IN), OPTIONAL     :: PTAB1,PTAB2,PTAB3,PTAB4,PTAB5,PTAB6,PTAB7,PTAB8,PTAB9,PTAB10
REAL, DIMENSION(:,:,:), INTENT(IN), OPTIONAL     :: PTAB11,PTAB12,PTAB13,PTAB14,PTAB15,PTAB16,PTAB17,PTAB18,PTAB19,PTAB20
! DO NOTHING IN AROME
END SUBROUTINE MPPDB_CHECK3DM
END MODULE MODE_MPPDB
