MODULE MODE_BUDGET_OFFLINE
!
USE MODD_BUDGET, ONLY: TBUDGETDATA
!
IMPLICIT NONE
!
TYPE, EXTENDS(TBUDGETDATA) :: TBUDGETDATA_OFFLINE
  CONTAINS
  PROCEDURE :: INIT_PHY => BUDGET_INIT
  PROCEDURE :: END_PHY => BUDGET_END
  PROCEDURE :: ADD_PHY => BUDGET_ADD
ENDTYPE TBUDGETDATA_OFFLINE
!
PRIVATE
PUBLIC :: TBUDGETDATA_OFFLINE
!
CONTAINS
!
SUBROUTINE BUDGET_INIT(SELF, D, HSOURCE, PVARS)
  USE MODD_DIMPHYEX, ONLY: DIMPHYEX_t
  CLASS(TBUDGETDATA_OFFLINE),    INTENT(INOUT) :: SELF
  TYPE(DIMPHYEX_t),              INTENT(IN)    :: D
  CHARACTER(LEN=*),              INTENT(IN)    :: HSOURCE
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN)    :: PVARS
END SUBROUTINE BUDGET_INIT
!
SUBROUTINE BUDGET_END(SELF, D, HSOURCE, PVARS)
  USE MODD_DIMPHYEX, ONLY: DIMPHYEX_t
  CLASS(TBUDGETDATA_OFFLINE),    INTENT(INOUT) :: SELF
  TYPE(DIMPHYEX_t),              INTENT(IN)    :: D
  CHARACTER(LEN=*),              INTENT(IN)    :: HSOURCE
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN)    :: PVARS
END SUBROUTINE BUDGET_END
!
SUBROUTINE BUDGET_ADD(SELF, D, HSOURCE, PVARS)
  USE MODD_DIMPHYEX, ONLY: DIMPHYEX_t
  CLASS(TBUDGETDATA_OFFLINE),    INTENT(INOUT) :: SELF
  TYPE(DIMPHYEX_t),              INTENT(IN)    :: D
  CHARACTER(LEN=*),              INTENT(IN)    :: HSOURCE
  REAL, DIMENSION(D%NIJT,D%NKT), INTENT(IN)    :: PVARS
END SUBROUTINE BUDGET_ADD
!
END MODULE MODE_BUDGET_OFFLINE
