MODULE MODE_POSNAM_PHY
IMPLICIT NONE
PRIVATE
PUBLIC :: POSNAM_PHY
CONTAINS
SUBROUTINE POSNAM_PHY(TFILENAM, CDNAML, LDNEEDNAM, LDFOUND)
!Wrapper to call fiat-compatible version of posname or the mesonh routine

USE MODD_IO, ONLY: TFILEDATA
USE MODE_MSG, ONLY: NVERB_FATAL, PRINT_MSG
#ifdef PHYEX_MESONH
USE MODE_POS, ONLY: POSNAM
#else
USE NAMELIST_MOD, ONLY: POSNAME
#endif

IMPLICIT NONE

TYPE(TFILEDATA),  INTENT(IN)    :: TFILENAM  !< Namelist file
CHARACTER(LEN=*), INTENT(IN)    :: CDNAML    !< Namelist name
LOGICAL,          INTENT(IN)    :: LDNEEDNAM !< True to abort if namelist is absent
LOGICAL,          INTENT(OUT)   :: LDFOUND   !< True if namelist has been found

INTEGER :: ISTAT
CHARACTER(LEN=LEN(CDNAML)+20) :: CTEMP

#ifdef PHYEX_MESONH
CALL POSNAM(TFILENAM, CDNAML, LDFOUND)
#else
CALL POSNAME(TFILENAM%NLU, CDNAML, ISTAT)
LDFOUND=ISTAT==0
#endif
IF(LDNEEDNAM .AND. .NOT. LDFOUND) THEN
  CTEMP='CANNOT LOCATE '//CDNAML
  CALL PRINT_MSG(NVERB_FATAL, 'GEN', 'POSNAM_PHY', CTEMP)
ENDIF

END SUBROUTINE POSNAM_PHY
END MODULE MODE_POSNAM_PHY
