!     ######spl
       MODULE MODI_AERMR_NC
!      ####################
!
INTERFACE
 SUBROUTINE AERMR_NC(PHYEX, PTSTEP, PRHODREF, PEXNREF, PPABST, &
     & PCLDFR, PTHT, PRVT, PRCT, KNAERO, &
     & PAER_MR, PSSAT, PAER_NC, PCCN_NC, PIFN_NC)
!
USE MODD_PHYEX, ONLY: PHYEX_t
!
TYPE(PHYEX_t),            INTENT(IN) :: PHYEX
REAL,                     INTENT(IN)    :: PTSTEP
INTEGER,                  INTENT(IN)    :: KNAERO
REAL, DIMENSION(:,:,:),   INTENT(IN)    :: PRHODREF
REAL, DIMENSION(:,:,:),   INTENT(IN)    :: PEXNREF
REAL, DIMENSION(:,:,:),   INTENT(IN)    :: PPABST
REAL, DIMENSION(:,:,:),   INTENT(IN)    :: PCLDFR
REAL, DIMENSION(:,:,:),   INTENT(IN)    :: PTHT
REAL, DIMENSION(:,:,:),   INTENT(IN)    :: PRVT
REAL, DIMENSION(:,:,:),   INTENT(IN)    :: PRCT
REAL, DIMENSION(:,:,:,:), INTENT(IN)    :: PAER_MR
REAL, DIMENSION(:,:,:),   INTENT(INOUT) :: PSSAT
REAL, DIMENSION(:,:,:,:), INTENT(  OUT) :: PAER_NC
REAL, DIMENSION(:,:,:,:), INTENT(  OUT) :: PCCN_NC
REAL, DIMENSION(:,:,:),   INTENT(  OUT) :: PIFN_NC
!
END SUBROUTINE AERMR_NC
END INTERFACE
END MODULE MODI_AERMR_NC
