INTERFACE

SUBROUTINE CONVECT_TRIGGER_SHAL(  CVP_SHAL, CVPEXT, CST, D,  &
PPRES, PTH, PTHV, PTHES,             &
PRV, PW, PZ, PTKECLS,                &
PTHLCL, PTLCL, PRVLCL, PWLCL, PZLCL, &
PTHVELCL, KLCL, KDPL, KPBL, OTRIG)
USE YOMHOOK , ONLY : LHOOK, DR_HOOK
USE MODD_CST, ONLY : CST_T
USE MODD_CONVPAR_SHAL, ONLY : CONVPAR_SHAL
USE MODD_CONVPAREXT, ONLY : CONVPAREXT
USE MODD_DIMPHYEX, ONLY: DIMPHYEX_T
TYPE(CONVPAR_SHAL),        INTENT(IN) :: CVP_SHAL
TYPE(CONVPAREXT),          INTENT(IN) :: CVPEXT
TYPE(CST_T),               INTENT(IN) :: CST
TYPE(DIMPHYEX_T),          INTENT(IN) :: D
REAL, DIMENSION(D%NIT),     INTENT(IN) :: PTKECLS
REAL, DIMENSION(D%NIT,D%NKT),INTENT(IN) :: PTH, PTHV
REAL, DIMENSION(D%NIT,D%NKT),INTENT(IN) :: PTHES
REAL, DIMENSION(D%NIT,D%NKT),INTENT(IN) :: PRV
REAL, DIMENSION(D%NIT,D%NKT),INTENT(IN) :: PPRES
REAL, DIMENSION(D%NIT,D%NKT),INTENT(IN) :: PZ
REAL, DIMENSION(D%NIT,D%NKT),INTENT(IN) :: PW
REAL, DIMENSION(D%NIT),     INTENT(OUT):: PTHLCL
REAL, DIMENSION(D%NIT),     INTENT(OUT):: PTLCL
REAL, DIMENSION(D%NIT),     INTENT(OUT):: PRVLCL
REAL, DIMENSION(D%NIT),     INTENT(OUT):: PWLCL
REAL, DIMENSION(D%NIT),     INTENT(OUT):: PZLCL
REAL, DIMENSION(D%NIT),     INTENT(OUT):: PTHVELCL
LOGICAL, DIMENSION(D%NIT),  INTENT(OUT):: OTRIG
INTEGER, DIMENSION(D%NIT),  INTENT(INOUT):: KLCL
INTEGER, DIMENSION(D%NIT),  INTENT(INOUT):: KDPL
INTEGER, DIMENSION(D%NIT),  INTENT(INOUT):: KPBL
END SUBROUTINE CONVECT_TRIGGER_SHAL

END INTERFACE
