INTERFACE

SUBROUTINE CONVECT_CLOSURE_ADJUST_SHAL( CVPEXT, D, PADJ,        &
PUMF, PZUMF, PUER, PZUER, PUDR, PZUDR  )
USE YOMHOOK , ONLY : LHOOK, DR_HOOK
USE MODD_CONVPAREXT, ONLY : CONVPAREXT
USE MODD_DIMPHYEX, ONLY: DIMPHYEX_T
TYPE(CONVPAREXT),           INTENT(IN) :: CVPEXT
TYPE(DIMPHYEX_T),           INTENT(IN) :: D
REAL, DIMENSION(D%NIT),      INTENT(IN) :: PADJ
REAL, DIMENSION(D%NIT,D%NKT), INTENT(INOUT) :: PUMF
REAL, DIMENSION(D%NIT,D%NKT), INTENT(INOUT) :: PZUMF
REAL, DIMENSION(D%NIT,D%NKT), INTENT(INOUT) :: PUER
REAL, DIMENSION(D%NIT,D%NKT), INTENT(INOUT) :: PZUER
REAL, DIMENSION(D%NIT,D%NKT), INTENT(INOUT) :: PUDR
REAL, DIMENSION(D%NIT,D%NKT), INTENT(INOUT) :: PZUDR
END SUBROUTINE CONVECT_CLOSURE_ADJUST_SHAL

END INTERFACE
