INTERFACE

SUBROUTINE CONVECT_UPDRAFT_SHAL( CVP_SHAL, CVPEXT, CST, D, CONVPAR,              &
KICE, PPRES, PDPRES, PZ, PTHL, PTHV, PTHES, PRW,&
PTHLCL, PTLCL, PRVLCL, PWLCL, PZLCL, PTHVELCL,  &
PMFLCL, OTRIG, KLCL, KDPL, KPBL,                &
PUMF, PUER, PUDR, PUTHL, PUTHV, PURW,           &
PURC, PURI, PCAPE, KCTL, KETL,GTRIG1 )
USE YOMHOOK , ONLY : LHOOK, DR_HOOK
USE MODD_CST, ONLY : CST_T
USE MODD_CONVPAR, ONLY : CONVPAR_T
USE MODD_CONVPAR_SHAL, ONLY : CONVPAR_SHAL
USE MODD_CONVPAREXT, ONLY : CONVPAREXT
USE MODD_DIMPHYEX, ONLY: DIMPHYEX_T
TYPE(CONVPAR_SHAL),         INTENT(IN) :: CVP_SHAL
TYPE(CONVPAREXT),           INTENT(IN) :: CVPEXT
TYPE(CST_T),                INTENT(IN) :: CST
TYPE(DIMPHYEX_T),           INTENT(IN) :: D
TYPE(CONVPAR_T),            INTENT(IN) :: CONVPAR
INTEGER,                    INTENT(IN) :: KICE
REAL, DIMENSION(D%NIT,D%NKT), INTENT(IN) :: PTHL
REAL, DIMENSION(D%NIT,D%NKT), INTENT(IN) :: PTHV
REAL, DIMENSION(D%NIT,D%NKT), INTENT(IN) :: PTHES
REAL, DIMENSION(D%NIT,D%NKT), INTENT(IN) :: PRW
REAL, DIMENSION(D%NIT,D%NKT), INTENT(IN) :: PPRES
REAL, DIMENSION(D%NIT,D%NKT), INTENT(IN) :: PDPRES
REAL, DIMENSION(D%NIT,D%NKT), INTENT(IN) :: PZ
REAL, DIMENSION(D%NIT),     INTENT(IN) :: PTHLCL
REAL, DIMENSION(D%NIT),     INTENT(IN) :: PTLCL
REAL, DIMENSION(D%NIT),     INTENT(IN) :: PRVLCL
REAL, DIMENSION(D%NIT),     INTENT(IN) :: PWLCL
REAL,                      INTENT(IN) :: PMFLCL
REAL, DIMENSION(D%NIT),     INTENT(IN) :: PZLCL
REAL, DIMENSION(D%NIT),     INTENT(IN) :: PTHVELCL
LOGICAL, DIMENSION(D%NIT),  INTENT(INOUT):: OTRIG
LOGICAL, DIMENSION(D%NIT),  INTENT(IN):: GTRIG1
INTEGER, DIMENSION(D%NIT),  INTENT(IN) :: KLCL
INTEGER, DIMENSION(D%NIT),  INTENT(IN) :: KDPL
INTEGER, DIMENSION(D%NIT),  INTENT(IN) :: KPBL
INTEGER, DIMENSION(D%NIT),  INTENT(OUT):: KCTL
INTEGER, DIMENSION(D%NIT),  INTENT(OUT):: KETL
REAL, DIMENSION(D%NIT,D%NKT), INTENT(OUT):: PUMF
REAL, DIMENSION(D%NIT,D%NKT), INTENT(OUT):: PUER
REAL, DIMENSION(D%NIT,D%NKT), INTENT(OUT):: PUDR
REAL, DIMENSION(D%NIT,D%NKT), INTENT(OUT):: PUTHL
REAL, DIMENSION(D%NIT,D%NKT), INTENT(OUT):: PUTHV
REAL, DIMENSION(D%NIT,D%NKT), INTENT(OUT):: PURW
REAL, DIMENSION(D%NIT,D%NKT), INTENT(OUT):: PURC
REAL, DIMENSION(D%NIT,D%NKT), INTENT(OUT):: PURI
REAL, DIMENSION(D%NIT),     INTENT(OUT):: PCAPE
END SUBROUTINE CONVECT_UPDRAFT_SHAL

END INTERFACE
