SUBROUTINE SHALLOW_CONVECTION_PART2_SELECT (CVP_SHAL, CVPEXT, CST, D, NSV, CONVPAR, KICE&
&, OSETTADJ, PTADJS, PPABST, PZZ, PTT, PRVT, PRCT, PRIT, OCH1CONV, KCH1, PCH1, PRDOCP,&
& PTHT, PSTHV, PSTHES, ISDPL, ISPBL, ISLCL, PSTHLCL, PSTLCL, PSRVLCL, PSWLCL, PSZLCL, PSTHVELCL&
&, GTRIG1, PUMF, PTHC, PRVC, PRCC, PRIC, ICTL, IMINCTL, PPCH1TEN)

USE MODD_CONVPAR,ONLY:CONVPAR_T
USE MODD_CONVPAR_SHAL,ONLY:CONVPAR_SHAL
USE MODD_CONVPAREXT,ONLY:CONVPAREXT
USE MODD_CST,ONLY:CST_T
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_NSV,ONLY:NSV_T
USE MODI_SHALLOW_CONVECTION_PART2, ONLY: SHALLOW_CONVECTION_PART2

IMPLICIT NONE

TYPE(CONVPAR_SHAL) ,INTENT(IN)   :: CVP_SHAL
TYPE(CONVPAREXT)   ,INTENT(IN)   :: CVPEXT
TYPE(CST_T)        ,INTENT(IN)   :: CST
TYPE(DIMPHYEX_T)   ,INTENT(IN)   :: D
TYPE(NSV_T)        ,INTENT(IN)   :: NSV
TYPE(CONVPAR_T)    ,INTENT(IN)   :: CONVPAR
INTEGER            ,INTENT(IN)   :: KICE
LOGICAL            ,INTENT(IN)   :: OSETTADJ
REAL               ,INTENT(IN)   :: PTADJS
REAL               ,INTENT(IN)   :: PPABST(D%NIJT,D%NKT)
REAL               ,INTENT(IN)   :: PZZ(D%NIJT,D%NKT)
REAL               ,INTENT(IN)   :: PTT(D%NIJT,D%NKT)
REAL               ,INTENT(IN)   :: PRVT(D%NIJT,D%NKT)
REAL               ,INTENT(IN)   :: PRCT(D%NIJT,D%NKT)
REAL               ,INTENT(IN)   :: PRIT(D%NIJT,D%NKT)
LOGICAL            ,INTENT(IN)   :: OCH1CONV
INTEGER            ,INTENT(IN)   :: KCH1
REAL               ,INTENT(IN)   :: PCH1(D%NIJT,D%NKT,KCH1)
REAL               ,INTENT(IN)   :: PRDOCP
REAL               ,INTENT(IN)   :: PTHT(D%NIJT,D%NKT)
REAL               ,INTENT(IN)   :: PSTHV(D%NIJT,D%NKT)
REAL               ,INTENT(IN)   :: PSTHES(D%NIJT,D%NKT)
INTEGER            ,INTENT(IN)   :: ISDPL(D%NIJT)
INTEGER            ,INTENT(IN)   :: ISPBL(D%NIJT)
INTEGER            ,INTENT(IN)   :: ISLCL(D%NIJT)
REAL               ,INTENT(IN)   :: PSTHLCL(D%NIJT)
REAL               ,INTENT(IN)   :: PSTLCL(D%NIJT)
REAL               ,INTENT(IN)   :: PSRVLCL(D%NIJT)
REAL               ,INTENT(IN)   :: PSWLCL(D%NIJT)
REAL               ,INTENT(IN)   :: PSZLCL(D%NIJT)
REAL               ,INTENT(IN)   :: PSTHVELCL(D%NIJT)
LOGICAL            ,INTENT(IN)   :: GTRIG1(D%NIJT)
REAL               ,INTENT(OUT)  :: PUMF(D%NIJT,D%NKT)
REAL               ,INTENT(OUT)  :: PTHC(D%NIJT,D%NKT)
REAL               ,INTENT(OUT)  :: PRVC(D%NIJT,D%NKT)
REAL               ,INTENT(OUT)  :: PRCC(D%NIJT,D%NKT)
REAL               ,INTENT(OUT)  :: PRIC(D%NIJT,D%NKT)
INTEGER            ,INTENT(OUT)  :: ICTL(D%NIJT)
INTEGER            ,INTENT(OUT)  :: IMINCTL(D%NIJT)
REAL               ,INTENT(OUT)  :: PPCH1TEN(D%NIJT,D%NKT,KCH1)

INTEGER :: ICNT

ICNT = COUNT (GTRIG1 (D%NIJB:D%NIJE))

IF (ICNT == 0) THEN
  ! Do nothing if there are no selected columns
  RETURN
ELSEIF (ICNT >= (D%NIJT*9)/10) THEN
! Avoid repack
  CALL SHALLOW_CONVECTION_PART2 (CVP_SHAL, CVPEXT, CST, D, NSV, CONVPAR, KICE, OSETTADJ, PTADJS&
  &, PPABST, PZZ, PTT, PRVT, PRCT, PRIT, OCH1CONV, KCH1, PCH1, PRDOCP, PTHT, PSTHV&
  &, PSTHES, ISDPL, ISPBL, ISLCL, PSTHLCL, PSTLCL, PSRVLCL, PSWLCL, PSZLCL, PSTHVELCL&
  &, GTRIG1, PUMF, PTHC, PRVC, PRCC, PRIC, ICTL, IMINCTL, PPCH1TEN)
ELSE
! Repack
  CALL DO_SELECT
ENDIF

CONTAINS

SUBROUTINE DO_SELECT

LOGICAL::GTRIG1_(ICNT)
INTEGER::ICTL_(ICNT)
INTEGER::IMINCTL_(ICNT)
INTEGER::ISDPL_(ICNT)
INTEGER::ISLCL_(ICNT)
INTEGER::ISPBL_(ICNT)
REAL::PCH1_(ICNT, D%NKT, KCH1)
REAL::PPABST_(ICNT, D%NKT)
REAL::PPCH1TEN_(ICNT, D%NKT, KCH1)
REAL::PRCC_(ICNT, D%NKT)
REAL::PRCT_(ICNT, D%NKT)
REAL::PRIC_(ICNT, D%NKT)
REAL::PRIT_(ICNT, D%NKT)
REAL::PRVC_(ICNT, D%NKT)
REAL::PRVT_(ICNT, D%NKT)
REAL::PSRVLCL_(ICNT)
REAL::PSTHES_(ICNT, D%NKT)
REAL::PSTHLCL_(ICNT)
REAL::PSTHV_(ICNT, D%NKT)
REAL::PSTHVELCL_(ICNT)
REAL::PSTLCL_(ICNT)
REAL::PSWLCL_(ICNT)
REAL::PSZLCL_(ICNT)
REAL::PTHC_(ICNT, D%NKT)
REAL::PTHT_(ICNT, D%NKT)
REAL::PTT_(ICNT, D%NKT)
REAL::PUMF_(ICNT, D%NKT)
REAL::PZZ_(ICNT, D%NKT)

INTEGER :: JI
INTEGER :: JI_
INTEGER :: ISORT (ICNT)
TYPE (DIMPHYEX_T) :: D_

D_ = D
D_%NIJB = 1
D_%NIJE = ICNT
D_%NIJT = ICNT

JI_ = 0

DO JI = D%NIJB, D%NIJE
  IF (GTRIG1 (JI)) THEN
    JI_ = JI_ + 1
    ISORT (JI_) = JI
  ENDIF
ENDDO

DO JI_ = 1, ICNT
  GTRIG1_(JI_) = GTRIG1(ISORT(JI_))
  ISDPL_(JI_) = ISDPL(ISORT(JI_))
  ISLCL_(JI_) = ISLCL(ISORT(JI_))
  ISPBL_(JI_) = ISPBL(ISORT(JI_))
  PCH1_(JI_,:,:) = PCH1(ISORT(JI_),:,:)
  PPABST_(JI_,:) = PPABST(ISORT(JI_),:)
  PRCT_(JI_,:) = PRCT(ISORT(JI_),:)
  PRIT_(JI_,:) = PRIT(ISORT(JI_),:)
  PRVT_(JI_,:) = PRVT(ISORT(JI_),:)
  PSRVLCL_(JI_) = PSRVLCL(ISORT(JI_))
  PSTHES_(JI_,:) = PSTHES(ISORT(JI_),:)
  PSTHLCL_(JI_) = PSTHLCL(ISORT(JI_))
  PSTHV_(JI_,:) = PSTHV(ISORT(JI_),:)
  PSTHVELCL_(JI_) = PSTHVELCL(ISORT(JI_))
  PSTLCL_(JI_) = PSTLCL(ISORT(JI_))
  PSWLCL_(JI_) = PSWLCL(ISORT(JI_))
  PSZLCL_(JI_) = PSZLCL(ISORT(JI_))
  PTHT_(JI_,:) = PTHT(ISORT(JI_),:)
  PTT_(JI_,:) = PTT(ISORT(JI_),:)
  PZZ_(JI_,:) = PZZ(ISORT(JI_),:)
ENDDO

CALL SHALLOW_CONVECTION_PART2(CVP_SHAL, CVPEXT, CST, D_, NSV, CONVPAR, KICE, OSETTADJ, PTADJS,&
&PPABST_, PZZ_, PTT_, PRVT_, PRCT_, PRIT_, OCH1CONV, KCH1, PCH1_, PRDOCP, PTHT_, PSTHV_, &
&PSTHES_, ISDPL_, ISPBL_, ISLCL_, PSTHLCL_, PSTLCL_, PSRVLCL_, PSWLCL_, PSZLCL_, PSTHVELCL_, &
&GTRIG1_, PUMF_, PTHC_, PRVC_, PRCC_, PRIC_, ICTL_, IMINCTL_, PPCH1TEN_)


DO JI_ = 1, ICNT
  ICTL(ISORT(JI_)) = ICTL_(JI_)
  IMINCTL(ISORT(JI_)) = IMINCTL_(JI_)
  PPCH1TEN(ISORT(JI_),:,:) = PPCH1TEN_(JI_,:,:)
  PRCC(ISORT(JI_),:) = PRCC_(JI_,:)
  PRIC(ISORT(JI_),:) = PRIC_(JI_,:)
  PRVC(ISORT(JI_),:) = PRVC_(JI_,:)
  PTHC(ISORT(JI_),:) = PTHC_(JI_,:)
  PUMF(ISORT(JI_),:) = PUMF_(JI_,:)
ENDDO

ENDSUBROUTINE DO_SELECT

ENDSUBROUTINE SHALLOW_CONVECTION_PART2_SELECT

