SUBROUTINE INI_PHYEX(HPROGRAM, KUNITNML, LDNEEDNAM, KLUOUT, KFROM, KTO, &
                    &PTSTEP, PDZMIN, &
                    &CMICRO, CSCONV, CTURB, &
                    &LDCHANGEMODEL, LDDEFAULTVAL, LDREADNAM, LDCHECK, KPRINT, LDINIT, &
                    &PHYEX_IN, PHYEX_OUT)
!
USE MODD_PHYEX, ONLY: PHYEX_t
USE MODD_CST, ONLY: CST, CST_t, PRINT_CST
USE MODD_PARAM_ICE_n, ONLY: PARAM_ICE_GOTO_MODEL, PARAM_ICEN_INIT, PARAM_ICEN, PARAM_ICE_t, &
                          & CSUBG_AUCV_RC, CSUBG_AUCV_RI
USE MODD_RAIN_ICE_DESCR_n, ONLY: RAIN_ICE_DESCR_GOTO_MODEL, RAIN_ICE_DESCRN, RAIN_ICE_DESCR_t
USE MODD_RAIN_ICE_PARAM_n, ONLY: RAIN_ICE_PARAM_GOTO_MODEL, RAIN_ICE_PARAMN, RAIN_ICE_PARAM_t
USE MODD_CLOUDPAR_N,     ONLY: CLOUDPAR_GOTO_MODEL, CLOUDPARN, CLOUDPAR_t
USE MODD_PARAM_MFSHALL_N,ONLY: PARAM_MFSHALLN, PARAM_MFSHALL_t, PARAM_MFSHALLN_INIT, PARAM_MFSHALL_GOTO_MODEL
USE MODD_TURB_N,         ONLY: TURBN, TURB_t, TURBN_INIT, TURB_GOTO_MODEL, LHARAT
USE MODD_CTURB,          ONLY: CSTURB, CSTURB_t, CTURB_ASSOCIATE
USE MODD_NEB_N,          ONLY: NEBN, NEB_t, NEBN_INIT, NEB_GOTO_MODEL, CCONDENS, LSTATNW
!
USE MODE_INI_CST, ONLY: INI_CST
USE MODE_INI_RAIN_ICE, ONLY: INI_RAIN_ICE
USE MODE_INI_TIWMX, ONLY: INI_TIWMX
USE MODE_INI_SNOW, ONLY: INI_SNOW
USE MODE_INI_MFSHALL, ONLY: INI_MFSHALL
USE MODE_INI_TURB, ONLY: INI_TURB
!
USE MODE_MSG, ONLY: PRINT_MSG, NVERB_FATAL
!
!!
!!      *INI_PHYEX* - PHYEX initialisation routine
!!
!!    PURPOSE
!!    -------
!!      The purpose of this routine is to initialise (default values, namelist, checks, prints)
!!      the different modules used by the physics
!!
!!
!!    AUTHOR
!!    ------
!!     S. Riette
!!
!!    MODIFICATIONS
!!    -------------
!!
!!    -  Original      Fev 2023
!!
!-------------------------------------------------------------------------------
!
!**       DECLARATIONS
!
IMPLICIT NONE

CHARACTER(LEN=6),  INTENT(IN) :: HPROGRAM     !< Current program
INTEGER,           INTENT(IN) :: KUNITNML     !< Logical unit to access the namelist
LOGICAL,           INTENT(IN) :: LDNEEDNAM    !< True to abort if namelist is absent
INTEGER,           INTENT(IN) :: KLUOUT       !< Logical unit for outputs
INTEGER,           INTENT(IN) :: KFROM        !< Old model number
INTEGER,           INTENT(IN) :: KTO          !< New model number
REAL,              INTENT(IN) :: PTSTEP       !< Timestep
REAL,              INTENT(IN) :: PDZMIN       !< Minimum thickness
CHARACTER(LEN=4),  INTENT(IN) :: CMICRO       !< Microphysical scheme to use
CHARACTER(LEN=4),  INTENT(IN) :: CTURB        !< Turbulence scheme to use
CHARACTER(LEN=4),  INTENT(IN) :: CSCONV       !< Shallow convection scheme to use
LOGICAL, OPTIONAL, INTENT(IN) :: LDCHANGEMODEL!< Must we change the active model
LOGICAL, OPTIONAL, INTENT(IN) :: LDDEFAULTVAL !< Must we initialize variables with default values (defaults to .TRUE.)
LOGICAL, OPTIONAL, INTENT(IN) :: LDREADNAM    !< Must we read the namelist (defaults to .TRUE.)
LOGICAL, OPTIONAL, INTENT(IN) :: LDCHECK      !< Must we perform some checks on values (defaults to .TRUE.)
INTEGER, OPTIONAL, INTENT(IN) :: KPRINT       !< Print level (defaults to 0): 0 for no print, 1 to safely print namelist,
                                              !! 2 to print informative messages
LOGICAL, OPTIONAL, INTENT(IN) :: LDINIT       !< Must we call the init routines
TYPE(PHYEX_t), OPTIONAL, INTENT(IN)    :: PHYEX_IN    !< Structure for constants (IN)
TYPE(PHYEX_t), OPTIONAL, INTENT(INOUT) :: PHYEX_OUT   !< Structure for constants (OUT)

!IMPORTANT NOTE on PHYEX_OUT arguments.
!Logically this argument should be declared with INTENT(OUT) but in this case ifort (at least) breaks the
!execution when the same structure is given for the PHYEX_IN and the PHYEX_OUT argument.
!When INITENT(INOUT) is used, execution is OK on ifort.

LOGICAL :: LLINIT, LLCHANGEMODEL, LLCHECK
INTEGER :: IPRINT
!
!**       ARGUMENTS
!
LLINIT=.TRUE.
IF(PRESENT(LDINIT)) LLINIT=LDINIT
LLCHECK=.TRUE.
IF(PRESENT(LDCHECK)) LLCHECK=LDCHECK
LLCHANGEMODEL=.TRUE.
IF(PRESENT(LDCHANGEMODEL)) LLCHANGEMODEL=LDCHANGEMODEL
IPRINT=0
IF(PRESENT(KPRINT)) IPRINT=KPRINT
!
!**       CST
!
IF(LLINIT) THEN
  IF(IPRINT==2) WRITE(UNIT=KLUOUT,FMT='('' MODD_CST '')')
  IF(PRESENT(PHYEX_IN)) CST=PHYEX_IN%CST
  CALL INI_CST()
  IF(IPRINT==2) CALL PRINT_CST(KLUOUT)
  IF(PRESENT(PHYEX_OUT)) PHYEX_OUT%CST=CST
ENDIF
!
!**       MICROPHYSICS SCHEME
!
IF(CMICRO=='ICE3' .OR. CMICRO=='ICE4' .OR. CMICRO=='LIMA') THEN
  IF(IPRINT==2) WRITE(UNIT=KLUOUT,FMT='('' MODD_PARAM_ICEN, MODD_RAIN_ICE_DESCRN, MODD_RAIN_ICE_PARAMN, MODD_CLOUDPARN '')')
  IF(LLCHANGEMODEL) THEN
    CALL CLOUDPAR_GOTO_MODEL(KFROM, KTO)
    CALL PARAM_ICE_GOTO_MODEL(KFROM, KTO)
    CALL RAIN_ICE_DESCR_GOTO_MODEL(KFROM, KTO)
    CALL RAIN_ICE_PARAM_GOTO_MODEL(KFROM, KTO)
  ENDIF
  IF(PRESENT(PHYEX_IN)) THEN
    PARAM_ICEN=PHYEX_IN%PARAM_ICEN
    RAIN_ICE_DESCRN=PHYEX_IN%RAIN_ICE_DESCRN
    RAIN_ICE_PARAMN=PHYEX_IN%RAIN_ICE_PARAMN
    CLOUDPARN=PHYEX_IN%CLOUDPARN
  ENDIF

  CALL PARAM_ICEN_INIT(HPROGRAM, KUNITNML, LDNEEDNAM, KLUOUT, &
                      &LDDEFAULTVAL, LDREADNAM, LDCHECK, KPRINT)
  IF(LLINIT) THEN
    CALL INI_RAIN_ICE(KLUOUT, PTSTEP, PDZMIN, CLOUDPARN%NSPLITR, CMICRO)
    CALL INI_TIWMX
  
    IF(RAIN_ICE_PARAMN%XFRMIN(16) > 0.) THEN
       CALL INI_SNOW(KLUOUT) ! Recalculate snow parameters :  XCCS = XFRMIN(16),XCXS = XFRMIN(17)
    ENDIF
  ENDIF

  IF(PRESENT(PHYEX_OUT)) THEN
    PHYEX_OUT%PARAM_ICEN=PARAM_ICEN
    PHYEX_OUT%RAIN_ICE_DESCRN=RAIN_ICE_DESCRN
    PHYEX_OUT%RAIN_ICE_PARAMN=RAIN_ICE_PARAMN
    PHYEX_OUT%CLOUDPARN=CLOUDPARN
  ENDIF
ENDIF
!
!**       SHALLOW CONVECTION SCHEME
!
IF(CSCONV=='EDKF') THEN
  IF(IPRINT==2) WRITE(UNIT=KLUOUT,FMT='('' MODD_PARAM_MFSHALL_n '')')
  IF(LLCHANGEMODEL) CALL PARAM_MFSHALL_GOTO_MODEL(KFROM, KTO)
  IF(PRESENT(PHYEX_IN)) PARAM_MFSHALLN=PHYEX_IN%PARAM_MFSHALLN

  CALL PARAM_MFSHALLN_INIT(HPROGRAM, KUNITNML, LDNEEDNAM, KLUOUT, &
                          &LDDEFAULTVAL, LDREADNAM, LDCHECK, KPRINT)
  IF(LLINIT) THEN
    CALL INI_MFSHALL()
  ENDIF

  IF(PRESENT(PHYEX_OUT)) PHYEX_OUT%PARAM_MFSHALLN=PARAM_MFSHALLN
ENDIF
!
!**       CLOUD SCHEME
!
IF(.TRUE.) THEN !Placeholder for configuration without cloud scheme or a different one
  IF(IPRINT==2) WRITE(UNIT=KLUOUT,FMT='('' MODD_NEB_n '')')
  IF(LLCHANGEMODEL) CALL NEB_GOTO_MODEL(KFROM, KTO)
  IF(PRESENT(PHYEX_IN)) NEBN=PHYEX_IN%NEBN

  CALL NEBN_INIT(HPROGRAM, KUNITNML, LDNEEDNAM, KLUOUT, &
                &LDDEFAULTVAL, LDREADNAM, LDCHECK, KPRINT)
  IF(LLINIT) THEN
    !Nothing to do, everything is read from namelist
  ENDIF

  IF(PRESENT(PHYEX_OUT)) PHYEX_OUT%NEBN=NEBN
ENDIF
!
!**       TURBULENCE SCHEME
!
IF(CTURB=='TKEL') THEN
  IF(IPRINT==2) WRITE(UNIT=KLUOUT,FMT='('' MODD_TURB_n MODD_CTURB '')')
  IF(LLCHANGEMODEL) CALL TURB_GOTO_MODEL(KFROM, KTO)
  IF(PRESENT(PHYEX_IN)) THEN
    TURBN=PHYEX_IN%TURBN
    CSTURB=PHYEX_IN%CSTURB
  ENDIF

  CALL CTURB_ASSOCIATE()
  CALL TURBN_INIT(HPROGRAM, KUNITNML, LDNEEDNAM, KLUOUT, &
                 &LDDEFAULTVAL, LDREADNAM, LDCHECK, KPRINT)
  IF(LLINIT) THEN
    CALL INI_TURB(HPROGRAM)
  ENDIF

  IF(PRESENT(PHYEX_OUT)) THEN
    PHYEX_OUT%TURBN=TURBN
    PHYEX_OUT%CSTURB=CSTURB
  ENDIF
ENDIF
!
!**       GLOBAL CONSISTENCY TESTS
!
IF(LLCHECK) THEN
  IF((CMICRO=='ICE3' .OR. CMICRO=='ICE4' .OR. CMICRO=='LIMA') .AND. CTURB=='TKEL') THEN
    IF ((CSUBG_AUCV_RC == 'ADJU' .OR. CSUBG_AUCV_RI == 'ADJU') .AND. CCONDENS /= 'GAUS') THEN
      CALL PRINT_MSG(NVERB_FATAL, 'GEN', 'INI_PHYEX', &
                    &"CSUBG_AUCV_RC and/or CSUBG_AUCV_RI cannot be 'ADJU' if CCONDENS is not 'GAUS'")
    ENDIF
    IF (.NOT. LHARAT .AND. LSTATNW) THEN
      CALL PRINT_MSG(NVERB_FATAL, 'GEN', 'INI_PHYEX', &
                    &'LSTATNW only tested in combination with HARATU and EDMFm!')
    ENDIF
  ENDIF
ENDIF

END SUBROUTINE INI_PHYEX
