MODULE MODD_IO
IMPLICIT NONE

INTEGER, PARAMETER :: NVERB_NO=0, NVERB_FATAL=1, NVERB_ERROR=2, NVERB_WARNING=3, NVERB_INFO=4, NVERB_DEBUG=5
INTEGER, SAVE :: N_ABORT_LEVEL = NVERB_ERROR
ENDMODULE MODD_IO
