MODULE MODE_IO_FIELD_WRITE_PHY
IMPLICIT NONE
INTERFACE IO_FIELD_WRITE_PHY
  MODULE PROCEDURE IO_FIELD_WRITE_PHY_BYNAME,  IO_FIELD_WRITE_PHY_BYFIELD
END INTERFACE
CONTAINS
SUBROUTINE IO_FIELD_WRITE(TPFILE,TZFIELD,PFIELD)
USE MODD_IO,         ONLY: TFILEDATA,NVERB_FATAL
USE MODD_FIELD, ONLY: TFIELDMETADATA
USE MODE_MSG,   ONLY: PRINT_MSG 
    !
    !*      0.1   Declarations of arguments
    !
    TYPE(TFILEDATA),           INTENT(IN) :: TPFILE
    CLASS(TFIELDMETADATA), INTENT(IN)      :: TZFIELD
    REAL, DIMENSION(:,:,:),    INTENT(IN) :: PFIELD   ! array containing the data field
    !
    CALL PRINT_MSG(NVERB_FATAL, 'GEN', 'IO_FIELD_WRITE', 'SHOULD NOT BE CALLED')
END SUBROUTINE IO_FIELD_WRITE
!
SUBROUTINE IO_FIELD_WRITE_PHY_BYFIELD(D,TPFILE,TZFIELD,PFIELD)
    USE MODD_DIMPHYEX, ONLY: DIMPHYEX_t
    USE MODD_IO,         ONLY: TFILEDATA,NVERB_FATAL
    USE MODD_FIELD, ONLY: TFIELDMETADATA
    USE MODE_MSG,   ONLY: PRINT_MSG 
    !
    !*      0.1   Declarations of arguments
    !
    TYPE(DIMPHYEX_t),          INTENT(IN) :: D
    TYPE(TFILEDATA),           INTENT(IN) :: TPFILE
    TYPE(TFIELDMETADATA), INTENT(IN)      :: TZFIELD
    REAL, DIMENSION(D%NIJT,D%NKT),    INTENT(IN) :: PFIELD   ! array containing the data field
    !
    CALL PRINT_MSG(NVERB_FATAL, 'GEN', 'IO_FIELD_WRITE_PHY', 'SHOULD NOT BE CALLED')
END SUBROUTINE IO_FIELD_WRITE_PHY_BYFIELD
!
SUBROUTINE IO_FIELD_WRITE_PHY_BYNAME(D, TPFILE, HNAME, PFIELD, KRESP, KOFFSET)
    USE MODD_DIMPHYEX, ONLY: DIMPHYEX_t
    USE MODD_IO,         ONLY: TFILEDATA,NVERB_FATAL
    USE MODE_MSG,   ONLY: PRINT_MSG 
    !
    !*      0.1   Declarations of arguments
    !
    TYPE(DIMPHYEX_t),          INTENT(IN) :: D
    TYPE(TFILEDATA),           INTENT(IN) :: TPFILE
    CHARACTER(LEN=*),                     INTENT(IN)  :: HNAME    ! name of the field to write
    REAL, DIMENSION(D%NIJT,D%NKT),    INTENT(IN) :: PFIELD   ! array containing the data field
    INTEGER,                    OPTIONAL, INTENT(OUT) :: KRESP    ! return-code
    INTEGER, DIMENSION(3),      OPTIONAL, INTENT(IN)  :: KOFFSET
    !
    CALL PRINT_MSG(NVERB_FATAL, 'GEN', 'IO_FIELD_WRITE_PHY', 'SHOULD NOT BE CALLED')
END SUBROUTINE IO_FIELD_WRITE_PHY_BYNAME
!
END MODULE MODE_IO_FIELD_WRITE_PHY

