MODULE MODE_IO_FIELD_WRITE
USE MODD_IO,         ONLY: TFILEDATA
USE MODD_FIELD, ONLY: TFIELDMETADATA
CONTAINS
SUBROUTINE IO_FIELD_WRITE(TPFILE,TZFIELD,PFIELD)
    !
    ! THIS ROUTINE IS TEMPORARY AND IS ONLY NEEDED BY MODE_TURB_HOR* WHICH HAVE NOT YET
    ! BEEN TRANSFORMED FOR GPU ADAPTATION
    !*      0.1   Declarations of arguments
    !
    TYPE(TFILEDATA),           INTENT(IN) :: TPFILE
    TYPE(TFIELDMETADATA), INTENT(IN)      :: TZFIELD
    REAL, DIMENSION(:,:,:),    INTENT(IN) :: PFIELD   ! array containing the data field
    !
    CALL ABORT
END SUBROUTINE IO_FIELD_WRITE
!
END MODULE MODE_IO_FIELD_WRITE
