MODULE MODE_IO_FIELD_WRITE
IMPLICIT NONE
CONTAINS
SUBROUTINE IO_FIELD_WRITE(TPFILE,TZFIELD,PFIELD)
USE MODD_IO,         ONLY: TFILEDATA,NVERB_FATAL
USE MODD_FIELD, ONLY: TFIELDMETADATA
USE MODE_MSG,        ONLY: PRINT_MSG 
    !
    ! THIS ROUTINE IS TEMPORARY AND IS ONLY NEEDED BY MODE_TURB_HOR* WHICH HAVE NOT YET
    ! BEEN TRANSFORMED FOR GPU ADAPTATION
    !*      0.1   Declarations of arguments
    !
    TYPE(TFILEDATA),           INTENT(IN) :: TPFILE
    TYPE(TFIELDMETADATA), INTENT(IN)      :: TZFIELD
    REAL, DIMENSION(:,:,:),    INTENT(IN) :: PFIELD   ! array containing the data field
    !
    CALL PRINT_MSG(NVERB_FATAL, 'GEN', 'IO_FIELD_WRITE', 'SHOULD NOT BE CALLED')
END SUBROUTINE IO_FIELD_WRITE
!
END MODULE MODE_IO_FIELD_WRITE
