MODULE MODE_IO_FIELD_WRITE_PHY
USE MODD_IO,         ONLY: TFILEDATA
USE MODD_FIELD, ONLY: TFIELDMETADATA
USE MODE_MSG,   ONLY: PRINT_MSG, NVERB_FATAL
IMPLICIT NONE
CONTAINS
SUBROUTINE IO_FIELD_WRITE(TPFILE,TZFIELD,PFIELD)
    !
    !*      0.1   Declarations of arguments
    !
    TYPE(TFILEDATA),           INTENT(IN) :: TPFILE
    TYPE(TFIELDMETADATA), INTENT(IN)      :: TZFIELD
    REAL, DIMENSION(:,:,:),    INTENT(IN) :: PFIELD   ! array containing the data field
    !
    CALL PRINT_MSG(NVERB_FATAL, 'GEN', 'IO_FIELD_WRITE', 'SHOULD NOT BE CALLED')
END SUBROUTINE IO_FIELD_WRITE
!
SUBROUTINE IO_FIELD_WRITE_PHY(D,TPFILE,TZFIELD,PFIELD)
    USE MODD_DIMPHYEX, ONLY: DIMPHYEX_t
    !
    !*      0.1   Declarations of arguments
    !
    TYPE(DIMPHYEX_t),          INTENT(IN) :: D
    TYPE(TFILEDATA),           INTENT(IN) :: TPFILE
    TYPE(TFIELDMETADATA), INTENT(IN)      :: TZFIELD
    REAL, DIMENSION(D%NIT,D%NJT,D%NKT),    INTENT(IN) :: PFIELD   ! array containing the data field
    !
    CALL PRINT_MSG(NVERB_FATAL, 'GEN', 'IO_FIELD_WRITE_PHY', 'SHOULD NOT BE CALLED')
END SUBROUTINE IO_FIELD_WRITE_PHY
!
END MODULE MODE_IO_FIELD_WRITE_PHY

