MODULE MODE_BUDGET
USE MODD_BUDGET, ONLY : TBUDGETDATA
IMPLICIT NONE
CONTAINS

SUBROUTINE BUDGET_STORE_INIT(TPBUDGET, HSOURCE, PVARS)
  TYPE(TBUDGETDATA),      INTENT(INOUT) :: TPBUDGET ! Budget datastructure
  CHARACTER(LEN=*),       INTENT(IN)    :: HSOURCE  ! Name of the source term
  REAL, DIMENSION(:,:,:), INTENT(IN)    :: PVARS    ! Current value to be stored
END SUBROUTINE BUDGET_STORE_INIT
!
SUBROUTINE BUDGET_STORE_INIT_PHY(D,TPBUDGET, HSOURCE, PVARS)
  USE MODD_DIMPHYEX, ONLY: DIMPHYEX_t
  TYPE(DIMPHYEX_t),       INTENT(IN)    :: D
  TYPE(TBUDGETDATA),      INTENT(INOUT) :: TPBUDGET ! Budget datastructure
  CHARACTER(LEN=*),       INTENT(IN)    :: HSOURCE  ! Name of the source term
  REAL, DIMENSION(D%NIT,D%NJT,D%NKT), INTENT(IN)    :: PVARS    ! Current value to be stored
  CALL BUDGET_STORE_INIT(TPBUDGET, HSOURCE, PVARS)
END SUBROUTINE BUDGET_STORE_INIT_PHY
!
SUBROUTINE BUDGET_STORE_END(TPBUDGET, HSOURCE, PVARS)
  TYPE(TBUDGETDATA),      INTENT(INOUT) :: TPBUDGET ! Budget datastructure
  CHARACTER(LEN=*),       INTENT(IN)    :: HSOURCE  ! Name of the source term
  REAL, DIMENSION(:,:,:), INTENT(IN)    :: PVARS    ! Current value to be stored
END SUBROUTINE BUDGET_STORE_END
!
SUBROUTINE BUDGET_STORE_END_PHY(D,TPBUDGET, HSOURCE, PVARS)
  USE MODD_DIMPHYEX, ONLY: DIMPHYEX_t
  TYPE(DIMPHYEX_t),       INTENT(IN)    :: D
  TYPE(TBUDGETDATA),      INTENT(INOUT) :: TPBUDGET ! Budget datastructure
  CHARACTER(LEN=*),       INTENT(IN)    :: HSOURCE  ! Name of the source term
  REAL, DIMENSION(D%NIT,D%NJT,D%NKT), INTENT(IN)    :: PVARS    ! Current value to be stored
  CALL BUDGET_STORE_END(TPBUDGET, HSOURCE, PVARS)
END SUBROUTINE BUDGET_STORE_END_PHY
!
SUBROUTINE BUDGET_STORE_ADD_PHY(D,TPBUDGET, HSOURCE, PVARS)
  USE MODD_DIMPHYEX, ONLY: DIMPHYEX_t
  TYPE(DIMPHYEX_t),       INTENT(IN)    :: D
  TYPE(TBUDGETDATA),      INTENT(INOUT) :: TPBUDGET ! Budget datastructure
  CHARACTER(LEN=*),       INTENT(IN)    :: HSOURCE  ! Name of the source term
  REAL, DIMENSION(D%NIT,D%NJT,D%NKT), INTENT(IN)    :: PVARS    ! Current value to be stored
  CALL BUDGET_STORE_ADD(TPBUDGET, HSOURCE, PVARS)
END SUBROUTINE BUDGET_STORE_ADD_PHY
!
SUBROUTINE BUDGET_STORE_ADD(TPBUDGET, HSOURCE, PVARS)
  TYPE(TBUDGETDATA),      INTENT(INOUT) :: TPBUDGET ! Budget datastructure
  CHARACTER(LEN=*),       INTENT(IN)    :: HSOURCE  ! Name of the source term
  REAL, DIMENSION(:,:,:), INTENT(IN)    :: PVARS    ! Current value to be stored
  REAL, DIMENSION(SIZE(PVARS, 1), SIZE(PVARS, 2), SIZE(PVARS, 3)) :: ZVARS
END SUBROUTINE BUDGET_STORE_ADD
!
SUBROUTINE BUDGET_DDH(PVARS, KBUDN, HSOURCE, YDDDH, YDLDDH, YDMDDH, LDISDIFF)
  USE DDH_MIX, ONLY  : TYP_DDH
  USE YOMLDDH, ONLY  : TLDDH
  USE YOMMDDH, ONLY  : TMDDH

  REAL, DIMENSION(:,:,:), INTENT(IN)    :: PVARS    ! source of the variable
  INTEGER,                INTENT(IN)    :: KBUDN    ! variable number
  CHARACTER(LEN=*),       INTENT(IN)    :: HSOURCE  ! Identifier of the Budget
  TYPE(TYP_DDH),          INTENT(INOUT) :: YDDDH
  TYPE(TLDDH),            INTENT(IN)    :: YDLDDH
  TYPE(TMDDH),            INTENT(IN)    :: YDMDDH
  LOGICAL, OPTIONAL,      INTENT(IN)    :: LDISDIFF ! PVARS contains the increment (default is .FALSE.)
END SUBROUTINE BUDGET_DDH
END MODULE MODE_BUDGET
