MODULE MODI_SHALLOW_CONVECTION_PART2_SELECT

IMPLICIT NONE
INTERFACE

SUBROUTINE SHALLOW_CONVECTION_PART2_SELECT (CVP_SHAL, CVPEXT, CST, D, NSV, CONVPAR, KICE&
&, OSETTADJ, PTADJS, PPABST, PZZ, PTT, PRVT, PRCT, PRIT, OCH1CONV, KCH1, PCH1, PRDOCP,&
& PTHT, PSTHV, PSTHES, ISDPL, ISPBL, ISLCL, PSTHLCL, PSTLCL, PSRVLCL, PSWLCL, PSZLCL, PSTHVELCL&
&, GTRIG1, PUMF, PTHC, PRVC, PRCC, PRIC, ICTL, IMINCTL, PPCH1TEN, KIT_)

!$ACDC singlecolumn

USE MODD_CONVPAR,ONLY:CONVPAR_T
USE MODD_CONVPAR_SHAL,ONLY:CONVPAR_SHAL
USE MODD_CONVPAREXT,ONLY:CONVPAREXT
USE MODD_CST,ONLY:CST_T
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_NSV,ONLY:NSV_T

IMPLICIT NONE

TYPE (CONVPAR_SHAL), INTENT (IN)::CVP_SHAL
TYPE (CONVPAREXT), INTENT (IN)::CVPEXT
TYPE (CST_T), INTENT (IN)::CST
TYPE (DIMPHYEX_T), INTENT (IN)::D
TYPE (NSV_T), INTENT (IN)::NSV
TYPE (CONVPAR_T), INTENT (IN)::CONVPAR
INTEGER, INTENT (IN)::KICE
LOGICAL, INTENT (IN)::OSETTADJ
REAL, INTENT (IN)::PTADJS
REAL, INTENT (IN)::PTT(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRVT(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRCT(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRIT(D%NIJT, D%NKT)
REAL, INTENT (IN)::PPABST(D%NIJT, D%NKT)
REAL, INTENT (IN)::PZZ(D%NIJT, D%NKT)
LOGICAL, INTENT (IN)::OCH1CONV
INTEGER, INTENT (IN)::KCH1
REAL, INTENT (IN)::PCH1(D%NIJT, D%NKT, KCH1)
REAL, INTENT (IN)::PRDOCP
REAL, INTENT (IN)::PSTHES(D%NIJT, D%NKT)
REAL, INTENT (IN)::PSTHV(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHT(D%NIJT, D%NKT)
INTEGER, INTENT (IN)::ISDPL(D%NIJT)
INTEGER, INTENT (IN)::ISPBL(D%NIJT)
INTEGER, INTENT (IN)::ISLCL(D%NIJT)
REAL, INTENT (IN)::PSTHLCL(D%NIJT)
REAL, INTENT (IN)::PSTLCL(D%NIJT)
REAL, INTENT (IN)::PSRVLCL(D%NIJT)
REAL, INTENT (IN)::PSWLCL(D%NIJT)
REAL, INTENT (IN)::PSZLCL(D%NIJT)
REAL, INTENT (IN)::PSTHVELCL(D%NIJT)
LOGICAL, INTENT (IN)::GTRIG1(D%NIJT)
REAL, INTENT (OUT)::PUMF(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PTHC(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PRVC(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PRCC(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PRIC(D%NIJT, D%NKT)
INTEGER, INTENT (OUT)::ICTL(D%NIJT)
INTEGER, INTENT (OUT)::IMINCTL(D%NIJT)
REAL, INTENT (OUT)::PPCH1TEN(D%NIJT, D%NKT, KCH1)
INTEGER, INTENT (IN) :: KIT_


ENDSUBROUTINE SHALLOW_CONVECTION_PART2_SELECT

END INTERFACE

END MODULE
