!     ######spl
       MODULE MODI_ARO_TIWMX
!      ####################
!
INTERFACE
FUNCTION ARO_TIWMX(P,T,QR,FICE,QRSN,RS,EPS)
  REAL,  INTENT(IN)           ::  P,T,QR,FICE,EPS
  REAL,  INTENT(OUT)          :: QRSN,RS
END FUNCTION ARO_TIWMX
END INTERFACE
END MODULE MODI_ARO_TIWMX
