!     ######spl
       MODULE MODI_ARO_ICECLD
!      ####################
!
INTERFACE
SUBROUTINE ARO_ICECLD  &
     & ( PP,PZ,PDZ,PT,PR,PPBLH,PWCLD,XW2D, &
     &  SIFRC,SSIO,SSIU,W2D,RSI)
REAL,  INTENT(IN)  ::      PP
REAL,  INTENT(IN)  ::      PZ
REAL,  INTENT(IN)  ::      PDZ
REAL,  INTENT(IN)  ::      PT
REAL,  INTENT(IN)  ::      PR
REAL,  INTENT(IN)  ::      PPBLH
REAL,  INTENT(IN)  ::      PWCLD
REAL,  INTENT(IN)  ::      XW2D
REAL,  INTENT(OUT) ::      SIFRC
REAL,  INTENT(OUT) ::      SSIO
REAL,  INTENT(OUT) ::      SSIU
REAL,  INTENT(OUT) ::      W2D
REAL,  INTENT(OUT) ::      RSI
END SUBROUTINE ARO_ICECLD
END INTERFACE
END MODULE MODI_ARO_ICECLD
