SUBROUTINE ARO_CONVBU(KFDIA,KLEV,KRR,PRHODJ,PRRS,PTHS,YDDDH, YDLDDH, YDMDDH)
USE PARKIND1, ONLY : JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK, JPHOOK

USE MODD_BUDGET,ONLY: LBU_ENABLE, LBUDGET_TH, LBUDGET_RV, LBUDGET_RC, LBUDGET_RI
USE MODE_BUDGET_PHY, ONLY: BUDGET_DDH
USE DDH_MIX, ONLY  : TYP_DDH
USE YOMLDDH, ONLY  : TLDDH
USE YOMMDDH, ONLY  : TMDDH

IMPLICIT NONE

INTEGER, INTENT(IN) :: KFDIA
INTEGER, INTENT(IN) :: KLEV
INTEGER, INTENT(IN) :: KRR
REAL, DIMENSION (KFDIA,1,KLEV),  INTENT(IN) :: PRHODJ
REAL, DIMENSION(KFDIA,1,KLEV),   INTENT(IN) :: PTHS
REAL, DIMENSION(KFDIA,1,KLEV,KRR), INTENT(IN) :: PRRS
TYPE(TYP_DDH), INTENT(INOUT) :: YDDDH
TYPE(TLDDH), INTENT(IN) :: YDLDDH
TYPE(TMDDH), INTENT(IN) :: YDMDDH

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('ARO_CONVBU',0,ZHOOK_HANDLE)
IF (LBU_ENABLE) THEN
  IF (LBUDGET_TH)  CALL BUDGET_DDH (PTHS(:,:,:)*PRHODJ(:,:,:),4,'DCONV_BU_RTH',YDDDH, YDLDDH, YDMDDH)
  IF (LBUDGET_RV)  CALL BUDGET_DDH (PRRS(:,:,:,1)*PRHODJ(:,:,:),6,'DCONV_BU_RRV',YDDDH, YDLDDH, YDMDDH)
  IF (LBUDGET_RC)  CALL BUDGET_DDH (PRRS(:,:,:,2)*PRHODJ(:,:,:),7,'DCONV_BU_RRC',YDDDH, YDLDDH, YDMDDH)
  IF (LBUDGET_RI)  CALL BUDGET_DDH (PRRS(:,:,:,4)*PRHODJ(:,:,:),9,'DCONV_BU_RRI',YDDDH, YDLDDH, YDMDDH)
  !IF (LCHTRANS .AND. LBUDGET_SV) THEN
  !  DO JSV = 1, SIZE(PRSVS,4)
  !    CALL BUDGET_DDH (PRSVS(:,:,:,JSV),JSV+12,'DCONV_BU_RSV',YDDDH, YDLDDH, YDMDDH)
  !  END DO
  !END IF
END IF
IF (LHOOK) CALL DR_HOOK('ARO_CONVBU',1,ZHOOK_HANDLE)
END SUBROUTINE ARO_CONVBU
