INTERFACE
 SUBROUTINE ARO_TURB_MNH(PHYEX,                                         &
                       & KKA,KKU,KKL,KLON,KLEV,                         &
                       & KRR, KRRL, KRRI, KSV,                          &
                       & KGRADIENTSLEO, KGRADIENTSGOG, CMICRO, PTSTEP,  &
                       & PZZ, PZZF, PZS, PZZTOP,                        &
                       & PRHODJ, PTHVREF,                               &
                       & PSFTH, PSFRV, PSFSV, PSFU, PSFV,               &
                       & PPABSM, PUM, PVM, PWM, PTKEM, PSVM, PSRCM,     &
                       & PTHM, PRM,                                     &
                       & PRUS, PRVS, PRWS, PRTHS, PRRS,                 &
                       & PRSVSIN, PRSVS, PRTKES, PRTKES_OUT,            &
                       & PHGRADLEO, PHGRADGOG, PDELTAX, PDELTAY, PSIGS, &
                       & PFLXZTHVMF, PFLXZUMF, PFLXZVMF, PLENGTHM, PLENGTHH, MFMOIST,       &
                       & PDRUS_TURB, PDRVS_TURB,                        &
                       & PDRTHLS_TURB, PDRRTS_TURB, PDRSVS_TURB,        &
                       & PDP, PTP, PDPMF, PTPMF, PTDIFF, PTDISS, PEDR,         &
                       & YDDDH,YDLDDH,YDMDDH)

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE DDH_MIX, ONLY : TYP_DDH
USE YOMLDDH, ONLY  : TLDDH
USE YOMMDDH, ONLY  : TMDDH
USE MODD_PHYEX, ONLY: PHYEX_t

TYPE(PHYEX_t),            INTENT(IN)   :: PHYEX
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN)   :: KKA   !Index of nearest point to ground
INTEGER(KIND=JPIM), INTENT(IN)   :: KKU   !Index of nearest point to top
INTEGER(KIND=JPIM), INTENT(IN)   :: KKL   !vertical levels type
                                                ! 1=MNH -1=ARO

INTEGER(KIND=JPIM), INTENT(IN) :: KRR
INTEGER(KIND=JPIM), INTENT(IN) :: KRRL
INTEGER(KIND=JPIM), INTENT(IN) :: KRRI
INTEGER(KIND=JPIM), INTENT(IN) :: KSV
INTEGER(KIND=JPIM), INTENT(IN) :: KGRADIENTSLEO  ! Number of stored horizontal gradients
INTEGER(KIND=JPIM), INTENT(IN) :: KGRADIENTSGOG  ! Number of stored horizontal gradients
CHARACTER(LEN=4),        INTENT(IN)   :: CMICRO  ! Microphysics scheme
REAL(KIND=JPRB), INTENT(IN) :: PTSTEP
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PZZ
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PZZF
REAL(KIND=JPRB), DIMENSION(KLON),        INTENT(IN) :: PZS
REAL(KIND=JPRB), DIMENSION(KLON),        INTENT(IN) :: PZZTOP
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2), INTENT(INOUT) :: PRHODJ
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2), INTENT(INOUT)  :: MFMOIST
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2), INTENT(INOUT) :: PTHVREF
REAL(KIND=JPRB), DIMENSION(KLON,1), INTENT(INOUT) :: PSFTH,PSFRV
REAL(KIND=JPRB), DIMENSION(KLON,1), INTENT(INOUT) :: PSFU,PSFV
REAL(KIND=JPRB), DIMENSION(KLON,1,KSV), INTENT(INOUT) :: PSFSV
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2), INTENT(INOUT) :: PPABSM
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2), INTENT(INOUT) :: PUM,PVM,PWM
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2), INTENT(INOUT) :: PTKEM
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV,KSV), INTENT(IN)  :: PSVM
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2), INTENT(INOUT) :: PSRCM
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2), INTENT(INOUT)   :: PLENGTHM, PLENGTHH
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2), INTENT(INOUT) :: PTHM
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV,KRR), INTENT(INOUT) :: PRM
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2), INTENT(INOUT) :: PRUS,PRVS,PRWS
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2),   INTENT(INOUT) :: PRTHS
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV),     INTENT(IN)  ::  PRTKES
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2),   INTENT(OUT) ::  PRTKES_OUT
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV,KRR), INTENT(INOUT) :: PRRS
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV,KSV), INTENT(IN)  ::  PRSVSIN
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV,KSV), INTENT(OUT) ::  PRSVS
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV,KGRADIENTSLEO),   INTENT(INOUT) :: PHGRADLEO    
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV,KGRADIENTSGOG),   INTENT(INOUT) :: PHGRADGOG    
REAL(KIND=JPRB),                                         INTENT(IN   ) :: PDELTAX      
REAL(KIND=JPRB),                                         INTENT(IN   ) :: PDELTAY      

REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2), INTENT(OUT) :: PSIGS
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2), INTENT(OUT) :: PDRUS_TURB
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2), INTENT(OUT) :: PDRVS_TURB
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2), INTENT(OUT) :: PDRTHLS_TURB
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2), INTENT(OUT) :: PDRRTS_TURB
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV,KSV), INTENT(OUT) :: PDRSVS_TURB
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2), INTENT(INOUT) :: PFLXZTHVMF, PFLXZUMF, PFLXZVMF
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2),  INTENT(OUT)   :: PDP
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2),  INTENT(OUT)   :: PTP
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2),  INTENT(OUT)   :: PDPMF, PTPMF
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2),  INTENT(OUT)   :: PTDIFF
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2),  INTENT(OUT)   :: PTDISS
!                                                !for TKE DDH budgets
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV+2),   INTENT(OUT) ::  PEDR
TYPE(TYP_DDH),                     INTENT(INOUT) :: YDDDH
TYPE(TLDDH),                       INTENT(IN)    :: YDLDDH
TYPE(TMDDH),                       INTENT(IN)    :: YDMDDH
END SUBROUTINE ARO_TURB_MNH
END INTERFACE
