INTERFACE
SUBROUTINE AROINI_CONF(KULOUT,OWTOTL,OCARTESIAN)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KULOUT
LOGICAL, INTENT(IN) :: OWTOTL
LOGICAL, INTENT(IN) :: OCARTESIAN
END SUBROUTINE AROINI_CONF
END INTERFACE
