MODULE FIELD_GFL_WRAPPER

! New model fields  AJG 5/11/2012
!
! For initial implementation in the IFS, we will point at the old 
! GFL/GMV/GMVS and surface fields, to allow a progressive 
! changeover. This subroutine does that mapping.
!

!**   MODIFICATIONS
!     -------------

! B. Ingleby       2019-03-12 Add y2sh

USE PARKIND1           , ONLY : JPIM, JPRB
USE YOMHOOK            , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCT0             , ONLY : NUNDEFLD
USE SURFACE_FIELDS_MIX , ONLY : TSURF,TYPE_SURF_MTL
USE YOMGMV             , ONLY : TGMV
USE YOMGFL             , ONLY : TGFL
USE YOM_YGFL           , ONLY : TYPE_GFLD,TYPE_GFL_COMP
USE YOMLUN             , ONLY : NULOUT,NULERR

USE FIELD_DEFINITIONS_BASE, ONLY : JP_T0, JP_T9, JP_T1, JP_PC,JP_PT,TYPE_FVAR ,JP_T0_DL,JP_T0_DM,JP_T9_DL,JP_T9_DM,RESET_FVAR
USE FIELD_DEFINITIONS, ONLY : FID

IMPLICIT NONE

PRIVATE

INTEGER(KIND=JPIM), PARAMETER :: JP_NOT_SET = 0, JP_NOT_ACTIVE=-1

TYPE TGFL_MAP_INTERNAL  
INTEGER(KIND=JPIM), POINTER :: MT9_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MT1_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MT0_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MPC_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MPT_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MT0_DL_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MT0_DM_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MT9_DL_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MT9_DM_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MT0_SIZE(:) => NULL()
END TYPE TGFL_MAP_INTERNAL

PUBLIC GFL_AS_A_WHOLE, GFL_ATTACH, GFL_FID_SETUP, GFL_MAPPING_SETUP,GFL_MAP,&
 & TGFL_MAP_INTERNAL
#include "abor1.intfb.h"

contains

! ----------------------------------------------------------------------
! Attaches to the GFL blocks as a whole. I.e., this just gives out direct
! access to the GFL!
! ----------------------------------------------------------------------
SUBROUTINE GFL_AS_A_WHOLE(KBLOCK, KATTACH, YDGFL,PFPTR)

INTEGER(KIND=JPIM),       INTENT(IN)    :: KBLOCK     ! block number
INTEGER(KIND=JPIM),       INTENT(IN)    :: KATTACH    ! Attachment time level (e.g. T9, T0 etc.)
TYPE(TGFL),      TARGET,  INTENT(INOUT) :: YDGFL
REAL(KIND=JPRB), POINTER, INTENT(OUT)   :: PFPTR(:,:,:)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELD_GFL_WRAPPER:GFL_AS_A_WHOLE',0,ZHOOK_HANDLE)
ASSOCIATE(GFL=>YDGFL%GFL,GFLT1=>YDGFL%GFLT1,GFLPC=>YDGFL%GFLPC,GFLPT=>YDGFL%GFLPT)

IF (KATTACH == JP_T1) THEN
  PFPTR => GFLT1(:,:,:,KBLOCK)
ELSEIF (KATTACH == JP_PC) THEN
  PFPTR => GFLPC(:,:,:,KBLOCK)
ELSEIF (KATTACH == JP_PT) THEN
  PFPTR => GFLPT(:,:,:,KBLOCK)
ELSE
  PFPTR => GFL(:,:,:,KBLOCK)
ENDIF
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('FIELD_GFL_WRAPPER:GFL_AS_A_WHOLE',1,ZHOOK_HANDLE)
END SUBROUTINE GFL_AS_A_WHOLE

! ----------------------------------------------------------------------
! Sets up the the mapping between new fields and old
! NFTBC - not deallocated ever ....
! ----------------------------------------------------------------------
SUBROUTINE GFL_MAPPING_SETUP(YDMAP,YDGMV,YDGFL,YDGFLDESC, YDSURF,FVAR)
TYPE(TGFL_MAP_INTERNAL), INTENT(INOUT) :: YDMAP
TYPE(TGMV)             , INTENT(INOUT) :: YDGMV
TYPE(TGFL)             , INTENT(INOUT) :: YDGFL
TYPE(TYPE_GFLD)        , INTENT(IN)    :: YDGFLDESC
TYPE(TSURF)            , INTENT(INOUT) :: YDSURF
TYPE(TYPE_FVAR)        , INTENT(INOUT) :: FVAR(:)
LOGICAL :: LLFIRST
INTEGER(KIND=JPIM) :: JGFL
REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELD_GFL_WRAPPER:GFL_MAPPING_SETUP',0,ZHOOK_HANDLE)

ASSOCIATE(YSP_SBD=>YDSURF%YSP_SBD, YSD_VXD=>YDSURF%YSD_VXD, YSD_SFOD=>YDSURF%YSD_SFOD, &
 & YSD_SFLD=>YDSURF%YSD_SFLD, YSD_WWD=>YDSURF%YSD_WWD, YSD_VDD=>YDSURF%YSD_VDD, &
 & YSP_RR=>YDSURF%YSP_RR, YSD_WS=>YDSURF%YSD_WS, YSD_WW=>YDSURF%YSD_WW,NPROGSURFL=>YDSURF%NPROGSURFL, &
 & YSP_OM=>YDSURF%YSP_OM, YSP_EP=>YDSURF%YSP_EP, YSP_CL=>YDSURF%YSP_CL, &
 & YSP_CLD=>YDSURF%YSP_CLD, YSD_VFD=>YDSURF%YSD_VFD, YSP_CI=>YDSURF%YSP_CI, &
 & YSD_WSD=>YDSURF%YSD_WSD, YSD_VC=>YDSURF%YSD_VC, YSD_VP=>YDSURF%YSD_VP, &
 & YSP_SB=>YDSURF%YSP_SB,  YSP_X2D=>YDSURF%YSP_X2D, &
 & YSP_SL=>YDSURF%YSP_SL, YSP_X2=>YDSURF%YSP_X2, &
 & YSD_VK=>YDSURF%YSD_VK, YSD_VA=>YDSURF%YSD_VA, YSD_XR=>YDSURF%YSD_XR, YSD_VX=>YDSURF%YSD_VX, &
 & NSURFL=>YDSURF%NSURFL, &
 & YSD_VV=>YDSURF%YSD_VV,YSD_SM=>YDSURF%YSD_SM,&
 & YSD_VND=>YDSURF%YSD_VND, YSD_VHD=>YDSURF%YSD_VHD, YSD_VF=>YDSURF%YSD_VF, &
 & YSD_VD=>YDSURF%YSD_VD, YSP_OMD=>YDSURF%YSP_OMD, YSD_VH=>YDSURF%YSD_VH, &
 & YSD_XA=>YDSURF%YSD_XA, YSD_VN=>YDSURF%YSD_VN, YSD_V3=>YDSURF%YSD_V3, &
 & YSD_V2=>YDSURF%YSD_V2, YSP_SG=>YDSURF%YSP_SG, YSP_RRD=>YDSURF%YSP_RRD, &
 & YSD_DID=>YDSURF%YSD_DID, YSP_SGD=>YDSURF%YSP_SGD,&
 & YSPF=>YDGFLDESC%YSPF,YCVGQ=>YDGFLDESC%YCVGQ,YLRAD=>YDGFLDESC%YLRAD,YIRAD=>YDGFLDESC%YIRAD,YRSPEC=>YDGFLDESC%YRSPEC,YLRCH4=>YDGFLDESC%YLRCH4, &
 & YG=>YDGFLDESC%YG, YI=>YDGFLDESC%YI, YL=>YDGFLDESC%YL, YQ=>YDGFLDESC%YQ, YA=>YDGFLDESC%YA,&
 & YR=>YDGFLDESC%YR, YS=>YDGFLDESC%YS,YO3=>YDGFLDESC%YO3, YH=>YDGFLDESC%YH,YTKE=>YDGFLDESC%YTKE,YTTE=>YDGFLDESC%YTTE, &
 & YCPF=>YDGFLDESC%YCPF, YEFB1=>YDGFLDESC%YEFB1,YEFB2=>YDGFLDESC%YEFB2,YEFB3=>YDGFLDESC%YEFB3,YEXT=>YDGFLDESC%YEXT, &
 & YEZDIAG=>YDGFLDESC%YEZDIAG,YNOGW=>YDGFLDESC%YNOGW, &
 & YLCONV=>YDGFLDESC%YLCONV,YICONV=>YDGFLDESC%YICONV,YRCONV=>YDGFLDESC%YRCONV,YSCONV=>YDGFLDESC%YSCONV, &
 & YMXL=>YDGFLDESC%YMXL,YSRC=>YDGFLDESC%YSRC,YSHTUR=>YDGFLDESC%YSHTUR,YFQTUR=>YDGFLDESC%YFQTUR,YFSTUR=>YDGFLDESC%YFSTUR, &
 & YLMF=>YDGFLDESC%YLMF,  YIMF=>YDGFLDESC%YIMF,  YAMF=>YDGFLDESC%YAMF, &
 & YWMFC=>YDGFLDESC%YWMFC, YHLMF=>YDGFLDESC%YHLMF, YHLCFMF=>YDGFLDESC%YHLCFMF, YHIMF=>YDGFLDESC%YHIMF, YHICFMF=>YDGFLDESC%YHICFMF, &
 & YCVV=>YDGFLDESC%YCVV, YRKTH=>YDGFLDESC%YRKTH,YRKTQV=>YDGFLDESC%YRKTQV,YRKTQC=>YDGFLDESC%YRKTQC,YUOM=>YDGFLDESC%YUOM, &
 & YUAL=>YDGFLDESC%YUAL,YDOM=>YDGFLDESC%YDOM,YDAL=>YDGFLDESC%YDAL,YUEN=>YDGFLDESC%YUEN,YUNEBH=>YDGFLDESC%YUNEBH, &
 & NGHG=>YDGFLDESC%NGHG, NCHEM=>YDGFLDESC%NCHEM, NAERO=>YDGFLDESC%NAERO, &
 & YGHG=>YDGFLDESC%YGHG, YCHEM=>YDGFLDESC%YCHEM, YAERO=>YDGFLDESC%YAERO, &
 & NNOGW=>YDGFLDESC%NNOGW, &
 & YPH9=>YDGMV%YPH9,YT9=>YDGMV%YT9,YT1=>YDGMV%YT1,YT0=>YDGMV%YT0,GMV=>YDGMV%GMV, GMVS=>YDGMV%GMVS,GMVT1=>YDGMV%GMVT1)

IF(ASSOCIATED(YDMAP%MT0_MAP)) THEN
  IF (LHOOK) CALL DR_HOOK('FIELD_GFL_WRAPPER:GFL_MAPPING_SETUP',1,ZHOOK_HANDLE)
  RETURN
ENDIF

! === T0 mapping ===
ALLOCATE(YDMAP%MT0_MAP(SIZE(FVAR)))
ALLOCATE(YDMAP%MT0_SIZE(SIZE(FVAR)))
YDMAP%MT0_MAP = JP_NOT_SET
YDMAP%MT0_SIZE = JP_NOT_SET
! GMV
LLFIRST = .TRUE.
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%U,YT0%MU,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V,YT0%MV,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%DIV,YT0%MDIV,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VOR,YT0%MVOR,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%T,YT0%MT,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%PD,YT0%MSPD,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD,YT0%MSVD,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%NHX,YT0%MNHX,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%EDOT,YT0%MEDOT,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SGRTL,YT0%MSGRTL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SGRTM,YT0%MSGRTM,LDFIRST=LLFIRST)
! GFL
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%Q,YQ%MP,YDGFLC=YQ)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%O3,YO3%MP,YDGFLC=YO3)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%L,YL%MP,YDGFLC=YL)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%I,YI%MP,YDGFLC=YI)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%A,YA%MP,YDGFLC=YA)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%S,YS%MP,YDGFLC=YS)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%R,YR%MP,YDGFLC=YR)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%G,YG%MP,YDGFLC=YG)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%H,YH%MP,YDGFLC=YH)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%LRCH4,YLRCH4%MP,YDGFLC=YLRCH4)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%LCONV,YLCONV%MP,YDGFLC=YLCONV)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%ICONV,YICONV%MP,YDGFLC=YICONV)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%RCONV,YRCONV%MP,YDGFLC=YRCONV)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SCONV,YSCONV%MP,YDGFLC=YSCONV)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%TKE,YTKE%MP,YDGFLC=YTKE)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%TTE,YTTE%MP,YDGFLC=YTTE)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%EFB1,YEFB1%MP,YDGFLC=YEFB1)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%EFB2,YEFB2%MP,YDGFLC=YEFB2)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%EFB3,YEFB3%MP,YDGFLC=YEFB3)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%MXL,YMXL%MP,YDGFLC=YMXL)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SRC,YSRC%MP,YDGFLC=YSRC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%LMF,YLMF%MP,YDGFLC=YLMF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%IMF,YIMF%MP,YDGFLC=YIMF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%AMF,YAMF%MP,YDGFLC=YAMF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WMFC,YWMFC%MP,YDGFLC=YWMFC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%HLMF,YHLMF%MP,YDGFLC=YHLMF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%HLCFMF,YHLCFMF%MP,YDGFLC=YHLCFMF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%HIMF,YHIMF%MP,YDGFLC=YHIMF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%HICFMF,YHICFMF%MP,YDGFLC=YHICFMF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SHTUR,YSHTUR%MP,YDGFLC=YSHTUR)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%FQTUR,YFQTUR%MP,YDGFLC=YFQTUR)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%FSTUR,YFSTUR%MP,YDGFLC=YFSTUR)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%CVV,YCVV%MP,YDGFLC=YCVV)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%RKTH,YRKTH%MP,YDGFLC=YRKTH)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%RKTQV,YRKTQV%MP,YDGFLC=YRKTQV)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%RKTQC,YRKTQC%MP,YDGFLC=YRKTQC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%CPF,YCPF%MP,YDGFLC=YCPF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SPF,YSPF%MP,YDGFLC=YSPF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%CVGQ,YCVGQ%MP,YDGFLC=YCVGQ)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%LRAD,YLRAD%MP,YDGFLC=YLRAD)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%IRAD,YIRAD%MP,YDGFLC=YIRAD)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%RSPEC,YRSPEC%MP,YDGFLC=YRSPEC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%UOM,YUOM%MP,YDGFLC=YUOM)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%UAL,YUAL%MP,YDGFLC=YUAL)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%DOM,YDOM%MP,YDGFLC=YDOM)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%DAL,YDAL%MP,YDGFLC=YDAL)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%UEN,YUEN%MP,YDGFLC=YUEN)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%UNEBH,YUNEBH%MP,YDGFLC=YUNEBH)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%EXTRA3D,YEXT(1)%MP,YDGFLC=YEXT(1))
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%EZDIAG,YEZDIAG(1)%MP,YDGFLC=YEZDIAG(1))
IF (NNOGW == 2) THEN
  CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%UNOGW,YNOGW(1)%MP,YDGFLC=YNOGW(1))
  CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VNOGW,YNOGW(2)%MP,YDGFLC=YNOGW(2))
ENDIF

! GMVS
LLFIRST = .TRUE.
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SP,YT0%MSP,LDFIRST=LLFIRST)
! Group SB
IF  (YDSURF%NSURF > 0) THEN
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SB_Q,YSP_SB%YQ%MP,YDSURF=YSP_SB%YQ)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SB_T,YSP_SB%YT%MP,YDSURF=YSP_SB%YT)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SB_TL,YSP_SB%YTL%MP,YDSURF=YSP_SB%YTL)
  ! Group SG   
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SG_F,YSP_SG%YF%MP,YDSURF=YSP_SG%YF)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SG_A,YSP_SG%YA%MP,YDSURF=YSP_SG%YA)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SG_R,YSP_SG%YR%MP,YDSURF=YSP_SG%YR)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SG_T,YSP_SG%YT%MP,YDSURF=YSP_SG%YT)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SG_W,YSP_SG%YW%MP,YDSURF=YSP_SG%YW)
! Group SL     
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SL_LICT,YSP_SL%YLICT%MP,YDSURF=YSP_SL%YLICT)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SL_LMLT,YSP_SL%YLMLT%MP,YDSURF=YSP_SL%YLMLT)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SL_LTLT,YSP_SL%YLTLT%MP,YDSURF=YSP_SL%YLTLT)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SL_LBLT,YSP_SL%YLBLT%MP,YDSURF=YSP_SL%YLBLT)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SL_LSHF,YSP_SL%YLSHF%MP,YDSURF=YSP_SL%YLSHF)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SL_LICD,YSP_SL%YLICD%MP,YDSURF=YSP_SL%YLICD)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SL_LMLD,YSP_SL%YLMLD%MP,YDSURF=YSP_SL%YLMLD)
! Group RR
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%RR_T,YSP_RR%YT%MP,YDSURF=YSP_RR%YT)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%RR_W,YSP_RR%YW%MP,YDSURF=YSP_RR%YW)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%RR_FC,YSP_RR%YFC%MP,YDSURF=YSP_RR%YFC)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%RR_IC,YSP_RR%YIC%MP,YDSURF=YSP_RR%YIC)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%RR_FP1,YSP_RR%YFP1%MP,YDSURF=YSP_RR%YFP1)
!Group CL
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%CL_TCLS,YSP_CL%YTCLS%MP,YDSURF=YSP_CL%YTCLS)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%CL_HUCLS,YSP_CL%YHUCLS%MP,YDSURF=YSP_CL%YHUCLS)
!Group OM
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%OM_TO,YSP_OM%YTO%MP,YDSURF=YSP_OM%YTO)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%OM_SO,YSP_OM%YSO%MP,YDSURF=YSP_OM%YSO)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%OM_UO,YSP_OM%YUO%MP,YDSURF=YSP_OM%YUO)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%OM_VO,YSP_OM%YVO%MP,YDSURF=YSP_OM%YVO)
! Group EP
!YDMAP%MT0_MAP(FID%EP_EP) = YSP_EP%YEP%MP
! Group X2
!YDMAP%MT0_MAP(FID%X2_X2) = YSP_X2%YX2%MP
! Group CI
!YDMAP%MT0_MAP(FID%CI_CI) = YSP_CI%YCI%MP

! Group VF
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_Z0F,YSD_VF%YZ0F%MP,YDSURF=YSD_VF%YZ0F)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_ALBF,YSD_VF%YALBF%MP,YDSURF=YSD_VF%YALBF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_EMISF,YSD_VF%YEMISF%MP,YDSURF=YSD_VF%YEMISF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_GETRL,YSD_VF%YGETRL%MP,YDSURF=YSD_VF%YGETRL)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_LSM,YSD_VF%YLSM%MP,YDSURF=YSD_VF%YLSM)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_VEG,YSD_VF%YVEG%MP,YDSURF=YSD_VF%YVEG)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_VRLAN,YSD_VF%YVRLAN%MP,YDSURF=YSD_VF%YVRLAN)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_VRLDI,YSD_VF%YVRLDI%MP,YDSURF=YSD_VF%YVRLDI)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_SIG,YSD_VF%YSIG%MP,YDSURF=YSD_VF%YSIG)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_ALBSF,YSD_VF%YALBSF%MP,YDSURF=YSD_VF%YALBSF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_LAN,YSD_VF%YLAN%MP,YDSURF=YSD_VF%YLAN)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_SST,YSD_VF%YSST%MP,YDSURF=YSD_VF%YSST)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_SSS,YSD_VF%YSSS%MP,YDSURF=YSD_VF%YSSS)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_LZ0H,YSD_VF%YLZ0H%MP,YDSURF=YSD_VF%YLZ0H)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_CVL,YSD_VF%YCVL%MP,YDSURF=YSD_VF%YCVL)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_CO2TYP,YSD_VF%YCO2TYP%MP,YDSURF=YSD_VF%YCO2TYP)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_CVH,YSD_VF%YCVH%MP,YDSURF=YSD_VF%YCVH)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_FWET,YSD_VF%YFWET%MP,YDSURF=YSD_VF%YFWET)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_CUR,YSD_VF%YCUR%MP,YDSURF=YSD_VF%YCUR)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_TVL,YSD_VF%YTVL%MP,YDSURF=YSD_VF%YTVL)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_TVH,YSD_VF%YTVH%MP,YDSURF=YSD_VF%YTVH)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_LAIL,YSD_VF%YLAIL%MP,YDSURF=YSD_VF%YLAIL)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_LAIH,YSD_VF%YLAIH%MP,YDSURF=YSD_VF%YLAIH)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_SOTY,YSD_VF%YSOTY%MP,YDSURF=YSD_VF%YSOTY)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_CLK,YSD_VF%YCLK%MP,YDSURF=YSD_VF%YCLK)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_DL,YSD_VF%YDL%MP,YDSURF=YSD_VF%YDL)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_CI,YSD_VF%YCI%MP,YDSURF=YSD_VF%YCI)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_UCUR,YSD_VF%YUCUR%MP,YDSURF=YSD_VF%YUCUR)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_VCUR,YSD_VF%YVCUR%MP,YDSURF=YSD_VF%YVCUR)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_Z0RLF,YSD_VF%YZ0RLF%MP,YDSURF=YSD_VF%YZ0RLF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_CGPP,YSD_VF%YCGPP%MP,YDSURF=YSD_VF%YCGPP)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_CREC,YSD_VF%YCREC%MP,YDSURF=YSD_VF%YCREC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_SDFOR,YSD_VF%YSDFOR%MP,YDSURF=YSD_VF%YSDFOR)
! 4-component MODIS albedo climatology
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_ALUVP,YSD_VF%YALUVP%MP,YDSURF=YSD_VF%YALUVP)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_ALUVD,YSD_VF%YALUVD%MP,YDSURF=YSD_VF%YALUVD)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_ALNIP,YSD_VF%YALNIP%MP,YDSURF=YSD_VF%YALNIP)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_ALNID,YSD_VF%YALNID%MP,YDSURF=YSD_VF%YALNID)
! 6-component MODIS albedo climatology
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_ALUVI,YSD_VF%YALUVI%MP,YDSURF=YSD_VF%YALUVI)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_ALNII,YSD_VF%YALNII%MP,YDSURF=YSD_VF%YALNII)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_ALUVV,YSD_VF%YALUVV%MP,YDSURF=YSD_VF%YALUVV)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_ALNIV,YSD_VF%YALNIV%MP,YDSURF=YSD_VF%YALNIV)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_ALUVG,YSD_VF%YALUVG%MP,YDSURF=YSD_VF%YALUVG)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_ALNIG,YSD_VF%YALNIG%MP,YDSURF=YSD_VF%YALNIG)
!
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_FP1,YSD_VF%YFP1%MP,YDSURF=YSD_VF%YFP1)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_SO2DD,YSD_VF%YSO2DD%MP,YDSURF=YSD_VF%YSO2DD)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_DMSO,YSD_VF%YDMSO%MP,YDSURF=YSD_VF%YDMSO)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_URBF,YSD_VF%YURBF%MP,YDSURF=YSD_VF%YURBF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_FCA1,YSD_VF%YFCA1%MP,YDSURF=YSD_VF%YFCA1)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_FCA2,YSD_VF%YFCA2%MP,YDSURF=YSD_VF%YFCA2)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_AERDEP,YSD_VF%YAERDEP%MP,YDSURF=YSD_VF%YAERDEP)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_AERLTS,YSD_VF%YAERLTS%MP,YDSURF=YSD_VF%YAERLTS)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_AERSCC,YSD_VF%YAERSCC%MP,YDSURF=YSD_VF%YAERSCC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_DSF,YSD_VF%YDSF%MP,YDSURF=YSD_VF%YDSF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_DSZ,YSD_VF%YDSZ%MP,YDSURF=YSD_VF%YDSZ)
 !YDMAP%MT0_MAP(FID%VF_CHEMDV) = YSD_VF%YCHEMDV%MP ! CHEMISTRY DEPOSITION VELOCITY
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_CHEMFLXO,YSD_VF%YCHEMFLXO(1)%MP,YDSURF=YSD_VF%YCHEMFLXO(1),&
 & KFIELDS=SIZE(YSD_VF%YCHEMFLXO),KMAPFIELDS=YDMAP%MT0_SIZE) ! CHEMISTRY EMISSIONS
WRITE(NULOUT,*) 'SET_MAP YCHEMFLXO ',YSD_VF%YCHEMFLXO(1)%MP,SIZE(YSD_VF%YCHEMFLXO),YDMAP%MT0_SIZE(FID%VF_CHEMFLXO)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_CHEMWDFLX,YSD_VF%YCHEMWDFLX(1)%MP,YDSURF=YSD_VF%YCHEMWDFLX(1),&
 & KFIELDS=SIZE(YSD_VF%YCHEMWDFLX),KMAPFIELDS=YDMAP%MT0_SIZE) ! CHEMISTRY WET DEPOSITION 
WRITE(NULOUT,*) 'SET_MAP YCHEMWDFLX ',YSD_VF%YCHEMWDFLX(1)%MP,SIZE(YSD_VF%YCHEMWDFLX),YDMAP%MT0_SIZE(FID%VF_CHEMWDFLX)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_CHEMDDFLX,YSD_VF%YCHEMDDFLX(1)%MP,YDSURF=YSD_VF%YCHEMDDFLX(1),&
 & KFIELDS=SIZE(YSD_VF%YCHEMDDFLX),KMAPFIELDS=YDMAP%MT0_SIZE) ! CHEMISTRY DRY DEPOSITION 
WRITE(NULOUT,*) 'SET_MAP YCHEMDDFLX ',YSD_VF%YCHEMDDFLX(1)%MP,SIZE(YSD_VF%YCHEMDDFLX),YDMAP%MT0_SIZE(FID%VF_CHEMDDFLX)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_CHEMDV,YSD_VF%YCHEMDV(1)%MP,YDSURF=YSD_VF%YCHEMDV(1),&
 & KFIELDS=SIZE(YSD_VF%YCHEMDV) ,KMAPFIELDS=YDMAP%MT0_SIZE) ! CHEMISTRY DEPOSITION VELOCITY
WRITE(NULOUT,*) 'SET_MAP YCHEMDV ',YSD_VF%YCHEMDV(1)%MP,SIZE(YSD_VF%YCHEMDV),YDMAP%MT0_SIZE(FID%VF_CHEMDV)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_NUDM,YSD_VF%YNUDM%MP,YDSURF=YSD_VF%YNUDM)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_EMIS2D,YSD_VF%YEMIS2D(1)%MP,YDSURF=YSD_VF%YEMIS2D(1),&
 & KFIELDS=SIZE(YSD_VF%YEMIS2D) ,KMAPFIELDS=YDMAP%MT0_SIZE) ! 2D EMISSIONS FOR COMPOSITION
WRITE(NULOUT,*) 'SET_MAP YEMIS2D ',YSD_VF%YEMIS2D(1)%MP,SIZE(YSD_VF%YEMIS2D),YDMAP%MT0_SIZE(FID%VF_EMIS2D)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VF_EMIS2DAUX,YSD_VF%YEMIS2DAUX(1)%MP,YDSURF=YSD_VF%YEMIS2DAUX(1),&
 & KFIELDS=SIZE(YSD_VF%YEMIS2DAUX) ,KMAPFIELDS=YDMAP%MT0_SIZE) ! 2D EMISSION AUX FIELDS FOR COMPOSITION
WRITE(NULOUT,*) 'SET_MAP YEMIS2DAUX ',YSD_VF%YEMIS2DAUX(1)%MP,SIZE(YSD_VF%YEMIS2DAUX),YDMAP%MT0_SIZE(FID%VF_EMIS2DAUX)
! * Group VP=VCLIP: deep soil diagnostic fields
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VP_TPC,YSD_VP%YTPC%MP,YDSURF=YSD_VP%YTPC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VP_WPC,YSD_VP%YWPC%MP,YDSURF=YSD_VP%YWPC)
! * Group VV=VCLIV: vegetation diagnostic fields:
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VV_ARG,YSD_VV%YARG%MP,YDSURF=YSD_VV%YARG)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VV_SAB,YSD_VV%YSAB%MP,YDSURF=YSD_VV%YSAB)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VV_D2,YSD_VV%YD2%MP,YDSURF=YSD_VV%YD2)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VV_IVEG,YSD_VV%YIVEG%MP,YDSURF=YSD_VV%YIVEG)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VV_RSMIN,YSD_VV%YRSMIN%MP,YDSURF=YSD_VV%YRSMIN)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VV_LAI,YSD_VV%YLAI%MP,YDSURF=YSD_VV%YLAI)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VV_HV,YSD_VV%YHV%MP,YDSURF=YSD_VV%YHV)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VV_Z0H,YSD_VV%YZ0H%MP,YDSURF=YSD_VV%YZ0H)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VV_ALS,YSD_VV%YALS%MP,YDSURF=YSD_VV%YALS)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VV_ALV,YSD_VV%YALV%MP,YDSURF=YSD_VV%YALV)
! * Group VN=VCLIN: cloudiness diagnostic predictors:
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VN_TOP,YSD_VN%YTOP%MP,YDSURF=YSD_VN%YTOP)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VN_BAS,YSD_VN%YBAS%MP,YDSURF=YSD_VN%YBAS)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VN_ACPR,YSD_VN%YACPR%MP,YDSURF=YSD_VN%YACPR)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VN_ACCPR,YSD_VN%YACCPR%MP,YDSURF=YSD_VN%YACCPR)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VN_ACCPR5,YSD_VN%YACCPR5%MP,YDSURF=YSD_VN%YACCPR5)
! * Group VH=VCLIH: convective cloud diagnostic fields:
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VH_TCCH,YSD_VH%YTCCH%MP,YDSURF=YSD_VH%YTCCH)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VH_SCCH,YSD_VH%YSCCH%MP,YDSURF=YSD_VH%YSCCH)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VH_BCCH,YSD_VH%YBCCH%MP,YDSURF=YSD_VH%YBCCH)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VH_PBLH,YSD_VH%YPBLH%MP,YDSURF=YSD_VH%YPBLH)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VH_SPSH,YSD_VH%YSPSH%MP,YDSURF=YSD_VH%YSPSH)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VH_SPSH,YSD_VH%YSPSH%MP,YDSURF=YSD_VH%YSPSH)
! Group VA=VCLIA: aerosol diagnostic fields:
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VA_SEA,YSD_VA%YSEA%MP,YDSURF=YSD_VA%YSEA)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VA_LAN,YSD_VA%YLAN%MP,YDSURF=YSD_VA%YLAN)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VA_SOO,YSD_VA%YSOO%MP,YDSURF=YSD_VA%YSOO)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VA_DES,YSD_VA%YDES%MP,YDSURF=YSD_VA%YDES)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VA_SUL,YSD_VA%YSUL%MP,YDSURF=YSD_VA%YSUL)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VA_VOL,YSD_VA%YVOL%MP,YDSURF=YSD_VA%YVOL)
!!$! Group  VG=VCLIG: ice-coupler diagnostic fields (currently unused)
!!$YDMAP%MT0_MAP(FID%VG_ICFR) = YSD_VG%YICFR%MP
!!$YDMAP%MT0_MAP(FID%VG_SOUP) = YSD_VG%YSOUP%MP
!!$YDMAP%MT0_MAP(FID%VG_IRUP) = YSD_VG%YIRUP%MP
!!$YDMAP%MT0_MAP(FID%VG_CHSS) = YSD_VG%YCHSS%MP
!!$YDMAP%MT0_MAP(FID%VG_EVAP) = YSD_VG%YEVAP%MP
!!$YDMAP%MT0_MAP(FID%VG_TAUX) = YSD_VG%YTAUX%MP
!!$YDMAP%MT0_MAP(FID%VG_TAUY) = YSD_VG%YTAUY%MP
!  Group VC=VO3ABC: A,B and C (Climatological ozone profiles) diagnostic fields
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VC_A,YSD_VC%YA%MP,YDSURF=YSD_VC%YA)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VC_B,YSD_VC%YB%MP,YDSURF=YSD_VC%YB)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VC_C,YSD_VC%YC%MP,YDSURF=YSD_VC%YC)
! Group V2=VDIAGO2: 2-D climatological/diagnostic fields for an ocean mixed layer model (KPP)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V2_OCDEP,YSD_V2%YOCDEP%MP,YDSURF=YSD_V2%YOCDEP)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V2_USTRC,YSD_V2%YUSTRC%MP,YDSURF=YSD_V2%YUSTRC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V2_VSTRC,YSD_V2%YVSTRC%MP,YDSURF=YSD_V2%YVSTRC)
! Group V3=VDIAGO3: 3-D climatological/diagnostic fields for an ocean mixed layer model (KPP or TKE):
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V3_DIFM,YSD_V3%YDIFM%MP,YDSURF=YSD_V3%YDIFM)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V3_DIFT,YSD_V3%YDIFT%MP,YDSURF=YSD_V3%YDIFT)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V3_DIFS,YSD_V3%YDIFS%MP,YDSURF=YSD_V3%YDIFS)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V3_ADVT,YSD_V3%YADVT%MP,YDSURF=YSD_V3%YADVT)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V3_ADVS,YSD_V3%YADVS%MP,YDSURF=YSD_V3%YADVS)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V3_TRI0,YSD_V3%YTRI0%MP,YDSURF=YSD_V3%YTRI0)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V3_TRI1,YSD_V3%YTRI1%MP,YDSURF=YSD_V3%YTRI1)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V3_SWDK,YSD_V3%YSWDK%MP,YDSURF=YSD_V3%YSWDK)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V3_ZO,YSD_V3%YZO%MP,YDSURF=YSD_V3%YZO)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V3_HO,YSD_V3%YHO%MP,YDSURF=YSD_V3%YHO)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V3_DO,YSD_V3%YDO%MP,YDSURF=YSD_V3%YDO)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V3_HO_INV,YSD_V3%YHO_INV%MP,YDSURF=YSD_V3%YHO_INV)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V3_UOC,YSD_V3%YUOC%MP,YDSURF=YSD_V3%YUOC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V3_VOC,YSD_V3%YVOC%MP,YDSURF=YSD_V3%YVOC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%V3_OTKE,YSD_V3%YOTKE%MP,YDSURF=YSD_V3%YOTKE)

! * Group VD=VDIAG: (ECMWF) diagnostic fields:
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_LSP,YSD_VD%YLSP%MP,YDSURF=YSD_VD%YLSP)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_CP,YSD_VD%YCP%MP,YDSURF=YSD_VD%YCP)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SF,YSD_VD%YSF%MP,YDSURF=YSD_VD%YSF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_FZRA,YSD_VD%YFZRA%MP,YDSURF=YSD_VD%YFZRA)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_BLD,YSD_VD%YBLD%MP,YDSURF=YSD_VD%YBLD)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SSHF,YSD_VD%YSSHF%MP,YDSURF=YSD_VD%YSSHF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SLHF,YSD_VD%YSLHF%MP,YDSURF=YSD_VD%YSLHF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_NEE,YSD_VD%YNEE%MP,YDSURF=YSD_VD%YNEE)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_GPP,YSD_VD%YGPP%MP,YDSURF=YSD_VD%YGPP)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_REC,YSD_VD%YREC%MP,YDSURF=YSD_VD%YREC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ACH4,YSD_VD%YACH4%MP,YDSURF=YSD_VD%YACH4)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_MSL,YSD_VD%YMSL%MP,YDSURF=YSD_VD%YMSL)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SP,YSD_VD%YSP%MP,YDSURF=YSD_VD%YSP)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TCC,YSD_VD%YTCC%MP,YDSURF=YSD_VD%YTCC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_10U,YSD_VD%Y10U%MP,YDSURF=YSD_VD%Y10U)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_10V,YSD_VD%Y10V%MP,YDSURF=YSD_VD%Y10V)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_2T,YSD_VD%Y2T%MP,YDSURF=YSD_VD%Y2T)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_2D,YSD_VD%Y2D%MP,YDSURF=YSD_VD%Y2D)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_2SH,YSD_VD%Y2SH%MP,YDSURF=YSD_VD%Y2SH)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SSR,YSD_VD%YSSR%MP,YDSURF=YSD_VD%YSSR)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_STR,YSD_VD%YSTR%MP,YDSURF=YSD_VD%YSTR)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TSR,YSD_VD%YTSR%MP,YDSURF=YSD_VD%YTSR)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TTR,YSD_VD%YTTR%MP,YDSURF=YSD_VD%YTTR)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_EWSS,YSD_VD%YEWSS%MP,YDSURF=YSD_VD%YEWSS)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_NSSS,YSD_VD%YNSSS%MP,YDSURF=YSD_VD%YNSSS)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_E,YSD_VD%YE%MP,YDSURF=YSD_VD%YE)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_PEV,YSD_VD%YPEV%MP,YDSURF=YSD_VD%YPEV)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_CCC,YSD_VD%YCCC%MP,YDSURF=YSD_VD%YCCC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_LCC,YSD_VD%YLCC%MP,YDSURF=YSD_VD%YLCC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_MCC,YSD_VD%YMCC%MP,YDSURF=YSD_VD%YMCC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_HCC,YSD_VD%YHCC%MP,YDSURF=YSD_VD%YHCC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_LGWS,YSD_VD%YLGWS%MP,YDSURF=YSD_VD%YLGWS)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_MGWS,YSD_VD%YMGWS%MP,YDSURF=YSD_VD%YMGWS)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_GWD,YSD_VD%YGWD%MP,YDSURF=YSD_VD%YGWD)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_MX2T,YSD_VD%YMX2T%MP,YDSURF=YSD_VD%YMX2T)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_MN2T,YSD_VD%YMN2T%MP,YDSURF=YSD_VD%YMN2T)
!YDMAP%MT0_MAP(FID%VD_MX2T6) = YSD_VD%YMX2T6%MP 
!YDMAP%MT0_MAP(FID%VD_MN2T6) = YSD_VD%YMN2T6%MP 
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_RO,YSD_VD%YRO%MP,YDSURF=YSD_VD%YRO)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SRO,YSD_VD%YSRO%MP,YDSURF=YSD_VD%YSRO)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SSRO,YSD_VD%YSSRO%MP,YDSURF=YSD_VD%YSSRO)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ALB,YSD_VD%YALB%MP,YDSURF=YSD_VD%YALB)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_IEWSS,YSD_VD%YIEWSS%MP,YDSURF=YSD_VD%YIEWSS)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_INSSS,YSD_VD%YINSSS%MP,YDSURF=YSD_VD%YINSSS)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ISSHF,YSD_VD%YISSHF%MP,YDSURF=YSD_VD%YISSHF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_IE,YSD_VD%YIE%MP,YDSURF=YSD_VD%YIE)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_INEE,YSD_VD%YINEE%MP,YDSURF=YSD_VD%YINEE)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_IGPP,YSD_VD%YIGPP%MP,YDSURF=YSD_VD%YIGPP)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_IREC,YSD_VD%YIREC%MP,YDSURF=YSD_VD%YIREC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ICH4,YSD_VD%YICH4%MP,YDSURF=YSD_VD%YICH4)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_CSF,YSD_VD%YCSF%MP,YDSURF=YSD_VD%YCSF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_LSSF,YSD_VD%YLSSF%MP,YDSURF=YSD_VD%YLSSF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_MXTPR,YSD_VD%YMXTPR%MP,YDSURF=YSD_VD%YMXTPR)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_MNTPR,YSD_VD%YMNTPR%MP,YDSURF=YSD_VD%YMNTPR)
!YDMAP%MT0_MAP(FID%VD_MXTPR6) = YSD_VD%YMXTPR6%MP 
!YDMAP%MT0_MAP(FID%VD_MNTPR6) = YSD_VD%YMNTPR6%MP 
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TPR,YSD_VD%YTPR%MP,YDSURF=YSD_VD%YTPR)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_LSRR,YSD_VD%YLSRR%MP,YDSURF=YSD_VD%YLSRR)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_CRR,YSD_VD%YCRR%MP,YDSURF=YSD_VD%YCRR)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_LSSFR,YSD_VD%YLSSFR%MP,YDSURF=YSD_VD%YLSSFR)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_CSFR,YSD_VD%YCSFR%MP,YDSURF=YSD_VD%YCSFR)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_PTYPE,YSD_VD%YPTYPE%MP,YDSURF=YSD_VD%YPTYPE)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ILSPF,YSD_VD%YILSPF%MP,YDSURF=YSD_VD%YILSPF)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_Z0F,YSD_VD%YZ0F%MP,YDSURF=YSD_VD%YZ0F)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_LZ0H,YSD_VD%YLZ0H%MP,YDSURF=YSD_VD%YLZ0H)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TCW,YSD_VD%YTCW%MP,YDSURF=YSD_VD%YTCW)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TCWV,YSD_VD%YTCWV%MP,YDSURF=YSD_VD%YTCWV)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TCLW,YSD_VD%YTCLW%MP,YDSURF=YSD_VD%YTCLW)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TCIW,YSD_VD%YTCIW%MP,YDSURF=YSD_VD%YTCIW)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TCRW,YSD_VD%YTCRW%MP,YDSURF=YSD_VD%YTCRW)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TCSW,YSD_VD%YTCSW%MP,YDSURF=YSD_VD%YTCSW)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TCSLW,YSD_VD%YTCSLW%MP,YDSURF=YSD_VD%YTCSLW)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SSRD,YSD_VD%YSSRD%MP,YDSURF=YSD_VD%YSSRD)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_STRD,YSD_VD%YSTRD%MP,YDSURF=YSD_VD%YSTRD)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SSRDC,YSD_VD%YSSRDC%MP,YDSURF=YSD_VD%YSSRDC)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_STRDC,YSD_VD%YSTRDC%MP,YDSURF=YSD_VD%YSTRDC)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_BLH,YSD_VD%YBLH%MP,YDSURF=YSD_VD%YBLH)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SUND,YSD_VD%YSUND%MP,YDSURF=YSD_VD%YSUND)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SPAR,YSD_VD%YSPAR%MP,YDSURF=YSD_VD%YSPAR)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SUVB,YSD_VD%YSUVB%MP,YDSURF=YSD_VD%YSUVB)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SFDIR,YSD_VD%YSFDIR%MP,YDSURF=YSD_VD%YSFDIR)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SCDIR,YSD_VD%YSCDIR%MP,YDSURF=YSD_VD%YSCDIR)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SDSRP,YSD_VD%YSDSRP%MP,YDSURF=YSD_VD%YSDSRP)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_CAPE,YSD_VD%YCAPE%MP,YDSURF=YSD_VD%YCAPE)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_CAPES,YSD_VD%YCAPES%MP,YDSURF=YSD_VD%YCAPES)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_MUCAPE,YSD_VD%YMUCAPE%MP,YDSURF=YSD_VD%YMUCAPE)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_PDEPL,YSD_VD%YPDEPL%MP,YDSURF=YSD_VD%YPDEPL)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_MLCAPE50,YSD_VD%YMLCAPE50%MP,YDSURF=YSD_VD%YMLCAPE50)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_MLCAPE100,YSD_VD%YMLCAPE100%MP,YDSURF=YSD_VD%YMLCAPE100)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_MLCIN50,YSD_VD%YMLCIN50%MP,YDSURF=YSD_VD%YMLCIN50)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_MLCIN100,YSD_VD%YMLCIN100%MP,YDSURF=YSD_VD%YMLCIN100)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TROPOTP,YSD_VD%YTROPOTP%MP,YDSURF=YSD_VD%YTROPOTP)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TSRC,YSD_VD%YTSRC%MP,YDSURF=YSD_VD%YTSRC)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TTRC,YSD_VD%YTTRC%MP,YDSURF=YSD_VD%YTTRC)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SSRC,YSD_VD%YSSRC%MP,YDSURF=YSD_VD%YSSRC)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_STRC,YSD_VD%YSTRC%MP,YDSURF=YSD_VD%YSTRC)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ES,YSD_VD%YES%MP,YDSURF=YSD_VD%YES)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SMLT,YSD_VD%YSMLT%MP,YDSURF=YSD_VD%YSMLT)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_10FG,YSD_VD%Y10FG%MP,YDSURF=YSD_VD%Y10FG)
 !YDMAP%MT0_MAP(FID%VD_10FG6) = YSD_VD%Y10FG6%MP 
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_10FGCV,YSD_VD%Y10FGCV%MP,YDSURF=YSD_VD%Y10FGCV)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_I10FG,YSD_VD%YI10FG%MP,YDSURF=YSD_VD%YI10FG)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_LSPF,YSD_VD%YLSPF%MP,YDSURF=YSD_VD%YLSPF)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TCO3,YSD_VD%YTCO3%MP,YDSURF=YSD_VD%YTCO3)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_VIMD,YSD_VD%YVIMD%MP,YDSURF=YSD_VD%YVIMD)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SPARC,YSD_VD%YSPARC%MP,YDSURF=YSD_VD%YSPARC)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_STINC,YSD_VD%YSTINC%MP,YDSURF=YSD_VD%YSTINC)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_CBASE,YSD_VD%YCBASE%MP,YDSURF=YSD_VD%YCBASE)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_0DEGL,YSD_VD%Y0DEGL%MP,YDSURF=YSD_VD%Y0DEGL)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_M10DEGL,YSD_VD%YM10DEGL%MP,YDSURF=YSD_VD%YM10DEGL)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_VISIH,YSD_VD%YVISIH%MP,YDSURF=YSD_VD%YVISIH)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_CIN,YSD_VD%YCIN%MP,YDSURF=YSD_VD%YCIN)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_KINDEX,YSD_VD%YKINDEX%MP,YDSURF=YSD_VD%YKINDEX)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TTINDEX,YSD_VD%YTTINDEX%MP,YDSURF=YSD_VD%YTTINDEX)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_CBASEA,YSD_VD%YCBASEA%MP,YDSURF=YSD_VD%YCBASEA)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_CTOPC,YSD_VD%YCTOPC%MP,YDSURF=YSD_VD%YCTOPC)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ZTWETB0,YSD_VD%YZTWETB0%MP,YDSURF=YSD_VD%YZTWETB0)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ZTWETB1,YSD_VD%YZTWETB1%MP,YDSURF=YSD_VD%YZTWETB1)
 !YDMAP%MT0_MAP(FID%VD_TCGHG) = YSD_VD%YTCGHG%MP 
 !YDMAP%MT0_MAP(FID%VD_TCCHEM) = YSD_VD%YTCCHEM%MP 
!YDMAP%MT0_MAP(FID%VD_AERODIAG) = YSD_VD%YAERODIAG%MP 
!YDMAP%MT0_MAP(FID%VD_AERO_WVL_DIAG) = YSD_VD%YAERO_WVL_DIAG%MP 
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_100U,YSD_VD%Y100U%MP,YDSURF=YSD_VD%Y100U)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_100V,YSD_VD%Y100V%MP,YDSURF=YSD_VD%Y100V)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ZUST,YSD_VD%YZUST%MP,YDSURF=YSD_VD%YZUST)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_10NU,YSD_VD%Y10NU%MP,YDSURF=YSD_VD%Y10NU)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_10NV,YSD_VD%Y10NV%MP,YDSURF=YSD_VD%Y10NV)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_DNDZN,YSD_VD%YDNDZN%MP,YDSURF=YSD_VD%YDNDZN)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_DNDZA,YSD_VD%YDNDZA%MP,YDSURF=YSD_VD%YDNDZA)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_DCTB,YSD_VD%YDCTB%MP,YDSURF=YSD_VD%YDCTB)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TPLB,YSD_VD%YTPLB%MP,YDSURF=YSD_VD%YTPLB)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_TPLT,YSD_VD%YTPLT%MP,YDSURF=YSD_VD%YTPLT)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ODSS,YSD_VD%YODSS%MP,YDSURF=YSD_VD%YODSS)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ODDU,YSD_VD%YODDU%MP,YDSURF=YSD_VD%YODDU)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ODOM,YSD_VD%YODOM%MP,YDSURF=YSD_VD%YODOM)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ODBC,YSD_VD%YODBC%MP,YDSURF=YSD_VD%YODBC)
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ODSU,YSD_VD%YODSU%MP,YDSURF=YSD_VD%YODSU)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ODNI,YSD_VD%YODNI%MP,YDSURF=YSD_VD%YODNI)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ODAM,YSD_VD%YODAM%MP,YDSURF=YSD_VD%YODAM)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ODSOA,YSD_VD%YODSOA%MP,YDSURF=YSD_VD%YODSOA)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ODVFA,YSD_VD%YODVFA%MP,YDSURF=YSD_VD%YODVFA)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ODVSU,YSD_VD%YODVSU%MP,YDSURF=YSD_VD%YODVSU)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_ODTOACC,YSD_VD%YODTOACC%MP,YDSURF=YSD_VD%YODTOACC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_AEPM1,YSD_VD%YAEPM1%MP,YDSURF=YSD_VD%YAEPM1)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_AEPM25,YSD_VD%YAEPM25%MP,YDSURF=YSD_VD%YAEPM25)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_AEPM10,YSD_VD%YAEPM10%MP,YDSURF=YSD_VD%YAEPM10)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_UVBED,YSD_VD%YUVBED%MP,YDSURF=YSD_VD%YUVBED)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_UVBEDCS,YSD_VD%YUVBEDCS%MP,YDSURF=YSD_VD%YUVBEDCS)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_LITOTI,YSD_VD%YLITOTI%MP,YDSURF=YSD_VD%YLITOTI)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_LICGI,YSD_VD%YLICGI%MP,YDSURF=YSD_VD%YLICGI)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_200U,YSD_VD%Y200U%MP,YDSURF=YSD_VD%Y200U)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_200V,YSD_VD%Y200V%MP,YDSURF=YSD_VD%Y200V)

CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VD_SDSL,YSD_VD%YSDSL%MP,YDSURF=YSD_VD%YSDSL)

! Group SM=SATSIM: (ECMWF) simulated satellite images
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SM_CLBT,YSD_SM%YCLBT%MP,YDSURF=YSD_SM%YCLBT)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%SM_CSBT,YSD_SM%YCSBT%MP,YDSURF=YSD_SM%YCSBT)

! Group WS=WAVES: surface prognostic quantities over sea (used by IFS)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WS_CHAR,YSD_WS%YCHAR%MP,YDSURF=YSD_WS%YCHAR)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WS_CHARHQ,YSD_WS%YCHARHQ%MP,YDSURF=YSD_WS%YCHARHQ)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WS_USTOKES,YSD_WS%YUSTOKES%MP,YDSURF=YSD_WS%YUSTOKES)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WS_VSTOKES,YSD_WS%YVSTOKES%MP,YDSURF=YSD_WS%YVSTOKES)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WS_TAUOCX,YSD_WS%YTAUOCX%MP,YDSURF=YSD_WS%YTAUOCX)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WS_TAUOCY,YSD_WS%YTAUOCY%MP,YDSURF=YSD_WS%YTAUOCY)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WS_PHIOC,YSD_WS%YPHIOC%MP,YDSURF=YSD_WS%YPHIOC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WS_WSEMEAN,YSD_WS%YWSEMEAN%MP,YDSURF=YSD_WS%YWSEMEAN)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WS_WSFMEAN,YSD_WS%YWSFMEAN%MP,YDSURF=YSD_WS%YWSFMEAN)

! Group WS=WAVES: surface prognostic quantities over sea (used by WAM)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WW_U10N,YSD_WW%YU10N%MP,YDSURF=YSD_WW%YU10N)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WW_V10N,YSD_WW%YV10N%MP,YDSURF=YSD_WW%YV10N)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WW_RHO,YSD_WW%YRHO%MP,YDSURF=YSD_WW%YRHO)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WW_ZIL,YSD_WW%YZIL%MP,YDSURF=YSD_WW%YZIL)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WW_CIF,YSD_WW%YCIF%MP,YDSURF=YSD_WW%YCIF)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WW_CLK,YSD_WW%YCLK%MP,YDSURF=YSD_WW%YCLK)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WW_USTRW,YSD_WW%YUSTRW%MP,YDSURF=YSD_WW%YUSTRW)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WW_VSTRW,YSD_WW%YVSTRW%MP,YDSURF=YSD_WW%YVSTRW)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WW_UCURW,YSD_WW%YUCURW%MP,YDSURF=YSD_WW%YUCURW)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%WW_VCURW,YSD_WW%YVCURW%MP,YDSURF=YSD_WW%YVCURW)

! * Group VX=VCLIX: auxilary climatological diagnostic fields:
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VX_ORO,YSD_VX%YORO%MP,YDSURF=YSD_VX%YORO)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VX_TSC,YSD_VX%YTSC%MP,YDSURF=YSD_VX%YTSC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VX_PWS,YSD_VX%YPWS%MP,YDSURF=YSD_VX%YPWS)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VX_PWP,YSD_VX%YPWP%MP,YDSURF=YSD_VX%YPWP)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VX_SNO,YSD_VX%YSNO%MP,YDSURF=YSD_VX%YSNO)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VX_TPC,YSD_VX%YTPC%MP,YDSURF=YSD_VX%YTPC)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VX_SAB,YSD_VX%YSAB%MP,YDSURF=YSD_VX%YSAB)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VX_XD2,YSD_VX%YXD2%MP,YDSURF=YSD_VX%YXD2)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VX_LSM,YSD_VX%YLSM%MP,YDSURF=YSD_VX%YLSM)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VX_IVEG,YSD_VX%YIVEG%MP,YDSURF=YSD_VX%YIVEG)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VX_ARG,YSD_VX%YARG%MP,YDSURF=YSD_VX%YARG)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VX_RSMIN,YSD_VX%YRSMIN%MP,YDSURF=YSD_VX%YRSMIN)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VX_LAI,YSD_VX%YLAI%MP,YDSURF=YSD_VX%YLAI)
CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VX_VEG,YSD_VX%YVEG%MP,YDSURF=YSD_VX%YVEG)
! * Group VK=VCLIK: Convective cloud pseudo-historic fields:
 CALL SET_MAP(FVAR,YDMAP%MT0_MAP,FID%VK_UDGRO,YSD_VK%YUDGRO%MP,YDSURF=YSD_VK%YUDGRO)
ENDIF 


! === T9 mapping ===
ALLOCATE(YDMAP%MT9_MAP(SIZE(FVAR)))
YDMAP%MT9_MAP = JP_NOT_SET

! GMV
LLFIRST = .TRUE.
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%U,YT9%MU,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%V,YT9%MV,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%T,YT9%MT,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%DIV,YT9%MDIV,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%EDOT,YT9%MEDOT,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SGRTL,YT9%MSGRTL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SGRTM,YT9%MSGRTM,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%UNL,YT9%MUNL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%UNL_SI,YT9%MUNL_SI,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%VNL,YT9%MVNL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%VNL_SI,YT9%MVNL_SI,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%TNL,YT9%MTNL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%TNL_SI,YT9%MTNL_SI,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SPNL,YT9%MSPNL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SPNL_SI,YT9%MSPNL_SI,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%VWVNL,YT9%MVWVNL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%VDNL_SI,YT9%MSVDNL_SI,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%PDNL,YT9%MSPDNL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%PDNL_SI,YT9%MSPDNL_SI,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%GW,YT9%MGW,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CURHS,YT9%MCURHS,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CVRHS,YT9%MCVRHS,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CTRHS,YT9%MCTRHS,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CSPRHS,YT9%MCSPRHS,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CSPDRHS,YT9%MCSPDRHS,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CSVDRHS,YT9%MCSVDRHS,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CUNL,YT9%MCUNL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CVNL,YT9%MCVNL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CTNL,YT9%MCTNL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CSPNL,YT9%MCSPNL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CVWVNL,YT9%MCVWVNL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CSPDNL,YT9%MCSPDNL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CUPT,YT9%MCUPT,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CVPT,YT9%MCVPT,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CTPT,YT9%MCTPT,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CPDPT,YT9%MCSPDPT,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CVDPT,YT9%MCSVDPT,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%DPHI,YT9%MDPHI,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%NHXNL,YT9%MNHXNL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CNHXNL,YT9%MCNHXNL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CSPPT,YT9%MCSPPT,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%DBBC,YT9%MDBBC,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%GWS,YT9%MGWS,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%PD,YT9%MSPD,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%VD,YT9%MSVD,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%NHX,YT9%MNHX,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%NHX,YT9%MNHX,LDFIRST=LLFIRST)
!!CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%NHY,YT9%MNHY,LDFIRST=LLFIRST)


! GMVS
LLFIRST = .TRUE.
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SP,YT9%MSP,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CSPPT,YT9%MCSPPT,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%DBBC,YT9%MDBBC,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%GWS,YT9%MGWS,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SPNL2,YT9%MSPNL2,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CSPNL2,YT9%MCSPNL2,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%PREHYDS,YT9%MPREHYDS,LDFIRST=LLFIRST)

! GFL
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%Q,YQ%MP9,YDGFLC=YQ)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%O3,YO3%MP9,YDGFLC=YO3)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%L,YL%MP9,YDGFLC=YL)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%I,YI%MP9,YDGFLC=YI)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%A,YA%MP9,YDGFLC=YA)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%S,YS%MP9,YDGFLC=YS)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%R,YR%MP9,YDGFLC=YR)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%G,YG%MP9,YDGFLC=YG)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%H,YH%MP9,YDGFLC=YH)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%TKE,YTKE%MP9,YDGFLC=YTKE)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%TTE,YTTE%MP9,YDGFLC=YTTE)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%MXL,YMXL%MP9,YDGFLC=YMXL)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SRC,YSRC%MP9,YDGFLC=YSRC)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%LMF,YLMF%MP9,YDGFLC=YLMF)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%IMF,YIMF%MP9,YDGFLC=YIMF)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%AMF,YAMF%MP9,YDGFLC=YAMF)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%WMFC,YWMFC%MP9,YDGFLC=YWMFC)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%HLMF,YHLMF%MP9,YDGFLC=YHLMF)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%HLCFMF,YHLCFMF%MP9,YDGFLC=YHLCFMF)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%HIMF,YHIMF%MP9,YDGFLC=YHIMF)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%HICFMF,YHICFMF%MP9,YDGFLC=YHICFMF)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SHTUR,YSHTUR%MP9,YDGFLC=YSHTUR)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%FQTUR,YFQTUR%MP9,YDGFLC=YFQTUR)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%FSTUR,YFSTUR%MP9,YDGFLC=YFSTUR)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CVV,YCVV%MP9,YDGFLC=YCVV)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%RKTH,YRKTH%MP9,YDGFLC=YRKTH)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%RKTQV,YRKTQV%MP9,YDGFLC=YRKTQV)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%RKTQC,YRKTQC%MP9,YDGFLC=YRKTQC)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CPF,YCPF%MP9,YDGFLC=YCPF)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SPF,YSPF%MP9,YDGFLC=YSPF)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%LRAD,YLRAD%MP9,YDGFLC=YLRAD)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%IRAD,YIRAD%MP9,YDGFLC=YIRAD)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%UOM,YUOM%MP9,YDGFLC=YUOM)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%UAL,YUAL%MP9,YDGFLC=YUAL)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%DOM,YDOM%MP9,YDGFLC=YDOM)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%DAL,YDAL%MP9,YDGFLC=YDAL)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%UEN,YUEN%MP9,YDGFLC=YUEN)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%UNEBH,YUNEBH%MP9,YDGFLC=YUNEBH)
  ! Group SB   
IF  (YDSURF%NSURF > 0) THEN
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SB_Q,YSP_SB%YQ%MP9,YDSURF=YSP_SB%YQ)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SB_T,YSP_SB%YT%MP9,YDSURF=YSP_SB%YT)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SB_TL,YSP_SB%YTL%MP9,YDSURF=YSP_SB%YTL)
  ! Group SG   
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SG_F,YSP_SG%YF%MP9,YDSURF=YSP_SG%YF)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SG_A,YSP_SG%YA%MP9,YDSURF=YSP_SG%YA)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SG_R,YSP_SG%YR%MP9,YDSURF=YSP_SG%YR)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SG_T,YSP_SG%YT%MP9,YDSURF=YSP_SG%YT)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SG_W,YSP_SG%YW%MP9,YDSURF=YSP_SG%YW)
! Groub SL     
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SL_LICT,YSP_SL%YLICT%MP9,YDSURF=YSP_SL%YLICT)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SL_LMLT,YSP_SL%YLMLT%MP9,YDSURF=YSP_SL%YLMLT)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SL_LTLT,YSP_SL%YLTLT%MP9,YDSURF=YSP_SL%YLTLT)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SL_LBLT,YSP_SL%YLBLT%MP9,YDSURF=YSP_SL%YLBLT)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SL_LSHF,YSP_SL%YLSHF%MP9,YDSURF=YSP_SL%YLSHF)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SL_LICD,YSP_SL%YLICD%MP9,YDSURF=YSP_SL%YLICD)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%SL_LMLD,YSP_SL%YLMLD%MP9,YDSURF=YSP_SL%YLMLD)
! Group RR
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%RR_T,YSP_RR%YT%MP9,YDSURF=YSP_RR%YT)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%RR_W,YSP_RR%YW%MP9,YDSURF=YSP_RR%YW)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%RR_FC,YSP_RR%YFC%MP9,YDSURF=YSP_RR%YFC)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%RR_IC,YSP_RR%YIC%MP9,YDSURF=YSP_RR%YIC)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%RR_FP1,YSP_RR%YFP1%MP9,YDSURF=YSP_RR%YFP1)
!Group CL
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CL_TCLS,YSP_CL%YTCLS%MP9,YDSURF=YSP_CL%YTCLS)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%CL_HUCLS,YSP_CL%YHUCLS%MP9,YDSURF=YSP_CL%YHUCLS)
!Group OM
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%OM_TO,YSP_OM%YTO%MP9,YDSURF=YSP_OM%YTO)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%OM_SO,YSP_OM%YSO%MP9,YDSURF=YSP_OM%YSO)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%OM_UO,YSP_OM%YUO%MP9,YDSURF=YSP_OM%YUO)
CALL SET_MAP(FVAR,YDMAP%MT9_MAP,FID%OM_VO,YSP_OM%YVO%MP9,YDSURF=YSP_OM%YVO)
ENDIF

! Group EP
!YDMAP%MT9_MAP(FID%EP_EP) = YSP_EP%YEP%MP9
! Group X2
!YDMAP%MT9_MAP(FID%X2_X2) = YSP_X2%YX2%MP9
! Group CI
!YDMAP%MT9_MAP(FID%CI_CI) = YSP_CI%YCI%MP9


! === T1 mapping ===
ALLOCATE(YDMAP%MT1_MAP(SIZE(FVAR)))
YDMAP%MT1_MAP = JP_NOT_SET

! GMV
LLFIRST = .TRUE.
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%U,YT1%MU,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%V,YT1%MV,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%T,YT1%MT,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%PD,YT1%MSPD,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%VD,YT1%MSVD,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%NHX,YT1%MNHX,LDFIRST=LLFIRST)

! GFL
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%Q,YQ%MP1,YDGFLC=YQ)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%O3,YO3%MP1,YDGFLC=YO3)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%L,YL%MP1,YDGFLC=YL)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%I,YI%MP1,YDGFLC=YI)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%A,YA%MP1,YDGFLC=YA)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%S,YS%MP1,YDGFLC=YS)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%R,YR%MP1,YDGFLC=YR)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%G,YG%MP1,YDGFLC=YG)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%H,YH%MP1,YDGFLC=YH)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%TKE,YTKE%MP1,YDGFLC=YTKE)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%TTE,YTTE%MP1,YDGFLC=YTTE)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%MXL,YMXL%MP1,YDGFLC=YMXL)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%SRC,YSRC%MP1,YDGFLC=YSRC)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%LMF,YLMF%MP1,YDGFLC=YLMF)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%IMF,YIMF%MP1,YDGFLC=YIMF)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%AMF,YAMF%MP1,YDGFLC=YAMF)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%WMFC,YWMFC%MP1,YDGFLC=YWMFC)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%HLMF,YHLMF%MP1,YDGFLC=YHLMF)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%HLCFMF,YHLCFMF%MP1,YDGFLC=YHLCFMF)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%HIMF,YHIMF%MP1,YDGFLC=YHIMF)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%HICFMF,YHICFMF%MP1,YDGFLC=YHICFMF)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%SHTUR,YSHTUR%MP1,YDGFLC=YSHTUR)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%FQTUR,YFQTUR%MP1,YDGFLC=YFQTUR)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%FSTUR,YFSTUR%MP1,YDGFLC=YFSTUR)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%CVV,YCVV%MP1,YDGFLC=YCVV)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%RKTH,YRKTH%MP1,YDGFLC=YRKTH)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%RKTQV,YRKTQV%MP1,YDGFLC=YRKTQV)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%RKTQC,YRKTQC%MP1,YDGFLC=YRKTQC)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%CPF,YCPF%MP1,YDGFLC=YCPF)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%SPF,YSPF%MP1,YDGFLC=YSPF)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%LRAD,YLRAD%MP1,YDGFLC=YLRAD)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%IRAD,YIRAD%MP1,YDGFLC=YIRAD)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%UOM,YUOM%MP1,YDGFLC=YUOM)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%UAL,YUAL%MP1,YDGFLC=YUAL)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%DOM,YDOM%MP1,YDGFLC=YDOM)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%DAL,YDAL%MP1,YDGFLC=YDAL)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%UEN,YUEN%MP1,YDGFLC=YUEN)
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%UNEBH,YUNEBH%MP1,YDGFLC=YUNEBH)


! GMVS

LLFIRST = .TRUE.
CALL SET_MAP(FVAR,YDMAP%MT1_MAP,FID%SP,YT1%MSP,LDFIRST=LLFIRST)

! Mapping for predictor corrector scheme 

ALLOCATE(YDMAP%MPC_MAP(SIZE(FVAR)))
YDMAP%MPC_MAP = JP_NOT_SET
! GFL
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%Q,YQ%MPPC,YDGFLC=YQ)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%O3,YO3%MPPC,YDGFLC=YO3)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%L,YL%MPPC,YDGFLC=YL)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%I,YI%MPPC,YDGFLC=YI)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%A,YA%MPPC,YDGFLC=YA)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%S,YS%MPPC,YDGFLC=YS)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%R,YR%MPPC,YDGFLC=YR)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%G,YG%MPPC,YDGFLC=YG)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%H,YH%MPPC,YDGFLC=YH)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%TKE,YTKE%MPPC,YDGFLC=YTKE)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%TTE,YTTE%MPPC,YDGFLC=YTTE)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%MXL,YMXL%MPPC,YDGFLC=YMXL)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%SRC,YSRC%MPPC,YDGFLC=YSRC)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%LMF,YLMF%MPPC,YDGFLC=YLMF)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%IMF,YIMF%MPPC,YDGFLC=YIMF)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%AMF,YAMF%MPPC,YDGFLC=YAMF)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%WMFC,YWMFC%MPPC,YDGFLC=YWMFC)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%HLMF,YHLMF%MPPC,YDGFLC=YHLMF)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%HLCFMF,YHLCFMF%MPPC,YDGFLC=YHLCFMF)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%HIMF,YHIMF%MPPC,YDGFLC=YHIMF)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%HICFMF,YHICFMF%MPPC,YDGFLC=YHICFMF)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%SHTUR,YSHTUR%MPPC,YDGFLC=YSHTUR)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%FQTUR,YFQTUR%MPPC,YDGFLC=YFQTUR)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%FSTUR,YFSTUR%MPPC,YDGFLC=YFSTUR)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%CVV,YCVV%MPPC,YDGFLC=YCVV)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%RKTH,YRKTH%MPPC,YDGFLC=YRKTH)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%RKTQV,YRKTQV%MPPC,YDGFLC=YRKTQV)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%RKTQC,YRKTQC%MPPC,YDGFLC=YRKTQC)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%CPF,YCPF%MPPC,YDGFLC=YCPF)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%SPF,YSPF%MPPC,YDGFLC=YSPF)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%LRAD,YLRAD%MPPC,YDGFLC=YLRAD)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%IRAD,YIRAD%MPPC,YDGFLC=YIRAD)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%UOM,YUOM%MPPC,YDGFLC=YUOM)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%UAL,YUAL%MPPC,YDGFLC=YUAL)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%DOM,YDOM%MPPC,YDGFLC=YDOM)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%DAL,YDAL%MPPC,YDGFLC=YDAL)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%UEN,YUEN%MPPC,YDGFLC=YUEN)
CALL SET_MAP(FVAR,YDMAP%MPC_MAP,FID%UNEBH,YUNEBH%MPPC,YDGFLC=YUNEBH)

ALLOCATE(YDMAP%MPT_MAP(SIZE(FVAR)))
YDMAP%MPT_MAP = JP_NOT_SET
! GFL
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%Q,YQ%MPPT,YDGFLC=YQ)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%O3,YO3%MPPT,YDGFLC=YO3)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%L,YL%MPPT,YDGFLC=YL)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%I,YI%MPPT,YDGFLC=YI)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%A,YA%MPPT,YDGFLC=YA)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%S,YS%MPPT,YDGFLC=YS)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%R,YR%MPPT,YDGFLC=YR)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%G,YG%MPPT,YDGFLC=YG)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%H,YH%MPPT,YDGFLC=YH)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%TKE,YTKE%MPPT,YDGFLC=YTKE)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%TTE,YTTE%MPPT,YDGFLC=YTTE)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%MXL,YMXL%MPPT,YDGFLC=YMXL)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%SRC,YSRC%MPPT,YDGFLC=YSRC)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%LMF,YLMF%MPPT,YDGFLC=YLMF)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%IMF,YIMF%MPPT,YDGFLC=YIMF)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%AMF,YAMF%MPPT,YDGFLC=YAMF)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%WMFC,YWMFC%MPPT,YDGFLC=YWMFC)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%HLMF,YHLMF%MPPT,YDGFLC=YHLMF)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%HLCFMF,YHLCFMF%MPPT,YDGFLC=YHLCFMF)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%HIMF,YHIMF%MPPT,YDGFLC=YHIMF)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%HICFMF,YHICFMF%MPPT,YDGFLC=YHICFMF)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%SHTUR,YSHTUR%MPPT,YDGFLC=YSHTUR)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%FQTUR,YFQTUR%MPPT,YDGFLC=YFQTUR)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%FSTUR,YFSTUR%MPPT,YDGFLC=YFSTUR)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%CVV,YCVV%MPPT,YDGFLC=YCVV)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%RKTH,YRKTH%MPPT,YDGFLC=YRKTH)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%RKTQV,YRKTQV%MPPT,YDGFLC=YRKTQV)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%RKTQC,YRKTQC%MPPT,YDGFLC=YRKTQC)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%CPF,YCPF%MPPT,YDGFLC=YCPF)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%SPF,YSPF%MPPT,YDGFLC=YSPF)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%LRAD,YLRAD%MPPT,YDGFLC=YLRAD)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%IRAD,YIRAD%MPPT,YDGFLC=YIRAD)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%UOM,YUOM%MPPT,YDGFLC=YUOM)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%UAL,YUAL%MPPT,YDGFLC=YUAL)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%DOM,YDOM%MPPT,YDGFLC=YDOM)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%DAL,YDAL%MPPT,YDGFLC=YDAL)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%UEN,YUEN%MPPT,YDGFLC=YUEN)
CALL SET_MAP(FVAR,YDMAP%MPT_MAP,FID%UNEBH,YUNEBH%MPPT,YDGFLC=YUNEBH)


! === T0L horisontal derivatives mapping ===

ALLOCATE(YDMAP%MT0_DL_MAP(SIZE(FVAR)))
ALLOCATE(YDMAP%MT0_DM_MAP(SIZE(FVAR)))
YDMAP%MT0_DL_MAP = JP_NOT_SET
YDMAP%MT0_DM_MAP = JP_NOT_SET

! GMV
LLFIRST = .TRUE.
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%U,YT0%MUL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%V,YT0%MVL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%T,YT0%MTL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%PD,YT0%MSPDL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%VD,YT0%MSVDL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%NHX,YT0%MNHXL,LDFIRST=LLFIRST)

!! GFL
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%Q,YQ%MPL,YDGFLC=YQ)
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%O3,YO3%MPL,YDGFLC=YO3)
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%L,YL%MPL,YDGFLC=YL)
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%I,YI%MPL,YDGFLC=YI)
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%A,YA%MPL,YDGFLC=YA)
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%S,YS%MPL,YDGFLC=YS)
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%R,YR%MPL,YDGFLC=YR)
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%G,YG%MPL,YDGFLC=YG)
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%H,YH%MPL,YDGFLC=YH)
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%CVGQ,YCVGQ%MPL,YDGFLC=YCVGQ)
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%RSPEC,YRSPEC%MPL,YDGFLC=YRSPEC)

! GMVS
YDMAP%MT0_DL_MAP(FID%SP) = YT0%MSPL
LLFIRST = .TRUE.
CALL SET_MAP(FVAR,YDMAP%MT0_DL_MAP,FID%SP,YT0%MSPL,LDFIRST=LLFIRST)

LLFIRST = .TRUE.
! This is intentionally wrong, we never have meridional ders of u and v
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%U,YT0%MUL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%V,YT0%MVL,LDFIRST=LLFIRST)
!
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%T,YT0%MTM,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%PD,YT0%MSPDM,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%VD,YT0%MSVDM,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%NHX,YT0%MNHXM,LDFIRST=LLFIRST)

!! GFL
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%Q,YQ%MPL,YDGFLC=YQ)
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%O3,YO3%MPL,YDGFLC=YO3)
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%L,YL%MPL,YDGFLC=YL)
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%I,YI%MPL,YDGFLC=YI)
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%A,YA%MPL,YDGFLC=YA)
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%S,YS%MPL,YDGFLC=YS)
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%R,YR%MPL,YDGFLC=YR)
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%G,YG%MPL,YDGFLC=YG)
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%H,YH%MPL,YDGFLC=YH)
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%CVGQ,YCVGQ%MPL,YDGFLC=YCVGQ)
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%RSPEC,YRSPEC%MPL,YDGFLC=YRSPEC)


! GMVS
LLFIRST = .TRUE.
CALL SET_MAP(FVAR,YDMAP%MT0_DM_MAP,FID%SP,YT0%MSPM,LDFIRST=LLFIRST)

! === T9L horisontal derivatives mapping ===

ALLOCATE(YDMAP%MT9_DL_MAP(SIZE(FVAR)))
ALLOCATE(YDMAP%MT9_DM_MAP(SIZE(FVAR)))
YDMAP%MT9_DL_MAP = JP_NOT_SET
YDMAP%MT9_DM_MAP = JP_NOT_SET

! GMV
LLFIRST = .TRUE.
CALL SET_MAP(FVAR,YDMAP%MT9_DL_MAP,FID%T,YT9%MTL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_DL_MAP,FID%PD,YT9%MSPDL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_DL_MAP,FID%VD,YT9%MSVDL,LDFIRST=LLFIRST)

! GMVS
LLFIRST = .TRUE.
CALL SET_MAP(FVAR,YDMAP%MT9_DL_MAP,FID%SP,YT9%MSPL,LDFIRST=LLFIRST)

LLFIRST = .TRUE.
CALL SET_MAP(FVAR,YDMAP%MT9_DM_MAP,FID%T,YT9%MTL,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_DM_MAP,FID%PD,YT9%MSPDM,LDFIRST=LLFIRST)
CALL SET_MAP(FVAR,YDMAP%MT9_DM_MAP,FID%VD,YT9%MSVDL,LDFIRST=LLFIRST)

! GMVS
LLFIRST = .TRUE.
CALL SET_MAP(FVAR,YDMAP%MT9_DM_MAP,FID%SP,YT9%MSPL,LDFIRST=LLFIRST)


! Dynamically-assigned COMPO 3D GFL fields (at T0, T1, T9):
IF (NGHG > 0) THEN
  DO JGFL=1,NGHG
    CALL SET_MAP(FVAR,YDMAP%MT0_MAP,YGHG(JGFL)%IFID,YGHG(JGFL)%MP,YDGFLC=YGHG(JGFL))
    CALL SET_MAP(FVAR,YDMAP%MT1_MAP,YGHG(JGFL)%IFID,YGHG(JGFL)%MP1,YDGFLC=YGHG(JGFL))
    CALL SET_MAP(FVAR,YDMAP%MT9_MAP,YGHG(JGFL)%IFID,YGHG(JGFL)%MP9,YDGFLC=YGHG(JGFL))
  ENDDO
ENDIF
IF (NCHEM > 0) THEN
  DO JGFL=1,NCHEM
    CALL SET_MAP(FVAR,YDMAP%MT0_MAP,YCHEM(JGFL)%IFID,YCHEM(JGFL)%MP,YDGFLC=YCHEM(JGFL))
    CALL SET_MAP(FVAR,YDMAP%MT1_MAP,YCHEM(JGFL)%IFID,YCHEM(JGFL)%MP1,YDGFLC=YCHEM(JGFL))
    CALL SET_MAP(FVAR,YDMAP%MT9_MAP,YCHEM(JGFL)%IFID,YCHEM(JGFL)%MP9,YDGFLC=YCHEM(JGFL))
  ENDDO
ENDIF
IF (NAERO > 0) THEN
  DO JGFL=1,NAERO
    CALL SET_MAP(FVAR,YDMAP%MT0_MAP,YAERO(JGFL)%IFID,YAERO(JGFL)%MP,YDGFLC=YAERO(JGFL))
    CALL SET_MAP(FVAR,YDMAP%MT1_MAP,YAERO(JGFL)%IFID,YAERO(JGFL)%MP1,YDGFLC=YAERO(JGFL))
    CALL SET_MAP(FVAR,YDMAP%MT9_MAP,YAERO(JGFL)%IFID,YAERO(JGFL)%MP9,YDGFLC=YAERO(JGFL))
  ENDDO
ENDIF


END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('FIELD_GFL_WRAPPER:GFL_MAPPING_SETUP',1,ZHOOK_HANDLE)

END SUBROUTINE GFL_MAPPING_SETUP

! ----------------------------------------------------------------------
! Maps from KID to the old GFL/GMV/surface pointer
!
! The GFL poiner can be +ve (== a "valid" ID)
!                        0  (== not_set, i.e. the mapping needs to be added above)
!                -99999999  (The value of an unused pointer in GFL world)       
! ----------------------------------------------------------------------
FUNCTION GFL_MAP(YDMAP,KID, KATTACH, LD_IGNORE_NOT_SET)

TYPE(TGFL_MAP_INTERNAL),INTENT(IN) :: YDMAP
INTEGER(KIND=JPIM), INTENT(IN) :: KID     ! New fields field ID
INTEGER(KIND=JPIM), INTENT(IN) :: KATTACH ! Attachment time level (e.g. T9, T0 etc.) 
LOGICAL, OPTIONAL,  INTENT(IN) :: LD_IGNORE_NOT_SET ! Raise an abort if a FID is not set?
INTEGER(KIND=JPIM)             :: GFL_MAP

LOGICAL :: LL_CHECK

REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELD_GFL_WRAPPER:GFL_MAP',0,ZHOOK_HANDLE)

LL_CHECK = .TRUE.
IF(PRESENT(LD_IGNORE_NOT_SET)) LL_CHECK = .NOT. LD_IGNORE_NOT_SET

SELECT CASE(KATTACH)
CASE(JP_T0) 
  GFL_MAP = YDMAP%MT0_MAP(KID)
CASE(JP_T9)
  GFL_MAP = YDMAP%MT9_MAP(KID)
CASE(JP_T1) 
  GFL_MAP = YDMAP%MT1_MAP(KID)
CASE(JP_PC) 
  GFL_MAP = YDMAP%MPC_MAP(KID)
CASE(JP_PT) 
  GFL_MAP = YDMAP%MPT_MAP(KID)
CASE(JP_T0_DL)
  GFL_MAP = YDMAP%MT0_DL_MAP(KID)
CASE(JP_T0_DM)
  GFL_MAP = YDMAP%MT0_DM_MAP(KID)
CASE(JP_T9_DL) 
  GFL_MAP = YDMAP%MT9_DL_MAP(KID)
CASE(JP_T9_DM)
  GFL_MAP = YDMAP%MT9_DM_MAP(KID)
CASE DEFAULT
  WRITE(NULERR,*) 'NFTBC ', KID
  CALL ABOR1("New fields mapping has not been set up at this time level")
END SELECT
! Check we have a valid GFL pointer
IF( LL_CHECK ) THEN
  IF( GFL_MAP == JP_NOT_SET ) THEN

    WRITE(NULERR,*) 'NFTBC ', KID, KATTACH
    CALL ABOR1("New fields mapping to GFL/GMV/surface has not been set up")

  ELSEIF( GFL_MAP < 0 .AND. GFL_MAP /= JP_NOT_ACTIVE .AND. GFL_MAP /= NUNDEFLD ) THEN

    WRITE(NULERR,*) 'NFTBC ', KID, KATTACH, GFL_MAP
    CALL ABOR1("New fields mapping: GFL/GMV/surface pointer is invalid")

  ENDIF
ENDIF

IF (LHOOK) CALL DR_HOOK('FIELD_GFL_WRAPPER:GFL_MAP',1,ZHOOK_HANDLE)

END FUNCTION GFL_MAP

! ----------------------------------------------------------------------
! Sets up the list of valid FIDS when attaching to a GFL. 
! ----------------------------------------------------------------------
SUBROUTINE GFL_FID_SETUP(YDMAP,KFIELDS_ALL, KATTACH, KFIELDS_USED, LDON, LDACTIVE,KFIDS_USED,KFIDS)

TYPE(TGFL_MAP_INTERNAL),INTENT(IN) :: YDMAP
INTEGER(KIND=JPIM), INTENT(IN)    :: KFIELDS_ALL    ! Total number of defined field IDs 
INTEGER(KIND=JPIM), INTENT(IN)    :: KATTACH        ! Attachment time level (e.g. T9, T0 etc.)
INTEGER(KIND=JPIM), INTENT(OUT)   :: KFIELDS_USED   ! Number of fields actually ON
LOGICAL,            INTENT(INOUT) :: LDON(:)        ! Whether this FID is ON. Assumed initiliased to .false.
LOGICAL,            INTENT(INOUT) :: LDACTIVE(:)        ! Whether this FID is ACTIVE. Assumed initiliased to .false.
INTEGER(KIND=JPIM), ALLOCATABLE, INTENT(OUT) :: KFIDS_USED(:)  ! OUT: list of FIDS that are ON
INTEGER(KIND=JPIM), OPTIONAL,INTENT(IN) :: KFIDS(:) ! Use this set of FIDS

INTEGER(KIND=JPIM) :: ID, IUSED_FIDS(KFIELDS_ALL), IGFL
LOGICAL            :: LLALL
REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('FIELD_GFL_WRAPPER:GFL_FID_SETUP',0,ZHOOK_HANDLE)

LLALL = .TRUE.

KFIELDS_USED = 0
DO ID=1,KFIELDS_ALL

  ! Check if this field is available from the GFL etc.
  IGFL = GFL_MAP(YDMAP,ID, KATTACH, LD_IGNORE_NOT_SET=.TRUE.)
  IF( ((IGFL /= NUNDEFLD) .OR. LLALL) .AND. IGFL /= JP_NOT_SET ) THEN
    IF (PRESENT(KFIDS)) THEN
      IF (ANY(ID==KFIDS)) THEN
        LDON(ID) = .TRUE.
      ENDIF
    ELSE
      LDON(ID) = .TRUE.
    ENDIF
  ENDIF

  IF( IGFL /= JP_NOT_ACTIVE .AND. IGFL /= JP_NOT_SET ) THEN
    IF (PRESENT(KFIDS)) THEN
      IF (ANY(ID==KFIDS)) THEN
        LDACTIVE(ID) = .TRUE.
      ENDIF
    ELSE
      LDACTIVE(ID) = .TRUE.
    ENDIF
  ENDIF
  

  IF(LDON(ID)) THEN
    KFIELDS_USED = KFIELDS_USED + 1
    IUSED_FIDS(KFIELDS_USED) = ID
  ENDIF

ENDDO

ALLOCATE(KFIDS_USED(KFIELDS_USED))
KFIDS_USED = IUSED_FIDS(1:KFIELDS_USED)
IF (LHOOK) CALL DR_HOOK('FIELD_GFL_WRAPPER:GFL_FID_SETUP',1,ZHOOK_HANDLE)

END SUBROUTINE GFL_FID_SETUP

! ----------------------------------------------------------------------
! Attaches to individual members in the GFL, GMV, and surface structures
! ----------------------------------------------------------------------
SUBROUTINE GFL_ATTACH(FVAR,YDMAP,KLON, KLEV, KID, KBLOCK, KATTACH, YDGMV,YDGFL,YDSURF,FPTR_1D, FPTR_2D, FPTR_3D,FPTR_UNASSIGNED,KDIM3 )
TYPE(TGFL_MAP_INTERNAL),INTENT(IN) :: YDMAP

TYPE(TYPE_FVAR),    INTENT(IN) :: FVAR(:)
INTEGER(KIND=JPIM), INTENT(IN) :: KLON, KLEV ! Expected dimensions
INTEGER(KIND=JPIM), INTENT(IN) :: KID        ! New fields field ID
INTEGER(KIND=JPIM), INTENT(IN) :: KBLOCK     ! block number
INTEGER(KIND=JPIM), INTENT(IN) :: KATTACH    ! Attachment time level (e.g. T9, T0 etc.) 
TYPE(TGMV),TARGET , INTENT(IN) :: YDGMV
TYPE(TGFL),TARGET , INTENT(IN) :: YDGFL
TYPE(TSURF),TARGET, INTENT(IN) :: YDSURF
REAL(KIND=JPRB), POINTER, OPTIONAL :: FPTR_1D(:), FPTR_2D(:,:), FPTR_3D(:,:,:)
INTEGER(KIND=JPIM), INTENT(IN),OPTIONAL :: KDIM3
REAL(KIND=JPRB), TARGET, INTENT(IN) :: FPTR_UNASSIGNED(:,:,:)

INTEGER(KIND=JPIM) :: ITMAP
REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELD_GFL_WRAPPER:GFL_ATTACH',0,ZHOOK_HANDLE)
ASSOCIATE(GMV=>YDGMV%GMV, GMVS=>YDGMV%GMVS,GMVT1S=>YDGMV%GMVT1S,GMVT1=>YDGMV%GMVT1,&
 & GFL=>YDGFL%GFL,GFLT1=>YDGFL%GFLT1,GFLPC=>YDGFL%GFLPC, GFLPT=>YDGFL%GFLPT,&
 & SP_SB=>YDSURF%SP_SB,SP_SG=>YDSURF%SP_SG,SP_CL=>YDSURF%SP_CL,SP_OM=>YDSURF%SP_OM,SP_SL=>YDSURF%SP_SL,&
 & SP_RR=>YDSURF%SP_RR,SD_VF=>YDSURF%SD_VF,SD_VP=>YDSURF%SD_VP,SD_VV=>YDSURF%SD_VV,SD_VN=>YDSURF%SD_VN,&
 & SD_VH=>YDSURF%SD_VH,SD_VK=>YDSURF%SD_VK,SD_VA=>YDSURF%SD_VA,SD_VC=>YDSURF%SD_VC,SD_V2=>YDSURF%SD_V2,SD_V3=>YDSURF%SD_V3,&
 & SD_VD=>YDSURF%SD_VD,SD_SM=>YDSURF%SD_SM,SD_WS=>YDSURF%SD_WS,SD_WW=>YDSURF%SD_WW,SD_VX=>YDSURF%SD_VX,KLEVSN=>YDSURF%YSP_SGD%NLEVS)

ITMAP = GFL_MAP(YDMAP,KID, KATTACH)
!write(nulout,'(a,6(1x,i5)') 'GFL_ATTACH ',KID,FVAR(KID)%IGFLGMV,KATTACH,ITMAP,KLON,KBLOCK
! GMV

SELECT CASE(FVAR(KID)%IGFLGMV)
CASE(1)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1 ) THEN
    IF( KATTACH == JP_T1 ) THEN
      FPTR_2D => GMVT1(1:KLON,:,ITMAP,KBLOCK)
    ELSE 
      FPTR_2D => GMV(1:KLON,:,ITMAP,KBLOCK)
    ENDIF
  ELSE
    FPTR_2D => FPTR_UNASSIGNED(1:KLON,:,1)
  ENDIF
! GFL
CASE(3)
  IF(PRESENT(FPTR_3D)) THEN
    IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
      IF(.NOT.PRESENT(KDIM3)) CALL ABOR1('FIELD_GFL_WRAPPER:GFL_ATTACH - KDIM3 MISSING')
      IF( KATTACH == JP_T1 ) THEN
        FPTR_3D => GFLT1(1:KLON,:,ITMAP:ITMAP+KDIM3-1,KBLOCK)
      ELSEIF( KATTACH == JP_PC ) THEN
        FPTR_3D => GFLPC(1:KLON,:,ITMAP:ITMAP+KDIM3-1,KBLOCK)
      ELSEIF( KATTACH == JP_PT ) THEN
        FPTR_3D => GFLPT(1:KLON,:,ITMAP:ITMAP+KDIM3-1,KBLOCK)
      ELSE
        FPTR_3D => GFL(1:KLON,:,ITMAP:ITMAP+KDIM3-1,KBLOCK)
      ENDIF
    ELSE
      FPTR_3D => FPTR_UNASSIGNED(1:KLON,:,:)
    ENDIF
  ELSE
    IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
      IF( KATTACH == JP_T1 ) THEN
        FPTR_2D => GFLT1(1:KLON,:,ITMAP,KBLOCK)
      ELSEIF( KATTACH == JP_PC ) THEN
        FPTR_2D => GFLPC(1:KLON,:,ITMAP,KBLOCK)
      ELSEIF( KATTACH == JP_PT ) THEN
        FPTR_2D => GFLPT(1:KLON,:,ITMAP,KBLOCK)
      ELSE
        FPTR_2D => GFL(1:KLON,:,ITMAP,KBLOCK)
      ENDIF
    ELSE
      FPTR_2D => FPTR_UNASSIGNED(1:KLON,:,1)
    ENDIF
  ENDIF
! GMVS
CASE(2)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    IF( KATTACH == JP_T1 ) THEN
      FPTR_1D => GMVT1S(1:KLON,ITMAP,KBLOCK)
    ELSE
      FPTR_1D => GMVS(1:KLON,ITMAP,KBLOCK)
    ENDIF
  ELSE
    FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
  ENDIF
! Group SB
CASE(11)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_2D => SP_SB(1:KLON,:,ITMAP,KBLOCK)
  ELSE
    FPTR_2D => FPTR_UNASSIGNED(1:KLON,1:KLEV,1)
  ENDIF
! Group SG
CASE(12)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    !FPTR_1D => SP_SG(1:KLON,ITMAP,KBLOCK)
    FPTR_2D => SP_SG(1:KLON,:,ITMAP,KBLOCK) ! ARDU: use ALL layer, double-check
  ELSE
    !FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
    FPTR_2D => FPTR_UNASSIGNED(1:KLON,1:KLEVSN,1) ! ARDU: use ALL layers, double-check
  ENDIF
! Group SL
CASE(13)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_1D => SP_SL(1:KLON,ITMAP,KBLOCK)
  ELSE
    FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
  ENDIF
! Group RR
CASE(14)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_1D => SP_RR(1:KLON,ITMAP,KBLOCK)
  ELSE
    FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
  ENDIF
!Group CL
CASE(15)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_1D => SP_CL(1:KLON,ITMAP,KBLOCK)
  ELSE
    FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
  ENDIF
!Group OM
CASE(16)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_2D => SP_OM(1:KLON,:,ITMAP,KBLOCK)
  ELSE
    FPTR_2D => FPTR_UNASSIGNED(1:KLON,1:KLEV,1)
  ENDIF
! Group EP
CASE(17)
  CALL ABOR1("GFL_ATTACH:Group EP not supported")
  
! Group X2
CASE(18)
  CALL ABOR1("GFL_ATTACH:Group X2 not supported")
! Group CI
CASE(19)
  CALL ABOR1("GFL_ATTACH:Group CI not supported")

! Group VF
CASE(20)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    IF(PRESENT(FPTR_2D)) THEN
      IF(YDMAP%MT0_SIZE(KID) == JP_NOT_SET) THEN 
        WRITE(NULERR,*) 'FIELD_GFL_WRAPPER:GFL_ATTACH, KID',KID
        CALL ABOR1("GFL_ATTACH:MT0_SIZE(KID NOT SET")
      ENDIF
      IF(YDMAP%MT0_SIZE(KID) /= KLEV) THEN
        WRITE(NULERR,*) 'FIELD_GFL_WRAPPER:GFL_ATTACH ',YDMAP%MT0_SIZE(KID),KLEV
        CALL ABOR1('FIELD_GFL_WRAPPER:GFL_ATTACH - NON-MATCHING NUMBER OF LEVELS (FIELDS)')
      ENDIF
      FPTR_2D => SD_VF(1:KLON,ITMAP:ITMAP+YDMAP%MT0_SIZE(KID)-1,KBLOCK)
    ELSE
      FPTR_1D => SD_VF(1:KLON,ITMAP,KBLOCK)
    ENDIF
  ELSE
    IF(PRESENT(FPTR_2D)) THEN
      FPTR_2D => FPTR_UNASSIGNED(1:KLON,1:1,1)
    ELSE
      FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
    ENDIF
  ENDIF
! * Group VP=VCLIP: deep soil diagnostic fields
CASE(21)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_1D => SD_VP(1:KLON,ITMAP,KBLOCK)
  ELSE
    FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
  ENDIF
! * Group VV=VCLIV: vegetation diagnostic fields:
CASE(22)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_1D => SD_VV(1:KLON,ITMAP,KBLOCK)
  ELSE
    FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
  ENDIF
! Group VN
CASE(23)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_1D => SD_VN(1:KLON,ITMAP,KBLOCK)
  ELSE
    FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
  ENDIF
! Group VH
CASE(24)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_1D => SD_VN(1:KLON,ITMAP,KBLOCK)
  ELSE
    FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
  ENDIF
! Group VA
CASE(25)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_1D => SD_VA(1:KLON,ITMAP,KBLOCK)
  ELSE
    FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
  ENDIF
! Group VG
CASE(26)
  CALL ABOR1("GFL_ATTACH:Group VG not supported")
!!$  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
!!$    FPTR_1D => SD_VA(1:KLON,ITMAP,KBLOCK)
!!$  ELSE
!!$    FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
!!$  ENDIF
! Group VC
CASE(27)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_1D => SD_VC(1:KLON,ITMAP,KBLOCK)
  ELSE
    FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
  ENDIF
! Group V2
CASE(28)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_1D => SD_V2(1:KLON,ITMAP,KBLOCK)
  ELSE
    FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
  ENDIF
! Group V3
CASE(29)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    IF(PRESENT(FPTR_2D)) THEN
      FPTR_2D => SD_V3(1:KLON,:,ITMAP,KBLOCK)
    ELSE
      FPTR_1D => SD_V3(1:KLON,1,ITMAP,KBLOCK)
    ENDIF
  ELSE
    IF(PRESENT(FPTR_2D)) THEN
      FPTR_2D => FPTR_UNASSIGNED(1:KLON,1:KLEV,1)
    ELSE
      FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
    ENDIF
  ENDIF
! Group VD
CASE(30)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_1D => SD_VD(1:KLON,ITMAP,KBLOCK)
  ELSE
    FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
  ENDIF
! 31 should not exist as Group VD has more than 100 members (covers FIDs 3001 - more than 3100)
! Group SM
CASE(32)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_2D => SD_SM(1:KLON,:,ITMAP,KBLOCK)
  ELSE
    FPTR_2D => FPTR_UNASSIGNED(1:KLON,1:KLEV,1)
  ENDIF
! Group WS
CASE(33)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_1D => SD_WS(1:KLON,ITMAP,KBLOCK)
  ELSE
    FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
  ENDIF
! Group VX
CASE(34)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_1D => SD_VX(1:KLON,ITMAP,KBLOCK)
  ELSE
    FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
  ENDIF
! Group VK
CASE(35)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_1D => SD_VK(1:KLON,ITMAP,KBLOCK)
  ELSE
    FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
  ENDIF
CASE(38)
  IF( ITMAP /= NUNDEFLD .OR. ITMAP == 1) THEN
    FPTR_1D => SD_WW(1:KLON,ITMAP,KBLOCK)
  ELSE
    FPTR_1D => FPTR_UNASSIGNED(1:KLON,1,1)
  ENDIF
END SELECT

IF( PRESENT(FPTR_2D)) THEN
  IF (ASSOCIATED(FPTR_2D) .AND. SIZE(FPTR_2D,2) /= KLEV) THEN
    WRITE(NULERR,*) 'NFTBC ', KID
    CALL ABOR1("FIELD_GFL_WRAPPER:GFL_ATTACH : New fields mapping: vertical levels have gone wrong")
  ENDIF
  IF (.NOT. ASSOCIATED(FPTR_2D)) THEN
    WRITE(NULERR,*) 'NFTBC ', KID
    CALL ABOR1("FIELD_GFL_WRAPPER:GFL_ATTACH : New fields mapping: a 2D variable ID is missing from this routine")
  ENDIF
ENDIF

IF( PRESENT(FPTR_1D)) THEN
  IF (.NOT. ASSOCIATED(FPTR_1D)) THEN
    WRITE(NULERR,*) 'NFTBC ', KID
    CALL ABOR1("FIELD_GFL_WRAPPER:GFL_ATTACH : New fields mapping- a 1D variable ID is missing from this routine")
  ENDIF
ENDIF

IF (LHOOK) CALL DR_HOOK('FIELD_GFL_WRAPPER:GFL_ATTACH',1,ZHOOK_HANDLE)
END ASSOCIATE

END SUBROUTINE GFL_ATTACH


SUBROUTINE SET_MAP(FVAR,KMAP,KFID,KTO,LDFIRST,YDGFLC,YDSURF,KFIELDS,KMAPFIELDS)

TYPE(TYPE_FVAR), INTENT(IN) :: FVAR(:)
INTEGER(KIND=JPIM), INTENT(OUT) :: KMAP(:)
INTEGER(KIND=JPIM), INTENT(IN) :: KFID
INTEGER(KIND=JPIM), INTENT(IN) :: KTO
LOGICAL, OPTIONAL, INTENT(IN)   :: LDFIRST
TYPE(TYPE_GFL_COMP),OPTIONAL,INTENT(IN) :: YDGFLC
CLASS(TYPE_SURF_MTL),OPTIONAL,INTENT(IN):: YDSURF
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KFIELDS
INTEGER(KIND=JPIM),OPTIONAL :: KMAPFIELDS(:)

! Do not add DR HOOK to this routine: it causes poor performance

IF(FVAR(KFID)%IGFLGMV == 1 .OR. FVAR(KFID)%IGFLGMV == 2) THEN ! GMV/GMVS
  IF(.NOT.PRESENT(LDFIRST)) &
   &  CALL ABOR1('FIELD_GFL_WRAPPER:SET_MAP -LDFIRST ARG MISSING')
  IF(KTO /= NUNDEFLD) THEN
    KMAP(KFID) = KTO
! The following check is not reliable, relies e.g. on LADER=.TRUE.
  ELSEIF(LDFIRST .AND. NUNDEFLD == 1) THEN
    KMAP(KFID) = KTO
  ELSE
    KMAP(KFID) = JP_NOT_ACTIVE
  ENDIF
ELSEIF(FVAR(KFID)%IGFLGMV == 3) THEN !GFL
  IF(.NOT.PRESENT(YDGFLC)) &
   &  CALL ABOR1('FIELD_GFL_WRAPPER:SET_MAP - YDGFLC ARG MISSING')
  IF(YDGFLC%LACTIVE) THEN
    KMAP(KFID) = KTO
  ELSE 
    KMAP(KFID) = JP_NOT_ACTIVE
  ENDIF
ELSE ! Surface fields
  IF(.NOT.PRESENT(YDSURF)) &
   &  CALL ABOR1('FIELD_GFL_WRAPPER:SET_MAP - YDSURF ARG MISSING')
  IF(YDSURF%LSET) THEN
    KMAP(KFID) = KTO
    IF(PRESENT(KFIELDS)) THEN
      IF(.NOT.PRESENT(KMAPFIELDS)) &
       &  CALL ABOR1('FIELD_GFL_WRAPPER:SET_MAP - KMAPFIELDS  ARG MISSING')
      KMAPFIELDS(KFID) = KFIELDS
    ENDIF
  ELSE 
    KMAP(KFID) = JP_NOT_ACTIVE

  ENDIF
ENDIF

! Do not add DR HOOK to this routine: it causes poor performance

END SUBROUTINE SET_MAP

END MODULE FIELD_GFL_WRAPPER
