MODULE MODE_INIT_PHYEX
IMPLICIT NONE
CONTAINS
SUBROUTINE FILL_DIMPHYEX(KLON, KLEV, D)
USE MODD_DIMPHYEX,   ONLY: DIMPHYEX_t
USE MODD_PARAMETERS, ONLY: JPVEXT_TURB, JPVEXT
USE MODE_MSG, ONLY: PRINT_MSG, NVERB_FATAL
IMPLICIT NONE
INTEGER, INTENT(IN) :: KLON
INTEGER, INTENT(IN) :: KLEV
TYPE(DIMPHYEX_t), INTENT(OUT) :: D

IF(JPVEXT /= 1 .OR. JPVEXT_TURB /= 1) THEN
  !All arrays are presently declared with klev+2
  CALL PRINT_MSG(NVERB_FATAL, 'GEN', 'FILL_DIMPHYEX', 'For now, JPVEXT and JPVEXT_TURB must be equal to 1')
ENDIF
D%NIT  = KLON
D%NIB  = 1
D%NIE  = KLON
D%NJT  = 1
D%NJB  = 1
D%NJE  = 1
D%NIJT = D%NIT * D%NJT
D%NIJB = 1
D%NIJE = KLON
D%NKL  = 1
D%NKT  = KLEV+2
D%NKA  = 1
D%NKU  = KLEV+2
D%NKB  = 1+JPVEXT_TURB
D%NKE  = D%NKT - JPVEXT_TURB
D%NKTB = 1+JPVEXT_TURB
D%NKTE = D%NKT - JPVEXT_TURB
D%NIBC = 1
D%NJBC = 1
D%NIEC = D%NIE
D%NJEC = D%NJT
END SUBROUTINE FILL_DIMPHYEX
!
SUBROUTINE INIT_PHYEX(PTSTEP, PDZMIN, PHYEX, MISC_LMDZ)
!
USE MODD_PHYEX,      ONLY: PHYEX_t
USE MODI_INI_PHYEX,  ONLY: INI_PHYEX
USE MODD_IO,         ONLY: TFILEDATA
USE MODD_MISC_LMDZ,  ONLY: MISC_LMDZ_t
USE print_control_mod, ONLY : lunout
!
IMPLICIT NONE
!
REAL, INTENT(IN)              :: PTSTEP
REAL, INTENT(IN)              :: PDZMIN
TYPE(PHYEX_t), INTENT(OUT), TARGET :: PHYEX
TYPE(MISC_LMDZ_t), TARGET, INTENT(OUT) :: MISC_LMDZ
!
CHARACTER(LEN=6) :: CPROGRAM
CHARACTER(LEN=4) :: CMICRO
CHARACTER(LEN=4) :: CSCONV
CHARACTER(LEN=4) :: CTURB
INTEGER :: K
LOGICAL :: LREADNAM, LOPENED
INTEGER :: ILUN
TYPE(TFILEDATA) :: TPFILE
!
!General configuration, cannot be modified by namelist
CPROGRAM='LMDZ'
CMICRO='ICE3'
CSCONV='EDKF'
CTURB='TKEL'
!
! Initialize PHYEX
!If the namelist file exists, we use it
INQUIRE(FILE='phyex.nam', EXIST=LREADNAM)
IF(LREADNAM) THEN
  TPFILE%NLU=-1
  DO ILUN=1,100
    INQUIRE(UNIT=ILUN, OPENED=LOPENED)
    IF (.NOT. LOPENED) THEN
      TPFILE%NLU=ILUN
      EXIT
    END IF
  END DO
  OPEN(ACTION='read', FILE='phyex.nam', UNIT=TPFILE%NLU)
ENDIF
CALL INI_PHYEX(HPROGRAM=CPROGRAM, TPFILE=TPFILE, LDNEEDNAM=.FALSE., &
              &KLUOUT=lunout, KFROM=0, KTO=1, &
              &PTSTEP=PTSTEP, PDZMIN=PDZMIN, &
              &CMICRO=CMICRO, CSCONV=CSCONV, CTURB=CTURB, &
              &LDDEFAULTVAL=.TRUE., LDREADNAM=LREADNAM, LDCHECK=.TRUE., &
              &KPRINT=2, LDINIT=.TRUE., &
              &PHYEX_OUT=PHYEX)
!
MISC_LMDZ%CPROGRAM=CPROGRAM
MISC_LMDZ%ZTFILE%LOPENED=.FALSE.
MISC_LMDZ%TLES%LLES=.FALSE.
MISC_LMDZ%TLES%LLES_CALL=.FALSE.
MISC_LMDZ%CMICRO=CMICRO
MISC_LMDZ%CSCONV=CSCONV
MISC_LMDZ%CTURB=CTURB
!
! Budgets
DO K=1, MISC_LMDZ%NBUDGET
  MISC_LMDZ%YLBUDGET(K)%PTR=>MISC_LMDZ%YLBUDGET_LMDZ(K)
  MISC_LMDZ%YLBUDGET(K)%PTR%NBUDGET=K
ENDDO
MISC_LMDZ%TBUCONF%LBU_ENABLE=.FALSE.
MISC_LMDZ%TBUCONF%LBUDGET_U=.FALSE.
MISC_LMDZ%TBUCONF%LBUDGET_V=.FALSE.
MISC_LMDZ%TBUCONF%LBUDGET_W=.FALSE.
MISC_LMDZ%TBUCONF%LBUDGET_TH=.FALSE.
MISC_LMDZ%TBUCONF%LBUDGET_TKE=.FALSE.
MISC_LMDZ%TBUCONF%LBUDGET_RV=.FALSE.
MISC_LMDZ%TBUCONF%LBUDGET_RC=.FALSE.
MISC_LMDZ%TBUCONF%LBUDGET_RR=.FALSE.
MISC_LMDZ%TBUCONF%LBUDGET_RI=.FALSE.
MISC_LMDZ%TBUCONF%LBUDGET_RS=.FALSE.
MISC_LMDZ%TBUCONF%LBUDGET_RG=.FALSE.
MISC_LMDZ%TBUCONF%LBUDGET_RH=.FALSE.
MISC_LMDZ%TBUCONF%LBUDGET_SV=.FALSE.
!
END SUBROUTINE INIT_PHYEX
END MODULE MODE_INIT_PHYEX
