!    ------------------------------------------------------------------
NAMELIST/NAMPARAR/LOSUBG_COND,CSUBG_AUCV_RC,CSUBG_AUCV_RI,LOSIGMAS,NSWB_MNH,NPRINTFR,LSQUALL,&
        &NREFROI1,NREFROI2,VSQUALL,NPTP,LDIAGWMAX,NDIAGWMAX,CMICRO,CSEDIM,&
        &LAROBU_ENABLE,CMF_UPDRAFT,CMF_CLOUD,LMIXUV,LLCRIT,LTOTPREC,&
        &LTOTPRECL,LHGT_QS,LOSEDIC,&
        &VSIGQSAT,XLINI,LOLSMC,LOTOWNC,LOCND2,LKOGAN,LMODICEDEP,&
        &LICERAD,RFRMIN,RADGR,RADSN,LSTATNW,LHARATU,NPROMICRO,&
        &XALP_PERT,XABUO,XBENTR,XBDETR,XCMF,XENTR_MF,XCRAD_MF,XENTR_DRY,&
        &XDETR_DRY,XDETR_LUP,XKCF_MF,XKRC_MF,XTAUSIGMF,XPRES_UV,XFRAC_UP_MAX,&
        &XALPHA_MF,XSIGMA_MF,XA1,XB,XC,XBETA1,LTHETAS,&
        &CSUBG_RC_RR_ACCR,CSUBG_RR_EVAP,CSUBG_PR_PDF,RCRIAUTI,RCRIAUTC,&
        &RT0CRIAUTI,LCRIAUTI,XCQVR,GQVPLIM,GQVTOP,LQVTOP,LFPREC3D, &
        &XTSTEP_TS, CSNOWRIMING, XMRSTEP, NMAXITER_MICRO, &
        &LFEEDBACKT,LEVLIMIT,LNULLWETG,LWETGPOST,LNULLWETH,LWETHPOST, &
        &XFRACM90, LCONVHG, LCRFLIMIT, &
        &CFRAC_ICE_ADJUST, XSPLIT_MAXCFL, CFRAC_ICE_SHALLOW_MF, LSEDIM_AFTER,&
        &LDEPOSC, XVDEPOSC, CCONDENS, CLAMBDA3, CSUBG_MF_PDF,&
        &LDEPSG,RDEPSRED,RDEPGRED
!       ------------------------------------------------------------------
