!OCL  SCALAR
SUBROUTINE SUGFL3(YDDIMV,YDMODEL)

!------------------------------------------------------------------------------
!**** *SUGFL3*   - Setting up GFL environment: part 3

!     Purpose.
!     --------
!      Initialization of YOM_YGFL, part 3.
!      Set GFL attributes.

!**   Interface.
!     ----------
!        *CALL* *SUGFL3

!        Explicit arguments :
!        --------------------
!         none

!        Implicit arguments :
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!      Mats Hamrud *ECMWF*
!      Original : 2002-03-11
!      Code in SUDYN until Feb 2007
!      Code in SUDYN_SETGFLATTR until 2011
!      Creation of SUGFL3 in Nov 2011.

!     Modifications.
!     --------------
!      K. YESSAD (Nov 2011) former SUDYN_SETGFLATTR code put in new SUGFL3; + minor cleanings
!      J.M. Piriou and E. Bazile (Sep 2011): new GFL variables (LCONV, ICONV, RCONV, SCONV)
!      M. Diamantakis Jun-2012: code for mass fixers
!      S. Malardel Nov. 2013: add LCOMAD attribute
!      K. Yessad (July 2014): Move some variables.
!      M. Diamantakis Feb-2014: New LQM3D attribute for QM interpol limiter
!      F. Vana & M. Kharoutdinov 09-Feb-2015 CRM fields.
!      M. Diamantakis Feb-2016: New LQML3D attribute for QM interpol limiter
!      M Ahlgrimm 2017-05-11 cloud heterogeneity FSD
!      M. Diamantakis Jun-2018: New LMGRID attribute for multiple (Atlas) grid advection scheme
!      F. Vana  15-Sep-2020 : SLAVEPP cleaning
!     End Modifications
!------------------------------------------------------------------------------

USE TYPE_MODEL   , ONLY : MODEL
USE YOMDIMV      , ONLY : TDIMV
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMLUN       , ONLY : NULOUT, NULERR
USE GFL_SUBS_MOD , ONLY : SET_GFL_ATTR,PRINT_GFL
USE YOE_AERODIAG , ONLY : NPAERAOT, NPAERLISI_VAR, NPAERLISI_WVL

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(TDIMV), INTENT(IN) :: YDDIMV
TYPE(MODEL) ,INTENT(INOUT):: YDMODEL

INTEGER(KIND=JPIM) :: JGFL, JVAR, JWVL

LOGICAL :: LLT9,LLPT,LLPC,LLPC0
LOGICAL :: LLAD
LOGICAL :: LLDIAB, LLTDIABLIN

CHARACTER(LEN=12) :: CLSLINT

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "sucslint.intfb.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SUGFL3',0,ZHOOK_HANDLE)
ASSOCIATE(YDDYN=>YDMODEL%YRML_DYN%YRDYN,YGFL=>YDMODEL%YRML_GCONF%YGFL,YDEPHY=>YDMODEL%YRML_PHY_EC%YREPHY, &
 & YDPHY=>YDMODEL%YRML_PHY_MF%YRPHY,YDSIMPHL=>YDMODEL%YRML_PHY_MF%YRSIMPHL,YDDYNA=>YDMODEL%YRML_DYN%YRDYNA)
ASSOCIATE(LSPLTHOIGFL=>YDDYN%LSPLTHOIGFL,LPC_FULL=>YDDYNA%LPC_FULL,LPC_CHEAP=>YDDYNA%LPC_CHEAP, &
 & YAERO=>YGFL%YAERO, YSRC=>YGFL%YSRC, YCVGQ=>YGFL%YCVGQ, &
 & YLMF=>YGFL%YLMF,YIMF=>YGFL%YIMF, YAMF=>YGFL%YAMF, &
 & YWMFC=>YGFL%YWMFC, YHLMF=>YGFL%YHLMF, YHLCFMF=>YGFL%YHLCFMF, YHIMF=>YGFL%YHIMF, YHICFMF=>YGFL%YHICFMF, &
 & YMXL_NL=>YGFL%YMXL_NL, NUVP=>YGFL%NUVP, YCPF=>YGFL%YCPF, &
 & YUVP_NL=>YGFL%YUVP_NL, YRKTQC_NL=>YGFL%YRKTQC_NL, YSHTUR_NL=>YGFL%YSHTUR_NL, &
 & LTRCMFMG=>YGFL%LTRCMFMG, YFQTUR=>YGFL%YFQTUR, &
 & YO3_NL=>YGFL%YO3_NL, YSLDIA=>YGFL%YSLDIA, YFORC=>YGFL%YFORC, &
 & YL_NL=>YGFL%YL_NL, YLRCH4_NL=>YGFL%YLRCH4_NL, YTKE=>YGFL%YTKE, &
 & YNOGW=>YGFL%YNOGW, YCOMP=>YGFL%YCOMP, YQVA_NL=>YGFL%YQVA_NL, &
 & YSLDIA_NL=>YGFL%YSLDIA_NL, YUEN=>YGFL%YUEN, YEZDIAG=>YGFL%YEZDIAG, &
 & YERA40=>YGFL%YERA40, YFQTUR_NL=>YGFL%YFQTUR_NL, YS_NL=>YGFL%YS_NL, &
 & YEFB3_NL=>YGFL%YEFB3_NL, YA_NL=>YGFL%YA_NL, NNOGW=>YGFL%NNOGW, &
 & YDOM_NL=>YGFL%YDOM_NL, NGFL_EXT=>YGFL%NGFL_EXT, &
 & YEFB1_NL=>YGFL%YEFB1_NL, YSDSAT_NL=>YGFL%YSDSAT_NL, YLRAD_NL=>YGFL%YLRAD_NL, &
 & NEMIS3D=>YGFL%NEMIS3D, YEMIS3D=>YGFL%YEMIS3D, &
 & YGHG=>YGFL%YGHG, YCPF_NL=>YGFL%YCPF_NL, NNEGAFIX=>YGFL%NNEGAFIX, &
 & YLCONV_NL=>YGFL%YLCONV_NL, YRCONV_NL=>YGFL%YRCONV_NL, &
 & NMFIXFLDS=>YGFL%NMFIXFLDS, YLRCH4=>YGFL%YLRCH4, YDOM=>YGFL%YDOM, &
 & YAERAOT_NL=>YGFL%YAERAOT_NL, YAERLISI_NL=>YGFL%YAERLISI_NL, &
 & YAEROUT_NL=>YGFL%YAEROUT_NL, YSCONV_NL=>YGFL%YSCONV_NL, YFSTUR=>YGFL%YFSTUR, &
 & YUNEBH=>YGFL%YUNEBH, YAEROCLIM_NL=>YGFL%YAEROCLIM_NL, &
 & YQ_NL=>YGFL%YQ_NL, YAERO_NL=>YGFL%YAERO_NL, NFLDSFIX=>YGFL%NFLDSFIX, &
 & NFMG=>YGFL%NFMG, NMGFLDS=>YGFL%NMGFLDS, &
 & YEZDIAG_NL=>YGFL%YEZDIAG_NL, YERA40_NL=>YGFL%YERA40_NL, NSLDIA=>YGFL%NSLDIA, &
 & YNOGW_NL=>YGFL%YNOGW_NL, YIRAD_NL=>YGFL%YIRAD_NL, YDAL_NL=>YGFL%YDAL_NL, &
 & YRKTQV_NL=>YGFL%YRKTQV_NL, YICONV=>YGFL%YICONV, &
 & YCVV_NL=>YGFL%YCVV_NL, YH_NL=>YGFL%YH_NL, YSHTUR=>YGFL%YSHTUR, &
 & YG_NL=>YGFL%YG_NL, YSPF_NL=>YGFL%YSPF_NL, YEXT_NL=>YGFL%YEXT_NL, &
 & NNEGFLDS=>YGFL%NNEGFLDS, YI_NL=>YGFL%YI_NL, LTRCMFIX=>YGFL%LTRCMFIX, &
 & YQVA=>YGFL%YQVA, YCVGQ_NL=>YGFL%YCVGQ_NL, &
 & YMXL=>YGFL%YMXL, YTTE=>YGFL%YTTE, &
 & LADVNEGFIX=>YGFL%LADVNEGFIX, NGHG=>YGFL%NGHG, &
 & YFSTUR_NL=>YGFL%YFSTUR_NL, YIRAD=>YGFL%YIRAD, YR_NL=>YGFL%YR_NL, &
 & YUEN_NL=>YGFL%YUEN_NL, YRKTQC=>YGFL%YRKTQC, YUOM=>YGFL%YUOM, &
 & YAERAOT=>YGFL%YAERAOT, YAERLISI=>YGFL%YAERLISI, &
 & YAEROUT=>YGFL%YAEROUT, YTTE_NL=>YGFL%YTTE_NL, NGFL_EZDIAG=>YGFL%NGFL_EZDIAG, &
 & YUNEBH_NL=>YGFL%YUNEBH_NL, NERA40=>YGFL%NERA40, YRKTQV=>YGFL%YRKTQV,&
 & YAEROCLIM=>YGFL%YAEROCLIM, YUAL=>YGFL%YUAL, LTRCMFPR=>YGFL%LTRCMFPR, &
 & YLCONV=>YGFL%YLCONV, NAEROUT=>YGFL%NAEROUT, NAEROCLIM=>YGFL%NAEROCLIM, &
 & YUVP=>YGFL%YUVP, YRCONV=>YGFL%YRCONV, YUOM_NL=>YGFL%YUOM_NL, &
 & YICONV_NL=>YGFL%YICONV_NL, YSRC_NL=>YGFL%YSRC_NL, YI=>YGFL%YI, YH=>YGFL%YH, &
 & YL=>YGFL%YL, YEXT=>YGFL%YEXT, NGFL_FORC=>YGFL%NGFL_FORC, YA=>YGFL%YA, &
 & YLMF_NL=>YGFL%YLMF_NL,YIMF_NL=>YGFL%YIMF_NL,YAMF_NL=>YGFL%YAMF_NL, &
 & YWMFC_NL=>YGFL%YWMFC_NL, YHLMF_NL=>YGFL%YHLMF_NL, YHLCFMF_NL=>YGFL%YHLCFMF_NL, &
 & YHIMF_NL=>YGFL%YHIMF_NL, YHICFMF_NL=>YGFL%YHICFMF_NL, &
 & YSPF=>YGFL%YSPF, YG=>YGFL%YG, YRKTH_NL=>YGFL%YRKTH_NL, YCHEM=>YGFL%YCHEM, &
 & YQ=>YGFL%YQ, YR=>YGFL%YR, YSCONV=>YGFL%YSCONV, &
 & YS=>YGFL%YS, YCHEM_NL=>YGFL%YCHEM_NL, YEFB3=>YGFL%YEFB3, YEFB2=>YGFL%YEFB2, &
 & YEFB1=>YGFL%YEFB1, YEFB2_NL=>YGFL%YEFB2_NL, &
 & YCVV=>YGFL%YCVV, YO3=>YGFL%YO3, NOPTNEGFIX=>YGFL%NOPTNEGFIX, &
 & YUAL_NL=>YGFL%YUAL_NL, YDAL=>YGFL%YDAL, LTRCMFBC=>YGFL%LTRCMFBC, &
 & NAERO=>YGFL%NAERO, NCHEM=>YGFL%NCHEM, YFORC_NL=>YGFL%YFORC_NL, &
 & YGHG_NL=>YGFL%YGHG_NL, YRKTH=>YGFL%YRKTH, &
 & YTKE_NL=>YGFL%YTKE_NL, YLRAD=>YGFL%YLRAD, YSDSAT=>YGFL%YSDSAT, &
 & LSIMPH=>YDSIMPHL%LSIMPH, &
 & LMPHYS=>YDPHY%LMPHYS, LTRCMFP=>YGFL%LTRCMFP, &
 & NOPTMFPR=>YGFL%NOPTMFPR, NUMFLDS=>YGFL%NUMFLDS, &
 & LEPHYS=>YDEPHY%LEPHYS, YLIMA=>YGFL%YLIMA, YLIMA_NL=>YGFL%YLIMA_NL, NLIMA=>YGFL%NLIMA, &
 & NFSD=>YGFL%NFSD, YFSD=>YGFL%YFSD,YFSD_NL=>YGFL%YFSD_NL, &
 & NEDRP=>YGFL%NEDRP, YEDRP=>YGFL%YEDRP,YEDRP_NL=>YGFL%YEDRP_NL, &
 & LAERAOT=>YGFL%LAERAOT,LAERLISI=>YGFL%LAERLISI,YPHYCTY=>YGFL%YPHYCTY,YPHYCTY_NL=>YGFL%YPHYCTY_NL)
!     ------------------------------------------------------------------

!*       1.    SET GFL ATTRIBUTES
!              ------------------

! * Note that in this part the order of the GFL variables is no longer
!   the "SUGFL2-standard order" (cf. in SUGFL2) but a random order which reduces
!   the risk of "hidden" bugs.
!   This SUGFL3-order is used to order the GFL variables at time "t-dt".

IF (LPC_FULL.AND..NOT.LPC_CHEAP) THEN
  ! EUL: true; SL3TL: not yet coded; SL2TL: false.
  LLPC0=.NOT.YDDYNA%LTWOTL
ELSEIF (LPC_FULL.AND.LPC_CHEAP.AND.YDDYNA%LTWOTL) THEN
  ! EUL: not coded; SL3TL: not yet coded; SL2TL: true.
  LLPC0=.TRUE.
ELSE
  LLPC0=.FALSE.
ENDIF
LLT9 = (.NOT. YDDYNA%LTWOTL) .OR. LPC_FULL

! ky: quid for HIRLAM physics? LLDIAB must be probably T in this case too.
LLDIAB=LEPHYS.OR.LMPHYS.OR.LSIMPH

LLTDIABLIN=.FALSE.

! * Ozone:
IF(YO3%LACTIVE) THEN
  CALL SUCSLINT(YO3_NL%LSLHD,YO3_NL%LCOMAD,YO3_NL%LVSPLIP,YO3_NL%LHV,&
   & YO3_NL%LQM,YO3_NL%LQMH,YO3_NL%LQM3D,YO3_NL%LQML3D,YO3_NL%LINTLIN,YO3_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YDDYNA%LSLAG .AND. YO3_NL%LPT
  LLPC = LLPC0.AND.YO3_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YO3,LDADV=YO3_NL%LADV,LDMGRID=YO3_NL%LMGRID,&
   & LDADV5=YO3_NL%LADV5,&
   & LDTDIABLIN=YO3_NL%LTDIABLIN,LDHORTURB=YO3_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YO3_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YO3_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YO3_NL%REFVALC)  
  LLTDIABLIN=LLTDIABLIN.OR.YO3_NL%LTDIABLIN
ENDIF

! * Specific humidity:
IF(YQ%LACTIVE) THEN
  CALL SUCSLINT(YQ_NL%LSLHD,YQ_NL%LCOMAD,YQ_NL%LVSPLIP,YQ_NL%LHV,&
   & YQ_NL%LQM,YQ_NL%LQMH,YQ_NL%LQM3D,YQ_NL%LQML3D,YQ_NL%LINTLIN,YQ_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YDDYNA%LSLAG .AND. YQ_NL%LPT
  LLPC = LLPC0.AND.YQ_NL%LPC 
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YQ,LDADV=YQ_NL%LADV,LDMGRID=YQ_NL%LMGRID,&
   & LDADV5=YQ_NL%LADV5,&
   & LDTDIABLIN=YQ_NL%LTDIABLIN,LDHORTURB=YQ_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YQ_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YQ_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YQ_NL%REFVALC)  
  LLTDIABLIN=LLTDIABLIN.OR.YQ_NL%LTDIABLIN
ENDIF

! * Cloud fraction:
IF(YA%LACTIVE) THEN
  CALL SUCSLINT(YA_NL%LSLHD,YA_NL%LCOMAD,YA_NL%LVSPLIP,YA_NL%LHV,&
   & YA_NL%LQM,YA_NL%LQMH,YA_NL%LQM3D,YA_NL%LQML3D,YA_NL%LINTLIN,YA_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YDDYNA%LSLAG .AND. YA_NL%LPT
  LLPC = LLPC0.AND.YA_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YA,LDADV=YA_NL%LADV,LDMGRID=YA_NL%LMGRID,&
   & LDADV5=YA_NL%LADV5,&
   & LDTDIABLIN=YA_NL%LTDIABLIN,LDHORTURB=YA_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YA_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YA_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YA_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YA_NL%LTDIABLIN
ENDIF

! * Second order flux (for AROME physics):
IF(YSRC%LACTIVE) THEN
  CALL SUCSLINT(YSRC_NL%LSLHD,YSRC_NL%LCOMAD,YSRC_NL%LVSPLIP,YSRC_NL%LHV,&
   & YSRC_NL%LQM,YSRC_NL%LQMH,YSRC_NL%LQM3D,YSRC_NL%LQML3D,YSRC_NL%LINTLIN,YSRC_NL%LVWENO,CLSLINT)
  ! Notice : this field is not supposed to be pronostic !
  LLPT=LPC_FULL .AND. LLDIAB .AND. YSRC_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YSRC_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YSRC,LDADV=YSRC_NL%LADV,LDMGRID=YSRC_NL%LMGRID,&
   & LDADV5=YSRC_NL%LADV5,&
   & LDTDIABLIN=YSRC_NL%LTDIABLIN,LDHORTURB=YSRC_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YSRC_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YSRC_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YSRC_NL%REFVALC)  
  LLTDIABLIN=LLTDIABLIN.OR.YSRC_NL%LTDIABLIN
ENDIF

! * liquid water from mass flux scheme (for AROME physics):
IF(YLMF%LACTIVE) THEN
  CALL SUCSLINT(YLMF_NL%LSLHD,YLMF_NL%LCOMAD,YLMF_NL%LVSPLIP,YLMF_NL%LHV,&
   &YLMF_NL%LQM,YLMF_NL%LQMH,YLMF_NL%LQM3D,YLMF_NL%LQML3D,YLMF_NL%LINTLIN,YLMF_NL%LVWENO,CLSLINT)
  ! Notice : this field is not supposed to be pronostic !
  LLPT=LPC_FULL .AND. LLDIAB .AND. YLMF_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YLMF_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YLMF,LDADV=YLMF_NL%LADV,LDMGRID=YLMF_NL%LMGRID,&
   & LDADV5=YLMF_NL%LADV5,&
   & LDTDIABLIN=YLMF_NL%LTDIABLIN,LDHORTURB=YLMF_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YLMF_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YLMF_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YLMF_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YLMF_NL%LTDIABLIN
ENDIF

! * ice water from mass flux scheme (for AROME physics):
IF(YIMF%LACTIVE) THEN
  CALL SUCSLINT(YIMF_NL%LSLHD,YIMF_NL%LCOMAD,YIMF_NL%LVSPLIP,YIMF_NL%LHV,&
   &YIMF_NL%LQM,YIMF_NL%LQMH,YIMF_NL%LQM3D,YIMF_NL%LQML3D,YIMF_NL%LINTLIN,YIMF_NL%LVWENO,CLSLINT)
  ! Notice : this field is not supposed to be pronostic !
  LLPT=LPC_FULL .AND. LLDIAB .AND. YIMF_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YIMF_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YIMF,LDADV=YIMF_NL%LADV,LDMGRID=YIMF_NL%LMGRID,&
   & LDADV5=YIMF_NL%LADV5,&
   & LDTDIABLIN=YIMF_NL%LTDIABLIN,LDHORTURB=YIMF_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YIMF_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YIMF_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YIMF_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YIMF_NL%LTDIABLIN
ENDIF

! * cloud fraction from mass flux scheme (for AROME physics):
IF(YAMF%LACTIVE) THEN
  CALL SUCSLINT(YAMF_NL%LSLHD,YAMF_NL%LCOMAD,YAMF_NL%LVSPLIP,YAMF_NL%LHV,&
   &YAMF_NL%LQM,YAMF_NL%LQMH,YAMF_NL%LQM3D,YAMF_NL%LQML3D,YAMF_NL%LINTLIN,YAMF_NL%LVWENO,CLSLINT)
  ! Notice : this field is not supposed to be pronostic !
  LLPT=LPC_FULL .AND. LLDIAB .AND. YAMF_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YAMF_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YAMF,LDADV=YAMF_NL%LADV,LDMGRID=YAMF_NL%LMGRID,&
   & LDADV5=YAMF_NL%LADV5,&
   & LDTDIABLIN=YAMF_NL%LTDIABLIN,LDHORTURB=YAMF_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YAMF_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YAMF_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YAMF_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YAMF_NL%LTDIABLIN
ENDIF

! * Weight of the Mass-Flux cloud
IF(YWMFC%LACTIVE) THEN
  CALL SUCSLINT(YWMFC_NL%LSLHD,YWMFC_NL%LCOMAD,YWMFC_NL%LVSPLIP,YWMFC_NL%LHV,&
   &YWMFC_NL%LQM,YWMFC_NL%LQMH,YWMFC_NL%LQM3D,YWMFC_NL%LQML3D,YWMFC_NL%LINTLIN,YWMFC_NL%LVWENO,CLSLINT)
  ! Notice : this field is not supposed to be pronostic !
  LLPT=LPC_FULL .AND. LLDIAB .AND. YWMFC_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YWMFC_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YWMFC,LDADV=YWMFC_NL%LADV,LDMGRID=YWMFC_NL%LMGRID,&
   & LDADV5=YWMFC_NL%LADV5,&
   & LDTDIABLIN=YWMFC_NL%LTDIABLIN,LDHORTURB=YWMFC_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YWMFC_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YWMFC_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YWMFC_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YWMFC_NL%LTDIABLIN
ENDIF

! * High liquid content due to Mass-Flux
IF(YHLMF%LACTIVE) THEN
  CALL SUCSLINT(YHLMF_NL%LSLHD,YHLMF_NL%LCOMAD,YHLMF_NL%LVSPLIP,YHLMF_NL%LHV,&
   &YHLMF_NL%LQM,YHLMF_NL%LQMH,YHLMF_NL%LQM3D,YHLMF_NL%LQML3D,YHLMF_NL%LINTLIN,YHLMF_NL%LVWENO,CLSLINT)
  ! Notice : this field is not supposed to be pronostic !
  LLPT=LPC_FULL .AND. LLDIAB .AND. YHLMF_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YHLMF_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YHLMF,LDADV=YHLMF_NL%LADV,LDMGRID=YHLMF_NL%LMGRID,&
   & LDADV5=YHLMF_NL%LADV5,&
   & LDTDIABLIN=YHLMF_NL%LTDIABLIN,LDHORTURB=YHLMF_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YHLMF_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YHLMF_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YHLMF_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YHLMF_NL%LTDIABLIN
ENDIF

! * High liquid cloud fraction due to Mass-Flux
IF(YHLCFMF%LACTIVE) THEN
  CALL SUCSLINT(YHLCFMF_NL%LSLHD,YHLCFMF_NL%LCOMAD,YHLCFMF_NL%LVSPLIP,YHLCFMF_NL%LHV,&
   &YHLCFMF_NL%LQM,YHLCFMF_NL%LQMH,YHLCFMF_NL%LQM3D,YHLCFMF_NL%LQML3D,YHLCFMF_NL%LINTLIN,YHLCFMF_NL%LVWENO,CLSLINT)
  ! Notice : this field is not supposed to be pronostic !
  LLPT=LPC_FULL .AND. LLDIAB .AND. YHLCFMF_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YHLCFMF_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YHLCFMF,LDADV=YHLCFMF_NL%LADV,LDMGRID=YHLCFMF_NL%LMGRID,&
   & LDADV5=YHLCFMF_NL%LADV5,&
   & LDTDIABLIN=YHLCFMF_NL%LTDIABLIN,LDHORTURB=YHLCFMF_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YHLCFMF_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YHLCFMF_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YHLCFMF_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YHLCFMF_NL%LTDIABLIN
ENDIF

! * High ice content due to Mass-Flux
IF(YHIMF%LACTIVE) THEN
  CALL SUCSLINT(YHIMF_NL%LSLHD,YHIMF_NL%LCOMAD,YHIMF_NL%LVSPLIP,YHIMF_NL%LHV,&
   &YHIMF_NL%LQM,YHIMF_NL%LQMH,YHIMF_NL%LQM3D,YHIMF_NL%LQML3D,YHIMF_NL%LINTLIN,YHIMF_NL%LVWENO,CLSLINT)
  ! Notice : this field is not supposed to be pronostic !
  LLPT=LPC_FULL .AND. LLDIAB .AND. YHIMF_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YHIMF_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YHIMF,LDADV=YHIMF_NL%LADV,LDMGRID=YHIMF_NL%LMGRID,&
   & LDADV5=YHIMF_NL%LADV5,&
   & LDTDIABLIN=YHIMF_NL%LTDIABLIN,LDHORTURB=YHIMF_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YHIMF_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YHIMF_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YHIMF_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YHIMF_NL%LTDIABLIN
ENDIF

! * High ice cloud fraction due to Mass-Flux
IF(YHICFMF%LACTIVE) THEN
  CALL SUCSLINT(YHICFMF_NL%LSLHD,YHICFMF_NL%LCOMAD,YHICFMF_NL%LVSPLIP,YHICFMF_NL%LHV,&
   &YHICFMF_NL%LQM,YHICFMF_NL%LQMH,YHICFMF_NL%LQM3D,YHICFMF_NL%LQML3D,YHICFMF_NL%LINTLIN,YHICFMF_NL%LVWENO,CLSLINT)
  ! Notice : this field is not supposed to be pronostic !
  LLPT=LPC_FULL .AND. LLDIAB .AND. YHICFMF_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YHICFMF_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YHICFMF,LDADV=YHICFMF_NL%LADV,LDMGRID=YHICFMF_NL%LMGRID,&
   & LDADV5=YHICFMF_NL%LADV5,&
   & LDTDIABLIN=YHICFMF_NL%LTDIABLIN,LDHORTURB=YHICFMF_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YHICFMF_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YHICFMF_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YHICFMF_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YHICFMF_NL%LTDIABLIN
ENDIF

! * Liquid water:
IF(YL%LACTIVE) THEN
  CALL SUCSLINT(YL_NL%LSLHD,YL_NL%LCOMAD,YL_NL%LVSPLIP,YL_NL%LHV,&
   & YL_NL%LQM,YL_NL%LQMH,YL_NL%LQM3D,YL_NL%LQML3D,YL_NL%LINTLIN,YL_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YDDYNA%LSLAG .AND. YL_NL%LPT
  LLPC = LLPC0.AND.YL_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YL,LDADV=YL_NL%LADV,LDMGRID=YL_NL%LMGRID,&
   & LDADV5=YL_NL%LADV5,&
   & LDTDIABLIN=YL_NL%LTDIABLIN,LDHORTURB=YL_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YL_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YL_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YL_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YL_NL%LTDIABLIN
ENDIF

! * Liquid water (convective part):
IF(YLCONV%LACTIVE) THEN
  CALL SUCSLINT(YLCONV_NL%LSLHD,YLCONV_NL%LCOMAD,YLCONV_NL%LVSPLIP,YLCONV_NL%LHV,&
   & YLCONV_NL%LQM,YLCONV_NL%LQMH,YLCONV_NL%LQM3D,YLCONV_NL%LQML3D,YLCONV_NL%LINTLIN,YLCONV_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YDDYNA%LSLAG .AND. YLCONV_NL%LPT
  LLPC = LLPC0.AND.YLCONV_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YLCONV,LDADV=YLCONV_NL%LADV,LDMGRID=YLCONV_NL%LMGRID,&
   & LDADV5=YLCONV_NL%LADV5,&
   & LDTDIABLIN=YLCONV_NL%LTDIABLIN,LDHORTURB=YLCONV_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YLCONV_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YLCONV_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YLCONV_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YLCONV_NL%LTDIABLIN
ENDIF

! * Ice water (convective part):
IF(YICONV%LACTIVE) THEN
  CALL SUCSLINT(YICONV_NL%LSLHD,YICONV_NL%LCOMAD,YICONV_NL%LVSPLIP,YICONV_NL%LHV,&
   & YICONV_NL%LQM,YICONV_NL%LQMH,YICONV_NL%LQM3D,YICONV_NL%LQML3D,YICONV_NL%LINTLIN,YICONV_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YDDYNA%LSLAG .AND. YICONV_NL%LPT
  LLPC = LLPC0.AND.YICONV_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YICONV,LDADV=YICONV_NL%LADV,LDMGRID=YICONV_NL%LMGRID,&
   & LDADV5=YICONV_NL%LADV5,&
   & LDTDIABLIN=YICONV_NL%LTDIABLIN,LDHORTURB=YICONV_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YICONV_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YICONV_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YICONV_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YICONV_NL%LTDIABLIN
ENDIF

! * Rain (convective part):
IF(YRCONV%LACTIVE) THEN
  CALL SUCSLINT(YRCONV_NL%LSLHD,YRCONV_NL%LCOMAD,YRCONV_NL%LVSPLIP,YRCONV_NL%LHV,&
   & YRCONV_NL%LQM,YRCONV_NL%LQMH,YRCONV_NL%LQM3D,YRCONV_NL%LQML3D,YRCONV_NL%LINTLIN,YRCONV_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YDDYNA%LSLAG .AND. YRCONV_NL%LPT
  LLPC = LLPC0.AND.YRCONV_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YRCONV,LDADV=YRCONV_NL%LADV,LDMGRID=YRCONV_NL%LMGRID,&
   & LDADV5=YRCONV_NL%LADV5,&
   & LDTDIABLIN=YRCONV_NL%LTDIABLIN,LDHORTURB=YRCONV_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YRCONV_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YRCONV_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YRCONV_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YRCONV_NL%LTDIABLIN
ENDIF

! * Snow (convective part):
IF(YSCONV%LACTIVE) THEN
  CALL SUCSLINT(YSCONV_NL%LSLHD,YSCONV_NL%LCOMAD,YSCONV_NL%LVSPLIP,YSCONV_NL%LHV,&
   & YSCONV_NL%LQM,YSCONV_NL%LQMH,YSCONV_NL%LQM3D,YSCONV_NL%LQML3D,YSCONV_NL%LINTLIN,YSCONV_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YDDYNA%LSLAG .AND. YSCONV_NL%LPT
  LLPC = LLPC0.AND.YSCONV_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YSCONV,LDADV=YSCONV_NL%LADV,LDMGRID=YSCONV_NL%LMGRID,&
   & LDADV5=YSCONV_NL%LADV5,&
   & LDTDIABLIN=YSCONV_NL%LTDIABLIN,LDHORTURB=YSCONV_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YSCONV_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YSCONV_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YSCONV_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YSCONV_NL%LTDIABLIN
ENDIF

! * Radiative Liquid water:
IF(YLRAD%LACTIVE) THEN
  CALL SUCSLINT(YLRAD_NL%LSLHD,YLRAD_NL%LCOMAD,YLRAD_NL%LVSPLIP,YLRAD_NL%LHV,&
   & YLRAD_NL%LQM,YLRAD_NL%LQMH,YLRAD_NL%LQM3D,YLRAD_NL%LQML3D,YLRAD_NL%LINTLIN,YLRAD_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YDDYNA%LSLAG .AND. YLRAD_NL%LPT
  LLPC = LLPC0.AND.YLRAD_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YLRAD,LDADV=YLRAD_NL%LADV,LDMGRID=YLRAD_NL%LMGRID,&
   & LDADV5=YLRAD_NL%LADV5,&
   & LDTDIABLIN=YLRAD_NL%LTDIABLIN,LDHORTURB=YLRAD_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YLRAD_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YLRAD_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YLRAD_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YLRAD_NL%LTDIABLIN
ENDIF

! * Ice:
IF(YI%LACTIVE) THEN
  CALL SUCSLINT(YI_NL%LSLHD,YI_NL%LCOMAD,YI_NL%LVSPLIP,YI_NL%LHV,&
   & YI_NL%LQM,YI_NL%LQMH,YI_NL%LQM3D,YI_NL%LQML3D,YI_NL%LINTLIN,YI_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YDDYNA%LSLAG .AND. YI_NL%LPT
  LLPC = LLPC0.AND.YI_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YI,LDADV=YI_NL%LADV,LDMGRID=YI_NL%LMGRID,&
   & LDADV5=YI_NL%LADV5,&
   & LDTDIABLIN=YI_NL%LTDIABLIN,LDHORTURB=YI_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YI_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YI_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YI_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YI_NL%LTDIABLIN
ENDIF

! * Radiative Ice:
IF(YIRAD%LACTIVE) THEN
  CALL SUCSLINT(YIRAD_NL%LSLHD,YIRAD_NL%LCOMAD,YIRAD_NL%LVSPLIP,YIRAD_NL%LHV,&
   & YIRAD_NL%LQM,YIRAD_NL%LQMH,YIRAD_NL%LQM3D,YIRAD_NL%LQML3D,YIRAD_NL%LINTLIN,YIRAD_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YDDYNA%LSLAG .AND. YIRAD_NL%LPT
  LLPC = LLPC0.AND.YIRAD_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YIRAD,LDADV=YIRAD_NL%LADV,LDMGRID=YIRAD_NL%LMGRID,&
   & LDADV5=YIRAD_NL%LADV5,&
   & LDTDIABLIN=YIRAD_NL%LTDIABLIN,LDHORTURB=YIRAD_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YIRAD_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YIRAD_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YIRAD_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YIRAD_NL%LTDIABLIN
ENDIF

! * Snow:
IF(YS%LACTIVE) THEN
  CALL SUCSLINT(YS_NL%LSLHD,YS_NL%LCOMAD,YS_NL%LVSPLIP,YS_NL%LHV,&
   & YS_NL%LQM,YS_NL%LQMH,YS_NL%LQM3D,YS_NL%LQML3D,YS_NL%LINTLIN,YS_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YS_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YS_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YS,LDADV=YS_NL%LADV,LDMGRID=YS_NL%LMGRID,&
   & LDADV5=YS_NL%LADV5,&
   & LDTDIABLIN=YS_NL%LTDIABLIN,LDHORTURB=YS_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YS_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YS_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YS_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YS_NL%LTDIABLIN
ENDIF

! * Rain:
IF(YR%LACTIVE) THEN
  CALL SUCSLINT(YR_NL%LSLHD,YR_NL%LCOMAD,YR_NL%LVSPLIP,YR_NL%LHV,&
   & YR_NL%LQM,YR_NL%LQMH,YR_NL%LQM3D,YR_NL%LQML3D,YR_NL%LINTLIN,YR_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YR_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YR_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YR,LDADV=YR_NL%LADV,LDMGRID=YR_NL%LMGRID,&
   & LDADV5=YR_NL%LADV5, &
   & LDTDIABLIN=YR_NL%LTDIABLIN,LDHORTURB=YR_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YR_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YR_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YR_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YR_NL%LTDIABLIN
ENDIF

! * Graupels:
IF(YG%LACTIVE) THEN
  CALL SUCSLINT(YG_NL%LSLHD,YG_NL%LCOMAD,YG_NL%LVSPLIP,YG_NL%LHV,&
   & YG_NL%LQM,YG_NL%LQMH,YG_NL%LQM3D,YG_NL%LQML3D,YG_NL%LINTLIN,YG_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YG_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YG_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YG,LDADV=YG_NL%LADV,LDMGRID=YG_NL%LMGRID,&
   & LDADV5=YG_NL%LADV5,&
   & LDTDIABLIN=YG_NL%LTDIABLIN,LDHORTURB=YG_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YG_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YG_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YG_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YG_NL%LTDIABLIN
ENDIF

! * Hail:
IF(YH%LACTIVE) THEN
  CALL SUCSLINT(YH_NL%LSLHD,YH_NL%LCOMAD,YH_NL%LVSPLIP,YH_NL%LHV,&
   & YH_NL%LQM,YH_NL%LQMH,YH_NL%LQM3D,YH_NL%LQML3D,YH_NL%LINTLIN,YH_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YH_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YH_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YH,LDADV=YH_NL%LADV,LDMGRID=YH_NL%LMGRID,&
   & LDADV5=YH_NL%LADV5,&
   & LDTDIABLIN=YH_NL%LTDIABLIN,LDHORTURB=YH_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YH_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YH_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YH_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YH_NL%LTDIABLIN
ENDIF

! * CVGQ:
LLAD=YCVGQ%LGP
IF(YCVGQ%LACTIVE) THEN
  CALL SUCSLINT(YCVGQ_NL%LSLHD,YCVGQ_NL%LCOMAD,YCVGQ_NL%LVSPLIP,&
   & YCVGQ_NL%LHV,YCVGQ_NL%LQM,YCVGQ_NL%LQMH,YCVGQ_NL%LQM3D, &
   & YCVGQ_NL%LQML3D,YCVGQ_NL%LINTLIN,YCVGQ_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YCPF_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YCPF_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YCVGQ,LDADV=LLAD,LDMGRID=YCVGQ_NL%LMGRID,&
   & LDADV5=YCVGQ_NL%LADV5,&
   & LDTDIABLIN=YCVGQ_NL%LTDIABLIN,LDHORTURB=YCVGQ_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YCVGQ_NL%LPHY,LDPT=LLPT,&
   & LDPC=LLPC,KCOUPLING=0,CDSLINT=CLSLINT,PREFVALC=YCVGQ_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YCVGQ_NL%LTDIABLIN
ENDIF

! * TKE:
IF(YTKE%LACTIVE) THEN
  CALL SUCSLINT(YTKE_NL%LSLHD,YTKE_NL%LCOMAD,YTKE_NL%LVSPLIP,&
   & YTKE_NL%LHV,YTKE_NL%LQM,YTKE_NL%LQMH,YTKE_NL%LQM3D, &
   & YTKE_NL%LQML3D,YTKE_NL%LINTLIN,YTKE_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YTKE_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YTKE_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YTKE,LDADV=YTKE_NL%LADV,LDMGRID=YTKE_NL%LMGRID,&
   & LDADV5=YTKE_NL%LADV5,&
   & LDTDIABLIN=YTKE_NL%LTDIABLIN,LDHORTURB=YTKE_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YTKE_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YTKE_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YTKE_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YTKE_NL%LTDIABLIN
ENDIF

! * EFB1:
IF(YEFB1%LACTIVE) THEN
  CALL SUCSLINT(YEFB1_NL%LSLHD,YEFB1_NL%LCOMAD,YEFB1_NL%LVSPLIP,&
   & YEFB1_NL%LHV,YEFB1_NL%LQM,YEFB1_NL%LQMH,YEFB1_NL%LQM3D, &
   & YEFB1_NL%LQML3D,YEFB1_NL%LINTLIN,YEFB1_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YEFB1_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YEFB1_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YEFB1,LDADV=YEFB1_NL%LADV,LDMGRID=YEFB1_NL%LMGRID,&
   & LDADV5=YEFB1_NL%LADV5,&
   & LDTDIABLIN=YEFB1_NL%LTDIABLIN,LDHORTURB=YEFB1_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YEFB1_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YEFB1_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YEFB1_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YEFB1_NL%LTDIABLIN
ENDIF

! * EFB2:
IF(YEFB2%LACTIVE) THEN
  CALL SUCSLINT(YEFB2_NL%LSLHD,YEFB2_NL%LCOMAD,YEFB2_NL%LVSPLIP,&
   & YEFB2_NL%LHV,YEFB2_NL%LQM,YEFB2_NL%LQMH,YEFB2_NL%LQM3D, &
   & YEFB2_NL%LQML3D,YEFB2_NL%LINTLIN,YEFB2_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YEFB2_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YEFB2_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YEFB2,LDADV=YEFB2_NL%LADV,LDMGRID=YEFB2_NL%LMGRID,&
   & LDADV5=YEFB2_NL%LADV5,&
   & LDTDIABLIN=YEFB2_NL%LTDIABLIN,LDHORTURB=YEFB2_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YEFB2_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YEFB2_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YEFB2_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YEFB2_NL%LTDIABLIN
ENDIF

! * EFB3:
IF(YEFB3%LACTIVE) THEN
  CALL SUCSLINT(YEFB3_NL%LSLHD,YEFB3_NL%LCOMAD,YEFB3_NL%LVSPLIP,&
   & YEFB3_NL%LHV,YEFB3_NL%LQM,YEFB3_NL%LQMH,YEFB3_NL%LQM3D, &
   & YEFB3_NL%LQML3D,YEFB3_NL%LINTLIN,YEFB3_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YEFB3_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YEFB3_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YEFB3,LDADV=YEFB3_NL%LADV,LDMGRID=YEFB3_NL%LMGRID,&
   & LDADV5=YEFB3_NL%LADV5,&
   & LDTDIABLIN=YEFB3_NL%LTDIABLIN,LDHORTURB=YEFB3_NL%LHORTURB,LDT9=LLT9,&
   & LDPHY=YEFB3_NL%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YEFB3_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YEFB3_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YEFB3_NL%LTDIABLIN
ENDIF

! * Convective precipitation flux:
IF(YCPF%LACTIVE) THEN
  CALL SUCSLINT(YCPF_NL%LSLHD,YCPF_NL%LCOMAD,YCPF_NL%LVSPLIP,&
   & YCPF_NL%LQML3D,YCPF_NL%LHV,YCPF_NL%LQM,YCPF_NL%LQMH,YCPF_NL%LQM3D, &
   & YCPF_NL%LINTLIN,YCPF_NL%LVWENO,CLSLINT)
  ! Notice : this field is not supposed to be pronostic !
  LLPT=LPC_FULL .AND. LLDIAB .AND. YCPF_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YCPF_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YCPF,LDADV=.FALSE.,LDMGRID=.FALSE.,&
   & LDT9=LLT9,LDPHY=YCPF_NL%LPHY, &
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YCPF_NL%NCOUPLING,&
   & PREFVALC=YCPF_NL%REFVALC)
ENDIF

! * Stratiform precipitation flux:
IF(YSPF%LACTIVE) THEN
  CALL SUCSLINT(YSPF_NL%LSLHD,YSPF_NL%LCOMAD,YSPF_NL%LVSPLIP,&
   & YSPF_NL%LHV,YSPF_NL%LQM,YSPF_NL%LQMH,YSPF_NL%LQM3D, &
   & YSPF_NL%LQML3D,YSPF_NL%LINTLIN,YSPF_NL%LVWENO,CLSLINT)
  ! Notice : this field is not supposed to be pronostic !
  LLPT=LPC_FULL .AND. LLDIAB .AND. YSPF_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YSPF_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YSPF,LDADV=.FALSE.,LDMGRID=.FALSE.,&
   & LDT9=LLT9,LDPHY=YSPF_NL%LPHY, &
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YSPF_NL%NCOUPLING,&
   & PREFVALC=YSPF_NL%REFVALC)
ENDIF

! * Standard deviation of the saturation depression:
IF(YSDSAT%LACTIVE) THEN
  CALL SUCSLINT(YSDSAT_NL%LSLHD,YSDSAT_NL%LCOMAD,YSDSAT_NL%LVSPLIP,&
   & YSDSAT_NL%LHV,YSDSAT_NL%LQM,YSDSAT_NL%LQMH,YSDSAT_NL%LQM3D,&
   & YSDSAT_NL%LQML3D,YSDSAT_NL%LINTLIN,YSDSAT_NL%LVWENO,CLSLINT)
  ! Notice : this field is not supposed to be pronostic !
  LLPT=LPC_FULL .AND. LLDIAB .AND. YSDSAT_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YSDSAT_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YSDSAT,&
   & LDMGRID=YSDSAT_NL%LMGRID,&
   & LDTDIABLIN=YSDSAT_NL%LTDIABLIN,LDHORTURB=YSDSAT_NL%LHORTURB,&
   & LDT9=LLT9,LDPHY=YSDSAT_NL%LPHY,&
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YSDSAT_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YSDSAT_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YSDSAT_NL%LTDIABLIN
ENDIF

! * Convective vertical velocity:
IF(YCVV%LACTIVE) THEN
  CALL SUCSLINT(YCVV_NL%LSLHD,YCVV_NL%LCOMAD,YCVV_NL%LVSPLIP,&
   & YCVV_NL%LHV,YCVV_NL%LQM,YCVV_NL%LQMH,YCVV_NL%LQM3D,&
   & YCVV_NL%LQML3D,YCVV_NL%LINTLIN,YCVV_NL%LVWENO,CLSLINT)
  ! Notice : this field is not supposed to be pronostic !
  LLPT=LPC_FULL .AND. LLDIAB .AND. YCVV_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YCVV_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YCVV,LDADV=YCVV_NL%LADV,&
   & LDMGRID=YCVV_NL%LMGRID,&
   & LDTDIABLIN=YCVV_NL%LTDIABLIN,LDHORTURB=YCVV_NL%LHORTURB,&
   & LDT9=LLT9,LDPHY=YCVV_NL%LPHY,&
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YCVV_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YCVV_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YCVV_NL%LTDIABLIN
ENDIF

! * Total humidity variation (for HIRLAM physics):
IF(YQVA%LACTIVE) THEN
  ! prepare variable YQVA used in HIRLAM cloud- and condensation. 
  CALL SUCSLINT(YQVA_NL%LSLHD,YQVA_NL%LCOMAD,YQVA_NL%LVSPLIP,&
   & YQVA_NL%LHV,YQVA_NL%LQM,YQVA_NL%LQMH,YQVA_NL%LQM3D, &
   & YQVA_NL%LQML3D,YQVA_NL%LINTLIN,YQVA_NL%LVWENO,CLSLINT)
  ! Notice : this field is not supposed to be pronostic 
  LLPT=LPC_FULL .AND. LLDIAB .AND. YQVA_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YQVA_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YQVA,LDADV=.FALSE.,LDMGRID=.FALSE.,&
   & LDT9=LLT9,LDPHY=YQVA_NL%LPHY, &
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YQVA_NL%NCOUPLING,&
   & PREFVALC=YQVA_NL%REFVALC)
ENDIF

! * "Prognostic convection" variables (for ALARO physics):
!   interpolations like for q.
IF(YUOM%LACTIVE) THEN
  CALL SUCSLINT(YUOM_NL%LSLHD,YUOM_NL%LCOMAD,YUOM_NL%LVSPLIP,&
   & YUOM_NL%LHV,YUOM_NL%LQM,YUOM_NL%LQMH,YUOM_NL%LQM3D, &
   & YUOM_NL%LQML3D,YUOM_NL%LINTLIN,YUOM_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YUOM_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YUOM_NL%LPC 
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YUOM,LDADV=YUOM_NL%LADV,&
   & LDMGRID=YUOM_NL%LMGRID,&
   & LDTDIABLIN=YUOM_NL%LTDIABLIN,LDHORTURB=YUOM_NL%LHORTURB,&
   & LDT9=LLT9,LDPHY=YUOM_NL%LPHY,&
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YUOM_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YUOM_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YUOM_NL%LTDIABLIN
ENDIF
IF(YUAL%LACTIVE) THEN
  CALL SUCSLINT(YUAL_NL%LSLHD,YUAL_NL%LCOMAD,YUAL_NL%LVSPLIP,&
   & YUAL_NL%LHV,YUAL_NL%LQM,YUAL_NL%LQMH,YUAL_NL%LQM3D, &
   & YUAL_NL%LQML3D,YUAL_NL%LINTLIN,YUAL_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YUAL_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YUAL_NL%LPC 
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YUAL,LDADV=YUAL_NL%LADV,&
   & LDMGRID=YUAL_NL%LMGRID,&
   & LDTDIABLIN=YUAL_NL%LTDIABLIN,LDHORTURB=YUAL_NL%LHORTURB,&
   & LDT9=LLT9,LDPHY=YUAL_NL%LPHY,&
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YUAL_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YUAL_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YUAL_NL%LTDIABLIN
ENDIF
IF(YDOM%LACTIVE) THEN
  CALL SUCSLINT(YDOM_NL%LSLHD,YDOM_NL%LCOMAD,YDOM_NL%LVSPLIP,&
   & YDOM_NL%LHV,YDOM_NL%LQM,YDOM_NL%LQMH,YDOM_NL%LQM3D, &
   & YDOM_NL%LQML3D,YDOM_NL%LINTLIN,YDOM_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YDOM_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YDOM_NL%LPC 
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YDOM,LDADV=YDOM_NL%LADV,&
   & LDMGRID=YDOM_NL%LMGRID,&
   & LDTDIABLIN=YDOM_NL%LTDIABLIN,LDHORTURB=YDOM_NL%LHORTURB,&
   & LDT9=LLT9,LDPHY=YDOM_NL%LPHY,&
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YDOM_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YDOM_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YDOM_NL%LTDIABLIN
ENDIF
IF(YDAL%LACTIVE) THEN
  CALL SUCSLINT(YDAL_NL%LSLHD,YDAL_NL%LCOMAD,YDAL_NL%LVSPLIP,&
   & YDAL_NL%LHV,YDAL_NL%LQM,YDAL_NL%LQMH,YDAL_NL%LQM3D, &
   & YDAL_NL%LQML3D,YDAL_NL%LINTLIN,YDAL_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YDAL_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YDAL_NL%LPC 
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YDAL,LDADV=YDAL_NL%LADV,&
   & LDMGRID=YDAL_NL%LMGRID,&
   & LDTDIABLIN=YDAL_NL%LTDIABLIN,LDHORTURB=YDAL_NL%LHORTURB,&
   & LDT9=LLT9,LDPHY=YDAL_NL%LPHY,&
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YDAL_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YDAL_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YDAL_NL%LTDIABLIN
ENDIF
IF(YUEN%LACTIVE) THEN
  CALL SUCSLINT(YUEN_NL%LSLHD,YUEN_NL%LCOMAD,YUEN_NL%LVSPLIP,&
   & YUEN_NL%LHV,YUEN_NL%LQM,YUEN_NL%LQMH,YUEN_NL%LQM3D, &
   & YUEN_NL%LQML3D,YUEN_NL%LINTLIN,YUEN_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YUEN_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YUEN_NL%LPC 
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YUEN,LDADV=YUEN_NL%LADV,&
   & LDMGRID=YUEN_NL%LMGRID,&
   & LDTDIABLIN=YUEN_NL%LTDIABLIN,LDHORTURB=YUEN_NL%LHORTURB,&
   & LDT9=LLT9,LDPHY=YUEN_NL%LPHY,&
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YUEN_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YUEN_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YUEN_NL%LTDIABLIN
ENDIF
IF(YUNEBH%LACTIVE) THEN
  CALL SUCSLINT(YUNEBH_NL%LSLHD,YUNEBH_NL%LCOMAD,YUNEBH_NL%LVSPLIP,&
   & YUNEBH_NL%LHV,YUNEBH_NL%LQM,YUNEBH_NL%LQMH,YUNEBH_NL%LQM3D,&
   & YUNEBH_NL%LQM3D,YUNEBH_NL%LINTLIN,YUNEBH_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YUNEBH_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YUNEBH_NL%LPC 
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YUNEBH,LDADV=YUNEBH_NL%LADV,&
   & LDMGRID=YUNEBH_NL%LMGRID,&
   & LDTDIABLIN=YUNEBH_NL%LTDIABLIN,LDHORTURB=YUNEBH_NL%LHORTURB,&
   & LDT9=LLT9,LDPHY=YUNEBH_NL%LPHY,&
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YUNEBH_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YUNEBH_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YUNEBH_NL%LTDIABLIN
ENDIF
IF(YTTE%LACTIVE) THEN
  CALL SUCSLINT(YTTE_NL%LSLHD,YTTE_NL%LCOMAD,YTTE_NL%LVSPLIP,&
   & YTTE_NL%LHV,YTTE_NL%LQM,YTTE_NL%LQMH,YTTE_NL%LQM3D,&
   & YTTE_NL%LQML3D,YTTE_NL%LINTLIN,YTTE_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YTTE_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YTTE_NL%LPC 
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YTTE,LDADV=YTTE_NL%LADV,&
   & LDMGRID=YTTE_NL%LMGRID,&
   & LDTDIABLIN=YTTE_NL%LTDIABLIN,LDHORTURB=YTTE_NL%LHORTURB,&
   & LDT9=LLT9,LDPHY=YTTE_NL%LPHY,&
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YTTE_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YTTE_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YTTE_NL%LTDIABLIN
ENDIF
IF(YMXL%LACTIVE) THEN
  CALL SUCSLINT(YMXL_NL%LSLHD,YMXL_NL%LCOMAD,YMXL_NL%LVSPLIP,&
   & YMXL_NL%LHV,YMXL_NL%LQM,YMXL_NL%LQMH,YMXL_NL%LQM3D,&
   & YMXL_NL%LQML3D,YMXL_NL%LINTLIN,YMXL_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YMXL_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YMXL_NL%LPC 
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YMXL,LDADV=YMXL_NL%LADV,&
   & LDMGRID=YMXL_NL%LMGRID,&
   & LDTDIABLIN=YMXL_NL%LTDIABLIN,LDHORTURB=YMXL_NL%LHORTURB,&
   & LDT9=LLT9,LDPHY=YMXL_NL%LPHY,&
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YMXL_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YMXL_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YMXL_NL%LTDIABLIN
ENDIF
IF(YSHTUR%LACTIVE) THEN
  CALL SUCSLINT(YSHTUR_NL%LSLHD,YSHTUR_NL%LCOMAD,YSHTUR_NL%LVSPLIP,&
   & YSHTUR_NL%LHV,YSHTUR_NL%LQM,YSHTUR_NL%LQMH,YSHTUR_NL%LQM3D,&
   & YSHTUR_NL%LQML3D,YSHTUR_NL%LINTLIN,YSHTUR_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YSHTUR_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YSHTUR_NL%LPC 
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YSHTUR,LDADV=YSHTUR_NL%LADV,&
   & LDMGRID=YSHTUR_NL%LMGRID,&
   & LDTDIABLIN=YSHTUR_NL%LTDIABLIN,LDHORTURB=YSHTUR_NL%LHORTURB,&
   & LDT9=LLT9,LDPHY=YSHTUR_NL%LPHY,&
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YSHTUR_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YSHTUR_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YSHTUR_NL%LTDIABLIN
ENDIF
IF(YFQTUR%LACTIVE) THEN
  CALL SUCSLINT(YFQTUR_NL%LSLHD,YFQTUR_NL%LCOMAD,YFQTUR_NL%LVSPLIP,&
   & YFQTUR_NL%LHV,YFQTUR_NL%LQM,YFQTUR_NL%LQMH,YFQTUR_NL%LQM3D,&
   & YFQTUR_NL%LQML3D,YFQTUR_NL%LINTLIN,YFQTUR_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YFQTUR_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YFQTUR_NL%LPC 
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YFQTUR,LDADV=YFQTUR_NL%LADV,&
   & LDMGRID=YFQTUR_NL%LMGRID,&
   & LDTDIABLIN=YFQTUR_NL%LTDIABLIN,LDHORTURB=YFQTUR_NL%LHORTURB,&
   & LDT9=LLT9,LDPHY=YFQTUR_NL%LPHY,&
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YFQTUR_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YFQTUR_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YFQTUR_NL%LTDIABLIN
ENDIF
IF(YFSTUR%LACTIVE) THEN
  CALL SUCSLINT(YFSTUR_NL%LSLHD,YFSTUR_NL%LCOMAD,YFSTUR_NL%LVSPLIP,&
   & YFSTUR_NL%LHV,YFSTUR_NL%LQM,YFSTUR_NL%LQMH,YFSTUR_NL%LQM3D,&
   & YFSTUR_NL%LQML3D,YFSTUR_NL%LINTLIN,YFSTUR_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YFSTUR_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YFSTUR_NL%LPC 
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YFSTUR,LDADV=YFSTUR_NL%LADV,&
   & LDMGRID=YFSTUR_NL%LMGRID,&
   & LDTDIABLIN=YFSTUR_NL%LTDIABLIN,LDHORTURB=YFSTUR_NL%LHORTURB,&
   & LDT9=LLT9,LDPHY=YFSTUR_NL%LPHY,&
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YFSTUR_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YFSTUR_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YFSTUR_NL%LTDIABLIN
ENDIF
IF(YRKTH%LACTIVE) THEN
  CALL SUCSLINT(YRKTH_NL%LSLHD,YRKTH_NL%LCOMAD,YRKTH_NL%LVSPLIP,&
   & YRKTH_NL%LHV,YRKTH_NL%LQM,YRKTH_NL%LQMH,YRKTH_NL%LQM3D,&
   & YRKTH_NL%LQML3D,YRKTH_NL%LINTLIN,YRKTH_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YRKTH_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YRKTH_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YRKTH,LDADV=YRKTH_NL%LADV,&
   & LDMGRID=YRKTH_NL%LMGRID,&
   & LDTDIABLIN=YRKTH_NL%LTDIABLIN,LDHORTURB=YRKTH_NL%LHORTURB,&
   & LDT9=LLT9,LDPHY=YRKTH_NL%LPHY,&
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YRKTH_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YRKTH_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YRKTH_NL%LTDIABLIN
ENDIF
IF(YRKTQV%LACTIVE) THEN
  CALL SUCSLINT(YRKTQV_NL%LSLHD,YRKTQV_NL%LCOMAD,YRKTQV_NL%LVSPLIP,&
   & YRKTQV_NL%LHV,YRKTQV_NL%LQM,YRKTQV_NL%LQMH,YRKTQV_NL%LQM3D,&
   & YRKTQV_NL%LQML3D,YRKTQV_NL%LINTLIN,YRKTQV_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YRKTQV_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YRKTQV_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YRKTQV,LDADV=YRKTQV_NL%LADV,&
   & LDMGRID=YRKTQV_NL%LMGRID,&
   & LDTDIABLIN=YRKTQV_NL%LTDIABLIN,LDHORTURB=YRKTQV_NL%LHORTURB,&
   & LDT9=LLT9,LDPHY=YRKTQV_NL%LPHY,&
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YRKTQV_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YRKTQV_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YRKTQV_NL%LTDIABLIN
ENDIF
IF(YRKTQC%LACTIVE) THEN
  CALL SUCSLINT(YRKTQC_NL%LSLHD,YRKTQC_NL%LCOMAD,YRKTQC_NL%LVSPLIP,&
   & YRKTQC_NL%LHV,YRKTQC_NL%LQM,YRKTQC_NL%LQMH,YRKTQC_NL%LQM3D,&
   & YRKTQC_NL%LQML3D,YRKTQC_NL%LINTLIN,YRKTQC_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YRKTQC_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YRKTQC_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YRKTQC,LDADV=YRKTQC_NL%LADV,&
   & LDMGRID=YRKTQC_NL%LMGRID,&
   & LDTDIABLIN=YRKTQC_NL%LTDIABLIN,LDHORTURB=YRKTQC_NL%LHORTURB,&
   & LDT9=LLT9,LDPHY=YRKTQC_NL%LPHY,&
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YRKTQC_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YRKTQC_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YRKTQC_NL%LTDIABLIN
ENDIF

!* PHYCTY
IF(YPHYCTY%LACTIVE) THEN
  CALL SUCSLINT(YPHYCTY_NL%LSLHD,YPHYCTY_NL%LCOMAD,YPHYCTY_NL%LVSPLIP,&
   & YPHYCTY_NL%LHV,YPHYCTY_NL%LQM,YPHYCTY_NL%LQMH,YPHYCTY_NL%LQM3D,&
   & YPHYCTY_NL%LQML3D,YPHYCTY_NL%LINTLIN,YPHYCTY_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YPHYCTY_NL%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YPHYCTY_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YPHYCTY,LDADV=YPHYCTY_NL%LADV,&
   & LDTDIABLIN=YPHYCTY_NL%LTDIABLIN,LDHORTURB=YPHYCTY_NL%LHORTURB,&
   & LDT9=.FALSE.,LDPHY=YPHYCTY_NL%LPHY,&
   & LDPT=LLPT,LDPC=LLPC,KCOUPLING=YPHYCTY_NL%NCOUPLING,&
   & CDSLINT=CLSLINT,PREFVALC=YPHYCTY_NL%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YRKTQC_NL%LTDIABLIN
ENDIF


! * LRCH4:
IF(NGHG > 0 .AND. YLRCH4%LACTIVE) THEN
  CALL SUCSLINT(YLRCH4_NL%LSLHD,YLRCH4_NL%LCOMAD,YLRCH4_NL%LVSPLIP,YLRCH4_NL%LHV,&
   & YLRCH4_NL%LQM,YLRCH4_NL%LQMH,YLRCH4_NL%LQM3D,&
   & YLRCH4_NL%LQML3D,YLRCH4_NL%LINTLIN,YLRCH4_NL%LVWENO,CLSLINT)
  LLPT=LPC_FULL.AND.LLDIAB.AND.YDDYNA%LSLAG.AND.YLRCH4_NL%LPT
  LLPC = LLPC0.AND.YLRCH4_NL%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YLRCH4,LDADV=YLRCH4_NL%LADV,LDMGRID=YLRCH4_NL%LMGRID,&
   & LDADV5=YLRCH4_NL%LADV5, &
   & LDT9=LLT9,LDPHY=YLRCH4_NL%LPHY,LDPT=LLPT,LDPC=LLPC,&
   & KCOUPLING=YLRCH4_NL%NCOUPLING,CDSLINT=CLSLINT,&
   & PREFVALC=YLRCH4_NL%REFVALC)
ENDIF


! * variable FSD
IF(NFSD > 0) THEN
  LLPT = .FALSE.
  LLPC = .FALSE.
  LLT9 = .FALSE.
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YFSD,LDADV=.FALSE.,LDT9=LLT9,&
     & LDPHY=YFSD_NL%LPHY,LDPT=LLPT, LDPC=LLPC,&
     & KCOUPLING=YFSD_NL%NCOUPLING,&
     & PREFVALC=YFSD_NL%REFVALC)
ENDIF

! * Aerosols, greenhouse gases, tracers, CHEM, reactive gases:
!   Remark k.y.: these variables are currently used for ECMWF applications
!    and LDADV=LSLAG in the CALL of SET_GFL_ATTR
!    (that means that the namelist value of Y[X]_NL(JGFL)%LADV and
!    Y[X]_NL(JGFL)%LPHY is not taken into account). The calls to SET_GFL_ATTR
!    must be probably revised if some other teams wanted to use such GFL for
!    their own applications.
DO JGFL=1,NAERO
  CALL SUCSLINT(YAERO_NL(JGFL)%LSLHD,YAERO_NL(JGFL)%LCOMAD,&
   & YAERO_NL(JGFL)%LVSPLIP,YAERO_NL(JGFL)%LHV,&
   & YAERO_NL(JGFL)%LQM,YAERO_NL(JGFL)%LQMH,YAERO_NL(JGFL)%LQM3D,&
   & YAERO_NL(JGFL)%LQML3D,YAERO_NL(JGFL)%LINTLIN,YAERO_NL(JGFL)%LVWENO,CLSLINT)
  LLPT = LPC_FULL .AND. LLDIAB .AND. YAERO_NL(JGFL)%LPT .AND. YDDYNA%LSLAG
  LLPC = LLPC0.AND.YAERO_NL(JGFL)%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YAERO(JGFL),LDADV=YAERO_NL(JGFL)%LADV,&
   & LDMGRID=YAERO_NL(JGFL)%LMGRID,LDADV5=YAERO_NL(JGFL)%LADV5, &
   & LDT9=LLT9,LDPHY=YAERO_NL(JGFL)%LPHY,LDPT=LLPT,LDPC=LLPC,&
   & KCOUPLING=YAERO_NL(JGFL)%NCOUPLING,CDSLINT=CLSLINT,&
   & PREFVALC=YAERO_NL(JGFL)%REFVALC)
ENDDO
DO JGFL=1,NGHG
  CALL SUCSLINT(YGHG_NL(JGFL)%LSLHD,YGHG_NL(JGFL)%LCOMAD,&
   & YGHG_NL(JGFL)%LVSPLIP,YGHG_NL(JGFL)%LHV,& 
   & YGHG_NL(JGFL)%LQM,YGHG_NL(JGFL)%LQMH,YGHG_NL(JGFL)%LQM3D,&
   & YGHG_NL(JGFL)%LQML3D,YGHG_NL(JGFL)%LINTLIN,YGHG_NL(JGFL)%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YGHG_NL(JGFL)%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YGHG_NL(JGFL)%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YGHG(JGFL),LDADV=YGHG_NL(JGFL)%LADV,&
   & LDMGRID=YGHG_NL(JGFL)%LMGRID,LDADV5=YGHG_NL(JGFL)%LADV5,&
   & LDT9=LLT9,LDPHY=YGHG_NL(JGFL)%LPHY,LDPT=LLPT,LDPC=LLPC,&
   & KCOUPLING=YGHG_NL(JGFL)%NCOUPLING,CDSLINT=CLSLINT,&
   & PREFVALC=YGHG_NL(JGFL)%REFVALC)
ENDDO
DO JGFL=1,NCHEM
  CALL SUCSLINT(YCHEM_NL(JGFL)%LSLHD,YCHEM_NL(JGFL)%LCOMAD,&
   & YCHEM_NL(JGFL)%LVSPLIP,YCHEM_NL(JGFL)%LHV,&
   & YCHEM_NL(JGFL)%LQM,YCHEM_NL(JGFL)%LQMH,YCHEM_NL(JGFL)%LQM3D,&
   & YCHEM_NL(JGFL)%LQML3D,YCHEM_NL(JGFL)%LINTLIN,YCHEM_NL(JGFL)%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YCHEM_NL(JGFL)%LPT.AND.YDDYNA%LSLAG
  LLPC = LLPC0.AND.YCHEM_NL(JGFL)%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YCHEM(JGFL),LDADV=YCHEM_NL(JGFL)%LADV,&
   & LDMGRID=YCHEM_NL(JGFL)%LMGRID,LDADV5=YCHEM_NL(JGFL)%LADV5,&
   & LDT9=LLT9,LDPHY=YCHEM_NL(JGFL)%LPHY,LDPT=LLPT,LDPC=LLPC,&
   & KCOUPLING=YCHEM_NL(JGFL)%NCOUPLING,CDSLINT=CLSLINT,&
   & PREFVALC=YCHEM_NL(JGFL)%REFVALC)
ENDDO

! * ERA40 fields: these variables are currently used for ECMWF applications.
DO JGFL=1,NERA40
  LLPT = .FALSE.
  LLPC = .FALSE. 
  LLT9 = .FALSE.
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YERA40(JGFL),LDADV=.FALSE.,LDMGRID=.FALSE.,&
   & LDT9=LLT9,LDPHY=YERA40_NL(JGFL)%LPHY,LDPT=LLPT, LDPC=LLPC,&
   & KCOUPLING=YERA40_NL(JGFL)%NCOUPLING,&
   & PREFVALC=YERA40_NL(JGFL)%REFVALC)
ENDDO

! * NOGW fields: noro gwd scheme fields used for ECMWF applications
DO JGFL=1,NNOGW
  LLPT = .FALSE.
  LLPC = .FALSE.
  LLT9 = .FALSE.
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YNOGW(JGFL),LDADV=.FALSE.,&
   & LDMGRID=.FALSE.,LDT9=LLT9,&
   & LDPHY=YNOGW_NL(JGFL)%LPHY,LDPT=LLPT, LDPC=LLPC,&
   & KCOUPLING=YNOGW_NL(JGFL)%NCOUPLING,&
   & PREFVALC=YNOGW_NL(JGFL)%REFVALC)
ENDDO

! 3D emissions for atmospheric composition
!DO JGFL=1,NEMIS3D
!  !ZKFIXME SUSCLINT and SET_GFL_ATTR for EMIS3D?
!ENDDO

! * EDRP fields: EDRP turbulence diagnostics for ECMWF applications
DO JGFL=1,NEDRP
  LLPT = .FALSE.
  LLPC = .FALSE.
  LLT9 = .FALSE.
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YEDRP(JGFL),LDADV=.FALSE.,&
   & LDMGRID=.FALSE.,LDT9=LLT9,&
   & LDPHY=YEDRP_NL(JGFL)%LPHY,LDPT=LLPT, LDPC=LLPC,&
   & KCOUPLING=YEDRP_NL(JGFL)%NCOUPLING,&
   & PREFVALC=YEDRP_NL(JGFL)%REFVALC)
ENDDO

! * NUVP fields: UV processor output fields used for ECMWF applications
DO JGFL=1,NUVP
  LLPT = .FALSE.
  LLPC = .FALSE.
  LLT9 = .FALSE.
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YUVP(JGFL),LDADV=.FALSE.,&
   & LDMGRID=.FALSE.,LDT9=LLT9,&
   & LDPHY=YUVP_NL(JGFL)%LPHY,LDPT=LLPT, LDPC=LLPC,&
   & KCOUPLING=YUVP_NL(JGFL)%NCOUPLING,&
   & PREFVALC=YUVP_NL(JGFL)%REFVALC)
ENDDO

IF (LAERAOT .AND. NAERO > 0) THEN
  ! * NPAERAOT fields: aerosol optical thicknesses used for ECMWF applications
  DO JGFL=1,NPAERAOT
    LLPT = .FALSE.
    LLPC = .FALSE.
    LLT9 = .FALSE.
    CALL SET_GFL_ATTR(YDDIMV,YGFL,YAERAOT(JGFL),LDADV=.FALSE.,LDT9=LLT9,&
     & LDPHY=YAERAOT_NL(JGFL)%LPHY,LDPT=LLPT, LDPC=LLPC,&
     & KCOUPLING=YAERAOT_NL(JGFL)%NCOUPLING,&
     & PREFVALC=YAERAOT_NL(JGFL)%REFVALC)
  ENDDO
ENDIF

IF (LAERLISI) THEN
  ! * NPAERLISI fields: aerosol lidar simulator used for ECMWF applications
  JGFL = 0
  DO JVAR=1,NPAERLISI_VAR
    DO JWVL=1,NPAERLISI_WVL
    JGFL = JGFL + 1
    LLPT = .FALSE.
    LLPC = .FALSE.
    LLT9 = .FALSE.
    CALL SET_GFL_ATTR(YDDIMV,YGFL,YAERLISI(JGFL),LDADV=.FALSE.,LDT9=LLT9,&
     & LDPHY=YAERLISI_NL(JWVL,JVAR)%LPHY,LDPT=LLPT, LDPC=LLPC,&
     & KCOUPLING=YAERLISI_NL(JWVL,JVAR)%NCOUPLING,&
     & PREFVALC=YAERLISI_NL(JWVL,JVAR)%REFVALC)
    ENDDO
  ENDDO
ENDIF

! * NAEROUT fields: aerosol output fields used for ECMWF applications
DO JGFL=1,NAEROUT
  LLPT = .FALSE.
  LLPC = .FALSE.
  LLT9 = .FALSE.
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YAEROUT(JGFL),LDADV=.FALSE.,&
   & LDMGRID=.FALSE.,LDT9=LLT9,&
   & LDPHY=YAEROUT_NL(JGFL)%LPHY,LDPT=LLPT, LDPC=LLPC,&
   & KCOUPLING=YAEROUT_NL(JGFL)%NCOUPLING,&
   & PREFVALC=YAEROUT_NL(JGFL)%REFVALC)
ENDDO

! * NAEROCLIM fields: aerosol 3D input fields used for ECMWF applications
DO JGFL=1,NAEROCLIM
  LLPT = .FALSE.
  LLPC = .FALSE.
  LLT9 = .FALSE.
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YAEROCLIM(JGFL),LDADV=.FALSE.,LDT9=LLT9,&
   & LDPHY=YAEROCLIM_NL(JGFL)%LPHY,LDPT=LLPT, LDPC=LLPC,&
   & KCOUPLING=YAEROCLIM_NL(JGFL)%NCOUPLING,&
   & PREFVALC=YAEROCLIM_NL(JGFL)%REFVALC)
ENDDO

! * Semi-Lagrangian diagnostic fields: these variables are currently used for ECMWF applications.
DO JGFL=1,NSLDIA
  LLPT = .FALSE.
  LLPC = .FALSE. 
  LLT9 = .FALSE.
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YSLDIA(JGFL),LDADV=.FALSE.,&
   & LDMGRID=.FALSE.,LDT9=LLT9,&
   & LDPHY=YSLDIA_NL(JGFL)%LPHY,LDPT=LLPT, LDPC=LLPC,&
   & KCOUPLING=YSLDIA_NL(JGFL)%NCOUPLING,&
   & PREFVALC=YSLDIA_NL(JGFL)%REFVALC)
ENDDO

! * Forcings (FORC):
DO JGFL=1,NGFL_FORC
  CALL SUCSLINT(YFORC_NL(JGFL)%LSLHD,YFORC_NL(JGFL)%LCOMAD,&
   & YFORC_NL(JGFL)%LVSPLIP,YFORC_NL(JGFL)%LHV,&
   & YFORC_NL(JGFL)%LQM,YFORC_NL(JGFL)%LQMH,YFORC_NL(JGFL)%LQM3D,&
   & YFORC_NL(JGFL)%LQML3D,YFORC_NL(JGFL)%LINTLIN,YFORC_NL(JGFL)%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YDDYNA%LSLAG .AND. YFORC_NL(JGFL)%LPT
  LLPC = LLPC0.AND.YFORC_NL(JGFL)%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YFORC(JGFL),LDADV=YFORC_NL(JGFL)%LADV,&
   & LDMGRID=YFORC_NL(JGFL)%LMGRID,LDT9=LLT9,&
   & LDPHY=YFORC_NL(JGFL)%LPHY,LDPT=LLPT,LDPC=LLPC,&
   & KCOUPLING=YFORC_NL(JGFL)%NCOUPLING,CDSLINT=CLSLINT,&
   & PREFVALC=YFORC_NL(JGFL)%REFVALC)
ENDDO

! * Easy diagnostics (EZDIAG):
DO JGFL=1,NGFL_EZDIAG
  CALL SUCSLINT(YEZDIAG_NL(JGFL)%LSLHD,YEZDIAG_NL(JGFL)%LCOMAD,&
   & YEZDIAG_NL(JGFL)%LVSPLIP,YEZDIAG_NL(JGFL)%LHV,&
   & YEZDIAG_NL(JGFL)%LQM,YEZDIAG_NL(JGFL)%LQMH,YEZDIAG_NL(JGFL)%LQM3D,&
   & YEZDIAG_NL(JGFL)%LQML3D,YEZDIAG_NL(JGFL)%LINTLIN,YEZDIAG_NL(JGFL)%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YDDYNA%LSLAG .AND. YEZDIAG_NL(JGFL)%LPT
  LLPC = LLPC0.AND.YEZDIAG_NL(JGFL)%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YEZDIAG(JGFL),LDADV=YEZDIAG_NL(JGFL)%LADV,&
   & LDMGRID=YEZDIAG_NL(JGFL)%LMGRID,LDT9=.FALSE.,&
   & LDPHY=YEZDIAG_NL(JGFL)%LPHY,LDPT=LLPT,LDPC=LLPC,&
   & KCOUPLING=YEZDIAG_NL(JGFL)%NCOUPLING,CDSLINT=CLSLINT,&
   & PREFVALC=YEZDIAG_NL(JGFL)%REFVALC)
ENDDO

! * Extra-GFL variables:
DO JGFL=1,NGFL_EXT
  CALL SUCSLINT(YEXT_NL(JGFL)%LSLHD,YEXT_NL(JGFL)%LCOMAD,&
   & YEXT_NL(JGFL)%LVSPLIP,YEXT_NL(JGFL)%LHV,&
   & YEXT_NL(JGFL)%LQM,YEXT_NL(JGFL)%LQMH,YEXT_NL(JGFL)%LQM3D,&
   & YEXT_NL(JGFL)%LQML3D,YEXT_NL(JGFL)%LINTLIN,YEXT_NL(JGFL)%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YDDYNA%LSLAG .AND. YEXT_NL(JGFL)%LPT
  LLPC = LLPC0.AND.YEXT_NL(JGFL)%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YEXT(JGFL),LDADV=YEXT_NL(JGFL)%LADV,&
   & LDMGRID=YEXT_NL(JGFL)%LMGRID,LDTDIABLIN=YEXT_NL(JGFL)%LTDIABLIN,&
   & LDHORTURB=YEXT_NL(JGFL)%LHORTURB,LDT9=LLT9,&
   & LDPHY=YEXT_NL(JGFL)%LPHY,LDPT=LLPT,LDPC=LLPC,&
   & KCOUPLING=YEXT_NL(JGFL)%NCOUPLING,CDSLINT=CLSLINT,&
   & PREFVALC=YEXT_NL(JGFL)%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YEXT_NL(JGFL)%LTDIABLIN
ENDDO

! LIMA group
DO JGFL=1,NLIMA
  CALL SUCSLINT(YLIMA_NL(JGFL)%LSLHD,YLIMA_NL(JGFL)%LCOMAD,&
   & YLIMA_NL(JGFL)%LVSPLIP,YLIMA_NL(JGFL)%LHV, &
   & YLIMA_NL(JGFL)%LQM,YLIMA_NL(JGFL)%LQMH,YLIMA_NL(JGFL)%LQM3D,&
   & YLIMA_NL(JGFL)%LQML3D,YLIMA_NL(JGFL)%LINTLIN,YLIMA_NL(JGFL)%LVWENO,CLSLINT)
  LLPT=LPC_FULL .AND. LLDIAB .AND. YDDYNA%LSLAG .AND. YLIMA_NL(JGFL)%LPT
  LLPC = LLPC0.AND.YLIMA_NL(JGFL)%LPC
  CALL SET_GFL_ATTR(YDDIMV,YGFL,YLIMA(JGFL),LDADV=YLIMA_NL(JGFL)%LADV,LDADV5=YLIMA_NL(JGFL)%LADV5,&
   & LDTDIABLIN=YLIMA_NL(JGFL)%LTDIABLIN,LDHORTURB=YLIMA_NL(JGFL)%LHORTURB,LDT9=LLT9, &
   & LDPHY=YLIMA_NL(JGFL)%LPHY,LDPT=LLPT,LDPC=LLPC,KCOUPLING=YLIMA_NL(JGFL)%NCOUPLING, &
   & CDSLINT=CLSLINT,PREFVALC=YLIMA_NL(JGFL)%REFVALC)
  LLTDIABLIN=LLTDIABLIN.OR.YLIMA_NL(JGFL)%LTDIABLIN
ENDDO

! * Additional actions:

LADVNEGFIX=.FALSE.
NNEGAFIX=0
! if an interpolation option is used which is already QM don't use
! separate neg fixer
DO JGFL=1,NUMFLDS
  IF ( (TRIM(YCOMP(JGFL)%CSLINT)/='LAITQM').AND.&
    &  (TRIM(YCOMP(JGFL)%CSLINT)/='LAITQM3D').AND.&
    &  (TRIM(YCOMP(JGFL)%CSLINT)/='LAITVSPCQM').AND.&
    &  (TRIM(YCOMP(JGFL)%CSLINT)/='LAIHVTQM').AND.&
    &  (TRIM(YCOMP(JGFL)%CSLINT)/='LAITQM(SLD)').AND.&
    &  (TRIM(YCOMP(JGFL)%CSLINT)/='LIN') ) THEN
    IF (YCOMP(JGFL)%LNEGFIX) THEN
      LADVNEGFIX=.TRUE.
      NNEGAFIX=NNEGAFIX+1
      NNEGFLDS(NNEGAFIX)=JGFL
    ENDIF
  ENDIF
ENDDO

IF (LADVNEGFIX) THEN
  IF (NOPTNEGFIX==1) THEN
    WRITE(NULOUT,*) 'SIMPLE NEGATIVE FIXER IN ADVECTION'
  ELSE
    WRITE(NULOUT,*) 'NEGATIVE FIXER USING LOCAL MIN VALUE IN ADVECTION'
  ENDIF
ENDIF

! Save index of fields where application of mass fixer is required
IF (LTRCMFIX) THEN
  NFLDSFIX=0
  IF (LTRCMFBC.OR.LTRCMFPR.OR.LTRCMFMG.OR.LTRCMFP) THEN
    DO JGFL=1,NUMFLDS
      IF (YCOMP(JGFL)%LMASSFIX.AND.YCOMP(JGFL)%LADV) THEN
        IF ((TRIM(YCOMP(JGFL)%CSLINT)/='LIN' .AND.&
    &        TRIM(YCOMP(JGFL)%CSLINT)/='LIN(MAD)').OR.LTRCMFMG.OR.LTRCMFP.OR.&
    &        (LTRCMFBC.AND.(YCOMP(JGFL)%BETAMFBC<0.0_JPRB))) THEN
          NFLDSFIX=NFLDSFIX+1
          NMFIXFLDS(NFLDSFIX)=JGFL
        ELSE
          WRITE(NULERR,*) 'SUGFL3: QM FIXER CANNOT BE APPLIED ON FIELD:',TRIM(YCOMP(JGFL)%CNAME)
          CALL ABOR1('SUGFL3: HIGH ORDER INTERPOLATION MUST BE USED FOR ADVECTION')
        ENDIF
! when "standard" (more expensive) Priestley algorithm we must have QM switched off
! QM and mass conserving solution will be computed by the algorithm internally
        IF (LTRCMFPR.AND.NOPTMFPR==2) THEN
          IF (YCOMP(JGFL)%LMASSFIX .AND.(TRIM(YCOMP(JGFL)%CSLINT)/='LAITRI' .AND.&
            &                            TRIM(YCOMP(JGFL)%CSLINT)/='LAIHVT' .AND.&
            &                            TRIM(YCOMP(JGFL)%CSLINT)/='LAITRI(SLD)' .AND.&
            &                            TRIM(YCOMP(JGFL)%CSLINT)/='LAITRI(MAD)' )) THEN
            WRITE(NULERR,*) 'SUGFL3: MFIXER PR WITH NOPTMFPR==2 FOR:',TRIM(YCOMP(JGFL)%CNAME)
            CALL ABOR1('SUGFL3: QM OPTIONS MUST BE SWITCHED OFF')           
          ENDIF
        ENDIF
      ENDIF
    ENDDO
  ENDIF
ENDIF

IF (YQ_NL%LCOMAD.AND.YQ_NL%LVWENO) THEN
  WRITE(NULERR,*) 'SUGFL3: BOTH COMAD AND WENO HAVE BEEN APPLIED ON Q FIELD:',TRIM(YCOMP(JGFL)%CNAME)
  CALL ABOR1('SUGFL3: COMAD AND WENO CANNOT BE USED AT THE SAME TIME')
ENDIF

! Save index of fields for mgrid simulation
NFMG=0
DO JGFL=1,NUMFLDS
  IF (YCOMP(JGFL)%LMGRID) THEN
    NFMG=NFMG+1
    NMGFLDS(NFMG)=JGFL
  ENDIF
ENDDO

!     ------------------------------------------------------------------

!*       2.    PRINT GFL ATTRIBUTES
!              --------------------

CALL PRINT_GFL(YGFL)

!     ------------------------------------------------------------------

!*       3.    Redefine LSPLTHOIGFL when required 
!              ----------------------------------

LSPLTHOIGFL=LLTDIABLIN


!*       4.    Set MGFL members
!              ----------------------------------

DO JGFL=1,NUMFLDS
  YCOMP(JGFL)%MGFL = JGFL
ENDDO

!     ------------------------------------------------------------------
END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUGFL3',1,ZHOOK_HANDLE)
END SUBROUTINE SUGFL3

