SUBROUTINE SUGFL2(YDEPHY,YDML_GCONF,YDCOMPO)

!**** *SUGFL2*  - Setting up GFL environment: part 2

!     Purpose.
!     --------
!      Initialization of YOM_YGFL, part 2.
!      Initialize definition of unified_treatment fields (GFL)
!      The GFL ordering in this routine is the ordering for "t" and
!      "t+dt" values of the GFL in grid-point arrays (GFL and GFLT1),
!      and also the ordering in the spectral array SPGFL.

!**   Interface.
!     ----------
!        *CALL* *SUGFL2

!        Explicit arguments :
!        --------------------

!        Implicit arguments :
!        --------------------
!        MODULE YOM_YGFL

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------
!        None

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!      Mats Hamrud *ECMWF*
!      Original : 2002-03-11
!      Code in SUGFL until 2011
!      Creation of SUGFL2 in Nov 2011.

!     Modifications.
!     --------------
!      K. YESSAD (Nov 2011) former SUGFL code put in new SUGFL2
!      J.M. Piriou and E. Bazile (Sep 2011): new GFL variables (LCONV, ICONV, RCONV, SCONV)
!      M. Diamantakis (Feb 2013): support for mass fixers
!         NOTE: GFL variables which can be "fixed" are currently only
!               the ones who have default %LADV=TRUE i.e. advected ones
!      F. Vana  15-Mar-2013  Better setup for ECMWF linear physics.
!      R. El Khatib 04-Aug-2014 Pruning of the conf. 927/928
!      F. Vana & M. Kharoutdinov 09-Feb-2015 CRM fields.
!      F. Vana   08-Apr-2016  Small fix.
!      M Ahlgrimm 2017-05-11 cloud heterogeneity FSD
!      P. Bechtold 14-Feb-2019: EDR Parameter added
!      F. Vana  20-Feb-2019  Quintic vertical interpolation
!      F. Vana  11-Sep-2020  Better setup for spectral q
!     ------------------------------------------------------------------

USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE PARKIND1               , ONLY : JPIM, JPRB
USE YOMHOOK                , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCST                 , ONLY : RV, RCPV, RCW, RCS, RLVZER, RLSZER
USE YOM_GRIB_CODES         , ONLY : NGRBQ, NGRBO3, NGRBCLWC, NGRBCIWC, NGRBCSWC, NGRBCRWC, &
 &                                  NGRBCC, NGRBSNR
USE YOMCT0                 , ONLY : NCONF, LECMWF
USE YOEPHY                 , ONLY : TEPHY
USE YOMFA                  , ONLY : YFAQ     ,YFAL     ,YFAI     ,YFAO3    ,&
 &                                  YFAS     ,YFAR     ,YFAG     ,YFAH  ,YFATKE   ,YFAEFB1   ,YFAEFB2   ,YFAEFB3,&
 &                                  YFACPF, YFASPF, YFACLF,YFASRC, YFACVGQ, &
 &                                  YFASDSAT, YFACVV ,YFALMF,YFAIMF,YFAAMF,&
 &                                  YFAWMFC, YFAHLMF, YFAHLCFMF, YFAHIMF, YFAHICFMF, &
 &                                  YFAQVA, YFARKTH, YFARKTQV, YFARKTQC,&
 &                                  YFALRAD ,YFAIRAD     ,&
 &                                  YFAUOM, YFAUAL, YFADOM, YFADAL, YFAUEN, YFAUNEBH, &
 &                                  YFALCONV,YFAICONV,YFARCONV,YFASCONV,YFATTE,YFAMXL,YFASHTUR,YFAFQTUR,YFAFSTUR
USE YOM_YGFL               , ONLY : JPGFL
USE GFL_SUBS_MOD           , ONLY : DEFINE_GFL_COMP, FALSIFY_GFL_COMP
USE FIELD_DEFINITIONS      , ONLY : FID
USE FIELD_DEFINITIONS_BASE , ONLY : TYPE_FVAR,JP_NAME_MAX_LEN,GETFID
USE FIELD_DEFINITIONS      , ONLY : FID,MAIN_FIELD_METADATA,NDYN_NAMES,COMPO_3D_FIRST,COMPO_3D_LAST
USE YOMCOMPO               , ONLY : TCOMPO
USE YOE_AERODIAG           , ONLY : NPAERAOT, NPAERLISI_VAR, NPAERLISI_WVL, NPAERLISI

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(TEPHY)                  ,INTENT(INOUT):: YDEPHY
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT), TARGET :: YDML_GCONF
TYPE(TCOMPO),                 INTENT(INOUT), TARGET :: YDCOMPO
INTEGER(KIND=JPIM) :: JGFL,JEMIS,JVAR,JWVL,IGFLPTR,INCR,JCOMPO_3D_FID,ILEVELTYPESDUMMY, I3DDUMMY,IFID
TYPE(TYPE_FVAR), ALLOCATABLE :: METADATA(:)
LOGICAL   :: LLDERS,LLT1,LL5,LLTHERMACT
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!-------------------------------------------------------------------------

#include "abor1.intfb.h"

!-------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SUGFL2',0,ZHOOK_HANDLE)
ASSOCIATE(YGFL=>YDML_GCONF%YGFL,YDDIMF=>YDML_GCONF%YRDIMF)
ASSOCIATE(LADER=>YDDIMF%LADER, &
 & YMXL_NL=>YGFL%YMXL_NL, NUVP=>YGFL%NUVP, YUVP_NL=>YGFL%YUVP_NL, &
 & YRKTQC_NL=>YGFL%YRKTQC_NL, LTRCMFMG=>YGFL%LTRCMFMG, YO3_NL=>YGFL%YO3_NL, &
 & YL_NL=>YGFL%YL_NL, YLRCH4_NL=>YGFL%YLRCH4_NL, YCOMP=>YGFL%YCOMP, &
 & YQVA_NL=>YGFL%YQVA_NL, YS_NL=>YGFL%YS_NL, YA_NL=>YGFL%YA_NL, NNOGW=>YGFL%NNOGW, &
 & YDOM_NL=>YGFL%YDOM_NL, YSLDIA_NL=>YGFL%YSLDIA_NL, YAERO_NL=>YGFL%YAERO_NL, &
 & YFQTUR_NL=>YGFL%YFQTUR_NL, YSDSAT_NL=>YGFL%YSDSAT_NL, YLRAD_NL=>YGFL%YLRAD_NL, &
 & YCPF_NL=>YGFL%YCPF_NL, ZMFIXEPS=>YGFL%ZMFIXEPS, YFSTUR_NL=>YGFL%YFSTUR_NL, &
 & YLCONV_NL=>YGFL%YLCONV_NL, YRCONV_NL=>YGFL%YRCONV_NL, YICONV_NL=>YGFL%YICONV_NL, &
 & YSHTUR_NL=>YGFL%YSHTUR_NL, YSCONV_NL=>YGFL%YSCONV_NL, YQ_NL=>YGFL%YQ_NL, &
 & NGFL_EXT=>YGFL%NGFL_EXT, NFLDSFIX=>YGFL%NFLDSFIX, &
 & YEZDIAG_NL=>YGFL%YEZDIAG_NL, YERA40_NL=>YGFL%YERA40_NL, NSLDIA=>YGFL%NSLDIA, &
 & YNOGW_NL=>YGFL%YNOGW_NL, YIRAD_NL=>YGFL%YIRAD_NL, YRKTQV_NL=>YGFL%YRKTQV_NL, &
 & YR_NL=>YGFL%YR_NL, YCVV_NL=>YGFL%YCVV_NL, YH_NL=>YGFL%YH_NL, &
 & YG_NL=>YGFL%YG_NL, YSPF_NL=>YGFL%YSPF_NL, YEXT_NL=>YGFL%YEXT_NL, &
 & YI_NL=>YGFL%YI_NL, LTRCMFIX=>YGFL%LTRCMFIX, YCVGQ_NL=>YGFL%YCVGQ_NL, &
 & YDAL_NL=>YGFL%YDAL_NL, NCHEM=>YGFL%NCHEM, &
 & NGHG=>YGFL%NGHG, YUEN_NL=>YGFL%YUEN_NL, &
 & YTTE_NL=>YGFL%YTTE_NL, YEFB1_NL=>YGFL%YEFB1_NL, YEFB2_NL=>YGFL%YEFB2_NL, &
 & YEFB3_NL=>YGFL%YEFB3_NL, NGFL_EZDIAG=>YGFL%NGFL_EZDIAG, &
 & YUNEBH_NL=>YGFL%YUNEBH_NL, NERA40=>YGFL%NERA40, &
 & LTRCMFPR=>YGFL%LTRCMFPR, NAEROUT=>YGFL%NAEROUT, NAEROCLIM=>YGFL%NAEROCLIM,&
 & YUOM_NL=>YGFL%YUOM_NL, YSRC_NL=>YGFL%YSRC_NL, NGFL_FORC=>YGFL%NGFL_FORC, &
 & YLMF_NL=>YGFL%YLMF_NL,YIMF_NL=>YGFL%YIMF_NL,YAMF_NL=>YGFL%YAMF_NL,&
 & YWMFC_NL=>YGFL%YWMFC_NL, YHLMF_NL=>YGFL%YHLMF_NL, YHLCFMF_NL=>YGFL%YHLCFMF_NL, &
 & YHIMF_NL=>YGFL%YHIMF_NL, YHICFMF_NL=>YGFL%YHICFMF_NL, &
 & YRKTH_NL=>YGFL%YRKTH_NL, YCHEM_NL=>YGFL%YCHEM_NL, YRSPEC_NL=>YGFL%YRSPEC_NL,&
 & YAERAOT_NL=>YGFL%YAERAOT_NL, YAERLISI_NL=>YGFL%YAERLISI_NL, &
 & YAEROUT_NL=>YGFL%YAEROUT_NL, YAEROCLIM_NL=>YGFL%YAEROCLIM_NL, YUAL_NL=>YGFL%YUAL_NL, LTRCMFBC=>YGFL%LTRCMFBC, &
 & NEMIS3D=>YGFL%NEMIS3D, YEMIS3D=>YGFL%YEMIS3D, &
 & NAERO=>YGFL%NAERO, YFORC_NL=>YGFL%YFORC_NL, &
 & YGHG_NL=>YGFL%YGHG_NL, YTKE_NL=>YGFL%YTKE_NL, &
 & LTRCMFP=>YGFL%LTRCMFP, NUMFLDS=>YGFL%NUMFLDS, &
 & LEPCLD=>YDEPHY%LEPCLD,LAERAOT=>YGFL%LAERAOT,LAERLISI=>YGFL%LAERLISI,YPHYCTY_NL=>YGFL%YPHYCTY_NL, &
 & NFSD=>YGFL%NFSD, YFSD=>YGFL%YFSD, YFSD_NL=>YGFL%YFSD_NL, &
 & NEDRP=>YGFL%NEDRP, YEDRP=>YGFL%YEDRP, YEDRP_NL=>YGFL%YEDRP_NL, &
 & YLIMA_NL=>YDML_GCONF%YGFL%YLIMA_NL, NLIMA=>YDML_GCONF%YGFL%NLIMA, &
 & NEMIS3D_DESC=>YDCOMPO%NEMIS3D_DESC, YEMIS3D_DESC=>YDCOMPO%YEMIS3D_DESC) 
!-------------------------------------------------------------------------

!      1.1  Initial settings.

  NUMFLDS=0
  IF (LTRCMFIX.AND.(LTRCMFBC.OR.LTRCMFPR.OR.LTRCMFMG.OR.LTRCMFP)) THEN
    NFLDSFIX=0
    ZMFIXEPS=2._JPRB*EPSILON(1.0_JPRB)
  ENDIF

  ! Thermodynamic activity only allowed when cloud scheme is activated
  LLTHERMACT=.TRUE.
  IF (LECMWF.AND.(.NOT.LEPCLD))  LLTHERMACT=.FALSE.

  LL5=NCONF/100 == 1.OR.NCONF == 801.OR.NCONF == 601.OR. &
   & NCONF == 401.OR.NCONF == 501  
  LLT1=.TRUE.
  ! All gridpoint fields have to be set up before the spectral ones
  !  (i.e. part 1.2 SHOULD be done before part 1.3)
  LLDERS=.FALSE.
  ! * Simple GFL variables:
  !   (order should be the same in parts 1.1, 1.2 and 1.3).
  INCR=0 
  YGFL%YQ    => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YL    => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YI    => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YS    => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YR    => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YG    => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YH    => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YTKE  => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YEFB1 => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YEFB2 => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YEFB3 => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YA    => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YO3   => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YCPF  => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YSPF  => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YSRC  => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YLMF  => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YIMF  => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YAMF  => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YWMFC => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YHLMF => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YHLCFMF => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YHIMF => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YHICFMF => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YCVGQ => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YLCONV  => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YICONV  => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YRCONV  => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YSCONV  => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YLRAD   => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YIRAD   => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YSDSAT => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YCVV  => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YQVA  => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YUOM => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YUAL => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YDOM => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YDAL => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YUEN => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YUNEBH => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YTTE => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YMXL => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YSHTUR => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YFQTUR => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YFSTUR => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YRKTH => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YRSPEC => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YRKTQV => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YRKTQC => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YLRCH4  => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YPHYCTY => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  YGFL%YFSD   => YGFL%YCOMP(JPGFL-INCR)
  INCR=INCR+1
  ! * Groups of multiple GFL variables:
  !   (order should be the same in parts 1.1, 1.2 and 1.3).
  IF (NGFL_EXT == 0) THEN
    YGFL%YEXT => YGFL%YCOMP(JPGFL-INCR:JPGFL-INCR)
    INCR=INCR+1
  ENDIF
  IF (NGFL_FORC == 0) THEN
    YGFL%YFORC => YGFL%YCOMP(JPGFL-INCR:JPGFL-INCR)
    INCR=INCR+1
  ENDIF
  IF (NGFL_EZDIAG == 0) THEN
    YGFL%YEZDIAG => YGFL%YCOMP(JPGFL-INCR:JPGFL-INCR)
    INCR=INCR+1
  ENDIF
  IF (NGHG == 0) THEN
    YGFL%YGHG => YGFL%YCOMP(JPGFL-INCR:JPGFL-INCR)
    INCR=INCR+1
  ENDIF
  IF (NCHEM == 0) THEN
    YGFL%YCHEM => YGFL%YCOMP(JPGFL-INCR:JPGFL-INCR)
    INCR=INCR+1
  ENDIF
  IF (NAERO == 0) THEN
    YGFL%YAERO => YGFL%YCOMP(JPGFL-INCR:JPGFL-INCR)
    INCR=INCR+1
  ENDIF
  IF (NERA40 == 0) THEN
    YGFL%YERA40 => YGFL%YCOMP(JPGFL-INCR:JPGFL-INCR)
    INCR=INCR+1
  ENDIF
  IF (NNOGW == 0) THEN
    YGFL%YNOGW => YGFL%YCOMP(JPGFL-INCR:JPGFL-INCR)
    INCR=INCR+1
  ENDIF
  IF (NEMIS3D == 0) THEN
    YGFL%YEMIS3D => YGFL%YCOMP(JPGFL-INCR:JPGFL-INCR)
    INCR=INCR+1
  ENDIF
  IF (NEDRP == 0) THEN
    YGFL%YEDRP => YGFL%YCOMP(JPGFL-INCR:JPGFL-INCR)
    INCR=INCR+1
  ENDIF
  IF ((.NOT. LAERLISI) .OR. NAERO == 0) THEN
    YGFL%YAERAOT => YGFL%YCOMP(JPGFL-INCR:JPGFL-INCR)
    INCR=INCR+1
  ENDIF
  IF (.NOT. LAERLISI) THEN
    YGFL%YAERLISI => YGFL%YCOMP(JPGFL-INCR:JPGFL-INCR)
    INCR=INCR+1
  ENDIF
  IF (NAEROUT == 0) THEN
    YGFL%YAEROUT => YGFL%YCOMP(JPGFL-INCR:JPGFL-INCR)
    INCR=INCR+1
  ENDIF
  IF (NAEROCLIM == 0) THEN
    YGFL%YAEROCLIM => YGFL%YCOMP(JPGFL-INCR:JPGFL-INCR)
    INCR=INCR+1
  ENDIF
  IF (NUVP == 0) THEN
    YGFL%YUVP => YGFL%YCOMP(JPGFL-INCR:JPGFL-INCR)
    INCR=INCR+1
  ENDIF
  IF (NSLDIA == 0) THEN
    YGFL%YSLDIA => YGFL%YCOMP(JPGFL-INCR:JPGFL-INCR)
    INCR=INCR+1
  ENDIF
  IF (NLIMA == 0) THEN
    YGFL%YLIMA => YGFL%YCOMP(JPGFL-INCR:JPGFL-INCR)
    INCR=INCR+1
  ENDIF

  DO JGFL=1,JPGFL
    CALL FALSIFY_GFL_COMP(YGFL,YGFL%YCOMP(JGFL))
  ENDDO

!      1.2  Grid-point GFL.

  IF(YQ_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YQ=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YQ,CDNAME=YFAQ%CLNAME,KGRIB=NGRBQ,LDGP=.TRUE.,&
     & KREQIN=YQ_NL%NREQIN,KFID=FID%Q,&
     & PREFVALI=YQ_NL%REFVALI,LDREQOUT=YQ_NL%LREQOUT,LDERS=YQ_NL%LCDERS,LD5=LL5,&
     & LDT1=LLT1,LDGPINGP=YQ_NL%LGPINGP,LDMGRID=YQ_NL%LMGRID,&
     & LDTRAJIO=YQ_NL%LTRAJIO,LDTHERMACT=.TRUE.,PR=RV,PRCP=RCPV,&
     & PBETAMFBC=YQ_NL%BETAMFBC,LDMASSFIX=YQ_NL%LMASSFIX,&
     & LDCOMAD=YQ_NL%LCOMAD,LDNEGFIX=YQ_NL%LNEGFIX,PWENO_ALPHA=YQ_NL%WENO_ALPHA,&
     & LDWATER=.TRUE.,LDPRECIP=.FALSE.,PLZER=0.0_JPRB)
  ENDIF
  IF(YL_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YL=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YL,CDNAME=YFAL%CLNAME,KGRIB=NGRBCLWC,&
     & LDGP=.TRUE.,KREQIN=YL_NL%NREQIN,KFID=FID%L,&
     & PREFVALI=YL_NL%REFVALI,LDREQOUT=YL_NL%LREQOUT,LDERS=LLDERS,LD5=LL5,&
     & LDT1=LLT1,LDGPINGP=YL_NL%LGPINGP,LDMGRID=YL_NL%LMGRID,& 
     & LDTRAJIO=YL_NL%LTRAJIO,&
     & LDTHERMACT=LLTHERMACT,PR=0.0_JPRB,PRCP=RCW,&
     & PBETAMFBC=YL_NL%BETAMFBC,LDMASSFIX=YL_NL%LMASSFIX,&
     & LDCOMAD=YL_NL%LCOMAD,LDNEGFIX=YL_NL%LNEGFIX,PWENO_ALPHA=YL_NL%WENO_ALPHA,&
     & LDWATER=.TRUE.,LDPRECIP=.FALSE.,PLZER=RLVZER)
  ENDIF
  IF(YI_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YI=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YI ,CDNAME=YFAI%CLNAME,KGRIB=NGRBCIWC,&
     & LDGP=.TRUE.,KREQIN=YI_NL%NREQIN, KFID=FID%I,&
     & PREFVALI=YI_NL%REFVALI,LDREQOUT=YI_NL%LREQOUT,LDERS=LLDERS,LD5=LL5,&
     & LDT1=LLT1,LDGPINGP=YI_NL%LGPINGP,LDMGRID=YI_NL%LMGRID,&
     & LDTRAJIO=YI_NL%LTRAJIO,LDTHERMACT=LLTHERMACT,PR=0.0_JPRB,PRCP=RCS,&
     & PBETAMFBC=YI_NL%BETAMFBC,LDMASSFIX=YI_NL%LMASSFIX,&
     & LDCOMAD=YI_NL%LCOMAD,LDNEGFIX=YI_NL%LNEGFIX,PWENO_ALPHA=YI_NL%WENO_ALPHA,&
     & LDWATER=.TRUE.,LDPRECIP=.FALSE.,PLZER=RLSZER)
  ENDIF
  IF(YS_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YS=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YS ,CDNAME=YFAS%CLNAME,KGRIB=NGRBCSWC,&
     & LDGP=.TRUE.,KREQIN=YS_NL%NREQIN, KFID=FID%S,&
     & PREFVALI=YS_NL%REFVALI,LDREQOUT=YS_NL%LREQOUT,LDERS=LLDERS,LD5=LL5,&
     & LDT1=LLT1,LDGPINGP=YS_NL%LGPINGP,LDMGRID=YS_NL%LMGRID,&
     & LDTRAJIO=YS_NL%LTRAJIO,&
     & LDTHERMACT=LLTHERMACT,PR=0.0_JPRB,PRCP=RCS,&
     & PBETAMFBC=YS_NL%BETAMFBC,LDMASSFIX=YS_NL%LMASSFIX,&
     & LDCOMAD=YS_NL%LCOMAD,LDNEGFIX=YS_NL%LNEGFIX,PWENO_ALPHA=YS_NL%WENO_ALPHA,&
     & LDWATER=.TRUE.,LDPRECIP=.TRUE.,PLZER=RLSZER)
  ENDIF
  IF(YR_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YR=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YR ,CDNAME=YFAR%CLNAME,KGRIB=NGRBCRWC,&
     & LDGP=.TRUE.,KREQIN=YR_NL%NREQIN,KFID=FID%R,&
     & PREFVALI=YR_NL%REFVALI,LDREQOUT=YR_NL%LREQOUT,LDERS=LLDERS,LD5=LL5,&
     & LDT1=LLT1,LDGPINGP=YR_NL%LGPINGP,LDMGRID=YR_NL%LMGRID,& 
     & LDTRAJIO=YR_NL%LTRAJIO,&
     & LDTHERMACT=LLTHERMACT,PR=0.0_JPRB,PRCP=RCW,&
     & PBETAMFBC=YR_NL%BETAMFBC,LDMASSFIX=YR_NL%LMASSFIX,&
     & LDCOMAD=YR_NL%LCOMAD,LDNEGFIX=YR_NL%LNEGFIX,PWENO_ALPHA=YR_NL%WENO_ALPHA,&
     & LDWATER=.TRUE.,LDPRECIP=.TRUE.,PLZER=RLVZER)
  ENDIF
  IF(YG_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YG=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YG ,CDNAME=YFAG%CLNAME,KGRIB=NGRBSNR,&
     & LDGP=.TRUE.,KREQIN=YG_NL%NREQIN, KFID=FID%G,&
     & PREFVALI=YG_NL%REFVALI,LDREQOUT=YG_NL%LREQOUT,LDERS=LLDERS,LD5=LL5,&
     & LDT1=LLT1,LDTHERMACT=LLTHERMACT,PR=0.0_JPRB,PRCP=RCS, &
     & PBETAMFBC=YG_NL%BETAMFBC,LDMASSFIX=YG_NL%LMASSFIX,&
     & LDCOMAD=YG_NL%LCOMAD,LDNEGFIX=YG_NL%LNEGFIX,PWENO_ALPHA=YG_NL%WENO_ALPHA,&
     & LDWATER=.TRUE.,LDPRECIP=.TRUE.,PLZER=RLSZER)
  ENDIF
  IF(YH_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YH=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YH ,CDNAME=YFAH%CLNAME,KGRIB=NGRBSNR,&
     & LDGP=.TRUE.,KREQIN=YH_NL%NREQIN, KFID=FID%H,&
     & PREFVALI=YH_NL%REFVALI,LDREQOUT=YH_NL%LREQOUT,LDERS=LLDERS,LD5=LL5,&
     & LDT1=LLT1,LDTHERMACT=LLTHERMACT,PR=0.0_JPRB,PRCP=RCS,&
     & PBETAMFBC=YH_NL%BETAMFBC,LDMASSFIX=YH_NL%LMASSFIX,&
     & LDCOMAD=YH_NL%LCOMAD,LDNEGFIX=YH_NL%LNEGFIX,PWENO_ALPHA=YH_NL%WENO_ALPHA,&
     & LDWATER=.TRUE.,LDPRECIP=.TRUE.,PLZER=RLSZER)

  ENDIF
  IF(YTKE_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YTKE=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YTKE ,CDNAME=YFATKE%CLNAME,KGRIB=YTKE_NL%IGRBCODE,&
     & LDGP=.TRUE.,KREQIN=YTKE_NL%NREQIN,KFID=FID%TKE,&
     & PREFVALI=YTKE_NL%REFVALI,LDREQOUT=YTKE_NL%LREQOUT,LDERS=LLDERS,LD5=LL5,&
     & LDT1=LLT1,PBETAMFBC=YTKE_NL%BETAMFBC,LDMASSFIX=YTKE_NL%LMASSFIX,&
     & LDCOMAD=YTKE_NL%LCOMAD,LDNEGFIX=YTKE_NL%LNEGFIX,PWENO_ALPHA=YTKE_NL%WENO_ALPHA)
  ENDIF
  IF(YEFB1_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YEFB1=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YEFB1 ,CDNAME=YFAEFB1%CLNAME,KGRIB=NGRBSNR,&
     & LDGP=.TRUE.,KREQIN=YEFB1_NL%NREQIN,&
     & PREFVALI=YEFB1_NL%REFVALI,LDREQOUT=YEFB1_NL%LREQOUT,LDERS=LLDERS,LD5=LL5,&
     & LDT1=LLT1)
  ENDIF
  IF(YEFB2_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YEFB2=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YEFB2,CDNAME=YFAEFB2%CLNAME,KGRIB=NGRBSNR,&
     & LDGP=.TRUE.,KREQIN=YEFB2_NL%NREQIN,&
     & PREFVALI=YEFB2_NL%REFVALI,LDREQOUT=YEFB2_NL%LREQOUT,LDERS=LLDERS,LD5=LL5,&
     & LDT1=LLT1)
  ENDIF
  IF(YEFB3_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YEFB3=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YEFB3,CDNAME=YFAEFB3%CLNAME,KGRIB=NGRBSNR,&
     & LDGP=.TRUE.,KREQIN=YEFB3_NL%NREQIN,&
     & PREFVALI=YEFB3_NL%REFVALI,LDREQOUT=YEFB3_NL%LREQOUT,LDERS=LLDERS,LD5=LL5,&
     & LDT1=LLT1)
  ENDIF
  IF(YA_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YA=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YA ,CDNAME=YFACLF%CLNAME,KGRIB=NGRBCC,&
     & LDGP=.TRUE.,KREQIN=YA_NL%NREQIN, KFID=FID%A,&
     & PREFVALI=YA_NL%REFVALI,LDREQOUT=YA_NL%LREQOUT,LDERS=LLDERS,LD5=LL5,&
     & LDT1=LLT1,LDGPINGP=YA_NL%LGPINGP,LDMGRID=YA_NL%LMGRID,&
     & LDTRAJIO=YA_NL%LTRAJIO,&
     & PBETAMFBC=YA_NL%BETAMFBC,LDMASSFIX=YA_NL%LMASSFIX,&
     & LDCOMAD=YA_NL%LCOMAD,LDNEGFIX=YA_NL%LNEGFIX,PWENO_ALPHA=YA_NL%WENO_ALPHA)
  ENDIF
  IF(YO3_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YO3=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YO3,CDNAME=YFAO3%CLNAME,KGRIB=NGRBO3,&
     & LDGP=.TRUE.,KREQIN=YO3_NL%NREQIN,KFID=FID%O3, &
     & PREFVALI=YO3_NL%REFVALI,LDREQOUT=YO3_NL%LREQOUT,LDERS=LLDERS,LD5=LL5,&
     & LDT1=LLT1,LDGPINGP=YO3_NL%LGPINGP, LDMGRID=YO3_NL%LMGRID,&
     & LDTRAJIO=YO3_NL%LTRAJIO,PBETAMFBC=YO3_NL%BETAMFBC,LDMASSFIX=YO3_NL%LMASSFIX,&
     & LDCOMAD=YO3_NL%LCOMAD,LDNEGFIX=YO3_NL%LNEGFIX,PWENO_ALPHA=YO3_NL%WENO_ALPHA)
  ENDIF
  IF(YCPF_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YCPF=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YCPF,CDNAME=YFACPF%CLNAME,&
     & KGRIB=YCPF_NL%IGRBCODE,LDGP=.TRUE.,KFID=FID%CPF, &
     & KREQIN=YCPF_NL%NREQIN,PREFVALI= YCPF_NL%REFVALI,&
     & LDREQOUT=YCPF_NL%LREQOUT,LDERS=.FALSE.,LD5=LL5, &
     & LDT1=LLT1,LDGPINGP=.TRUE.,LDMGRID=YCPF_NL%LMGRID)
  ENDIF
  IF(YSPF_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YSPF=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YSPF,CDNAME=YFASPF%CLNAME,&
     & KGRIB=YSPF_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YSPF_NL%NREQIN, PREFVALI=YSPF_NL%REFVALI,&
     & LDREQOUT=YSPF_NL%LREQOUT,LDERS=.FALSE.,LD5=LL5, &
     & LDT1=LLT1,LDGPINGP=.TRUE.,LDMGRID=YSPF_NL%LMGRID)
  ENDIF
  IF(YSRC_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YSRC=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YSRC,CDNAME=YFASRC%CLNAME,KGRIB=NGRBSNR,&
     & LDGP=.TRUE.,KREQIN=YSRC_NL%NREQIN, &
     & PREFVALI=YSRC_NL%REFVALI,LDREQOUT=YSRC_NL%LREQOUT,LDERS=LLDERS,&
     & LD5=LL5,LDT1=LLT1)
  ENDIF
  IF(YLMF_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YLMF=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YLMF,CDNAME=YFALMF%CLNAME,KGRIB=NGRBSNR,&
     & LDGP=.TRUE.,KREQIN=YLMF_NL%NREQIN, &
     & PREFVALI=YLMF_NL%REFVALI,LDREQOUT=YLMF_NL%LREQOUT,LDERS=LLDERS,&
     & LD5=LL5,LDT1=LLT1)
  ENDIF
  IF(YIMF_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YIMF=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YIMF,CDNAME=YFAIMF%CLNAME,KGRIB=NGRBSNR,&
     & LDGP=.TRUE.,KREQIN=YIMF_NL%NREQIN, &
     & PREFVALI=YIMF_NL%REFVALI,LDREQOUT=YIMF_NL%LREQOUT,LDERS=LLDERS,&
     & LD5=LL5,LDT1=LLT1)
  ENDIF
  IF(YAMF_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YAMF=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YAMF,CDNAME=YFAAMF%CLNAME,KGRIB=NGRBSNR,&
     & LDGP=.TRUE.,KREQIN=YAMF_NL%NREQIN, &
     & PREFVALI=YAMF_NL%REFVALI,LDREQOUT=YAMF_NL%LREQOUT,LDERS=LLDERS,&
     & LD5=LL5,LDT1=LLT1)
  ENDIF
  IF(YWMFC_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YWMFC=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YWMFC,CDNAME=YFAWMFC%CLNAME,KGRIB=NGRBSNR,&
     & LDGP=.TRUE.,KREQIN=YWMFC_NL%NREQIN, &
     & PREFVALI=YWMFC_NL%REFVALI,LDREQOUT=YWMFC_NL%LREQOUT,LDERS=LLDERS,&
     & LD5=LL5,LDT1=LLT1)
  ENDIF
  IF(YHLMF_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YHLMF=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YHLMF,CDNAME=YFAHLMF%CLNAME,KGRIB=NGRBSNR,&
     & LDGP=.TRUE.,KREQIN=YHLMF_NL%NREQIN, &
     & PREFVALI=YHLMF_NL%REFVALI,LDREQOUT=YHLMF_NL%LREQOUT,LDERS=LLDERS,&
     & LD5=LL5,LDT1=LLT1)
  ENDIF
  IF(YHLCFMF_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YHLCFMF=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YHLCFMF,CDNAME=YFAHLCFMF%CLNAME,KGRIB=NGRBSNR,&
     & LDGP=.TRUE.,KREQIN=YHLCFMF_NL%NREQIN, &
     & PREFVALI=YHLCFMF_NL%REFVALI,LDREQOUT=YHLCFMF_NL%LREQOUT,LDERS=LLDERS,&
     & LD5=LL5,LDT1=LLT1)
  ENDIF
  IF(YHIMF_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YHIMF=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YHIMF,CDNAME=YFAHIMF%CLNAME,KGRIB=NGRBSNR,&
     & LDGP=.TRUE.,KREQIN=YHIMF_NL%NREQIN, &
     & PREFVALI=YHIMF_NL%REFVALI,LDREQOUT=YHIMF_NL%LREQOUT,LDERS=LLDERS,&
     & LD5=LL5,LDT1=LLT1)
  ENDIF
  IF(YHICFMF_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YHICFMF=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YHICFMF,CDNAME=YFAHICFMF%CLNAME,KGRIB=NGRBSNR,&
     & LDGP=.TRUE.,KREQIN=YHICFMF_NL%NREQIN, &
     & PREFVALI=YHICFMF_NL%REFVALI,LDREQOUT=YHICFMF_NL%LREQOUT,LDERS=LLDERS,&
     & LD5=LL5,LDT1=LLT1)
  ENDIF
  IF(YCVGQ_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YCVGQ=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YCVGQ,CDNAME=YFACVGQ%CLNAME,KGRIB=NGRBSNR,&
     & LDGP=.TRUE.,KREQIN=YCVGQ_NL%NREQIN, &
     & PREFVALI=YCVGQ_NL%REFVALI, LDREQOUT=YCVGQ_NL%LREQOUT,LDERS=LLDERS,&
     & LD5=LL5,LDT1=LLT1)
  ENDIF
  IF(YLCONV_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YLCONV=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YLCONV,CDNAME=YFALCONV%CLNAME,KGRIB=NGRBCLWC,&
     & LDGP=.TRUE.,KREQIN=YLCONV_NL%NREQIN, &
     & PREFVALI=YLCONV_NL%REFVALI,LDREQOUT=YLCONV_NL%LREQOUT,LDERS=LLDERS,LD5=LL5, &
     & LDT1=LLT1,LDGPINGP=YLCONV_NL%LGPINGP,LDMGRID=YLCONV_NL%LMGRID, &
     & LDTRAJIO=YLCONV_NL%LTRAJIO, LDTHERMACT=.FALSE.,PR=0.0_JPRB,PRCP=RCW, &
     & LDWATER=.TRUE.,LDPRECIP=.FALSE.,PLZER=RLVZER)
  ENDIF
  IF(YICONV_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YICONV=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YICONV,CDNAME=YFAICONV%CLNAME,KGRIB=NGRBCIWC,&
     & LDGP=.TRUE.,KREQIN=YICONV_NL%NREQIN, &
     & PREFVALI=YICONV_NL%REFVALI,LDREQOUT=YICONV_NL%LREQOUT,LDERS=LLDERS,LD5=LL5, &
     & LDT1=LLT1,LDGPINGP=YICONV_NL%LGPINGP,LDMGRID=YICONV_NL%LMGRID,&
     & LDTRAJIO=YICONV_NL%LTRAJIO, &
     & LDTHERMACT=.FALSE.,PR=0.0_JPRB,PRCP=RCS, &
     & LDWATER=.TRUE.,LDPRECIP=.FALSE.,PLZER=RLSZER)
  ENDIF
  IF(YRCONV_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YRCONV=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YRCONV,CDNAME=YFARCONV%CLNAME,KGRIB=NGRBCRWC,&
     & LDGP=.TRUE.,KREQIN=YRCONV_NL%NREQIN, &
     & PREFVALI=YRCONV_NL%REFVALI,LDREQOUT=YRCONV_NL%LREQOUT,LDERS=LLDERS,LD5=LL5, &
     & LDT1=LLT1,LDGPINGP=YRCONV_NL%LGPINGP,LDMGRID=YRCONV_NL%LMGRID,&
     & LDTRAJIO=YRCONV_NL%LTRAJIO, &
     & LDTHERMACT=.FALSE.,PR=0.0_JPRB,PRCP=RCW, &
     & LDWATER=.TRUE.,LDPRECIP=.TRUE.,PLZER=RLVZER)
  ENDIF
  IF(YSCONV_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YSCONV=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YSCONV,CDNAME=YFASCONV%CLNAME,KGRIB=NGRBCSWC,&
     & LDGP=.TRUE.,KREQIN=YSCONV_NL%NREQIN, &
     & PREFVALI=YSCONV_NL%REFVALI,LDREQOUT=YSCONV_NL%LREQOUT,LDERS=LLDERS,LD5=LL5, &
     & LDT1=LLT1,LDGPINGP=YSCONV_NL%LGPINGP,LDMGRID=YSCONV_NL%LMGRID,&
     & LDTRAJIO=YSCONV_NL%LTRAJIO, &
     & LDTHERMACT=.FALSE.,PR=0.0_JPRB,PRCP=RCS, &
     & LDWATER=.TRUE.,LDPRECIP=.TRUE.,PLZER=RLSZER)
  ENDIF
  IF(YLRAD_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YLRAD=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YLRAD,CDNAME=YFALRAD%CLNAME,KGRIB=NGRBCLWC,&
     & LDGP=.TRUE.,KREQIN=YLRAD_NL%NREQIN, &
     & PREFVALI=YLRAD_NL%REFVALI,LDREQOUT=YLRAD_NL%LREQOUT,LDERS=LLDERS,LD5=LL5, &
     & LDT1=LLT1,LDGPINGP=YLRAD_NL%LGPINGP,LDMGRID=YLRAD_NL%LMGRID,&
     & LDTRAJIO=YLRAD_NL%LTRAJIO, &
     & LDTHERMACT=.FALSE.,PR=0.0_JPRB,PRCP=RCW)
  ENDIF
  IF(YIRAD_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YIRAD=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YIRAD,CDNAME=YFAIRAD%CLNAME,KGRIB=NGRBCIWC,&
     & LDGP=.TRUE.,KREQIN=YIRAD_NL%NREQIN, &
     & PREFVALI=YIRAD_NL%REFVALI,LDREQOUT=YIRAD_NL%LREQOUT,LDERS=LLDERS,LD5=LL5, &
     & LDT1=LLT1,LDGPINGP=YIRAD_NL%LGPINGP,LDMGRID=YIRAD_NL%LMGRID,&
     & LDTRAJIO=YIRAD_NL%LTRAJIO, &
     & LDTHERMACT=.FALSE.,PR=0.0_JPRB,PRCP=RCS)
  ENDIF
  IF(YSDSAT_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YSDSAT=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YSDSAT,CDNAME=YFASDSAT%CLNAME,KGRIB=NGRBSNR,&
     & LDGP=.TRUE.,KREQIN=YSDSAT_NL%NREQIN, &
     & PREFVALI=YSDSAT_NL%REFVALI, LDREQOUT=YSDSAT_NL%LREQOUT,LDERS=LLDERS,&
     & LD5=LL5,LDT1=LLT1)
  ENDIF
  IF(YCVV_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YCVV=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YCVV,CDNAME=YFACVV%CLNAME,KGRIB=NGRBSNR,&
     & LDGP=.TRUE.,KREQIN=YCVV_NL%NREQIN, &
     & PREFVALI=YCVV_NL%REFVALI, LDREQOUT=YCVV_NL%LREQOUT,LDERS=LLDERS,&
     & LD5=LL5,LDT1=LLT1)
  ENDIF
  IF(YQVA_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YQVA=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YQVA,CDNAME=YFAQVA%CLNAME,&
     & KGRIB=YQVA_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YQVA_NL%NREQIN, PREFVALI=YQVA_NL%REFVALI,&
     & LDREQOUT=YQVA_NL%LREQOUT,LDERS=.FALSE.,LD5=LL5, &
     & LDT1=LLT1,LDGPINGP=.TRUE.)
  ENDIF
  IF(YUOM_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YUOM=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YUOM,CDNAME=YFAUOM%CLNAME,&
     & KGRIB=YUOM_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YUOM_NL%NREQIN,&
     & PREFVALI=YUOM_NL%REFVALI,LDREQOUT=YUOM_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=LL5,LDT1=LLT1,LDGPINGP=.TRUE.)
  ENDIF
  IF(YUAL_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YUAL=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YUAL,CDNAME=YFAUAL%CLNAME,&
     & KGRIB=YUAL_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YUAL_NL%NREQIN,&
     & PREFVALI=YUAL_NL%REFVALI,LDREQOUT=YUAL_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=LL5,LDT1=LLT1,LDGPINGP=.TRUE.)
  ENDIF
  IF(YDOM_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YDOM=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YDOM,CDNAME=YFADOM%CLNAME,&
     & KGRIB=YDOM_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YDOM_NL%NREQIN,&
     & PREFVALI=YDOM_NL%REFVALI,LDREQOUT=YDOM_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=LL5,LDT1=LLT1,LDGPINGP=.TRUE.)
  ENDIF
  IF(YDAL_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YDAL=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YDAL,CDNAME=YFADAL%CLNAME,&
     & KGRIB=YDAL_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YDAL_NL%NREQIN,&
     & PREFVALI=YDAL_NL%REFVALI,LDREQOUT=YDAL_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=LL5,LDT1=LLT1,LDGPINGP=.TRUE.)
  ENDIF
  IF(YUEN_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YUEN=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YUEN,CDNAME=YFAUEN%CLNAME,&
     & KGRIB=YUEN_NL%IGRBCODE,LDGP=.TRUE., & 
     & KREQIN=YUEN_NL%NREQIN,&
     & PREFVALI=YUEN_NL%REFVALI,LDREQOUT=YUEN_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=LL5,LDT1=LLT1,LDGPINGP=.TRUE.)
  ENDIF
  IF(YUNEBH_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YUNEBH=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YUNEBH,CDNAME=YFAUNEBH%CLNAME,&
     & KGRIB=YUNEBH_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YUNEBH_NL%NREQIN,&
     & PREFVALI=YUNEBH_NL%REFVALI,LDREQOUT=YUNEBH_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=LL5,LDT1=LLT1,LDGPINGP=.TRUE.)
  ENDIF
  IF(YTTE_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YTTE=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YTTE,CDNAME=YFATTE%CLNAME,&
     & KGRIB=YTTE_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YTTE_NL%NREQIN,&
     & PREFVALI=YTTE_NL%REFVALI,LDREQOUT=YTTE_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=LL5,LDT1=LLT1,LDGPINGP=.TRUE.)
  ENDIF
  IF(YMXL_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YMXL=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YMXL,CDNAME=YFAMXL%CLNAME,&
     & KGRIB=YMXL_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YMXL_NL%NREQIN,&
     & PREFVALI=YMXL_NL%REFVALI,LDREQOUT=YMXL_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=LL5,LDT1=LLT1,LDGPINGP=.TRUE.)
  ENDIF
  IF(YSHTUR_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YSHTUR=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YSHTUR,CDNAME=YFASHTUR%CLNAME,&
     & KGRIB=YSHTUR_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YSHTUR_NL%NREQIN,&
     & PREFVALI=YSHTUR_NL%REFVALI,LDREQOUT=YSHTUR_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=LL5,LDT1=LLT1,LDGPINGP=.TRUE.)
  ENDIF
  IF(YFQTUR_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YFQTUR=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YFQTUR,CDNAME=YFAFQTUR%CLNAME,&
     & KGRIB=YFQTUR_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YFQTUR_NL%NREQIN,&
     & PREFVALI=YFQTUR_NL%REFVALI,LDREQOUT=YFQTUR_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=LL5,LDT1=LLT1,LDGPINGP=.TRUE.)
  ENDIF
  IF(YFSTUR_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YFSTUR=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YFSTUR,CDNAME=YFAFSTUR%CLNAME,&
     & KGRIB=YFSTUR_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YFSTUR_NL%NREQIN,&
     & PREFVALI=YFSTUR_NL%REFVALI,LDREQOUT=YFSTUR_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=LL5,LDT1=LLT1,LDGPINGP=.TRUE.)
  ENDIF
  IF(YRKTH_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YRKTH=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YRKTH,CDNAME=YFARKTH%CLNAME,&
     & KGRIB=YRKTH_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YRKTH_NL%NREQIN,&
     & PREFVALI=YRKTH_NL%REFVALI,LDREQOUT=YRKTH_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=LL5,LDT1=LLT1,LDGPINGP=.TRUE.)
  ENDIF
  IF(YRSPEC_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YRSPEC=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YRSPEC,CDNAME='SpecificR       ',&
     & KGRIB=YRSPEC_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YRSPEC_NL%NREQIN,&
     & PREFVALI=YRSPEC_NL%REFVALI,LDREQOUT=YRSPEC_NL%LREQOUT,&
     & LDERS=YRSPEC_NL%LCDERS,LD5=.FALSE.,LDT1=.FALSE.,LDGPINGP=.TRUE.)
  ENDIF
  IF(YRKTQV_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YRKTQV=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YRKTQV,CDNAME=YFARKTQV%CLNAME,&
     & KGRIB=YRKTQV_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YRKTQV_NL%NREQIN,&
     & PREFVALI=YRKTQV_NL%REFVALI,LDREQOUT=YRKTQV_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=LL5,LDT1=LLT1,LDGPINGP=.TRUE.)
  ENDIF
  IF(YRKTQC_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YRKTQC=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YRKTQC,CDNAME=YFARKTQC%CLNAME,&
     & KGRIB=YRKTQC_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YRKTQC_NL%NREQIN,&
     & PREFVALI=YRKTQC_NL%REFVALI,LDREQOUT=YRKTQC_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=LL5,LDT1=LLT1,LDGPINGP=.TRUE.)
  ENDIF
  IF(YPHYCTY_NL%LGP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YPHYCTY=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YPHYCTY,CDNAME="PHYCTY          ",KGRIB=YPHYCTY_NL%IGRBCODE,&
     & LDGP=.TRUE.,KREQIN=YPHYCTY_NL%NREQIN, &
     & PREFVALI=YPHYCTY_NL%REFVALI, LDREQOUT=YPHYCTY_NL%LREQOUT,LDERS=.FALSE.,&
     & LD5=.FALSE.,LDT1=.FALSE.)
  ENDIF
  IF(NGHG > 0 .AND. YLRCH4_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YLRCH4=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YLRCH4,CDNAME=YLRCH4_NL%CNAME,&
     & KGRIB=YLRCH4_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YLRCH4_NL%NREQIN,&
     & PREFVALI=YLRCH4_NL%REFVALI,LDREQOUT=YLRCH4_NL%LREQOUT,&
     & LDERS=LLDERS,LD5=LL5,LDT1=LLT1,LDGPINGP=YLRCH4_NL%LGPINGP,&
     & LDMGRID=YLRCH4_NL%LMGRID,LDTRAJIO=YLRCH4_NL%LTRAJIO)
  ENDIF
  IF(NFSD > 0 .AND. YFSD_NL%LGP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YFSD=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YFSD,CDNAME=YFSD_NL%CNAME,&
     & KGRIB=YFSD_NL%IGRBCODE,LDGP=.TRUE., &
     & KREQIN=YFSD_NL%NREQIN,&
     & PREFVALI=YFSD_NL%REFVALI,LDREQOUT=YFSD_NL%LREQOUT,&
     & LDERS=LLDERS,LD5=LL5,LDT1=.FALSE.,LDGPINGP=.TRUE.,&
     & LDTRAJIO=.FALSE.)
  ENDIF
  ! Extra GFL variables
  ! - do a preliminary test to see if, when there are extra-GFL and when at
  !   least one of them is a grid-point one, there is no extra-GFL which is
  !   a spectral one (not allowed):
  !   in this case all the extra-GFL must be grid-point ones.
  IF (NGFL_EXT > 1) THEN
   IF(ANY(YEXT_NL(1:NGFL_EXT)%LGP)) THEN
    DO JGFL=1,NGFL_EXT
      IF (YEXT_NL(JGFL)%LSP) CALL ABOR1&
       & ('SUGFL2:EXTRA GFL FIELDS HAVE TO BE ALL EITHER SPECTRAL OR GRIDPOINT')
    ENDDO
   ENDIF
  ENDIF
  ! - define the GFL components (all the extra-GFL are grid-point ones).
  DO JGFL=1,NGFL_EXT
    IF(YEXT_NL(JGFL)%LGP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YEXT=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NGFL_EXT-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YEXT(JGFL),CDNAME=YEXT_NL(JGFL)%CNAME ,&
       & KGRIB=YEXT_NL(JGFL)%IGRBCODE,LDGP=.TRUE.,KREQIN=YEXT_NL(JGFL)%NREQIN,&
       & PREFVALI=YEXT_NL(JGFL)%REFVALI, LDREQOUT=YEXT_NL(JGFL)%LREQOUT ,&
       & LDERS=LLDERS, LD5=LL5, LDT1=LLT1,LDGPINGP=YEXT_NL(JGFL)%LGPINGP, &
       & LDMGRID=YEXT_NL(JGFL)%LMGRID,LDTRAJIO=YEXT_NL(JGFL)%LTRAJIO)
    ENDIF
  ENDDO

  ! Forcings
  DO JGFL=1,NGFL_FORC
    IF(YFORC_NL(JGFL)%LGP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YFORC=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NGFL_FORC-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YFORC(JGFL),CDNAME=YFORC_NL(JGFL)%CNAME ,&
       & KGRIB=YFORC_NL(JGFL)%IGRBCODE,LDGP=.TRUE.,KREQIN=YFORC_NL(JGFL)%NREQIN,&
       & PREFVALI=YFORC_NL(JGFL)%REFVALI, LDREQOUT=YFORC_NL(JGFL)%LREQOUT ,&
       & LDERS=LLDERS, LD5=LL5, LDT1=LLT1,LDGPINGP=YFORC_NL(JGFL)%LGPINGP, &
       & LDMGRID=YFORC_NL(JGFL)%LMGRID,LDTRAJIO=YFORC_NL(JGFL)%LTRAJIO)
    ENDIF
  ENDDO

  ! Easy diagnostics
  DO JGFL=1,NGFL_EZDIAG
    IF(YEZDIAG_NL(JGFL)%LGP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YEZDIAG=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NGFL_EZDIAG-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YEZDIAG(JGFL),CDNAME=YEZDIAG_NL(JGFL)%CNAME ,&
       & KGRIB=YEZDIAG_NL(JGFL)%IGRBCODE,LDGP=.TRUE.,KREQIN=YEZDIAG_NL(JGFL)%NREQIN,&
       & PREFVALI=YEZDIAG_NL(JGFL)%REFVALI, LDREQOUT=YEZDIAG_NL(JGFL)%LREQOUT ,&
       & LDERS=LLDERS, LD5=LL5, LDT1=YEZDIAG_NL(JGFL)%LT1,LDGPINGP=YEZDIAG_NL(JGFL)%LGPINGP, &
       & LDTRAJIO=YEZDIAG_NL(JGFL)%LTRAJIO)
    ENDIF
  ENDDO


  IF(NDYN_NAMES > 0) THEN
    CALL MAIN_FIELD_METADATA%FIELD_SET_METADATA(METADATA,ILEVELTYPESDUMMY,I3DDUMMY)
  ENDIF

  ! Use this to generate dynamic FIDs for COMPO fields
  JCOMPO_3D_FID = COMPO_3D_FIRST

  !-- Greenhouse Gases
  DO JGFL=1,NGHG
    IF(YGHG_NL(JGFL)%LGP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YGHG=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NGHG-1)
      ENDIF
      IF(NDYN_NAMES > 0) THEN
        IFID = GETFID(METADATA,YGHG_NL(JGFL)%CNAME)
      ELSE
        IFID = JCOMPO_3D_FID
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YGHG(JGFL),CDNAME=YGHG_NL(JGFL)%CNAME ,&
       & KGRIB=YGHG_NL(JGFL)%IGRBCODE, LDGP=.TRUE.,  KREQIN=YGHG_NL(JGFL)%NREQIN ,&
       & PREFVALI=YGHG_NL(JGFL)%REFVALI, LDREQOUT=YGHG_NL(JGFL)%LREQOUT ,&
       & LDERS=LLDERS, LD5=LL5, LDT1=LLT1,LDGPINGP=YGHG_NL(JGFL)%LGPINGP, &
       & LDASSIM=YGHG_NL(JGFL)%LASSIM,LDMGRID=YGHG_NL(JGFL)%LMGRID, &
       & LDTRAJIO=YGHG_NL(JGFL)%LTRAJIO,PBETAMFBC=YGHG_NL(JGFL)%BETAMFBC, &
       & LDMASSFIX=YGHG_NL(JGFL)%LMASSFIX,LDCOMAD=YGHG_NL(JGFL)%LCOMAD,&
       & LDNEGFIX=YGHG_NL(JGFL)%LNEGFIX,PWENO_ALPHA=YGHG_NL(JGFL)%WENO_ALPHA, KFID=IFID)
      JCOMPO_3D_FID=JCOMPO_3D_FID + 1
    ENDIF
  ENDDO

  !-- Chemical species
  DO JGFL=1,NCHEM
    IF(YCHEM_NL(JGFL)%LGP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YCHEM=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NCHEM-1)
      ENDIF
      IF(NDYN_NAMES > 0) THEN
        IFID = GETFID(METADATA,YCHEM_NL(JGFL)%CNAME)
      ELSE
        IFID = JCOMPO_3D_FID
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YCHEM(JGFL),CDNAME=YCHEM_NL(JGFL)%CNAME ,&
       & KGRIB=YCHEM_NL(JGFL)%IGRBCODE, LDGP=.TRUE.,  KREQIN=YCHEM_NL(JGFL)%NREQIN ,&
       & PREFVALI=YCHEM_NL(JGFL)%REFVALI, LDREQOUT=YCHEM_NL(JGFL)%LREQOUT ,&
       & LDERS=LLDERS, LD5=LL5, LDT1=LLT1,LDGPINGP=YCHEM_NL(JGFL)%LGPINGP,LDMGRID=YCHEM_NL(JGFL)%LMGRID, &
       & LDTRAJIO=YCHEM_NL(JGFL)%LTRAJIO,KCOUPLO4=YCHEM_NL(JGFL)%NCOUPLO4,LDASSIM=YCHEM_NL(JGFL)%LASSIM, &
       & LDDIFF=YCHEM_NL(JGFL)%LDIFF,LDCONV=YCHEM_NL(JGFL)%LCONV,PMOLMASS=YCHEM_NL(JGFL)%RMOLMASS,PEFOLD=YCHEM_NL(JGFL)%REFOLD,&
       & PHENRYA=YCHEM_NL(JGFL)%HENRYA, PHENRYB=YCHEM_NL(JGFL)%HENRYB, &
       & KGRIBTC=YCHEM_NL(JGFL)%IGRIBTC,KGRBFLXO=YCHEM_NL(JGFL)%IGRBFLXO, &
       & KGRBWDFLX=YCHEM_NL(JGFL)%IGRBWDFLX, KGRBDDFLX=YCHEM_NL(JGFL)%IGRBDDFLX, &
       & KGRIBDV=YCHEM_NL(JGFL)%IGRIBDV,PBETAMFBC=YCHEM_NL(JGFL)%BETAMFBC, &
       & LDMASSFIX=YCHEM_NL(JGFL)%LMASSFIX,LDCOMAD=YCHEM_NL(JGFL)%LCOMAD, &
       & LDNEGFIX=YCHEM_NL(JGFL)%LNEGFIX,PWENO_ALPHA=YCHEM_NL(JGFL)%WENO_ALPHA,KFID=IFID)
      JCOMPO_3D_FID=JCOMPO_3D_FID + 1
    ENDIF
  ENDDO

  !-- Aerosols
  DO JGFL=1,NAERO
    IF(YAERO_NL(JGFL)%LGP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YAERO=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NAERO-1)
      ENDIF
      IF(NDYN_NAMES > 0) THEN
        IFID = GETFID(METADATA,YAERO_NL(JGFL)%CNAME)
      ELSE
        IFID = JCOMPO_3D_FID
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YAERO(JGFL),CDNAME=YAERO_NL(JGFL)%CNAME ,&
       & KGRIB=YAERO_NL(JGFL)%IGRBCODE, LDGP=.TRUE.,  KREQIN=YAERO_NL(JGFL)%NREQIN ,&
       & PREFVALI=YAERO_NL(JGFL)%REFVALI, LDREQOUT=YAERO_NL(JGFL)%LREQOUT ,&
       & LDERS=LLDERS, LD5=LL5, LDT1=LLT1,LDGPINGP=YAERO_NL(JGFL)%LGPINGP, &
       & LDASSIM=YAERO_NL(JGFL)%LASSIM, LDMGRID=YAERO_NL(JGFL)%LMGRID,LDTRAJIO=YAERO_NL(JGFL)%LTRAJIO, &
       & PBETAMFBC=YAERO_NL(JGFL)%BETAMFBC,LDMASSFIX=YAERO_NL(JGFL)%LMASSFIX,&
       & LDCOMAD=YAERO_NL(JGFL)%LCOMAD,LDNEGFIX=YAERO_NL(JGFL)%LNEGFIX,PWENO_ALPHA=YAERO_NL(JGFL)%WENO_ALPHA, &
       & KFID=IFID )
      JCOMPO_3D_FID=JCOMPO_3D_FID + 1
    ENDIF
  ENDDO

  !-- ERA40 diagnostic fields 
  DO JGFL=1,NERA40
    YERA40_NL(JGFL)%NREQIN=0
    YERA40_NL(JGFL)%LGP=.TRUE.
    
    IF(YERA40_NL(JGFL)%LGP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YERA40=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NERA40-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YERA40(JGFL),CDNAME=YERA40_NL(JGFL)%CNAME ,&
       & KGRIB=YERA40_NL(JGFL)%IGRBCODE, LDGP=.TRUE.,  KREQIN=YERA40_NL(JGFL)%NREQIN ,&
       & PREFVALI=YERA40_NL(JGFL)%REFVALI, LDREQOUT=YERA40_NL(JGFL)%LREQOUT ,&
       & LDERS=LLDERS, LD5=.FALSE., LDT1=.FALSE.,LDGPINGP=.TRUE. ,&
       & LDTRAJIO=.FALSE.)
    ENDIF
  ENDDO

  !-- NORO GWD SCHEME fields
  DO JGFL=1,NNOGW
    YNOGW_NL(JGFL)%NREQIN=0
    YNOGW_NL(JGFL)%LGP=.TRUE.

    IF(YNOGW_NL(JGFL)%LGP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YNOGW=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NNOGW-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YNOGW(JGFL),CDNAME=YNOGW_NL(JGFL)%CNAME ,&
       & KGRIB=YNOGW_NL(JGFL)%IGRBCODE, LDGP=.TRUE.,  KREQIN=YNOGW_NL(JGFL)%NREQIN ,&
       & PREFVALI=YNOGW_NL(JGFL)%REFVALI, LDREQOUT=YNOGW_NL(JGFL)%LREQOUT ,&
       & LDERS=LLDERS, LD5=LL5, LDT1=.FALSE.,LDGPINGP=.TRUE. ,&
       & LDTRAJIO=.FALSE.)
    ENDIF
  ENDDO

  !-- 3D emission fields
  DO JGFL=1,NEMIS3D
    IF(JGFL == 1) THEN
      IGFLPTR=NUMFLDS+1
      YGFL%YEMIS3D=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NEMIS3D-1)
    ENDIF
    DO JEMIS=1,NEMIS3D_DESC
      IF (YEMIS3D_DESC(JEMIS)%PARAM_INDEX == JGFL) THEN
        CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YEMIS3D(JGFL),&
         & CDNAME='EM3D '//TRIM(YEMIS3D_DESC(JGFL)%SPECIES)//' '//YEMIS3D_DESC(JGFL)%SECTOR, &
         & KGRIB=YEMIS3D_DESC(JGFL)%PARAMID, LDGP=.TRUE.,  KREQIN=YEMIS3D_DESC(JGFL)%NREQIN, &
         & LDREQOUT=.TRUE., LDERS=.FALSE., LD5=LL5, LDT1=.FALSE., KFID=JCOMPO_3D_FID)
        JCOMPO_3D_FID=JCOMPO_3D_FID + 1
        EXIT
      ENDIF
    ENDDO
  ENDDO

  IF (JCOMPO_3D_FID-1 > COMPO_3D_LAST) THEN
    CALL ABOR1('SUGFL2: too many COMPO 3D fields - increase range in field_definitions.f90')
  ENDIF

  !-- Eddy dissipation Parameter turbulence diagnostics fields
  DO JGFL=1,NEDRP
    YEDRP_NL(JGFL)%NREQIN=0
    YEDRP_NL(JGFL)%LGP=.TRUE.

    IF(YEDRP_NL(JGFL)%LGP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YEDRP=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NEDRP-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YEDRP(JGFL),CDNAME=YEDRP_NL(JGFL)%CNAME ,&
       & KGRIB=YEDRP_NL(JGFL)%IGRBCODE, LDGP=.TRUE.,  KREQIN=YEDRP_NL(JGFL)%NREQIN ,&
       & PREFVALI=YEDRP_NL(JGFL)%REFVALI, LDREQOUT=YEDRP_NL(JGFL)%LREQOUT ,&
       & LDERS=LLDERS, LD5=.FALSE., LDT1=.FALSE.,LDGPINGP=.TRUE. ,&
       & LDTRAJIO=.FALSE.)
    ENDIF
  ENDDO

  IF (LAERAOT .AND. NAERO > 0) THEN
    !-- NPAERAOT aerosol optical thickness fields
    DO JGFL=1,NPAERAOT
      YAERAOT_NL(JGFL)%NREQIN=0
      YAERAOT_NL(JGFL)%LGP=.TRUE.

      IF(YAERAOT_NL(JGFL)%LGP) THEN
        IF(JGFL == 1) THEN
          IGFLPTR=NUMFLDS+1
          YGFL%YAERAOT=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NPAERAOT-1)
        ENDIF
        CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YAERAOT(JGFL),CDNAME=YAERAOT_NL(JGFL)%CNAME ,&
         & KGRIB=YAERAOT_NL(JGFL)%IGRBCODE, LDGP=.TRUE.,  KREQIN=YAERAOT_NL(JGFL)%NREQIN ,&
         & PREFVALI=YAERAOT_NL(JGFL)%REFVALI, LDREQOUT=YAERAOT_NL(JGFL)%LREQOUT ,&
         & LDERS=LLDERS, LD5=.FALSE., LDT1=.FALSE.,LDGPINGP=.TRUE. ,&
         & LDTRAJIO=.FALSE.)
      ENDIF
    ENDDO
  ENDIF

  IF (LAERLISI) THEN
    !-- NPAERLISI aerosol lidar simulator fields
    JGFL = 0
    DO JVAR=1,NPAERLISI_VAR
      DO JWVL=1,NPAERLISI_WVL
        JGFL = JGFL + 1

        YAERLISI_NL(JWVL,JVAR)%NREQIN=0
        YAERLISI_NL(JWVL,JVAR)%LGP=.TRUE.

        IF(YAERLISI_NL(JWVL,JVAR)%LGP) THEN

          IF(JGFL == 1) THEN
            IGFLPTR=NUMFLDS+1
            YGFL%YAERLISI=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NPAERLISI-1)
          ENDIF
          CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YAERLISI(JGFL),CDNAME=YAERLISI_NL(JWVL,JVAR)%CNAME ,&
           & KGRIB=YAERLISI_NL(JWVL,JVAR)%IGRBCODE, LDGP=.TRUE.,  KREQIN=YAERLISI_NL(JWVL,JVAR)%NREQIN ,&
           & PREFVALI=YAERLISI_NL(JWVL,JVAR)%REFVALI, LDREQOUT=YAERLISI_NL(JWVL,JVAR)%LREQOUT ,&
           & LDERS=LLDERS, LD5=.FALSE., LDT1=.FALSE.,LDGPINGP=.TRUE. ,&
           & LDTRAJIO=.FALSE.)
        ENDIF
      ENDDO
    ENDDO
  ENDIF

  !-- NAEROUT aerosol output fields
  DO JGFL=1,NAEROUT
    YAEROUT_NL(JGFL)%NREQIN=0
    YAEROUT_NL(JGFL)%LGP=.TRUE.

    IF(YAEROUT_NL(JGFL)%LGP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YAEROUT=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NAEROUT-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YAEROUT(JGFL),CDNAME=YAEROUT_NL(JGFL)%CNAME ,&
       & KGRIB=YAEROUT_NL(JGFL)%IGRBCODE, LDGP=.TRUE.,  KREQIN=YAEROUT_NL(JGFL)%NREQIN ,&
       & PREFVALI=YAEROUT_NL(JGFL)%REFVALI, LDREQOUT=YAEROUT_NL(JGFL)%LREQOUT ,&
       & LDERS=LLDERS, LD5=.FALSE., LDT1=.FALSE.,LDGPINGP=.TRUE. ,&
       & LDMGRID=YAEROUT_NL(JGFL)%LMGRID,LDTRAJIO=.FALSE.)
    ENDIF
  ENDDO

  !-- NAEROCLIM aerosol input fields
  DO JGFL=1,NAEROCLIM
    YAEROCLIM_NL(JGFL)%NREQIN=1
    YAEROCLIM_NL(JGFL)%LGP=.TRUE.

    IF(YAEROCLIM_NL(JGFL)%LGP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YAEROCLIM=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NAEROCLIM-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YAEROCLIM(JGFL),CDNAME=YAEROCLIM_NL(JGFL)%CNAME ,&
       & KGRIB=YAEROCLIM_NL(JGFL)%IGRBCODE, LDGP=.TRUE.,KREQIN=YAEROCLIM_NL(JGFL)%NREQIN ,&
       & PREFVALI=YAEROCLIM_NL(JGFL)%REFVALI, LDREQOUT=YAEROCLIM_NL(JGFL)%LREQOUT,&
       & LDERS=LLDERS, LD5=.FALSE., LDT1=.FALSE.,LDGPINGP=.TRUE. ,&
       & LDTRAJIO=.FALSE.)
    ENDIF
  ENDDO

  !-- NUVP UV processor output fields
  DO JGFL=1,NUVP
    YUVP_NL(JGFL)%NREQIN=0
    YUVP_NL(JGFL)%LGP=.TRUE.

    IF(YUVP_NL(JGFL)%LGP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YUVP=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NUVP-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YUVP(JGFL),CDNAME=YUVP_NL(JGFL)%CNAME ,&
       & KGRIB=YUVP_NL(JGFL)%IGRBCODE, LDGP=.TRUE.,  KREQIN=YUVP_NL(JGFL)%NREQIN ,&
       & PREFVALI=YUVP_NL(JGFL)%REFVALI, LDREQOUT=YUVP_NL(JGFL)%LREQOUT ,&
       & LDERS=LLDERS, LD5=.FALSE., LDT1=.FALSE.,LDGPINGP=.TRUE. ,&
       & LDTRAJIO=.FALSE.)
    ENDIF
  ENDDO

  !-- Semi-Lagrangian diagnostics
  DO JGFL=1,NSLDIA
    IF(YSLDIA_NL(JGFL)%LGP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YSLDIA=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NSLDIA-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YSLDIA(JGFL),CDNAME=YSLDIA_NL(JGFL)%CNAME ,&
       & KGRIB=YSLDIA_NL(JGFL)%IGRBCODE, LDGP=.TRUE.,  KREQIN=YSLDIA_NL(JGFL)%NREQIN ,&
       & PREFVALI=YSLDIA_NL(JGFL)%REFVALI, LDREQOUT=YSLDIA_NL(JGFL)%LREQOUT ,&
       & LDERS=LLDERS, LD5=.FALSE., LDT1=LLT1,LDGPINGP=YSLDIA_NL(JGFL)%LGPINGP,&
       & LDTRAJIO=.FALSE.)
    ENDIF
  ENDDO

  !-- LIMA fields
  DO JGFL=1,NLIMA
    IF(YLIMA_NL(JGFL)%LGP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YLIMA=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NLIMA-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YDML_GCONF%YGFL, YDCOMP=YGFL%YLIMA(JGFL),CDNAME=YLIMA_NL(JGFL)%CNAME,&
       & KGRIB=YLIMA_NL(JGFL)%IGRBCODE, LDGP=.TRUE.,  KREQIN=YLIMA_NL(JGFL)%NREQIN ,&
       & PREFVALI=YLIMA_NL(JGFL)%REFVALI, LDREQOUT=YLIMA_NL(JGFL)%LREQOUT ,&
       & LDERS=LLDERS, LD5=LL5, LDT1=LLT1, LDGPINGP=YLIMA_NL(JGFL)%LGPINGP ,&
       & LDTRAJIO=YLIMA_NL(JGFL)%LTRAJIO, LDTHERMACT=.FALSE.,PR=0.0_JPRB,PRCP=RCW,&
       & PBETAMFBC=YLIMA_NL(JGFL)%BETAMFBC,LDMASSFIX=YLIMA_NL(JGFL)%LMASSFIX,&
       & LDCOMAD=YLIMA_NL(JGFL)%LCOMAD,LDNEGFIX=YLIMA_NL(JGFL)%LNEGFIX,PWENO_ALPHA=YLIMA_NL(JGFL)%WENO_ALPHA, &
       & LDWATER=.FALSE.,LDPRECIP=.FALSE.,PLZER=RLVZER)
    ENDIF
  ENDDO

!      1.3  Spectral GFL.
  
  IF(YQ_NL%LSP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YQ=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YQ,CDNAME=YFAQ%CLNAME,KGRIB=NGRBQ,&
     & LDGP=.FALSE.,KREQIN=YQ_NL%NREQIN,KFID=FID%Q, & 
     & PREFVALI=YQ_NL%REFVALI,LDREQOUT=YQ_NL%LREQOUT,LDERS=LADER,LD5=LL5,&
     & LDT1=LLT1,LDGPINGP=YQ_NL%LGPINGP,LDMGRID=YQ_NL%LMGRID,&
     & LDTRAJIO=YQ_NL%LTRAJIO,LDTHERMACT=.TRUE.,PR=RV,PRCP=RCPV,&
     & PBETAMFBC=YQ_NL%BETAMFBC,LDMASSFIX=YQ_NL%LMASSFIX,&
     & LDCOMAD=YQ_NL%LCOMAD,LDNEGFIX=YQ_NL%LNEGFIX,PWENO_ALPHA=YQ_NL%WENO_ALPHA,&
     & LDWATER=.TRUE.,LDPRECIP=.FALSE.,PLZER=0.0_JPRB)
  ENDIF
  IF(YL_NL%LSP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YL=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YL,CDNAME=YFAL%CLNAME,KGRIB=NGRBCLWC,&
     & LDGP=.FALSE.,KREQIN=YL_NL%NREQIN, KFID=FID%L, &
     & PREFVALI=YL_NL%REFVALI, LDREQOUT=YL_NL%LREQOUT, LDERS=LADER,LD5=LL5, &
     & LDT1=LLT1,LDTHERMACT=LLTHERMACT,PR=0.0_JPRB,PRCP=RCW, &
     & LDWATER=.TRUE.,LDPRECIP=.FALSE.,PLZER=RLVZER)
  ENDIF
  IF(YI_NL%LSP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YI=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YI,CDNAME=YFAI%CLNAME,KGRIB=NGRBCIWC,&
     & LDGP=.FALSE.,KREQIN=YI_NL%NREQIN, KFID=FID%I, &
     & PREFVALI=YI_NL%REFVALI, LDREQOUT=YI_NL%LREQOUT, LDERS=LADER,LD5=LL5, &
     & LDT1=LLT1,LDTHERMACT=LLTHERMACT,PR=0.0_JPRB,PRCP=RCS, &
     & LDWATER=.TRUE.,LDPRECIP=.FALSE.,PLZER=RLSZER)
  ENDIF
  IF(YS_NL%LSP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YS=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YS,CDNAME=YFAS%CLNAME,KGRIB=NGRBCIWC,&
     & LDGP=.FALSE.,KREQIN=YS_NL%NREQIN, KFID=FID%S, &
     & PREFVALI=YS_NL%REFVALI, LDREQOUT=YS_NL%LREQOUT, LDERS=LADER,LD5=LL5, &
     & LDT1=LLT1,LDTHERMACT=LLTHERMACT,PR=0.0_JPRB,PRCP=RCS, &
     & LDWATER=.TRUE.,LDPRECIP=.TRUE.,PLZER=RLSZER)
  ENDIF
  IF(YR_NL%LSP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YR=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YR,CDNAME=YFAR%CLNAME,KGRIB=NGRBCIWC,&
     & LDGP=.FALSE.,KREQIN=YR_NL%NREQIN,KFID=FID%R, &
     & PREFVALI=YR_NL%REFVALI, LDREQOUT=YR_NL%LREQOUT, LDERS=LADER,LD5=LL5, &
     & LDT1=LLT1,LDTHERMACT=LLTHERMACT,PR=0.0_JPRB,PRCP=RCW, &
     & LDWATER=.TRUE.,LDPRECIP=.TRUE.,PLZER=RLVZER)
  ENDIF
  IF(YG_NL%LSP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YG=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YG,CDNAME=YFAG%CLNAME,KGRIB=NGRBCIWC,&
     & LDGP=.FALSE.,KREQIN=YG_NL%NREQIN, KFID=FID%G, &
     & PREFVALI=YG_NL%REFVALI, LDREQOUT=YG_NL%LREQOUT, LDERS=LADER,LD5=LL5, &
     & LDT1=LLT1,LDTHERMACT=LLTHERMACT,PR=0.0_JPRB,PRCP=RCS, &
     & LDWATER=.TRUE.,LDPRECIP=.TRUE.,PLZER=RLSZER)
  ENDIF
  IF(YH_NL%LSP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YH=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YH,CDNAME=YFAH%CLNAME,KGRIB=NGRBCIWC,&
     & LDGP=.FALSE.,KREQIN=YH_NL%NREQIN, KFID=FID%H, &
     & PREFVALI=YH_NL%REFVALI, LDREQOUT=YH_NL%LREQOUT, LDERS=LADER,LD5=LL5, &
     & LDT1=LLT1,LDTHERMACT=LLTHERMACT,PR=0.0_JPRB,PRCP=RCS, &
     & LDWATER=.TRUE.,LDPRECIP=.TRUE.,PLZER=RLSZER)
  ENDIF
  IF(YTKE_NL%LSP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YTKE=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YTKE,CDNAME=YFATKE%CLNAME,KGRIB=NGRBCIWC,&
     & LDGP=.FALSE.,KREQIN=YTKE_NL%NREQIN,KFID=FID%TKE, &
     & PREFVALI=YTKE_NL%REFVALI,LDREQOUT=YTKE_NL%LREQOUT,LDERS=LADER,LD5=LL5, &
     & LDT1=LLT1)
  ENDIF  
  IF(YEFB1_NL%LSP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YEFB1=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YEFB1,CDNAME=YFAEFB1%CLNAME,KGRIB=NGRBCIWC,&
     & LDGP=.FALSE.,KREQIN=YEFB1_NL%NREQIN, &
     & PREFVALI=YEFB1_NL%REFVALI,LDREQOUT=YEFB1_NL%LREQOUT,LDERS=LADER,LD5=LL5, &
     & LDT1=LLT1)
  ENDIF  
  IF(YEFB2_NL%LSP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YEFB2=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YEFB2,CDNAME=YFAEFB2%CLNAME,KGRIB=NGRBCIWC,&
     & LDGP=.FALSE.,KREQIN=YEFB2_NL%NREQIN, &
     & PREFVALI=YEFB2_NL%REFVALI,LDREQOUT=YEFB2_NL%LREQOUT,LDERS=LADER,LD5=LL5, &
     & LDT1=LLT1)
  ENDIF  
  IF(YEFB3_NL%LSP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YEFB3=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YEFB3,CDNAME=YFAEFB3%CLNAME,KGRIB=NGRBCIWC,&
     & LDGP=.FALSE.,KREQIN=YEFB3_NL%NREQIN, &
     & PREFVALI=YEFB3_NL%REFVALI,LDREQOUT=YEFB3_NL%LREQOUT,LDERS=LADER,LD5=LL5, &
     & LDT1=LLT1)
  ENDIF  
  IF(YA_NL%LSP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YA=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YA,CDNAME=YFACLF%CLNAME,KGRIB=NGRBCC,&
     & LDGP=.FALSE.,KREQIN=YA_NL%NREQIN, KFID=FID%A, &
     & PREFVALI=YA_NL%REFVALI, LDREQOUT=YA_NL%LREQOUT, LDERS=LADER,LD5=LL5,&
     & LDT1=LLT1)
  ENDIF
  IF(YO3_NL%LSP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YO3=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YO3,CDNAME=YFAO3%CLNAME,KGRIB=NGRBO3,&
     & LDGP=.FALSE.,KREQIN=YO3_NL%NREQIN,KFID=FID%O3, & 
     & PREFVALI=YO3_NL%REFVALI, LDREQOUT=YO3_NL%LREQOUT, LDERS=LADER,LD5=LL5,&
     & LDT1=LLT1)
  ENDIF
  IF(YCPF_NL%LSP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YCPF=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YCPF,CDNAME=YFACPF%CLNAME,&
     & KGRIB=YCPF_NL%IGRBCODE, LDGP=.FALSE.,KFID=FID%CPF, &
     & KREQIN=YCPF_NL%NREQIN,PREFVALI=YCPF_NL%REFVALI,LDREQOUT=YCPF_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=.FALSE., &
     & LDT1=LLT1)
  ENDIF
  IF(YSPF_NL%LSP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YSPF=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YSPF,CDNAME=YFASPF%CLNAME,&
     & KGRIB=YSPF_NL%IGRBCODE,LDGP= .FALSE., &
     & KREQIN=YSPF_NL%NREQIN,PREFVALI=YSPF_NL%REFVALI,LDREQOUT=YSPF_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=.FALSE., &
     & LDT1=LLT1)
  ENDIF
  IF(YSRC_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral SRC not coded ')
  ENDIF
  IF(YLMF_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral LMF not coded ')
  ENDIF
  IF(YIMF_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral IMF not coded ')
  ENDIF
  IF(YAMF_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral AMF not coded ')
  ENDIF
  IF(YWMFC_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral WMFC not coded ')
  ENDIF
  IF(YHLMF_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral HLMF not coded ')
  ENDIF
  IF(YHLCFMF_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral HLCFMF not coded ')
  ENDIF
  IF(YHIMF_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral HIMF not coded ')
  ENDIF
  IF(YHICFMF_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral HICFMF not coded ')
  ENDIF
  IF(YCVGQ_NL%LSP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YCVGQ=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YCVGQ,CDNAME=YFACVGQ%CLNAME,&
     & KGRIB=YCVGQ_NL%IGRBCODE,LDGP= .FALSE., &
     & KREQIN=YCVGQ_NL%NREQIN,PREFVALI=YCVGQ_NL%REFVALI,&
     & LDREQOUT=YCVGQ_NL%LREQOUT,LDERS= .TRUE.,LD5=.FALSE., & 
     & LDT1=LLT1)
  ENDIF
  IF(YLCONV_NL%LSP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YLCONV=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YLCONV ,CDNAME=YFALCONV%CLNAME,KGRIB=NGRBCLWC,&
     & LDGP=.FALSE.,KREQIN=YLCONV_NL%NREQIN, &
     & PREFVALI=YLCONV_NL%REFVALI, LDREQOUT=YLCONV_NL%LREQOUT, LDERS=LADER,LD5=LL5, &
     & LDT1=LLT1,LDTHERMACT=.FALSE.,PR=0.0_JPRB,PRCP=RCW, &
     & LDWATER=.TRUE.,LDPRECIP=.FALSE.,PLZER=RLVZER)
  ENDIF
  IF(YICONV_NL%LSP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YICONV=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YICONV,CDNAME=YFAICONV%CLNAME,KGRIB=NGRBCIWC,&
     & LDGP=.FALSE.,KREQIN=YICONV_NL%NREQIN, &
     & PREFVALI=YICONV_NL%REFVALI, LDREQOUT=YICONV_NL%LREQOUT, LDERS=LADER,LD5=LL5, &
     & LDT1=LLT1,LDTHERMACT=.FALSE.,PR=0.0_JPRB,PRCP=RCS, &
     & LDWATER=.TRUE.,LDPRECIP=.FALSE.,PLZER=RLSZER)
  ENDIF
  IF(YRCONV_NL%LSP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YRCONV=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YRCONV,CDNAME=YFARCONV%CLNAME,KGRIB=NGRBCRWC,&
     & LDGP=.FALSE.,KREQIN=YRCONV_NL%NREQIN, &
     & PREFVALI=YRCONV_NL%REFVALI, LDREQOUT=YRCONV_NL%LREQOUT, LDERS=LADER,LD5=LL5, &
     & LDT1=LLT1,LDTHERMACT=.FALSE.,PR=0.0_JPRB,PRCP=RCW, &
     & LDWATER=.TRUE.,LDPRECIP=.TRUE.,PLZER=RLVZER)
  ENDIF
  IF(YSCONV_NL%LSP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YSCONV=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YSCONV,CDNAME=YFASCONV%CLNAME,KGRIB=NGRBCSWC,&
     & LDGP=.FALSE.,KREQIN=YSCONV_NL%NREQIN, &
     & PREFVALI=YSCONV_NL%REFVALI, LDREQOUT=YSCONV_NL%LREQOUT, LDERS=LADER,LD5=LL5, &
     & LDT1=LLT1,LDTHERMACT=.FALSE.,PR=0.0_JPRB,PRCP=RCS, &
     & LDWATER=.TRUE.,LDPRECIP=.TRUE.,PLZER=RLSZER)
  ENDIF
  IF(YLRAD_NL%LSP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YLRAD=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YLRAD,CDNAME=YFAL%CLNAME,KGRIB=NGRBCLWC,&
     & LDGP=.FALSE.,KREQIN=YLRAD_NL%NREQIN, &
     & PREFVALI=YLRAD_NL%REFVALI, LDREQOUT=YLRAD_NL%LREQOUT, LDERS=LADER,LD5=LL5, &
     & LDT1=LLT1,LDTHERMACT=LLTHERMACT,PR=0.0_JPRB,PRCP=RCW)
  ENDIF
  IF(YIRAD_NL%LSP)THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YIRAD=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YIRAD,CDNAME=YFAI%CLNAME,KGRIB=NGRBCIWC,&
     & LDGP=.FALSE.,KREQIN=YIRAD_NL%NREQIN, &
     & PREFVALI=YIRAD_NL%REFVALI, LDREQOUT=YIRAD_NL%LREQOUT, LDERS=LADER,LD5=LL5, &
     & LDT1=LLT1,LDTHERMACT=LLTHERMACT,PR=0.0_JPRB,PRCP=RCS)
  ENDIF
  IF(YSDSAT_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral SDSAT not coded ')
  ENDIF
  IF(YCVV_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral CVV not coded ')
  ENDIF
  IF(YQVA_NL%LSP) THEN
    IGFLPTR=NUMFLDS+1
    YGFL%YQVA=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YQVA,CDNAME=YFAQVA%CLNAME,&
     & KGRIB=YQVA_NL%IGRBCODE, LDGP=.FALSE., &
     & KREQIN=YQVA_NL%NREQIN,PREFVALI=YQVA_NL%REFVALI,LDREQOUT=YQVA_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=.FALSE., &
     & LDT1=LLT1)
  ENDIF
  IF(YUOM_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral UOM not coded ')
    ! ----------------------------------------------------------------------
    ! what is below must be checked when UOM will be coded!
    IGFLPTR=NUMFLDS+1
    YGFL%YUOM=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YUOM,CDNAME=YFAUOM%CLNAME,&
     & KGRIB=YUOM_NL%IGRBCODE,LDGP=.FALSE., &
     & KREQIN=YUOM_NL%NREQIN,&
     & PREFVALI=YUOM_NL%REFVALI,LDREQOUT=YUOM_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=.FALSE.,LDT1=LLT1)
    ! ----------------------------------------------------------------------
  ENDIF
  IF(YUAL_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral UAL not coded ')
    ! ----------------------------------------------------------------------
    ! what is below must be checked when UAL will be coded!
    IGFLPTR=NUMFLDS+1
    YGFL%YUAL=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YUAL,CDNAME=YFAUAL%CLNAME,&
     & KGRIB=YUAL_NL%IGRBCODE,LDGP=.FALSE., &
     & KREQIN=YUAL_NL%NREQIN,&
     & PREFVALI=YUAL_NL%REFVALI,LDREQOUT=YUAL_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=.FALSE.,LDT1=LLT1)
    ! ----------------------------------------------------------------------
  ENDIF
  IF(YDOM_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral DOM not coded ')
    ! ----------------------------------------------------------------------
    ! what is below must be checked when DOM will be coded!
    IGFLPTR=NUMFLDS+1
    YGFL%YDOM=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YDOM,CDNAME=YFADOM%CLNAME,&
     & KGRIB=YDOM_NL%IGRBCODE,LDGP=.FALSE., &
     & KREQIN=YDOM_NL%NREQIN,&
     & PREFVALI=YDOM_NL%REFVALI,LDREQOUT=YDOM_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=.FALSE.,LDT1=LLT1)
    ! ----------------------------------------------------------------------
  ENDIF
  IF(YDAL_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral DAL not coded ')
    ! ----------------------------------------------------------------------
    ! what is below must be checked when DAL will be coded!
    IGFLPTR=NUMFLDS+1
    YGFL%YDAL=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YDAL,CDNAME=YFADAL%CLNAME,&
     & KGRIB=YDAL_NL%IGRBCODE,LDGP=.FALSE., & 
     & KREQIN=YDAL_NL%NREQIN,&
     & PREFVALI=YDAL_NL%REFVALI,LDREQOUT=YDOM_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=.FALSE.,LDT1=LLT1)
    ! ----------------------------------------------------------------------
  ENDIF
  IF(YUEN_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral UEN not coded ')
    ! ----------------------------------------------------------------------
    ! what is below must be checked when UEN will be coded!
    IGFLPTR=NUMFLDS+1
    YGFL%YUEN=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YUEN,CDNAME=YFAUEN%CLNAME,&
     & KGRIB=YUEN_NL%IGRBCODE,LDGP=.FALSE., &
     & KREQIN=YUEN_NL%NREQIN,&
     & PREFVALI=YUEN_NL%REFVALI,LDREQOUT=YUEN_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=.FALSE.,LDT1=LLT1)
    ! ----------------------------------------------------------------------
  ENDIF
  IF(YUNEBH_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral UNEBH not coded ')
    ! ----------------------------------------------------------------------
    ! what is below must be checked when UNEBH will be coded!
    IGFLPTR=NUMFLDS+1
    YGFL%YUNEBH=>YGFL%YCOMP(IGFLPTR)
    CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YUNEBH,CDNAME=YFAUNEBH%CLNAME,&
     & KGRIB=YUNEBH_NL%IGRBCODE,LDGP=.FALSE., &
     & KREQIN=YUNEBH_NL%NREQIN,&
     & PREFVALI=YUNEBH_NL%REFVALI,LDREQOUT=YUNEBH_NL%LREQOUT,&
     & LDERS=.FALSE.,LD5=.FALSE.,LDT1=LLT1)
    ! ----------------------------------------------------------------------
  ENDIF
  IF(YTTE_NL%LSP)THEN
    CALL ABOR1('SUGFL: spectral TTE not coded ')
  ENDIF
  IF(YMXL_NL%LSP)THEN
    CALL ABOR1('SUGFL: spectral MXL not coded ')
  ENDIF
  IF(YSHTUR_NL%LSP)THEN
    CALL ABOR1('SUGFL: spectral SHTUR not coded ')
  ENDIF
  IF(YFQTUR_NL%LSP)THEN
    CALL ABOR1('SUGFL: spectral FQTUR not coded ')
  ENDIF
  IF(YFSTUR_NL%LSP)THEN
    CALL ABOR1('SUGFL: spectral FSTUR not coded ')
  ENDIF
  IF(YRKTH_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral RKTH not coded ')
  ENDIF
  IF(YRKTQV_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral RKTQV not coded ')
  ENDIF
  IF(YRKTQC_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral RKTQC not coded ')
  ENDIF
  IF(YPHYCTY_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral PHYCTY not coded ')
  ENDIF
  IF(NGHG > 0 .AND. YLRCH4_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral LRCH4 not coded ')
  ENDIF
  IF(YFSD_NL%LSP)THEN
    CALL ABOR1('SUGFL2: spectral FSD not coded ')
  ENDIF
  DO JGFL=1,NEDRP
    IF(YEDRP_NL(JGFL)%LSP) CALL ABOR1('SUGFL2: spectral EDR Parameters not coded ')
  ENDDO

  ! Extra GFL variables (assumed to be all spectral in this piece of code)
  DO JGFL=1,NGFL_EXT
    IF(YEXT_NL(JGFL)%LSP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YEXT=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NGFL_EXT-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YEXT(JGFL),CDNAME=YEXT_NL(JGFL)%CNAME ,&
       & KGRIB=YEXT_NL(JGFL)%IGRBCODE,LDGP=.FALSE.,KREQIN=YEXT_NL(JGFL)%NREQIN,&
       & PREFVALI=YEXT_NL(JGFL)%REFVALI, LDREQOUT=YEXT_NL(JGFL)%LREQOUT ,&
       & LDERS=LADER, LD5=LL5, LDT1=LLT1)
    ENDIF
  ENDDO

  ! Forcings
  DO JGFL=1,NGFL_FORC
    IF(YFORC_NL(JGFL)%LSP) THEN
      CALL ABOR1('SUGFL2: FORCINGS HAVE TO BE GRIDPOINT FIELDS')
      ! ----------------------------------------------------------------------
      ! what is below must be checked when spectral forcings will be coded!
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YFORC=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NGFL_FORC-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YFORC(JGFL),CDNAME=YFORC_NL(JGFL)%CNAME,&
       & KGRIB=YFORC_NL(JGFL)%IGRBCODE,LDGP=.FALSE.,KREQIN=YFORC_NL(JGFL)%NREQIN,&
       & PREFVALI=YFORC_NL(JGFL)%REFVALI, LDREQOUT=YFORC_NL(JGFL)%LREQOUT, &
       & LDERS=.FALSE.,LD5=.FALSE.,LDT1=.FALSE.)
      ! ----------------------------------------------------------------------
    ENDIF
  ENDDO

  ! Easy diagnostics
  DO JGFL=1,NGFL_EZDIAG
    IF(YEZDIAG_NL(JGFL)%LSP) THEN
      CALL ABOR1('SUGFL2: EZDIAG HAVE TO BE GRIDPOINT FIELDS')
      ! ----------------------------------------------------------------------
      ! what is below must be checked when spectral easy diag. will be coded!
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YEZDIAG=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NGFL_EZDIAG-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YEZDIAG(JGFL),CDNAME=YEZDIAG_NL(JGFL)%CNAME,&
       & KGRIB=YEZDIAG_NL(JGFL)%IGRBCODE,LDGP=.FALSE.,&
       & KREQIN=YEZDIAG_NL(JGFL)%NREQIN,&
       & PREFVALI=YEZDIAG_NL(JGFL)%REFVALI, LDREQOUT=YEZDIAG_NL(JGFL)%LREQOUT, &
       & LDERS=.FALSE.,LD5=.FALSE.,LDT1=.FALSE.)
      ! ----------------------------------------------------------------------
    ENDIF
  ENDDO

  ! Greenhouse Gases
  DO JGFL=1,NGHG
    IF(YGHG_NL(JGFL)%LSP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YGHG=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NGHG-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YGHG(JGFL),CDNAME=YGHG_NL(JGFL)%CNAME ,&
       & KGRIB=YGHG_NL(JGFL)%IGRBCODE, LDGP=.FALSE.,  KREQIN=YGHG_NL(JGFL)%NREQIN ,&
       & PREFVALI=YGHG_NL(JGFL)%REFVALI, LDREQOUT=YGHG_NL(JGFL)%LREQOUT ,&
       & LDERS=LADER, LD5=LL5, LDT1=LLT1)
    ENDIF
  ENDDO

  ! Chemical species 
  DO JGFL=1,NCHEM
    IF(YCHEM_NL(JGFL)%LSP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YCHEM=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NCHEM-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YCHEM(JGFL),CDNAME=YCHEM_NL(JGFL)%CNAME ,&
       & KGRIB=YCHEM_NL(JGFL)%IGRBCODE, LDGP=.FALSE.,  KREQIN=YCHEM_NL(JGFL)%NREQIN ,&
       & PREFVALI=YCHEM_NL(JGFL)%REFVALI, LDREQOUT=YCHEM_NL(JGFL)%LREQOUT ,&
       & LDERS=LADER, LD5=LL5, LDT1=LLT1)
    ENDIF
  ENDDO

  ! Aerosols
  DO JGFL=1,NAERO
    IF(YAERO_NL(JGFL)%LSP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YAERO=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NAERO-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YAERO(JGFL),CDNAME=YAERO_NL(JGFL)%CNAME ,&
       & KGRIB=YAERO_NL(JGFL)%IGRBCODE, LDGP=.FALSE.,  KREQIN=YAERO_NL(JGFL)%NREQIN ,&
       & PREFVALI=YAERO_NL(JGFL)%REFVALI, LDREQOUT=YAERO_NL(JGFL)%LREQOUT ,&
       & LDERS=LADER, LD5=LL5, LDT1=LLT1)
    ENDIF
  ENDDO

  ! ERA40 diagnostic fields
  DO JGFL=1,NERA40
    IF(YERA40_NL(JGFL)%LSP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YERA40=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NERA40-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL, YDCOMP=YGFL%YERA40(JGFL),CDNAME=YERA40_NL(JGFL)%CNAME ,&
       & KGRIB=YERA40_NL(JGFL)%IGRBCODE, LDGP=.FALSE.,  KREQIN=0 ,&
       & PREFVALI=YERA40_NL(JGFL)%REFVALI, LDREQOUT=YERA40_NL(JGFL)%LREQOUT ,&
       & LDERS=LADER, LD5=.FALSE., LDT1=.FALSE.)
    ENDIF
  ENDDO

  !-- NORO GWD SCHEME fields
  DO JGFL=1,NNOGW
    IF(YNOGW_NL(JGFL)%LSP) THEN
      CALL ABOR1('SUGFL2: NOGW HAVE TO BE GRIDPOINT FIELDS')
      ! ----------------------------------------------------------------------
      ! what is below must be checked when spectral NORO GWD scheme will be coded!
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YNOGW=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NNOGW-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YNOGW(JGFL),CDNAME=YNOGW_NL(JGFL)%CNAME,&
       & KGRIB=YNOGW_NL(JGFL)%IGRBCODE,LDGP=.FALSE.,&
       & KREQIN=YNOGW_NL(JGFL)%NREQIN,&
       & PREFVALI=YNOGW_NL(JGFL)%REFVALI, LDREQOUT=YNOGW_NL(JGFL)%LREQOUT, &
       & LDERS=.FALSE.,LD5=.FALSE.,LDT1=.FALSE.)
      ! ----------------------------------------------------------------------
    ENDIF
  ENDDO

  IF (LAERAOT .AND. NAERO > 0) THEN
    !-- NPAERAOT aerosol optical thickness fields
    DO JGFL=1,NPAERAOT
      IF(YAERAOT_NL(JGFL)%LSP) THEN
        CALL ABOR1('SUGFL2: AERAOT HAVE TO BE GRIDPOINT FIELDS')
        ! ----------------------------------------------------------------------
        ! what is below must be checked when spectral aerosol output will be coded!
        IF(JGFL == 1) THEN
          IGFLPTR=NUMFLDS+1
          YGFL%YAERAOT=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NPAERAOT-1)
        ENDIF
        CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YAERAOT(JGFL),CDNAME=YAERAOT_NL(JGFL)%CNAME,&
         & KGRIB=YAERAOT_NL(JGFL)%IGRBCODE,LDGP=.FALSE.,&
         & KREQIN=YAERAOT_NL(JGFL)%NREQIN,&
         & PREFVALI=YAERAOT_NL(JGFL)%REFVALI, LDREQOUT=YAERAOT_NL(JGFL)%LREQOUT, &
         & LDERS=.FALSE.,LD5=.FALSE.,LDT1=.FALSE.)
        ! ----------------------------------------------------------------------
      ENDIF
    ENDDO
  ENDIF

  IF (LAERLISI) THEN
    !-- NPAERLISI aerosol lidar simulator fields
    JGFL = 0
    DO JVAR=1,NPAERLISI_VAR
      DO JWVL=1,NPAERLISI_WVL
        JGFL = JGFL + 1
        IF(YAERLISI_NL(JWVL,JVAR)%LSP) THEN
          CALL ABOR1('SUGFL2: AERLISI HAVE TO BE GRIDPOINT FIELDS')
          ! ----------------------------------------------------------------------
          ! what is below must be checked when spectral aerosol output will be coded!
          IF(JGFL == 1) THEN
            IGFLPTR=NUMFLDS+1
            YGFL%YAERLISI=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NPAERLISI-1)
          ENDIF
          CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YAERLISI(JGFL),CDNAME=YAERLISI_NL(JWVL,JVAR)%CNAME,&
           & KGRIB=YAERLISI_NL(JWVL,JVAR)%IGRBCODE,LDGP=.FALSE.,&
           & KREQIN=YAERLISI_NL(JWVL,JVAR)%NREQIN,&
           & PREFVALI=YAERLISI_NL(JWVL,JVAR)%REFVALI, LDREQOUT=YAERLISI_NL(JWVL,JVAR)%LREQOUT, &
           & LDERS=.FALSE.,LD5=.FALSE.,LDT1=.FALSE.)
          ! ----------------------------------------------------------------------
        ENDIF
      ENDDO
    ENDDO
  ENDIF

  !-- NAEROUT aerosol output fields
  DO JGFL=1,NAEROUT
    IF(YAEROUT_NL(JGFL)%LSP) THEN
      CALL ABOR1('SUGFL2: AEROUT HAVE TO BE GRIDPOINT FIELDS')
      ! ----------------------------------------------------------------------
      ! what is below must be checked when spectral aerosol output will be coded!
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YAEROUT=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NAEROUT-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YAEROUT(JGFL),CDNAME=YAEROUT_NL(JGFL)%CNAME,&
       & KGRIB=YAEROUT_NL(JGFL)%IGRBCODE,LDGP=.FALSE.,&
       & KREQIN=YAEROUT_NL(JGFL)%NREQIN,&
       & PREFVALI=YAEROUT_NL(JGFL)%REFVALI, LDREQOUT=YAEROUT_NL(JGFL)%LREQOUT, &
       & LDERS=.FALSE.,LD5=.FALSE.,LDT1=.FALSE.)
      ! ----------------------------------------------------------------------
    ENDIF
  ENDDO

  !-- NAEROCLIM aerosol 3D input fields
  DO JGFL=1,NAEROCLIM
    IF(YAEROCLIM_NL(JGFL)%LSP) THEN
      CALL ABOR1('SUGFL2: AEROCLIM HAVE TO BE GRIDPOINT FIELDS')
      ! ----------------------------------------------------------------------
      ! what is below must be checked when spectral aerosol output will be
      ! coded!
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YAEROCLIM=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NAEROCLIM-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YAEROCLIM(JGFL),CDNAME=YAEROCLIM_NL(JGFL)%CNAME,&
       & KGRIB=YAEROCLIM_NL(JGFL)%IGRBCODE,LDGP=.FALSE.,&
       & KREQIN=YAEROCLIM_NL(JGFL)%NREQIN,&
       & PREFVALI=YAEROCLIM_NL(JGFL)%REFVALI, LDREQOUT=YAEROCLIM_NL(JGFL)%LREQOUT, &
       & LDERS=.FALSE.,LD5=.FALSE.,LDT1=.FALSE.)
      ! ----------------------------------------------------------------------
    ENDIF
  ENDDO


  !-- NUVP UV processor output fields
  DO JGFL=1,NUVP
    IF(YUVP_NL(JGFL)%LSP) THEN
      CALL ABOR1('SUGFL2: UVP HAVE TO BE GRIDPOINT FIELDS')
      ! ----------------------------------------------------------------------
      ! what is below must be checked when spectral UV processor output will be coded!
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YUVP=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NUVP-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YUVP(JGFL),CDNAME=YUVP_NL(JGFL)%CNAME,&
       & KGRIB=YUVP_NL(JGFL)%IGRBCODE,LDGP=.FALSE.,&
       & KREQIN=YUVP_NL(JGFL)%NREQIN,&
       & PREFVALI=YUVP_NL(JGFL)%REFVALI, LDREQOUT=YUVP_NL(JGFL)%LREQOUT, &
       & LDERS=.FALSE.,LD5=.FALSE.,LDT1=.FALSE.)
      ! ----------------------------------------------------------------------
    ENDIF
  ENDDO

  ! Semi-Lagrangian diagnostics
  DO JGFL=1,NSLDIA
    IF(YSLDIA_NL(JGFL)%LSP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YSLDIA=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NSLDIA-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YGFL,YDCOMP=YGFL%YSLDIA(JGFL),CDNAME=YSLDIA_NL(JGFL)%CNAME ,&
       & KGRIB=YSLDIA_NL(JGFL)%IGRBCODE, LDGP=.FALSE.,  KREQIN=0 ,&
       & PREFVALI=YSLDIA_NL(JGFL)%REFVALI, LDREQOUT=YSLDIA_NL(JGFL)%LREQOUT ,&
       & LDERS=.TRUE., LD5=.FALSE., LDT1=LLT1)
    ENDIF
  ENDDO

  ! LIMA fields
  DO JGFL=1,NLIMA
    IF(YLIMA_NL(JGFL)%LSP) THEN
      IF(JGFL == 1) THEN
        IGFLPTR=NUMFLDS+1
        YGFL%YLIMA=>YGFL%YCOMP(IGFLPTR:IGFLPTR+NLIMA-1)
      ENDIF
      CALL DEFINE_GFL_COMP(YDML_GCONF%YGFL, YDCOMP=YGFL%YLIMA(JGFL),CDNAME=YLIMA_NL(JGFL)%CNAME ,&
       & KGRIB=YLIMA_NL(JGFL)%IGRBCODE, LDGP=.FALSE.,  KREQIN=YLIMA_NL(JGFL)%NREQIN ,&
       & PREFVALI=YLIMA_NL(JGFL)%REFVALI, LDREQOUT=YLIMA_NL(JGFL)%LREQOUT ,&
       & LDERS=LADER, LD5=LL5, LDT1=LLT1, LDTHERMACT=.FALSE.,PR=0.0_JPRB,PRCP=RCW, &
       & LDWATER=.FALSE.,LDPRECIP=.FALSE.,PLZER=RLVZER)
    ENDIF
  ENDDO

!-------------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUGFL2',1,ZHOOK_HANDLE)
END SUBROUTINE SUGFL2
