SUBROUTINE VPOS_PREP(YDGMV,YGFL,YDIN_GFL,YDGFL,YDIN_GMV)

!****-------------------------------------------------------------------
!**** *VPOS_PREP* - Preparation for VPOS
!****-------------------------------------------------------------------
!     Purpose.   Preparation for VPOS: computes input quantities for VPOS
!     --------   

!**   Interface.
!     ----------
!        *CALL* *VPOS_PREP (..)

!        Explicit arguments :
!        --------------------  
!        OUTPUT:
!         YDIN_GFL  : Pointers allowing to retrieve individual fields in PGFL
!         YDGFL     : Says if GFL is active or not
!         YDIN_GMV  : Pointers allowing to retrieve individual fields in PGMV and PGMVS

!        Implicit arguments :  None.
!        --------------------

!     Method.
!     -------

!     Externals.   See includes below.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!        Karim YESSAD (after SCAN2M). August 2009

! Modifications
! -------------
!  K. Yessad (Dec 2011): various contributions.
!-----------------------------------------------------------------------------

USE YOMGMV   , ONLY : TGMV
USE PARKIND1 , ONLY : JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOM_YGFL , ONLY : TYPE_GFLD
USE TYPE_GFLFLDS, ONLY: TYPE_IGFLFLDD,TYPE_LGFLFLDD
USE TYPE_GMVS, ONLY: TYPE_T0
USE YOE_AERODIAG, ONLY : NPAERAOT, NPAERLISI

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(TGMV) , INTENT(IN) :: YDGMV
TYPE(TYPE_GFLD),INTENT(IN) :: YGFL
TYPE(TYPE_IGFLFLDD),INTENT(OUT)  :: YDIN_GFL
TYPE(TYPE_LGFLFLDD),INTENT(OUT)  :: YDGFL
TYPE(TYPE_T0)      ,INTENT(OUT)  :: YDIN_GMV
!     ------------------------------------------------------------------
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('VPOS_PREP',0,ZHOOK_HANDLE)
ASSOCIATE(NDIMGMV=>YDGMV%NDIMGMV, YT0=>YDGMV%YT0, &
 & YI=>YGFL%YI, YH=>YGFL%YH, YAERO=>YGFL%YAERO, &
 & YEZDIAG=>YGFL%YEZDIAG, YL=>YGFL%YL, YEXT=>YGFL%YEXT, YGHG=>YGFL%YGHG, &
 & YA=>YGFL%YA, YSRC=>YGFL%YSRC, YSPF=>YGFL%YSPF, YRKTQV=>YGFL%YRKTQV, &
 & YLMF=>YGFL%YLMF,  YIMF=>YGFL%YIMF,  YAMF=>YGFL%YAMF, &
 & YWMFC=>YGFL%YWMFC, YHLMF=>YGFL%YHLMF, YHLCFMF=>YGFL%YHLCFMF, YHIMF=>YGFL%YHIMF, YHICFMF=>YGFL%YHICFMF, &
 & YQVA=>YGFL%YQVA, YG=>YGFL%YG, NAEROUT=>YGFL%NAEROUT, NNOGW=>YGFL%NNOGW, &
 & YCVGQ=>YGFL%YCVGQ, NUVP=>YGFL%NUVP, YMXL=>YGFL%YMXL, YCHEM=>YGFL%YCHEM, &
 & YQ=>YGFL%YQ, YS=>YGFL%YS, YR=>YGFL%YR, YCPF=>YGFL%YCPF, &
 & YFORC=>YGFL%YFORC, NGFL_FORC=>YGFL%NGFL_FORC, YLRCH4=>YGFL%YLRCH4, &
 & YLRCH4_NL=>YGFL%YLRCH4_NL, &
 & NEMIS3D=>YGFL%NEMIS3D, YEMIS3D=>YGFL%YEMIS3D, &
 & NGHG=>YGFL%NGHG, YDOM=>YGFL%YDOM, &
 & YSLDIA=>YGFL%YSLDIA, YUNEBH=>YGFL%YUNEBH, YIRAD=>YGFL%YIRAD, YCVV=>YGFL%YCVV, &
 & YO3=>YGFL%YO3, NGFL_EXT=>YGFL%NGFL_EXT, YRKTQC=>YGFL%YRKTQC, YTKE=>YGFL%YTKE, &
 & YPHYCTY=>YGFL%YPHYCTY, NEDRP=>YGFL%NEDRP, YEDRP=>YGFL%YEDRP,&
 & YUOM=>YGFL%YUOM, YAERAOT=>YGFL%YAERAOT, YAERLISI=>YGFL%YAERLISI, &
 & YAEROUT=>YGFL%YAEROUT, YNOGW=>YGFL%YNOGW, &
 & NSLDIA=>YGFL%NSLDIA, YDAL=>YGFL%YDAL, NGFL_EZDIAG=>YGFL%NGFL_EZDIAG, &
 & NAERO=>YGFL%NAERO, YSHTUR=>YGFL%YSHTUR, NERA40=>YGFL%NERA40, YUEN=>YGFL%YUEN, &
 & YUAL=>YGFL%YUAL, YTTE=>YGFL%YTTE, YERA40=>YGFL%YERA40, NCHEM=>YGFL%NCHEM, &
 & YFQTUR=>YGFL%YFQTUR, &
 & YUVP=>YGFL%YUVP, YRKTH=>YGFL%YRKTH, YFSTUR=>YGFL%YFSTUR,&
 & YLRAD=>YGFL%YLRAD, YSDSAT=>YGFL%YSDSAT, YLCONV=>YGFL%YLCONV, YICONV=>YGFL%YICONV, &
 & YRCONV=>YGFL%YRCONV, YSCONV=>YGFL%YSCONV, LAERAOT=>YGFL%LAERAOT, LAERLISI=>YGFL%LAERLISI)

!     ------------------------------------------------------------------
!*       1.    COMPUTES YDIN_GFL.
!     ------------------------------------------------------------------

! * historical (advectable) variables:
YDIN_GFL%IQ=YQ%MP
YDIN_GFL%IQL=YQ%MPL
YDIN_GFL%IQM=YQ%MPM
YDIN_GFL%IL=YL%MP
YDIN_GFL%ILL=YL%MPL
YDIN_GFL%ILM=YL%MPM
YDIN_GFL%ILRAD=YLRAD%MP
YDIN_GFL%ILRADL=YLRAD%MPL
YDIN_GFL%ILRADM=YLRAD%MPM
YDIN_GFL%II=YI%MP
YDIN_GFL%IIL=YI%MPL
YDIN_GFL%IIM=YI%MPM
YDIN_GFL%IIRAD=YIRAD%MP
YDIN_GFL%IIRADL=YIRAD%MPL
YDIN_GFL%IIRADM=YIRAD%MPM
YDIN_GFL%IA=YA%MP
YDIN_GFL%IAL=YA%MPL
YDIN_GFL%IAM=YA%MPM
YDIN_GFL%IO3=YO3%MP
YDIN_GFL%IO3L=YO3%MPL
YDIN_GFL%IO3M=YO3%MPM
YDIN_GFL%IS=YS%MP
YDIN_GFL%ISL=YS%MPL
YDIN_GFL%ISM=YS%MPM
YDIN_GFL%IRR=YR%MP
YDIN_GFL%IRRL=YR%MPL
YDIN_GFL%IRRM=YR%MPM
YDIN_GFL%IG=YG%MP
YDIN_GFL%IGL=YG%MPL
YDIN_GFL%IGM=YG%MPM
YDIN_GFL%IH=YH%MP
YDIN_GFL%IHL=YH%MPL
YDIN_GFL%IHM=YH%MPM
YDIN_GFL%ITKE=YTKE%MP
YDIN_GFL%ITKEL=YTKE%MPL
YDIN_GFL%ITKEM=YTKE%MPM
YDIN_GFL%IPHYCTY=YPHYCTY%MP
IF (NAERO>0) YDIN_GFL%IAERO=YAERO(1)%MP
IF (NAERO>0) YDIN_GFL%IAEROL=YAERO(1)%MPL
IF (NAERO>0) YDIN_GFL%IAEROM=YAERO(1)%MPM
IF (NGFL_EXT>0) YDIN_GFL%IEXT=YEXT(1)%MP
IF (NGFL_EXT>0) YDIN_GFL%IEXTL=YEXT(1)%MPL
IF (NGFL_EXT>0) YDIN_GFL%IEXTM=YEXT(1)%MPM
! * other variables (irrelevant horizontal derivatives):
YDIN_GFL%IDAL=YDAL%MP
YDIN_GFL%IDOM=YDOM%MP
YDIN_GFL%IUAL=YUAL%MP
YDIN_GFL%IUOM=YUOM%MP
YDIN_GFL%ILCONV=YLCONV%MP
YDIN_GFL%IICONV=YICONV%MP
YDIN_GFL%IRCONV=YRCONV%MP
YDIN_GFL%ISCONV=YSCONV%MP
YDIN_GFL%IUEN=YUEN%MP
YDIN_GFL%IUNEBH=YUNEBH%MP
YDIN_GFL%ITTE=YTTE%MP
YDIN_GFL%IMXL=YMXL%MP
YDIN_GFL%ISHTUR=YSHTUR%MP
YDIN_GFL%IFQTUR=YFQTUR%MP
YDIN_GFL%IFSTUR=YFSTUR%MP
YDIN_GFL%IRKTH=YRKTH%MP
YDIN_GFL%IRKTQV=YRKTQV%MP
YDIN_GFL%IRKTQC=YRKTQC%MP
YDIN_GFL%ISRC=YSRC%MP
YDIN_GFL%ILMF=YLMF%MP
YDIN_GFL%IIMF=YIMF%MP
YDIN_GFL%IAMF=YAMF%MP
YDIN_GFL%IWMFC=YWMFC%MP
YDIN_GFL%IHLMF=YHLMF%MP
YDIN_GFL%IHLCFMF=YHLCFMF%MP
YDIN_GFL%IHIMF=YHIMF%MP
YDIN_GFL%IHICFMF=YHICFMF%MP
YDIN_GFL%ICPF=YCPF%MP
YDIN_GFL%ISPF=YSPF%MP
YDIN_GFL%ICVGQ=YCVGQ%MP
YDIN_GFL%ISDSAT=YSDSAT%MP
YDIN_GFL%ICVV=YCVV%MP
YDIN_GFL%IQVA=YQVA%MP
IF (NGHG>0 .AND. YLRCH4_NL%LGP) YDIN_GFL%ILRCH4=YLRCH4%MP
IF (NGFL_FORC>0) YDIN_GFL%IFORC=YFORC(1)%MP
IF (NGFL_EZDIAG>0) YDIN_GFL%IEZDIAG=YEZDIAG(1)%MP
IF (NEMIS3D>0) YDIN_GFL%IEMIS3D=YEMIS3D(1)%MP
IF (NGHG>0) YDIN_GFL%IGHG=YGHG(1)%MP
IF (NERA40>0) YDIN_GFL%IERA40=YERA40(1)%MP
IF (NNOGW>0) YDIN_GFL%INOGW=YNOGW(1)%MP
IF (NEDRP>0) YDIN_GFL%IEDRP=YEDRP(1)%MP
IF (LAERAOT .AND. NAERO>0) YDIN_GFL%IAERAOT=YAERAOT(1)%MP
IF (LAERLISI) YDIN_GFL%IAERLISI=YAERLISI(1)%MP
IF (NAEROUT>0) YDIN_GFL%IAEROUT=YAEROUT(1)%MP
IF (NUVP>0) YDIN_GFL%IUVP=YUVP(1)%MP
IF (NSLDIA>0) YDIN_GFL%ISLDIA=YSLDIA(1)%MP
IF (NCHEM>0) YDIN_GFL%ICHEM=YCHEM(1)%MP

!     ------------------------------------------------------------------
!*       2.    COMPUTES YDGFL.
!     ------------------------------------------------------------------

! * historical (advectable) variables:
YDGFL%LLQ=YQ%LACTIVE
YDGFL%LLQL=YQ%LCDERS
YDGFL%LLQM=YQ%LCDERS
YDGFL%LLL=YL%LACTIVE
YDGFL%LLLL=YL%LCDERS
YDGFL%LLLM=YL%LCDERS
YDGFL%LLLRAD=YLRAD%LACTIVE
YDGFL%LLLRADL=YLRAD%LCDERS
YDGFL%LLLRADM=YLRAD%LCDERS
YDGFL%LLI=YI%LACTIVE
YDGFL%LLIL=YI%LCDERS
YDGFL%LLIM=YI%LCDERS
YDGFL%LLIRAD=YIRAD%LACTIVE
YDGFL%LLIRADL=YIRAD%LCDERS
YDGFL%LLIRADM=YIRAD%LCDERS
YDGFL%LLA=YA%LACTIVE
YDGFL%LLAL=YA%LCDERS
YDGFL%LLAM=YA%LCDERS
YDGFL%LLO3=YO3%LACTIVE
YDGFL%LLO3L=YO3%LCDERS
YDGFL%LLO3M=YO3%LCDERS
YDGFL%LLS=YS%LACTIVE
YDGFL%LLSL=YS%LCDERS
YDGFL%LLSM=YS%LCDERS
YDGFL%LLRR=YR%LACTIVE
YDGFL%LLRRL=YR%LCDERS
YDGFL%LLRRM=YR%LCDERS
YDGFL%LLG=YG%LACTIVE
YDGFL%LLGL=YG%LCDERS
YDGFL%LLGM=YG%LCDERS
YDGFL%LLH=YH%LACTIVE
YDGFL%LLHL=YH%LCDERS
YDGFL%LLHM=YH%LCDERS
YDGFL%LLTKE=YTKE%LACTIVE
YDGFL%LLTKEL=YTKE%LCDERS
YDGFL%LLTKEM=YTKE%LCDERS
YDGFL%LLPHYCTY=YPHYCTY%LACTIVE
IF (NAERO>0) YDGFL%LLAERO(1:NAERO)=YAERO(1:NAERO)%LACTIVE
IF (NAERO>0) YDGFL%LLAEROL(1:NAERO)=YAERO(1:NAERO)%LCDERS
IF (NAERO>0) YDGFL%LLAEROM(1:NAERO)=YAERO(1:NAERO)%LCDERS
IF (NGFL_EXT>0) YDGFL%LLEXT(1:NGFL_EXT)=YEXT(1:NGFL_EXT)%LACTIVE
IF (NGFL_EXT>0) YDGFL%LLEXTL(1:NGFL_EXT)=YEXT(1:NGFL_EXT)%LCDERS
IF (NGFL_EXT>0) YDGFL%LLEXTM(1:NGFL_EXT)=YEXT(1:NGFL_EXT)%LCDERS
! * other variables (irrelevant horizontal derivatives):
YDGFL%LLDAL=YDAL%LACTIVE
YDGFL%LLDOM=YDOM%LACTIVE
YDGFL%LLUAL=YUAL%LACTIVE
YDGFL%LLUOM=YUOM%LACTIVE
YDGFL%LLLCONV=YLCONV%LACTIVE
YDGFL%LLICONV=YICONV%LACTIVE
YDGFL%LLRCONV=YRCONV%LACTIVE
YDGFL%LLSCONV=YSCONV%LACTIVE
YDGFL%LLUEN=YUEN%LACTIVE
YDGFL%LLUNEBH=YUNEBH%LACTIVE
YDGFL%LLTTE=YTTE%LACTIVE
YDGFL%LLMXL=YMXL%LACTIVE
YDGFL%LLSHTUR=YSHTUR%LACTIVE
YDGFL%LLFQTUR=YFQTUR%LACTIVE
YDGFL%LLFSTUR=YFSTUR%LACTIVE
YDGFL%LLRKTH=YRKTH%LACTIVE
YDGFL%LLRKTQV=YRKTQV%LACTIVE
YDGFL%LLRKTQC=YRKTQC%LACTIVE
YDGFL%LLSRC=YSRC%LACTIVE
YDGFL%LLLMF=YLMF%LACTIVE
YDGFL%LLIMF=YIMF%LACTIVE
YDGFL%LLAMF=YAMF%LACTIVE
YDGFL%LWMFC=YWMFC%LACTIVE
YDGFL%LHLMF=YHLMF%LACTIVE
YDGFL%LHLCFMF=YHLCFMF%LACTIVE
YDGFL%LHIMF=YHIMF%LACTIVE
YDGFL%LHICFMF=YHICFMF%LACTIVE
YDGFL%LLCPF=YCPF%LACTIVE
YDGFL%LLSPF=YSPF%LACTIVE
YDGFL%LLCVGQ=YCVGQ%LACTIVE
YDGFL%LLSDSAT=YSDSAT%LACTIVE
YDGFL%LLCVV=YCVV%LACTIVE
YDGFL%LLQVA=YQVA%LACTIVE
IF (NGHG>0 .AND. YLRCH4_NL%LGP) YDGFL%LLLRCH4=YLRCH4%LACTIVE
IF (NGFL_FORC>0) YDGFL%LLFORC(1:NGFL_FORC)=YFORC(1:NGFL_FORC)%LACTIVE
IF (NGFL_EZDIAG>0) YDGFL%LLEZDIAG(1:NGFL_EZDIAG)=YEZDIAG(1:NGFL_EZDIAG)%LACTIVE
IF (NEMIS3D>0) YDGFL%LLEMIS3D(1:NEMIS3D)=YEMIS3D(1:NEMIS3D)%LACTIVE
IF (NGHG>0) YDGFL%LLGHG(1:NGHG)=YGHG(1:NGHG)%LACTIVE
IF (NCHEM>0) YDGFL%LLCHEM(1:NCHEM)=YCHEM(1:NCHEM)%LACTIVE
IF (NERA40>0) YDGFL%LLERA40(1:NERA40)=YERA40(1:NERA40)%LACTIVE
IF (NNOGW>0) YDGFL%LLNOGW(1:NNOGW)=YNOGW(1:NNOGW)%LACTIVE
IF (NEDRP>0) YDGFL%LLEDRP(1:NEDRP)=YEDRP(1:NEDRP)%LACTIVE
IF (LAERAOT .AND. NAERO>0) YDGFL%LLAERAOT(1:NPAERAOT)=YAERAOT(1:NPAERAOT)%LACTIVE
IF (LAERLISI) YDGFL%LLAERLISI(1:NPAERLISI)=YAERLISI(1:NPAERLISI)%LACTIVE
IF (NAEROUT>0) YDGFL%LLAEROUT(1:NAEROUT)=YAEROUT(1:NAEROUT)%LACTIVE
IF (NUVP>0) YDGFL%LLUVP(1:NUVP)=YUVP(1:NUVP)%LACTIVE
IF (NSLDIA>0) YDGFL%LLSLDIA(1:NSLDIA)=YSLDIA(1:NSLDIA)%LACTIVE

!     ------------------------------------------------------------------
!*       3.    COMPUTES YDIN_GMV.
!     ------------------------------------------------------------------

YDIN_GMV=YT0
! Attributes of YDIN_GMV for GMV should have a value between 1 and NDIMGMV:
! ensure that pointers are between 1 and NDIMGMV for some conditionally allocated fields.
YDIN_GMV%MEDOT=MIN(NDIMGMV,MAX(1,YDIN_GMV%MEDOT))
YDIN_GMV%MUL=MIN(NDIMGMV,MAX(1,YDIN_GMV%MUL))
YDIN_GMV%MVL=MIN(NDIMGMV,MAX(1,YDIN_GMV%MVL))
YDIN_GMV%MVOR=MIN(NDIMGMV,MAX(1,YDIN_GMV%MVOR))
YDIN_GMV%MSPD=MIN(NDIMGMV,MAX(1,YDIN_GMV%MSPD))
YDIN_GMV%MSPDL=MIN(NDIMGMV,MAX(1,YDIN_GMV%MSPDL))
YDIN_GMV%MSPDM=MIN(NDIMGMV,MAX(1,YDIN_GMV%MSPDM))
YDIN_GMV%MSVD=MIN(NDIMGMV,MAX(1,YDIN_GMV%MSVD))
YDIN_GMV%MNHX=MIN(NDIMGMV,MAX(1,YDIN_GMV%MNHX))

!     ------------------------------------------------------------------
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('VPOS_PREP',1,ZHOOK_HANDLE)
END SUBROUTINE VPOS_PREP

