!     ######spl
      SUBROUTINE CH_ALLOCATE_TACCS(KMI,KVECNPT)
      USE PARKIND1, ONLY : JPRB
      USE YOMHOOK , ONLY : LHOOK, DR_HOOK
!     ######################################
!! This code has been created automatically by preprocessor m10,
!! version: 9.7, copyright 1995-1999 by Meteo France/Universite Paul Sabatier.
!! Please report all bugs to K. Suhre (Lab. d'Aerologie UPS/CNRS).
!!*** *CH_ALLOCATE_TACCS*
!!
!!    PURPOSE
!!    -------
!       Allocation of all CCSTYPE variables for model KMI
!!
!!**  METHOD
!!    ------
!!
!!   
!!
!!    REFERENCE
!!    ---------
!!    none
!!
!!    AUTHOR
!!    ------
!!    Gazen Didier (LA)
!!
!!    MODIFICATIONS
!!    -------------
!!    Original 21/06/2005
!!
!!----------------------------------------------------------------------
!!
!!    EXTERNAL
!!    --------
!!    none
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------
USE MODD_CH_M9_SCHEME
!!
!!    EXPLICIT ARGUMENTS
!!    ------------------
IMPLICIT NONE
INTEGER, INTENT(IN)  :: KMI    ! model index
INTEGER, INTENT(IN)  :: KVECNPT
!!
!!----------------------------------------------------------------------
! /BEGIN_INITIAL/
! /END_INITIAL/
! initialisation of the names of the chemical species
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('CH_ALLOCATE_TACCS',0,ZHOOK_HANDLE)
ALLOCATE(TACCS(KMI)%K001(KVECNPT))
ALLOCATE(TACCS(KMI)%K002(KVECNPT))
ALLOCATE(TACCS(KMI)%K003(KVECNPT))
ALLOCATE(TACCS(KMI)%K004(KVECNPT))
ALLOCATE(TACCS(KMI)%K005(KVECNPT))
ALLOCATE(TACCS(KMI)%K006(KVECNPT))
ALLOCATE(TACCS(KMI)%K007(KVECNPT))
ALLOCATE(TACCS(KMI)%K008(KVECNPT))
ALLOCATE(TACCS(KMI)%K009(KVECNPT))
ALLOCATE(TACCS(KMI)%K010(KVECNPT))
ALLOCATE(TACCS(KMI)%K011(KVECNPT))
ALLOCATE(TACCS(KMI)%K012(KVECNPT))
ALLOCATE(TACCS(KMI)%K013(KVECNPT))
ALLOCATE(TACCS(KMI)%K014(KVECNPT))
ALLOCATE(TACCS(KMI)%K015(KVECNPT))
ALLOCATE(TACCS(KMI)%K016(KVECNPT))
ALLOCATE(TACCS(KMI)%K017(KVECNPT))
ALLOCATE(TACCS(KMI)%K018(KVECNPT))
ALLOCATE(TACCS(KMI)%K019(KVECNPT))
ALLOCATE(TACCS(KMI)%K020(KVECNPT))
ALLOCATE(TACCS(KMI)%K021(KVECNPT))
ALLOCATE(TACCS(KMI)%K022(KVECNPT))
ALLOCATE(TACCS(KMI)%K023(KVECNPT))
ALLOCATE(TACCS(KMI)%K024(KVECNPT))
ALLOCATE(TACCS(KMI)%K025(KVECNPT))
ALLOCATE(TACCS(KMI)%K026(KVECNPT))
ALLOCATE(TACCS(KMI)%K027(KVECNPT))
ALLOCATE(TACCS(KMI)%K028(KVECNPT))
ALLOCATE(TACCS(KMI)%K029(KVECNPT))
ALLOCATE(TACCS(KMI)%K030(KVECNPT))
ALLOCATE(TACCS(KMI)%K031(KVECNPT))
ALLOCATE(TACCS(KMI)%K032(KVECNPT))
ALLOCATE(TACCS(KMI)%K033(KVECNPT))
ALLOCATE(TACCS(KMI)%K034(KVECNPT))
ALLOCATE(TACCS(KMI)%K035(KVECNPT))
ALLOCATE(TACCS(KMI)%K036(KVECNPT))
ALLOCATE(TACCS(KMI)%K037(KVECNPT))
ALLOCATE(TACCS(KMI)%K038(KVECNPT))
ALLOCATE(TACCS(KMI)%K039(KVECNPT))
ALLOCATE(TACCS(KMI)%K040(KVECNPT))
ALLOCATE(TACCS(KMI)%K041(KVECNPT))
ALLOCATE(TACCS(KMI)%K042(KVECNPT))
ALLOCATE(TACCS(KMI)%K043(KVECNPT))
ALLOCATE(TACCS(KMI)%K044(KVECNPT))
ALLOCATE(TACCS(KMI)%K045(KVECNPT))
ALLOCATE(TACCS(KMI)%K046(KVECNPT))
ALLOCATE(TACCS(KMI)%K047(KVECNPT))
ALLOCATE(TACCS(KMI)%K048(KVECNPT))
ALLOCATE(TACCS(KMI)%K049(KVECNPT))
ALLOCATE(TACCS(KMI)%K050(KVECNPT))
ALLOCATE(TACCS(KMI)%K051(KVECNPT))
ALLOCATE(TACCS(KMI)%K052(KVECNPT))
ALLOCATE(TACCS(KMI)%K053(KVECNPT))
ALLOCATE(TACCS(KMI)%K054(KVECNPT))
ALLOCATE(TACCS(KMI)%K055(KVECNPT))
ALLOCATE(TACCS(KMI)%K056(KVECNPT))
ALLOCATE(TACCS(KMI)%K057(KVECNPT))
ALLOCATE(TACCS(KMI)%K058(KVECNPT))
ALLOCATE(TACCS(KMI)%K059(KVECNPT))
ALLOCATE(TACCS(KMI)%K060(KVECNPT))
ALLOCATE(TACCS(KMI)%K061(KVECNPT))
ALLOCATE(TACCS(KMI)%K062(KVECNPT))
ALLOCATE(TACCS(KMI)%K063(KVECNPT))
ALLOCATE(TACCS(KMI)%K064(KVECNPT))
ALLOCATE(TACCS(KMI)%K065(KVECNPT))
ALLOCATE(TACCS(KMI)%K066(KVECNPT))
ALLOCATE(TACCS(KMI)%K067(KVECNPT))
ALLOCATE(TACCS(KMI)%K068(KVECNPT))
ALLOCATE(TACCS(KMI)%K069(KVECNPT))
ALLOCATE(TACCS(KMI)%K070(KVECNPT))
ALLOCATE(TACCS(KMI)%K071(KVECNPT))
ALLOCATE(TACCS(KMI)%K072(KVECNPT))
ALLOCATE(TACCS(KMI)%K073(KVECNPT))
ALLOCATE(TACCS(KMI)%K074(KVECNPT))
ALLOCATE(TACCS(KMI)%K075(KVECNPT))
ALLOCATE(TACCS(KMI)%K076(KVECNPT))
ALLOCATE(TACCS(KMI)%K077(KVECNPT))
ALLOCATE(TACCS(KMI)%K078(KVECNPT))
ALLOCATE(TACCS(KMI)%K079(KVECNPT))
ALLOCATE(TACCS(KMI)%K080(KVECNPT))
ALLOCATE(TACCS(KMI)%K081(KVECNPT))
ALLOCATE(TACCS(KMI)%K082(KVECNPT))
ALLOCATE(TACCS(KMI)%K083(KVECNPT))
ALLOCATE(TACCS(KMI)%K084(KVECNPT))
ALLOCATE(TACCS(KMI)%K085(KVECNPT))
ALLOCATE(TACCS(KMI)%K086(KVECNPT))
ALLOCATE(TACCS(KMI)%K087(KVECNPT))
ALLOCATE(TACCS(KMI)%K088(KVECNPT))
ALLOCATE(TACCS(KMI)%K089(KVECNPT))
ALLOCATE(TACCS(KMI)%K090(KVECNPT))
ALLOCATE(TACCS(KMI)%K091(KVECNPT))
ALLOCATE(TACCS(KMI)%K092(KVECNPT))
ALLOCATE(TACCS(KMI)%K093(KVECNPT))
ALLOCATE(TACCS(KMI)%K094(KVECNPT))
ALLOCATE(TACCS(KMI)%K095(KVECNPT))
ALLOCATE(TACCS(KMI)%K096(KVECNPT))
ALLOCATE(TACCS(KMI)%K097(KVECNPT))
ALLOCATE(TACCS(KMI)%K098(KVECNPT))
ALLOCATE(TACCS(KMI)%K099(KVECNPT))
ALLOCATE(TACCS(KMI)%K100(KVECNPT))
ALLOCATE(TACCS(KMI)%K101(KVECNPT))
ALLOCATE(TACCS(KMI)%K102(KVECNPT))
ALLOCATE(TACCS(KMI)%K103(KVECNPT))
ALLOCATE(TACCS(KMI)%K104(KVECNPT))
ALLOCATE(TACCS(KMI)%K105(KVECNPT))
ALLOCATE(TACCS(KMI)%K106(KVECNPT))
ALLOCATE(TACCS(KMI)%K107(KVECNPT))
ALLOCATE(TACCS(KMI)%K108(KVECNPT))
ALLOCATE(TACCS(KMI)%K109(KVECNPT))
ALLOCATE(TACCS(KMI)%K110(KVECNPT))
ALLOCATE(TACCS(KMI)%K111(KVECNPT))
ALLOCATE(TACCS(KMI)%K112(KVECNPT))
ALLOCATE(TACCS(KMI)%K113(KVECNPT))
ALLOCATE(TACCS(KMI)%K114(KVECNPT))
ALLOCATE(TACCS(KMI)%K115(KVECNPT))
ALLOCATE(TACCS(KMI)%K116(KVECNPT))
ALLOCATE(TACCS(KMI)%K117(KVECNPT))
ALLOCATE(TACCS(KMI)%K118(KVECNPT))
ALLOCATE(TACCS(KMI)%K119(KVECNPT))
ALLOCATE(TACCS(KMI)%K120(KVECNPT))
ALLOCATE(TACCS(KMI)%K121(KVECNPT))
ALLOCATE(TACCS(KMI)%K122(KVECNPT))
ALLOCATE(TACCS(KMI)%K123(KVECNPT))
ALLOCATE(TACCS(KMI)%K124(KVECNPT))
ALLOCATE(TACCS(KMI)%K125(KVECNPT))
ALLOCATE(TACCS(KMI)%K126(KVECNPT))
ALLOCATE(TACCS(KMI)%K127(KVECNPT))
ALLOCATE(TACCS(KMI)%K128(KVECNPT))
ALLOCATE(TACCS(KMI)%NOUT(KVECNPT))
ALLOCATE(TACCS(KMI)%NVERB(KVECNPT))
ALLOCATE(TACCS(KMI)%MODELLEVEL(KVECNPT))
ALLOCATE(TACCS(KMI)%T(KVECNPT))
ALLOCATE(TACCS(KMI)%PRESSURE(KVECNPT))
ALLOCATE(TACCS(KMI)%M(KVECNPT))
ALLOCATE(TACCS(KMI)%H2O(KVECNPT))
ALLOCATE(TACCS(KMI)%CLOUDWATER(KVECNPT))
ALLOCATE(TACCS(KMI)%O2(KVECNPT))
ALLOCATE(TACCS(KMI)%N2(KVECNPT))
ALLOCATE(TACCS(KMI)%H2(KVECNPT))
ALLOCATE(TACCS(KMI)%OH(KVECNPT))
ALLOCATE(TACCS(KMI)%O1D(KVECNPT))
ALLOCATE(TACCS(KMI)%O3P(KVECNPT))
ALLOCATE(TACCS(KMI)%LAT(KVECNPT))
ALLOCATE(TACCS(KMI)%LON(KVECNPT))
ALLOCATE(TACCS(KMI)%YEAR(KVECNPT))
ALLOCATE(TACCS(KMI)%MONTH(KVECNPT))
ALLOCATE(TACCS(KMI)%DAY(KVECNPT))
IF (LHOOK) CALL DR_HOOK('CH_ALLOCATE_TACCS',1,ZHOOK_HANDLE)
END SUBROUTINE CH_ALLOCATE_TACCS
