MODULE MODI_ICE4_TENDENCIES
INTERFACE
SUBROUTINE ICE4_TENDENCIES(KPROMA,KSIZE, KIB, KIE, KIT, KJB, KJE, KJT, KKB, KKE, KKT, KKL, &
                          &KRR, LDSOFT, PCOMPUTE, &
                          &OWARM, HSUBG_RC_RR_ACCR, HSUBG_RR_EVAP, HSUBG_AUCV_RC, HSUBG_PR_PDF, &
                          &PEXN, PRHODREF, PLVFACT, PLSFACT, K1, K2, K3, &
                          &PPRES, PCF, PSIGMA_RC, &
                          &PCIT, &
                          &PT, PVART, &
                          &PRRT3D, &
                          &PRVHENI_MR, PRRHONG_MR, PRIMLTC_MR, PRSRIMCG_MR, &
                          &PRCHONI, PRVDEPS, PRIAGGS, PRIAUTS, PRVDEPG, &
                          &PRCAUTR, PRCACCR, PRREVAV, &
                          &PRCRIMSS, PRCRIMSG, PRSRIMCG, PRRACCSS, PRRACCSG, PRSACCRG, PRSMLTG, PRCMLTSR, &
                          &PRICFRRG, PRRCFRIG, PRICFRR, PRCWETG, PRIWETG, PRRWETG, PRSWETG, &
                          &PRCDRYG, PRIDRYG, PRRDRYG, PRSDRYG, PRWETGH, PRWETGH_MR, PRGMLTR, &
                          &PRCWETH, PRIWETH, PRSWETH, PRGWETH, PRRWETH, &
                          &PRCDRYH, PRIDRYH, PRSDRYH, PRRDRYH, PRGDRYH, PRDRYHG, PRHMLTR, &
                          &PRCBERI, &
                          &PRS_TEND, PRG_TEND, PRH_TEND, PSSI, &
                          &PA, PB, &
                          &PHLC_HCF, PHLC_LCF, PHLC_HRC, PHLC_LRC)
IMPLICIT NONE
INTEGER,                      INTENT(IN)    :: KPROMA,KSIZE, KIB, KIE, KIT, KJB, KJE, KJT, KKB, KKE, KKT, KKL
INTEGER,                      INTENT(IN)    :: KRR
LOGICAL,                      INTENT(IN)    :: LDSOFT
REAL, DIMENSION(KPROMA),      INTENT(IN)    :: PCOMPUTE
LOGICAL,                      INTENT(IN)    :: OWARM
CHARACTER*80,                 INTENT(IN)    :: HSUBG_RC_RR_ACCR
CHARACTER*80,                 INTENT(IN)    :: HSUBG_RR_EVAP
CHARACTER(len=4),             INTENT(IN)    :: HSUBG_AUCV_RC
CHARACTER*80,                 INTENT(IN)    :: HSUBG_PR_PDF ! pdf for subgrid precipitation
REAL, DIMENSION(KPROMA),      INTENT(IN)    :: PEXN
REAL, DIMENSION(KPROMA),      INTENT(IN)    :: PRHODREF
REAL, DIMENSION(KPROMA),      INTENT(IN)    :: PLVFACT
REAL, DIMENSION(KPROMA),      INTENT(IN)    :: PLSFACT
INTEGER, DIMENSION(KPROMA),   INTENT(IN)    :: K1
INTEGER, DIMENSION(KPROMA),   INTENT(IN)    :: K2
INTEGER, DIMENSION(KPROMA),   INTENT(IN)    :: K3
REAL, DIMENSION(KPROMA),      INTENT(IN)    :: PPRES
REAL, DIMENSION(KPROMA),      INTENT(IN)    :: PCF
REAL, DIMENSION(KPROMA),      INTENT(IN)    :: PSIGMA_RC
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PCIT
REAL, DIMENSION(KPROMA),      INTENT(IN)    :: PT
REAL, DIMENSION(KPROMA,0:KRR),INTENT(IN)    :: PVART
REAL, DIMENSION(KIT,KJT,KKT), INTENT(IN)    :: PRRT3D
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRVHENI_MR
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRRHONG_MR
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRIMLTC_MR
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRSRIMCG_MR
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRCHONI
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRVDEPS
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRIAGGS
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRIAUTS
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRVDEPG
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRCAUTR
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRCACCR
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRREVAV
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRCRIMSS
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRCRIMSG
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRSRIMCG
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRRACCSS
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRRACCSG
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRSACCRG
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRSMLTG
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRCMLTSR
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRICFRRG
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRRCFRIG
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRICFRR
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRCWETG
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRIWETG
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRRWETG
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRSWETG
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRCDRYG
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRIDRYG
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRRDRYG
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRSDRYG
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRWETGH
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRWETGH_MR
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRGMLTR
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRCWETH
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRIWETH
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRSWETH
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRGWETH
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRRWETH
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRCDRYH
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRIDRYH
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRSDRYH
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRRDRYH
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRGDRYH
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRDRYHG
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRHMLTR
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PRCBERI
REAL, DIMENSION(KPROMA, 8),   INTENT(INOUT) :: PRS_TEND
REAL, DIMENSION(KPROMA, 8),   INTENT(INOUT) :: PRG_TEND
REAL, DIMENSION(KPROMA, 10),  INTENT(INOUT) :: PRH_TEND
REAL, DIMENSION(KPROMA),      INTENT(INOUT) :: PSSI
REAL, DIMENSION(KPROMA,0:KRR),INTENT(OUT)   :: PA
REAL, DIMENSION(KPROMA,0:KRR),INTENT(OUT)   :: PB
REAL, DIMENSION(KPROMA),      INTENT(OUT)   :: PHLC_HCF
REAL, DIMENSION(KPROMA),      INTENT(OUT)   :: PHLC_LCF
REAL, DIMENSION(KPROMA),      INTENT(OUT)   :: PHLC_HRC
REAL, DIMENSION(KPROMA),      INTENT(OUT)   :: PHLC_LRC
END SUBROUTINE ICE4_TENDENCIES
END INTERFACE
END MODULE MODI_ICE4_TENDENCIES
