!     ######spl
MODULE MODI_TIWMX
!      ####################
!
INTERFACE
FUNCTION TIWMX_TAB(P,T,QR,FICE,QRSN,RS,EPS)
  REAL,  INTENT(IN)           :: P,T,QR,FICE,EPS
  REAL,  INTENT(OUT)          :: QRSN,RS
END FUNCTION TIWMX_TAB
END INTERFACE
END MODULE MODI_TIWMX
