!     ######spl
      MODULE MODI_READ_XKER_RACCS 
!     ###########################
!
INTERFACE
      SUBROUTINE READ_XKER_RACCS (KACCLBDAS,KACCLBDAR,KND,                     &
                      PALPHAS,PNUS,PALPHAR,PNUR,PESR,PBS,PBR,PCS,PDS,PCR,PDR,  &
                      PACCLBDAS_MAX,PACCLBDAR_MAX,PACCLBDAS_MIN,PACCLBDAR_MIN, &
                      PFDINFTY,PKER_RACCSS,PKER_RACCS,PKER_SACCRG              )
!
INTEGER, INTENT(OUT) :: KND,KACCLBDAS,KACCLBDAR
REAL,    INTENT(OUT) :: PALPHAS
REAL,    INTENT(OUT) :: PNUS
REAL,    INTENT(OUT) :: PALPHAR
REAL,    INTENT(OUT) :: PNUR
REAL,    INTENT(OUT) :: PESR
REAL,    INTENT(OUT) :: PBS
REAL,    INTENT(OUT) :: PBR
REAL,    INTENT(OUT) :: PCS
REAL,    INTENT(OUT) :: PDS
REAL,    INTENT(OUT) :: PCR
REAL,    INTENT(OUT) :: PDR
REAL,    INTENT(OUT) :: PACCLBDAS_MAX
REAL,    INTENT(OUT) :: PACCLBDAR_MAX
REAL,    INTENT(OUT) :: PACCLBDAS_MIN
REAL,    INTENT(OUT) :: PACCLBDAR_MIN
REAL,    INTENT(OUT) :: PFDINFTY
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PKER_RACCSS
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PKER_RACCS 
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PKER_SACCRG
!
END SUBROUTINE READ_XKER_RACCS
!
END INTERFACE
!
END MODULE MODI_READ_XKER_RACCS
