!     ######spl
      MODULE MODI_READ_XKER_RWETH
!     ###########################
!
INTERFACE
      SUBROUTINE READ_XKER_RWETH (KWETLBDAH,KWETLBDAR,KND,                   &
                    PALPHAH,PNUH,PALPHAR,PNUR,PEHR,PBR,PCH,PDH,PCR,PDR,      &
                    PWETLBDAH_MAX,PWETLBDAR_MAX,PWETLBDAH_MIN,PWETLBDAR_MIN, &
                    PFDINFTY,PKER_RWETH                                      )
!
IMPLICIT NONE
INTEGER, INTENT(OUT) :: KND,KWETLBDAH,KWETLBDAR
REAL,    INTENT(OUT) :: PALPHAH
REAL,    INTENT(OUT) :: PNUH
REAL,    INTENT(OUT) :: PALPHAR
REAL,    INTENT(OUT) :: PNUR
REAL,    INTENT(OUT) :: PEHR
REAL,    INTENT(OUT) :: PBR
REAL,    INTENT(OUT) :: PCH
REAL,    INTENT(OUT) :: PDH
REAL,    INTENT(OUT) :: PCR
REAL,    INTENT(OUT) :: PDR
REAL,    INTENT(OUT) :: PWETLBDAH_MAX
REAL,    INTENT(OUT) :: PWETLBDAR_MAX
REAL,    INTENT(OUT) :: PWETLBDAH_MIN
REAL,    INTENT(OUT) :: PWETLBDAR_MIN
REAL,    INTENT(OUT) :: PFDINFTY
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PKER_RWETH
!
END SUBROUTINE 
!
END INTERFACE
!
END MODULE MODI_READ_XKER_RWETH
