!     ######spl
       MODULE MODI_ICECLOUD
!      ####################
!
INTERFACE
SUBROUTINE ICECLOUD  &
     & ( NP,PP,PZ,PDZ,PT,PR,PTSTEP,PPBLH,PWCLD,XW2D, &
     &  SIFRC,SSIO,SSIU,W2D,RSI)
INTEGER, INTENT(IN) ::     NP
REAL,  INTENT(IN)  ::      PP(NP)
REAL,  INTENT(IN)  ::      PZ(NP)
REAL,  INTENT(IN)  ::      PDZ(NP)
REAL,  INTENT(IN)  ::      PT(NP)
REAL,  INTENT(IN)  ::      PR(NP)
REAL,  INTENT(IN)  ::      PTSTEP
REAL,  INTENT(IN)  ::      PPBLH
REAL,  INTENT(IN)  ::      PWCLD(NP)
REAL,  INTENT(IN)  ::      XW2D
REAL,  INTENT(OUT) ::      SIFRC(NP)
REAL,  INTENT(OUT) ::      SSIO(NP)
REAL,  INTENT(OUT) ::      SSIU(NP)
REAL,  INTENT(OUT) ::      W2D(NP)
REAL,  INTENT(OUT) ::      RSI(NP)
END SUBROUTINE ICECLOUD
END INTERFACE
END MODULE MODI_ICECLOUD
