!     ######spl
      MODULE MODI_READ_XKER_SDRYG
!     ###########################
!
INTERFACE
      SUBROUTINE READ_XKER_SDRYG (KDRYLBDAG,KDRYLBDAS,KND,                   &
                    PALPHAG,PNUG,PALPHAS,PNUS,PEGS,PBS,PCG,PDG,PCS,PDS,      &
                    PDRYLBDAG_MAX,PDRYLBDAS_MAX,PDRYLBDAG_MIN,PDRYLBDAS_MIN, &
                    PFDINFTY,PKER_SDRYG                                      )
!
INTEGER, INTENT(OUT) :: KND,KDRYLBDAG,KDRYLBDAS
REAL,    INTENT(OUT) :: PALPHAG
REAL,    INTENT(OUT) :: PNUG
REAL,    INTENT(OUT) :: PALPHAS
REAL,    INTENT(OUT) :: PNUS
REAL,    INTENT(OUT) :: PEGS
REAL,    INTENT(OUT) :: PBS
REAL,    INTENT(OUT) :: PCG
REAL,    INTENT(OUT) :: PDG
REAL,    INTENT(OUT) :: PCS
REAL,    INTENT(OUT) :: PDS
REAL,    INTENT(OUT) :: PDRYLBDAG_MAX
REAL,    INTENT(OUT) :: PDRYLBDAS_MAX
REAL,    INTENT(OUT) :: PDRYLBDAG_MIN
REAL,    INTENT(OUT) :: PDRYLBDAS_MIN
REAL,    INTENT(OUT) :: PFDINFTY
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PKER_SDRYG 
!
END SUBROUTINE READ_XKER_SDRYG
!
END INTERFACE
!
END MODULE MODI_READ_XKER_SDRYG
