!     ######spl
      MODULE MODI_READ_XKER_GWETH
!     ###########################
!
INTERFACE
      SUBROUTINE READ_XKER_GWETH (KWETLBDAH,KWETLBDAG,KND,                   &
                    PALPHAH,PNUH,PALPHAG,PNUG,PEHG,PBG,PCH,PDH,PCG,PDG,      &
                    PWETLBDAH_MAX,PWETLBDAG_MAX,PWETLBDAH_MIN,PWETLBDAG_MIN, &
                    PFDINFTY,PKER_GWETH                                      )
!
INTEGER, INTENT(OUT) :: KND,KWETLBDAH,KWETLBDAG
REAL,    INTENT(OUT) :: PALPHAH
REAL,    INTENT(OUT) :: PNUH
REAL,    INTENT(OUT) :: PALPHAG
REAL,    INTENT(OUT) :: PNUG
REAL,    INTENT(OUT) :: PEHG
REAL,    INTENT(OUT) :: PBG
REAL,    INTENT(OUT) :: PCH
REAL,    INTENT(OUT) :: PDH
REAL,    INTENT(OUT) :: PCG
REAL,    INTENT(OUT) :: PDG
REAL,    INTENT(OUT) :: PWETLBDAH_MAX
REAL,    INTENT(OUT) :: PWETLBDAG_MAX
REAL,    INTENT(OUT) :: PWETLBDAH_MIN
REAL,    INTENT(OUT) :: PWETLBDAG_MIN
REAL,    INTENT(OUT) :: PFDINFTY
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PKER_GWETH 
!
END SUBROUTINE READ_XKER_GWETH
!
END INTERFACE
!
END MODULE MODI_READ_XKER_GWETH
