!     ######spl
      MODULE MODI_READ_XKER_SWETH
!     ###########################
!
INTERFACE
      SUBROUTINE READ_XKER_SWETH (KWETLBDAH,KWETLBDAS,KND,                   &
                    PALPHAH,PNUH,PALPHAS,PNUS,PEHS,PBS,PCH,PDH,PCS,PDS,      &
                    PWETLBDAH_MAX,PWETLBDAS_MAX,PWETLBDAH_MIN,PWETLBDAS_MIN, &
                    PFDINFTY,PKER_SWETH                                      )
!
INTEGER, INTENT(OUT) :: KND,KWETLBDAH,KWETLBDAS
REAL,    INTENT(OUT) :: PALPHAH
REAL,    INTENT(OUT) :: PNUH
REAL,    INTENT(OUT) :: PALPHAS
REAL,    INTENT(OUT) :: PNUS
REAL,    INTENT(OUT) :: PEHS
REAL,    INTENT(OUT) :: PBS
REAL,    INTENT(OUT) :: PCH
REAL,    INTENT(OUT) :: PDH
REAL,    INTENT(OUT) :: PCS
REAL,    INTENT(OUT) :: PDS
REAL,    INTENT(OUT) :: PWETLBDAH_MAX
REAL,    INTENT(OUT) :: PWETLBDAS_MAX
REAL,    INTENT(OUT) :: PWETLBDAH_MIN
REAL,    INTENT(OUT) :: PWETLBDAS_MIN
REAL,    INTENT(OUT) :: PFDINFTY
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PKER_SWETH 
!
END SUBROUTINE READ_XKER_SWETH
!
END INTERFACE
!
END MODULE MODI_READ_XKER_SWETH
