!     ######spl
      MODULE MODI_READ_XKER_RDRYG
!     ###########################
!
INTERFACE
      SUBROUTINE READ_XKER_RDRYG (KDRYLBDAG,KDRYLBDAR,KND,                   &
                    PALPHAG,PNUG,PALPHAR,PNUR,PEGR,PBR,PCG,PDG,PCR,PDR,      &
                    PDRYLBDAG_MAX,PDRYLBDAR_MAX,PDRYLBDAG_MIN,PDRYLBDAR_MIN, &
                    PFDINFTY,PKER_RDRYG                                      )
!
INTEGER, INTENT(OUT) :: KND,KDRYLBDAG,KDRYLBDAR
REAL,    INTENT(OUT) :: PALPHAG
REAL,    INTENT(OUT) :: PNUG
REAL,    INTENT(OUT) :: PALPHAR
REAL,    INTENT(OUT) :: PNUR
REAL,    INTENT(OUT) :: PEGR
REAL,    INTENT(OUT) :: PBR
REAL,    INTENT(OUT) :: PCG
REAL,    INTENT(OUT) :: PDG
REAL,    INTENT(OUT) :: PCR
REAL,    INTENT(OUT) :: PDR
REAL,    INTENT(OUT) :: PDRYLBDAG_MAX
REAL,    INTENT(OUT) :: PDRYLBDAR_MAX
REAL,    INTENT(OUT) :: PDRYLBDAG_MIN
REAL,    INTENT(OUT) :: PDRYLBDAR_MIN
REAL,    INTENT(OUT) :: PFDINFTY
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PKER_RDRYG 
!
END SUBROUTINE READ_XKER_RDRYG
!
END INTERFACE
!
END MODULE MODI_READ_XKER_RDRYG
