!     ######spl
 MODULE MODI_MASK_COMPRESS
!#########################
!
INTERFACE
!
FUNCTION MASK_COMPRESS(PVARS) RESULT(PCOMPRESS)
!
USE MODD_BUDGET
!
REAL, DIMENSION(:,:,:), INTENT(IN) :: PVARS     ! Source 
REAL, DIMENSION(NBUKMAX,NBUMASK)   :: PCOMPRESS ! result
!
END FUNCTION MASK_COMPRESS
!
END INTERFACE
!
END MODULE MODI_MASK_COMPRESS
