INTERFACE
 SUBROUTINE ARO_RAIN_ICE(CST, PARAM_ICEN, RAIN_ICE_PARAMN, RAIN_ICE_DESCRN, CLOUDPARN, TURBN, &
 & KKA,KKU,KKL,KLON,KLEV, KFDIA,KRR, KTCOUNT,&
 & CMICRO,&
 & PTSTEP, PDZZ, PRHODJ, PRHODREF, PEXNREF,&
 & PPABSM, PHLC_HRC, PHLC_HCF, PHLI_HRI, PHLI_HCF, PTHT, PRT, PSIGS,PCLDFR,&
 & PTHS, PRS, PEVAP,&
 & PCIT, PSEA, PTOWN, &
 & PICLDFR, PWCLDFR, PSSIO, PSSIU, PIFR,  &
 & LKOGAN, LMODICEDEP,&
 & PINPRR,PINPRS,&
 & PINPRG,PINPRH,PFPR,&
 & YDDDH,YDLDDH,YDMDDH,&
 & YSPP_ICENU,YSPP_KGN_ACON,YSPP_KGN_SBGR)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE DDH_MIX, ONLY : TYP_DDH
USE SPP_MOD_TYPE, ONLY : TSPP_CONFIG_TYPE
USE YOMLDDH, ONLY : TLDDH
USE YOMMDDH, ONLY : TMDDH
USE MODD_CST, ONLY: CST_t
USE MODD_RAIN_ICE_DESCR_n, ONLY: RAIN_ICE_DESCR_t
USE MODD_RAIN_ICE_PARAM_n, ONLY: RAIN_ICE_PARAM_t
USE MODD_PARAM_ICE_n,      ONLY: PARAM_ICE_t
USE MODD_CLOUDPAR_N,     ONLY: CLOUDPAR_t
USE MODD_TURB_n,         ONLY: TURB_t
TYPE(CST_t),            INTENT(IN) :: CST
TYPE(PARAM_ICE_t),      INTENT(IN) :: PARAM_ICEN
TYPE(RAIN_ICE_PARAM_t), INTENT(IN) :: RAIN_ICE_PARAMN
TYPE(RAIN_ICE_DESCR_t), INTENT(IN) :: RAIN_ICE_DESCRN
TYPE(CLOUDPAR_t),       INTENT(IN) :: CLOUDPARN
TYPE(TURB_t),           INTENT(IN) :: TURBN
INTEGER(KIND=JPIM), INTENT(IN) :: KKA
INTEGER(KIND=JPIM), INTENT(IN) :: KKU
INTEGER(KIND=JPIM), INTENT(IN) :: KKL
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KRR
INTEGER(KIND=JPIM), INTENT(IN) :: KTCOUNT
CHARACTER(LEN=4), INTENT(IN) :: CMICRO
REAL(KIND=JPRB), INTENT(IN) :: PTSTEP
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PDZZ
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PRHODJ
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PRHODREF
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PEXNREF
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PPABSM
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(INOUT) :: PHLC_HRC
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(INOUT) :: PHLC_HCF
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(INOUT) :: PHLI_HRI
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(INOUT) :: PHLI_HCF
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PTHT
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV,KRR), INTENT(INOUT):: PRT
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PSIGS
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PCLDFR
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(INOUT) :: PTHS
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV,KRR), INTENT(INOUT) :: PRS
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(INOUT) :: PEVAP
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(INOUT) :: PCIT
REAL(KIND=JPRB), DIMENSION(KLON,1), INTENT(IN)    :: PSEA
REAL(KIND=JPRB), DIMENSION(KLON,1), INTENT(IN)    :: PTOWN
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV),   INTENT(IN)  :: PICLDFR 
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV),   INTENT(IN)  :: PWCLDFR 
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV),   INTENT(IN)  :: PSSIO   
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV),   INTENT(IN)  :: PSSIU   
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV),   INTENT(IN)  :: PIFR
LOGICAL, INTENT(IN) :: LKOGAN
LOGICAL, INTENT(IN) :: LMODICEDEP
REAL(KIND=JPRB), DIMENSION(KLON,1), INTENT(INOUT) :: PINPRR
REAL(KIND=JPRB), DIMENSION(KLON,1), INTENT(INOUT) :: PINPRS
REAL(KIND=JPRB), DIMENSION(KLON,1), INTENT(INOUT) :: PINPRG
REAL(KIND=JPRB), DIMENSION(KLON,1), INTENT(INOUT) :: PINPRH
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV,KRR), INTENT(INOUT) :: PFPR
TYPE(TYP_DDH),                       INTENT(INOUT) :: YDDDH
TYPE(TLDDH),                         INTENT(IN) :: YDLDDH
TYPE(TMDDH),                         INTENT(IN) :: YDMDDH
TYPE(TSPP_CONFIG_TYPE), INTENT(INOUT) :: YSPP_ICENU,YSPP_KGN_ACON,YSPP_KGN_SBGR
END SUBROUTINE ARO_RAIN_ICE
END INTERFACE
