INTERFACE
SUBROUTINE ARO_ADJUST_LIMA(PHYEX, &
 & KKA,KKU,KKL,KLON,KLEV,KIDIA,KFDIA, KRR, KSV, KTCOUNT,&
 & OSUBG_COND, OSIGMAS,&
 & PTSTEP, PSIGQSAT,&
 & PZZF, PRHODJ, PRHODREF, PEXNREF,&
 & PPABSM, PTHT, PRT, PSVT, PSIGS,&
 & PW_NU, PDTHRAD,&
 & PMFCONV, PRC_MF, PRI_MF, PCF_MF, PWEIGHT_MF_CLOUD, &
 & PTHS, PRS, PSVS, PSRCS, PCLDFR, PICEFR, PPRCFR, &
 & YDDDH,YDLDDH,YDMDDH, LLIMAINIT, &
 & PHLC_HRC, PHLC_HCF, PHLI_HRI, PHLI_HCF, &
 & PHLC_HRC_MF, PHLC_HCF_MF, PHLI_HRI_MF, PHLI_HCF_MF ) 
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE DDH_MIX, ONLY : TYP_DDH
USE YOMLDDH, ONLY : TLDDH
USE YOMMDDH, ONLY : TMDDH
USE MODD_PHYEX, ONLY: PHYEX_t
TYPE(PHYEX_t),      INTENT(IN) :: PHYEX
INTEGER(KIND=JPIM), INTENT(IN) :: KKA
INTEGER(KIND=JPIM), INTENT(IN) :: KKU
INTEGER(KIND=JPIM), INTENT(IN) :: KKL
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KRR
INTEGER(KIND=JPIM), INTENT(IN) :: KSV
INTEGER(KIND=JPIM), INTENT(IN) :: KTCOUNT
LOGICAL, INTENT(IN) :: OSUBG_COND
LOGICAL, INTENT(IN) :: OSIGMAS
REAL(KIND=JPRB), INTENT(IN) :: PTSTEP
REAL(KIND=JPRB), INTENT(IN) :: PSIGQSAT
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PZZF
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PRHODJ
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PRHODREF
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PEXNREF
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PPABSM
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PTHT
REAL(KIND=JPRB), DIMENSION(KLON,KLEV,KRR), INTENT(INOUT) :: PRT
REAL(KIND=JPRB), DIMENSION(KLON,KLEV,KSV), INTENT(INOUT) :: PSVT
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PSIGS
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN)   :: PW_NU
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN)   :: PDTHRAD
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PMFCONV
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PRC_MF,PRI_MF,PCF_MF,PWEIGHT_MF_CLOUD
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(INOUT) :: PTHS
REAL(KIND=JPRB), DIMENSION(KLON,KLEV,KRR), INTENT(INOUT) :: PRS
REAL(KIND=JPRB), DIMENSION(KLON,KLEV,KSV), INTENT(INOUT) :: PSVS
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(OUT) :: PSRCS
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(INOUT) :: PCLDFR
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(INOUT) :: PICEFR
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(INOUT) :: PPRCFR
TYPE(TYP_DDH), INTENT(INOUT) :: YDDDH
TYPE(TLDDH), INTENT(IN) :: YDLDDH
TYPE(TMDDH), INTENT(IN) :: YDMDDH
LOGICAL, INTENT(IN)    :: LLIMAINIT
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(OUT)   :: PHLC_HRC
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(OUT)   :: PHLC_HCF
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(OUT)   :: PHLI_HRI
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(OUT)   :: PHLI_HCF
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN)    :: PHLC_HRC_MF
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN)    :: PHLC_HCF_MF
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN)    :: PHLI_HRI_MF
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN)    :: PHLI_HCF_MF
END SUBROUTINE ARO_ADJUST_LIMA
END INTERFACE
