INTERFACE
SUBROUTINE ARO_LIMA(PHYEX,KKA,KKU,KKL,KLON,KLEV,KIDIA, KFDIA, KRR, KSV, &
 & PTSTEP, PDZZ, PRHODJ, PRHODREF, PEXNREF,&
 & PPABSM, PW_NU, PDTHRAD, PTHT, PRT, PSVT, PCIT, &
 & PTHS, PRS, PSVS, PEVAP,&
 & PINPRR,PINPRS,&
 & PINPRG,PINPRH,PFPR,&
 & PCLDFR,PICEFR,PPRCFR,&
 & PHLC_HRC, PHLC_HCF, PHLI_HRI, PHLI_HCF, &
 & YDDDH,YDLDDH,YDMDDH)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE DDH_MIX, ONLY : TYP_DDH
USE YOMLDDH, ONLY : TLDDH
USE YOMMDDH, ONLY : TMDDH
USE MODD_PHYEX, ONLY: PHYEX_t
TYPE(PHYEX_t),      INTENT(IN) :: PHYEX
INTEGER(KIND=JPIM), INTENT(IN) :: KKA
INTEGER(KIND=JPIM), INTENT(IN) :: KKU
INTEGER(KIND=JPIM), INTENT(IN) :: KKL
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KRR
INTEGER(KIND=JPIM), INTENT(IN) :: KSV
REAL(KIND=JPRB), INTENT(IN) :: PTSTEP
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PDZZ
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PRHODJ
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PRHODREF
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PEXNREF
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PPABSM
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PW_NU
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PDTHRAD
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PTHT
REAL(KIND=JPRB), DIMENSION(KLON,KLEV,KRR), INTENT(INOUT):: PRT
REAL(KIND=JPRB), DIMENSION(KLON,KLEV,KSV), INTENT(INOUT):: PSVT
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(INOUT) :: PCIT
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(INOUT) :: PTHS
REAL(KIND=JPRB), DIMENSION(KLON,KLEV,KRR), INTENT(INOUT) :: PRS
REAL(KIND=JPRB), DIMENSION(KLON,KLEV,KSV), INTENT(INOUT) :: PSVS
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(INOUT) :: PEVAP
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(INOUT) :: PINPRR
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(INOUT) :: PINPRS
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(INOUT) :: PINPRG
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(INOUT) :: PINPRH
REAL(KIND=JPRB), DIMENSION(KLON,KLEV,KRR), INTENT(INOUT) :: PFPR
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(INOUT) :: PCLDFR
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(INOUT) :: PICEFR
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(INOUT) :: PPRCFR
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(INOUT) :: PHLC_HRC
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(INOUT) :: PHLC_HCF
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(INOUT) :: PHLI_HRI
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(INOUT) :: PHLI_HCF
TYPE(TYP_DDH), INTENT(INOUT) :: YDDDH
TYPE(TLDDH), INTENT(IN) :: YDLDDH
TYPE(TMDDH), INTENT(IN) :: YDMDDH
END SUBROUTINE ARO_LIMA
END INTERFACE
