INTERFACE
 SUBROUTINE ARO_RAIN_ICE(KPROMA,KKA,KKU,KKL,KLON,KLEV, KFDIA,KRR, KTCOUNT, KSPLITR,&
 & KEZDIAG, &
 & OSUBG_COND, CSUBG_AUCV_RC, CSUBG_AUCV_RI, OSEDIC,CSEDIM,CMICRO,&
 & PTSTEP, PDZZ, PRHODJ, PRHODREF, PEXNREF,&
 & PPABSM, PHLC_HRC, PHLC_HCF, PHLI_HRI, PHLI_HCF, PTHT, PRT, PSIGS,PCLDFR,&
 & PTHS, PRS, PEVAP,&
 & PCIT, OWARM, PSEA, PTOWN, &
 & OCND2, LGRSN, &
 & PINPRR,PINPRS,&
 & PINPRG,PINPRH,PFPR,&
 & PGP2DSPP,PEZDIAG, &
 & YDDDH,YDLDDH,YDMDDH)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE DDH_MIX, ONLY : TYP_DDH
USE SPP_MOD, ONLY : YSPP
USE YOMLDDH, ONLY : TLDDH
USE YOMMDDH, ONLY : TMDDH
INTEGER,            INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM), INTENT(IN) :: KKA
INTEGER(KIND=JPIM), INTENT(IN) :: KKU
INTEGER(KIND=JPIM), INTENT(IN) :: KKL
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KRR
INTEGER(KIND=JPIM), INTENT(IN) :: KTCOUNT
INTEGER(KIND=JPIM), INTENT(IN) :: KSPLITR
INTEGER(KIND=JPIM), INTENT(IN) :: KEZDIAG
LOGICAL, INTENT(IN) :: OSUBG_COND
CHARACTER(LEN=4), INTENT(IN) :: CSUBG_AUCV_RC
CHARACTER(LEN=80), INTENT(IN) :: CSUBG_AUCV_RI
LOGICAL, INTENT(IN) :: OSEDIC
CHARACTER(LEN=4), INTENT(IN) :: CSEDIM
CHARACTER(LEN=4), INTENT(IN) :: CMICRO
REAL(KIND=JPRB), INTENT(IN) :: PTSTEP
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PDZZ
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PRHODJ
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PRHODREF
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PEXNREF
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PPABSM
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PHLC_HRC
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PHLC_HCF
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PHLI_HRI
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PHLI_HCF
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PTHT
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV,KRR), INTENT(INOUT):: PRT
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PSIGS
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(IN) :: PCLDFR
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(INOUT) :: PTHS
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV,KRR), INTENT(INOUT) :: PRS
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(INOUT) :: PEVAP
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV), INTENT(INOUT) :: PCIT
LOGICAL, INTENT(IN) :: OWARM
REAL(KIND=JPRB), DIMENSION(KLON,1), INTENT(IN)    :: PSEA
REAL(KIND=JPRB), DIMENSION(KLON,1), INTENT(IN)    :: PTOWN
LOGICAL, INTENT(IN) :: OCND2
LOGICAL, INTENT(IN) :: LGRSN
REAL(KIND=JPRB), DIMENSION(KLON,1), INTENT(INOUT) :: PINPRR
REAL(KIND=JPRB), DIMENSION(KLON,1), INTENT(INOUT) :: PINPRS
REAL(KIND=JPRB), DIMENSION(KLON,1), INTENT(INOUT) :: PINPRG
REAL(KIND=JPRB), DIMENSION(KLON,1), INTENT(INOUT) :: PINPRH
REAL(KIND=JPRB), DIMENSION(KLON,1,KLEV,KRR), INTENT(INOUT) :: PFPR
REAL(KIND=JPRB), DIMENSION(KLON,YSPP%N2D), INTENT(INOUT) :: PGP2DSPP
REAL(KIND=JPRB), DIMENSION(KLON,KLEV,1), INTENT(INOUT) :: PEZDIAG
TYPE(TYP_DDH),                       INTENT(INOUT) :: YDDDH
TYPE(TLDDH),                         INTENT(IN) :: YDLDDH
TYPE(TMDDH),                         INTENT(IN) :: YDMDDH
END SUBROUTINE ARO_RAIN_ICE
END INTERFACE
