INTERFACE
SUBROUTINE AROINI_TURB(PLINI,OHARATU,OSTATNW)
USE PARKIND1  ,ONLY : JPRB
REAL(KIND=JPRB),INTENT(IN)::PLINI
LOGICAL, INTENT(IN) ::OHARATU
LOGICAL, INTENT(IN) ::OSTATNW
END SUBROUTINE AROINI_TURB
END INTERFACE
