INTERFACE
SUBROUTINE AROINI_MICRO_LIMA(KULOUT,KULNAM,PTSTEP,CMICRO,KSPLITR,KSPLITG)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
INTEGER(KIND=JPIM), INTENT (IN) :: KULOUT
INTEGER(KIND=JPIM), INTENT (IN) :: KULNAM
REAL(KIND=JPRB), INTENT (IN) :: PTSTEP
CHARACTER (LEN=4), INTENT (IN) :: CMICRO
INTEGER(KIND=JPIM), INTENT (OUT) :: KSPLITR
INTEGER(KIND=JPIM), INTENT (OUT) :: KSPLITG
END SUBROUTINE AROINI_MICRO_LIMA
END INTERFACE
