INTERFACE
SUBROUTINE AROINI_TURB(PLINI,OHARATU,OSTATNW,OSUBG_COND,HCONDENS,HLAMBDA3,HSUBG_MF_PDF, &
                       OSIGMAS)
USE PARKIND1  ,ONLY : JPRB
REAL(KIND=JPRB),INTENT(IN)::PLINI
LOGICAL, INTENT(IN) ::OHARATU
LOGICAL, INTENT(IN) ::OSTATNW
LOGICAL, INTENT(IN) :: OSUBG_COND
CHARACTER(LEN=80),INTENT(IN)   :: HCONDENS
CHARACTER(LEN=4),INTENT(IN)    :: HLAMBDA3
CHARACTER(LEN=80),INTENT(IN)  :: HSUBG_MF_PDF
LOGICAL, INTENT(IN) :: OSIGMAS
END SUBROUTINE AROINI_TURB
END INTERFACE
