!     ------------------------------------------------------------------
NAMELIST / NAMGFL / YQ_NL,YI_NL,YL_NL,YLCONV_NL,YICONV_NL,YRCONV_NL,YSCONV_NL,&
                   &YIRAD_NL,YLRAD_NL,YS_NL,YR_NL,YG_NL,YH_NL,&
                   &YIMF_NL,YLMF_NL,YAMF_NL,&
                   &YWMFC_NL, YHLMF_NL, YHLCFMF_NL, YHIMF_NL, YHICFMF_NL,&
                   &YTKE_NL,YEFB1_NL,YEFB2_NL,YEFB3_NL,YRSPEC_NL,&
                   &YA_NL,YO3_NL,YEXT_NL,NGFL_EXT,YCPF_NL,YSPF_NL,YSRC_NL,&
                   &YGHG_NL,NGHG,&
                   &YAERO_NL,NAERO,NCHEM,YCHEM_NL,LSPPTGFL,&
                   &NACTAERO,LAERCHEM,YCVGQ_NL,&
                   &LAEROCLIM,NAEROCLIM,YAEROCLIM_NL,&
                   &YLRCH4_NL,YSDSAT_NL,YCVV_NL,YERA40_NL,NERA40,LTRCMFIX_PS,LTRCMFQM,&
                   &LTRCMFBC,LTRCMFPR,LTRCMFMG,LTRCMFP,LTRCMFA_DIF,LTRCMFA_VER,LTRCMFA_LAP,LEXTRADF,&
                   &LQM3DCONS,NOPTMFBC,NOPTMFPR,NOPTVFE,NOPTNEGFIX,&
                   &NMFDIAGLEV,YFORC_NL,NGFL_FORC,YEZDIAG_NL,&
                   &NGFL_EZDIAG,YQVA_NL,YUOM_NL,YUAL_NL,YDOM_NL,YDAL_NL,YUEN_NL,YUNEBH_NL,YNOGW_NL,&
                   &NSLDIA, YSLDIA_NL,LAERAOT,LAERLISI,LAEROUT,NAEROUT,YAERAOT_NL,YAERLISI_NL,YAEROUT_NL,NUVP,LUVPOUT,YUVP_NL,&
                   &YRKTH_NL,YRKTQV_NL,YRKTQC_NL,YTTE_NL,YMXL_NL,YSHTUR_NL,YFQTUR_NL,YFSTUR_NL,&
                   &NAERO_WVL_DIAG,NAERO_WVL_DIAG_TYPES,YAERO_WVL_DIAG_NL,&
                   &YLIMA_NL,NLIMA,YPHYCTY_NL,YEDRP_NL
!     -------------------------------------------------------------------
