!    ------------------------------------------------------------------
NAMELIST/NAMPARAR/LOSUBG_COND,CSUBG_AUCV_RC,CSUBG_AUCV_RI,LOSIGMAS,NSWB_MNH,NPRINTFR,LSQUALL,&
        &NREFROI1,NREFROI2,VSQUALL,NPTP,LDIAGWMAX,NDIAGWMAX,CMICRO,&
        &LAROBU_ENABLE,CMF_UPDRAFT,CMF_CLOUD,LMIXUV,LLCRIT,LTOTPREC,&
        &LTOTPRECL,LHGT_QS,&
        &VSIGQSAT,XLINI,LOLSMC,LOTOWNC,LKOGAN,LMODICEDEP,&
        &LICERAD,RADGR,RADSN,LSTATNW,LHARATU,&
        &XALP_PERT,XABUO,XBENTR,XBDETR,XCMF,XENTR_MF,XCRAD_MF,XENTR_DRY,&
        &XDETR_DRY,XDETR_LUP,XKCF_MF,XKRC_MF,XTAUSIGMF,XPRES_UV,XFRAC_UP_MAX,&
        &XALPHA_MF,XSIGMA_MF,XA1,XB,XC,XBETA1,LTHETAS,&
        &XCQVR,GQVPLIM,GQVTOP,LQVTOP,LFPREC3D, &
        &CCONDENS, CLAMBDA3, CSUBG_MF_PDF
!       ------------------------------------------------------------------
