!    ------------------------------------------------------------------
NAMELIST/NAMPARAR/LOSUBG_COND,CSUBG_AUCV_RC,CSUBG_AUCV_RI,LOSIGMAS,NSWB_MNH,NPRINTFR,LSQUALL,&
        &NREFROI1,NREFROI2,VSQUALL,NPTP,LDIAGWMAX,NDIAGWMAX,CMICRO,&
        &LAROBU_ENABLE,LLCRIT,LTOTPREC,&
        &LTOTPRECL,LHGT_QS,&
        &VSIGQSAT,XLINI,LOLSMC,LOTOWNC,LKOGAN,LMODICEDEP,&
        &LICERAD,RADGR,RADSN,LSTATNW,LHARATU,&
        &XCQVR,GQVPLIM,GQVTOP,LQVTOP,LFPREC3D, &
        &CCONDENS, CLAMBDA3, CSUBG_MF_PDF
!       ------------------------------------------------------------------
