SUBROUTINE SUFA

!**** *SUFA*  - Initialize characteristics for GRIB packing
!               in FA files (to do before FA files opening)
!               Sous-programme de definition de quelques caracteristiques
!               du compactage GRIB dans les fichiers FA (a appeler avant
!               l'ouverture des fichiers FA)

!     PURPOSE.
!     --------
!        Read namelist NAMFA / Lit et verifie la namelist NAMFA.

!**   INTERFACE.
!     ----------
!       *CALL* *SUFA*

!        EXPLICIT ARGUMENTS
!        --------------------
!        NONE

!     METHOD.
!     -------

!     EXTERNALS.
!     ----------
!        calls FAVORI and FAGIOT
!        Is called by SU0YOMA.

!     REFERENCE.
!     ----------

!     AUTHOR.
!     -------
!      D. Paradis  *METEO-FRANCE*
!      ORIGINAL : 99-07-27

!     MODIFICATIONS.
!     --------------
!      R. El Khatib 01-01-25 Cleanings
!      R. El Khatib 03-08-19
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      M. Tudor 03-10-17 add YFACPF and YFASPF
!      Y. Seity 04-11-16 define AROME fields name
!      P. Termonia 04-09-01 add YFAFSPi, i=1,2,3,4,5
!      D. Paradis & R. El Khatib : 04-07-22 GRIBEX
!      Y. Bouteloup 05-01-20 add YFAR (atmospheric rain)
!      F. Bouyssel 05-11-09 Change second descriptor of YSUFAD
!      B. Sass 01-06-06 Define YFAQVA used with HIRLAM
!      A. Alias 06-04-03 SDSAT and CVV added
!      M. Bellus 29-Sep-2006 add prognostic convection
!           and MAC scheme (coded by L. Gerard 09-Mar-2005)
!      Y. Bouteloup  : 01-05-2009 Add Total (radiative) cloud water and ice
!      R. El Khatib 30-Mar-2012 fanmsg
!      R. El Khatib 07-Aug-2014 change default value of LSUPPDATE.
!      R. El Khatib 05-May-2015 change default value of LPROGRID+LEXTERN
!      R. El Khatib 08-Dec-2015 Interoperability GRIB2 vs FA
!      R. El Khatib 17-Aug-2016 Better interoperability GRIB2 vs FA
!      Y. Bouteloup 11-Jan-2017 FA GRIB packing parameters for convective variables
!      R. El Khatib  22-Jun-2022 pruning of conf. 901
!     ------------------------------------------------------------------

USE PARKIND1 , ONLY : JPIM     ,JPRB
USE YOMHOOK  , ONLY : LHOOK    ,DR_HOOK, JPHOOK
USE YOMLUN   , ONLY : NULOUT   ,NULNAM   ,NSCRTCH
USE YOMCT0   , ONLY : LARPEGEF ,LAROME   ,LECMWF   ,NCONF
USE YOMOPH0  , ONLY : CNMCA
USE YOMFA    , ONLY : NVGRIB,   NBITPG   ,NBITCS   ,NSTRON   ,NPULAP   , &
 & YFA_MSAT7C1, YFA_MSAT7C2, YFA_MSAT8C1, YFA_MSAT8C2, YFA_MSAT8C3, YFA_MSAT8C4, &
 & YFA_MSAT8C5, YFA_MSAT8C6, YFA_MSAT8C7, YFA_MSAT8C8, YFA_MSAT9C1, YFA_MSAT9C2, &
 & YFA_MSAT9C3, YFA_MSAT9C4, YFA_MSAT9C5, YFA_MSAT9C6, YFA_MSAT9C7, YFA_MSAT9C8, &
 & YFA_MSAT10C1, YFA_MSAT10C2, YFA_MSAT10C3, YFA_MSAT10C4, YFA_MSAT10C5, YFA_MSAT10C6, &
 & YFA_MSAT10C7, YFA_MSAT10C8, &
 & YFA_MSAT11C1, YFA_MSAT11C2, YFA_MSAT11C3, YFA_MSAT11C4, YFA_MSAT11C5, YFA_MSAT11C6, &
 & YFA_MSAT11C7, YFA_MSAT11C8, &
 & YFA_GOES11C1,YFA_GOES11C2,YFA_GOES11C3,YFA_GOES11C4,YFA_GOES12C1,YFA_GOES12C2,&
 & YFA_GOES12C3,YFA_GOES12C4,YFA_GOES15C1,YFA_GOES15C2,YFA_GOES15C3,YFA_GOES15C4,&
 & YFA_GOES16C1,YFA_GOES16C2,YFA_GOES16C3,YFA_GOES16C4,YFA_GOES16C5,&
 & YFA_GOES16C6,YFA_GOES16C7,YFA_GOES16C8,YFA_GOES16C9,YFA_GOES16C10,&
 & YFA_GOES17C1,YFA_GOES17C2,YFA_GOES17C3,YFA_GOES17C4,YFA_GOES17C5,&
 & YFA_GOES17C6,YFA_GOES17C7,YFA_GOES17C8,YFA_GOES17C9,YFA_GOES17C10,&
 & YFA_MTSAT1C1,YFA_MTSAT1C2,YFA_MTSAT1C3,YFA_MTSAT1C4,&
 & YFA_HIMA8C1,YFA_HIMA8C2,YFA_HIMA8C3,YFA_HIMA8C4,YFA_HIMA8C5,&
 & YFA_HIMA8C6,YFA_HIMA8C7,YFA_HIMA8C8,YFA_HIMA8C9,YFA_HIMA8C10,&
 & YFA_XTCC,  YFA_X10U,  YFA_X10V,  YFA_X10NU, YFA_X10NV, &
 & YFA_X2T,   YFA_X2SH,  YFA_X2RH,  YFA_XCCC,  YFA_XHCC, YFA_XSIC, YFA_XSNWDE, &
 & YFA_XMCC,  YFA_XLCC,  YFA_XX2T,  YFA_XN2T,  YFA_XCVU,  YFA_XCVV,  YFA_XCVQ,  YFA_XCVS,  &
 & YFA_XTUU,  YFA_XTUV,  YFA_XTUQ,  YFA_XTUS,  YFA_XGDU,  YFA_XGDV,  YFA_XLSP,  YFA_XCP,   &
 & YFA_XLSS,  YFA_XCSF,  YFA_XLSG,  YFA_XCSG,  YFA_XLSH,  YFA_XCSH,  YFA_XSSR,  YFA_XSTR,  &
 & YFA_XTSR,  YFA_XTTR,  YFA_X10FF, YFA_XCAPE, YFA_XCTOP, YFA_XMOCO, YFA_XCLPH, YFA_XVEIN, YFA_XGUST, &
 & YFA_XCLPHMF, YFA_XVMAXTH , &
 & YFA_XUGST, YFA_XVGST,YFA_XUGST2,YFA_XVGST2,YFA_XX2HU, YFA_XN2HU, YFA_XTHW,  YFA_XXDIAGH, YFA_XMRT, &
 & YFA_VISICLD, YFA_VISIHYD, YFA_MXCLWC, YFA_VISICLD2, YFA_VISIHYD2, YFA_MXCLWC2, YFA_XPTYPE, &
 & YFA_XPTYPESEV, YFA_XPTYPE2, YFA_XPTYPESEV2, YFA_X2TPW, YFA_ST,&
 & YFA_CLSP , YFA_CCP  , YFA_CLSS , YFA_CCSF , YFA_CLSG , YFA_CCSG , YFA_CLSH , YFA_CCSH , &
 & YFA_CUSS , YFA_CVSS , YFA_CSSH , YFA_CSLH , YFA_CTSP , YFA_CTCC , YFA_CBLD , YFA_CSSR , &
 & YFA_CSTR , YFA_CTSR , YFA_CTTR , YFA_CCCC , YFA_CHCC , YFA_CMCC , YFA_CLCC , YFA_CUGW , &
 & YFA_CVGW , YFA_CUTO , YFA_CVTO , YFA_CE   , YFA_CS   , YFA_CT   , YFA_CLHE , YFA_CLHS , YFA_CLHT , &
 & YFA_CWS  , YFA_CSNS , YFA_CQTO , YFA_CTO3 , YFA_CTME , YFA_CICE , YFA_CLI  , YFA_CCVU , YFA_CCVV , &
 & YFA_CCVQ , YFA_CCVS , YFA_CTUQ , YFA_CTUS , YFA_CSOC , YFA_CTHC , YFA_CSOP , YFA_CDNI , YFA_CGNI , YFA_CTOP , &
 & YFA_CSOD , YFA_CTHD , YFA_CFON , YFA_CCHS , YFA_CEAS , YFA_CSRU , YFA_CDRU , YFA_CIRU , YFA_CETP , &
 & YFA_CTP  , YFA_CSMR , YFA_CTSOC, YFA_CTTHC, YFA_CDUTP, YFA_CFLASH,&
 & YFA_CWLS , YFA_CWLI , YFA_CWDS , YFA_CWPS , YFA_CWPI , &
 & YFA_CAPE , YFA_CIEN , YFA_MUMLCAPE ,YFA_MLCAPE,YFA_TCVS , &
 & YFA_ASMC , YFA_VSMC , YFA_ACCGREL, &
 & YFAOROG  ,YFASP    ,YFAPSI   ,YFAKHI   ,YFAUGEO  ,YFAVGEO  , &
 & YFAT     ,YFAPD    ,YFAVD    ,YFAQ     ,YFAL     ,YFALCONV ,YFAICONV , &
 & YFARCONV ,YFASCONV ,YFAI     ,NVERBOSE , LSUPPDATE, &
 & YFAO3    ,YFACLF   ,YFAS     ,YFAR     ,YFAG     ,YFAH     ,YFATKE   , &
 & YFAEFB1  ,YFAEFB2  ,YFAEFB3,&
 & YFACPF   ,YFASPF   ,YFAFSP1  ,YFAFSP2  ,YFAFSP3  ,YFAFSP4  , &
 & YFAFSP5  ,YFASRC   ,YFASDSAT ,YFACVV   ,YFACVGQ  ,YFAQVA   , &
 & YFAUOM   ,YFAUAL   ,YFADOM   ,YFADAL   ,YFAUEN   ,YFAUNEBH , &
 & YFARKTH  ,YFARKTQV ,YFARKTQC ,YFALRAD  ,YFAIRAD  ,YFATTE   , &
 & YFALMF   ,YFAIMF   ,YFAAMF   ,YFAWMFC  ,YFAHLMF  ,YFAHLCFMF, &
 & YFAHIMF  ,YFAHICFMF,YFAMXL ,CMODEL , NIDCEN, &
 & LEXTERN  ,YFASHTUR  ,YFAFQTUR, YFAFSTUR
USE YOMARG   , ONLY : NGRIBFILE
USE TYPE_FADS, ONLY : YSUFAD

!     ------------------------------------------------------------------

IMPLICIT NONE

INTEGER(KIND=JPIM) :: IDMOPL, INBARI, IREP

CHARACTER(LEN=12) :: CLSCRTCH

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "posnam.intfb.h"

!     ------------------------------------------------------------------

#include "namfa.nam.h"

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('SUFA',0,ZHOOK_HANDLE)

!     ------------------------------------------------------------------

!*       1. SET DEFAULT VALUES
!           -------------------

IF (NGRIBFILE==0.OR.LARPEGEF) THEN

! FAVORI gives implicit options of GRIB packing for *FA* files
  CALL FAVORI (NVGRIB, NBITPG, NBITCS, NSTRON, NPULAP, IDMOPL)

ELSE

  NBITPG=24
  NBITCS=24
  NVGRIB=2
  NSTRON=10
  NPULAP=1

ENDIF

YFAOROG =YSUFAD('SPECSURFGEOPOTEN',0)
YFASP   =YSUFAD('SURFPRESSION    ',-1)
YFAPSI  =YSUFAD('POT.VITESSE     ',-1)
YFAKHI  =YSUFAD('FONC.COURANT    ',-1)
YFAUGEO =YSUFAD('WIND.U.PHYS     ',-1)
YFAVGEO =YSUFAD('WIND.V.PHYS     ',-1)
YFAT    =YSUFAD('TEMPERATURE     ',-1)
YFAPD   =YSUFAD('PRESS.DEPART    ',-1)
YFAVD   =YSUFAD('VERTIC.DIVER    ',-1)
YFAFSP1 =YSUFAD('CUF1PRESSURE    ',-1)
YFAFSP2 =YSUFAD('CUF2PRESSURE    ',-1)
YFAFSP3 =YSUFAD('CUF3PRESSURE    ',-1)
YFAFSP4 =YSUFAD('CUF4PRESSURE    ',-1)
YFAFSP5 =YSUFAD('CUF5PRESSURE    ',-1)
SELECT CASE(LECMWF.AND..NOT.LARPEGEF)
CASE (.TRUE.)
  YFAQ    =YSUFAD(' HUMIDITY       ',-1)
  YFAL    =YSUFAD(' LIQUID WATER   ',-1)
  YFALCONV=YSUFAD('QL_CONV         ',-1)
  YFAICONV=YSUFAD('QI_CONV         ',-1)
  YFARCONV=YSUFAD('QR_CONV         ',-1)
  YFASCONV=YSUFAD('QS_CONV         ',-1)
  YFAI    =YSUFAD(' ICE WATER      ',-1)
  YFALRAD =YSUFAD('RAD_LIQUID_WATER',-1)
  YFAIRAD =YSUFAD('RAD_SOLID_WATER ',-1)
  YFAO3   =YSUFAD(' OZONE          ',-1)
  YFACLF  =YSUFAD(' CLOUD FRACTION ',-1)
  YFACPF  =YSUFAD('CV_PREC_FLUX    ',-1)
  YFASPF  =YSUFAD('ST_PREC_FLUX    ',-1)
  YFAS    =YSUFAD('SNOW            ',-1)
  YFAR    =YSUFAD('RAIN            ',-1)
  YFAG    =YSUFAD('GRAUPEL         ',-1)
  YFAH    =YSUFAD('HAIL            ',-1)
  YFATKE  =YSUFAD('TKE             ',-1)
  YFAEFB1 =YSUFAD('EFB1            ',-1)
  YFAEFB2 =YSUFAD('EFB2            ',-1)
  YFAEFB3 =YSUFAD('EFB3            ',-1)
  YFASRC  =YSUFAD('SRC             ',-1)
  YFALMF  =YSUFAD('MF_LIQUID_WATER ',-1)
  YFAIMF  =YSUFAD('MF_ICE_WATER    ',-1)
  YFAAMF  =YSUFAD('MF_CLOUD_FRACTI ',-1)
  YFAWMFC =YSUFAD('                ',-1)
  YFAHLMF =YSUFAD('                ',-1)
  YFAHLCFMF=YSUFAD('                ',-1)
  YFAHIMF =YSUFAD('                ',-1)
  YFAHICFMF=YSUFAD('                ',-1)
  YFACVGQ =YSUFAD('CVGQ            ',-1)
  YFAQVA  =YSUFAD('QVA_AMPLITUDE   ',-1)
  YFASDSAT=YSUFAD('                ',-1)
  YFACVV  =YSUFAD('                ',-1)
  YFAUOM  =YSUFAD('                ',-1)
  YFAUAL  =YSUFAD('                ',-1)
  YFADOM  =YSUFAD('                ',-1)
  YFADAL  =YSUFAD('                ',-1)
  YFAUEN  =YSUFAD('                ',-1)
  YFAUNEBH=YSUFAD('                ',-1)
  YFATTE  =YSUFAD('                ',-1)
  YFAMXL  =YSUFAD('                ',-1)
  YFASHTUR=YSUFAD('                ',-1)
  YFAFQTUR=YSUFAD('                ',-1)
  YFAFSTUR=YSUFAD('                ',-1)
  YFARKTH =YSUFAD('                ',-1)
  YFARKTQV=YSUFAD('                ',-1)
  YFARKTQC=YSUFAD('                ',-1)
CASE DEFAULT
  YFAQ    =YSUFAD('HUMI.SPECIFI    ',-1)
  YFAL    =YSUFAD('LIQUID_WATER    ',-1)
  YFALCONV=YSUFAD('QL_CONV         ',-1)
  YFAICONV=YSUFAD('QI_CONV         ',-1)
  YFARCONV=YSUFAD('QR_CONV         ',-1)
  YFASCONV=YSUFAD('QS_CONV         ',-1)
  YFAI    =YSUFAD('SOLID_WATER     ',-1)
  YFALRAD =YSUFAD('RAD_LIQUID_WATER',-1)
  YFAIRAD =YSUFAD('RAD_SOLID_WATER ',-1)
  YFAO3   =YSUFAD('OZONE           ',-1)
  YFACLF  =YSUFAD('CLOUD_FRACTI    ',-1)
  YFACPF  =YSUFAD('CV_PREC_FLUX    ',-1)
  YFASPF  =YSUFAD('ST_PREC_FLUX    ',-1)
  YFAS    =YSUFAD('SNOW            ',-1)
  YFAR    =YSUFAD('RAIN            ',-1)
  YFAG    =YSUFAD('GRAUPEL         ',-1)
  YFAH    =YSUFAD('HAIL            ',-1)
  YFATKE  =YSUFAD('TKE             ',-1)
  YFAEFB1 =YSUFAD('EFB1            ',-1)
  YFAEFB2 =YSUFAD('EFB2            ',-1)
  YFAEFB3 =YSUFAD('EFB3            ',-1)
  YFASRC  =YSUFAD('SRC             ',-1)
  YFALMF  =YSUFAD('MF_LIQUID_WATER ',-1)
  YFAIMF  =YSUFAD('MF_ICE_WATER    ',-1)
  YFAWMFC =YSUFAD('                ',-1)
  YFAHLMF =YSUFAD('                ',-1)
  YFAHLCFMF=YSUFAD('                ',-1)
  YFAHIMF =YSUFAD('                ',-1)
  YFAHICFMF=YSUFAD('                ',-1)
  YFAAMF  =YSUFAD('MF_CLOUD_FRACTI ',-1)
  YFACVGQ =YSUFAD('CVGQ            ',-1)
  YFAQVA  =YSUFAD('QVA_AMPLITUDE   ',-1)
  YFASDSAT=YSUFAD('SDSAT           ',-1)
  YFACVV  =YSUFAD('CVV             ',-1)
  YFAUOM  =YSUFAD('UD_OMEGA        ',-1)
  YFAUAL  =YSUFAD('UD_MESH_FRAC    ',-1)
  YFADOM  =YSUFAD('DD_OMEGA        ',-1)
  YFADAL  =YSUFAD('DD_MESH_FRAC    ',-1)
  YFAUEN  =YSUFAD('UD_ENTRAINMENT  ',-1)
  YFAUNEBH=YSUFAD('PSHI_CONV_CLOUD ',-1)
  YFATTE  =YSUFAD('TOTAL_TUR_ENERGY',-1)
  YFAMXL  =YSUFAD('MIXING_LENGTH   ',-1)
  YFASHTUR=YSUFAD('SHEAR TERM TURB ',-1)
  YFAFQTUR=YSUFAD('Q SRC TERM TURB ',-1)
  YFAFSTUR=YSUFAD('S SRC TERM TURB ',-1)
  YFARKTH =YSUFAD('RK_TEMPTEND     ',-1)
  YFARKTQV=YSUFAD('RK_QVTEND       ',-1)
  YFARKTQC=YSUFAD('RK_QCTEND       ',-1)
END SELECT
IF (LAROME) THEN
  YFAQ    =YSUFAD('HUMI.SPECIFI    ',-1)
  YFAL    =YSUFAD('CLOUD_WATER     ',-1)
  YFALCONV=YSUFAD('QL_CONV         ',-1)
  YFAICONV=YSUFAD('QI_CONV         ',-1)
  YFARCONV=YSUFAD('QR_CONV         ',-1)
  YFASCONV=YSUFAD('QS_CONV         ',-1)
  YFAI    =YSUFAD('ICE_CRYSTAL     ',-1)
  YFAS    =YSUFAD('SNOW            ',-1)
  YFAR    =YSUFAD('RAIN            ',-1)
  YFAG    =YSUFAD('GRAUPEL         ',-1)
  YFAH    =YSUFAD('HAIL            ',-1)
  YFATKE  =YSUFAD('TKE             ',-1)
  YFAEFB1 =YSUFAD('EFB1            ',-1)
  YFAEFB2 =YSUFAD('EFB2            ',-1)
  YFAEFB3 =YSUFAD('EFB3            ',-1)
  YFACLF  =YSUFAD('CLOUD_FRACTI    ',-1)
  YFASRC  =YSUFAD('SRC             ',-1)
ENDIF

! Simulated satellite images
YFA_MSAT7C1=YSUFAD('C001_METEOSAT_07',-1)
YFA_MSAT7C2=YSUFAD('C002_METEOSAT_07',-1)
YFA_MSAT8C1=YSUFAD('C001_METEOSAT_08',-1)
YFA_MSAT8C2=YSUFAD('C002_METEOSAT_08',-1)
YFA_MSAT8C3=YSUFAD('C003_METEOSAT_08',-1)
YFA_MSAT8C4=YSUFAD('C004_METEOSAT_08',-1)
YFA_MSAT8C5=YSUFAD('C005_METEOSAT_08',-1)
YFA_MSAT8C6=YSUFAD('C006_METEOSAT_08',-1)
YFA_MSAT8C7=YSUFAD('C007_METEOSAT_08',-1)
YFA_MSAT8C8=YSUFAD('C008_METEOSAT_08',-1)
YFA_MSAT9C1=YSUFAD('C001_METEOSAT_09',-1)
YFA_MSAT9C2=YSUFAD('C002_METEOSAT_09',-1)
YFA_MSAT9C3=YSUFAD('C003_METEOSAT_09',-1)
YFA_MSAT9C4=YSUFAD('C004_METEOSAT_09',-1)
YFA_MSAT9C5=YSUFAD('C005_METEOSAT_09',-1)
YFA_MSAT9C6=YSUFAD('C006_METEOSAT_09',-1)
YFA_MSAT9C7=YSUFAD('C007_METEOSAT_09',-1)
YFA_MSAT9C8=YSUFAD('C008_METEOSAT_09',-1)
YFA_MSAT10C1=YSUFAD('C001_METEOSAT_10',-1)
YFA_MSAT10C2=YSUFAD('C002_METEOSAT_10',-1)
YFA_MSAT10C3=YSUFAD('C003_METEOSAT_10',-1)
YFA_MSAT10C4=YSUFAD('C004_METEOSAT_10',-1)
YFA_MSAT10C5=YSUFAD('C005_METEOSAT_10',-1)
YFA_MSAT10C6=YSUFAD('C006_METEOSAT_10',-1)
YFA_MSAT10C7=YSUFAD('C007_METEOSAT_10',-1)
YFA_MSAT10C8=YSUFAD('C008_METEOSAT_10',-1)
YFA_MSAT11C1=YSUFAD('C001_METEOSAT_11',-1)
YFA_MSAT11C2=YSUFAD('C002_METEOSAT_11',-1)
YFA_MSAT11C3=YSUFAD('C003_METEOSAT_11',-1)
YFA_MSAT11C4=YSUFAD('C004_METEOSAT_11',-1)
YFA_MSAT11C5=YSUFAD('C005_METEOSAT_11',-1)
YFA_MSAT11C6=YSUFAD('C006_METEOSAT_11',-1)
YFA_MSAT11C7=YSUFAD('C007_METEOSAT_11',-1)
YFA_MSAT11C8=YSUFAD('C008_METEOSAT_11',-1)
YFA_GOES11C1=YSUFAD('C001_GOES_11_IMA',-1)
YFA_GOES11C2=YSUFAD('C002_GOES_11_IMA',-1)
YFA_GOES11C3=YSUFAD('C003_GOES_11_IMA',-1)
YFA_GOES11C4=YSUFAD('C004_GOES_11_IMA',-1)
YFA_GOES12C1=YSUFAD('C001_GOES_12_IMA',-1)
YFA_GOES12C2=YSUFAD('C002_GOES_12_IMA',-1)
YFA_GOES12C3=YSUFAD('C003_GOES_12_IMA',-1)
YFA_GOES12C4=YSUFAD('C004_GOES_12_IMA',-1)
YFA_GOES15C1=YSUFAD('C001_GOES_15_IMA',-1)
YFA_GOES15C2=YSUFAD('C002_GOES_15_IMA',-1)
YFA_GOES15C3=YSUFAD('C003_GOES_15_IMA',-1)
YFA_GOES15C4=YSUFAD('C004_GOES_15_IMA',-1)
YFA_GOES16C1=YSUFAD('C001_GOES_16_ABI',-1)
YFA_GOES16C2=YSUFAD('C002_GOES_16_ABI',-1)
YFA_GOES16C3=YSUFAD('C003_GOES_16_ABI',-1)
YFA_GOES16C4=YSUFAD('C004_GOES_16_ABI',-1)
YFA_GOES16C5=YSUFAD('C005_GOES_16_ABI',-1)
YFA_GOES16C6=YSUFAD('C006_GOES_16_ABI',-1)
YFA_GOES16C7=YSUFAD('C007_GOES_16_ABI',-1)
YFA_GOES16C8=YSUFAD('C008_GOES_16_ABI',-1)
YFA_GOES16C9=YSUFAD('C009_GOES_16_ABI',-1)
YFA_GOES16C10=YSUFAD('C010_GOES_16_ABI',-1)
YFA_GOES17C1=YSUFAD('C001_GOES_17_ABI',-1)
YFA_GOES17C2=YSUFAD('C002_GOES_17_ABI',-1)
YFA_GOES17C3=YSUFAD('C003_GOES_17_ABI',-1)
YFA_GOES17C4=YSUFAD('C004_GOES_17_ABI',-1)
YFA_GOES17C5=YSUFAD('C005_GOES_17_ABI',-1)
YFA_GOES17C6=YSUFAD('C006_GOES_17_ABI',-1)
YFA_GOES17C7=YSUFAD('C007_GOES_17_ABI',-1)
YFA_GOES17C8=YSUFAD('C008_GOES_17_ABI',-1)
YFA_GOES17C9=YSUFAD('C009_GOES_17_ABI',-1)
YFA_GOES17C10=YSUFAD('C010_GOES_17_ABI',-1)
YFA_MTSAT1C1=YSUFAD('C001_MTSAT_01_IM',-1)
YFA_MTSAT1C2=YSUFAD('C002_MTSAT_01_IM',-1)
YFA_MTSAT1C3=YSUFAD('C003_MTSAT_01_IM',-1)
YFA_MTSAT1C4=YSUFAD('C004_MTSAT_01_IM',-1)
YFA_HIMA8C1=YSUFAD('C001_HIMAWARI_08',-1)
YFA_HIMA8C2=YSUFAD('C002_HIMAWARI_08',-1)
YFA_HIMA8C3=YSUFAD('C003_HIMAWARI_08',-1)
YFA_HIMA8C4=YSUFAD('C004_HIMAWARI_08',-1)
YFA_HIMA8C5=YSUFAD('C005_HIMAWARI_08',-1)
YFA_HIMA8C6=YSUFAD('C006_HIMAWARI_08',-1)
YFA_HIMA8C7=YSUFAD('C007_HIMAWARI_08',-1)
YFA_HIMA8C8=YSUFAD('C008_HIMAWARI_08',-1)
YFA_HIMA8C9=YSUFAD('C009_HIMAWARI_08',-1)
YFA_HIMA8C10=YSUFAD('C010_HIMAWARI_08',-1)

! Instantaneous fluxes
IF (LAROME) THEN
  YFA_XLSS =YSUFAD('SURFINSNEIGE    ',-1)
  YFA_XLSP =YSUFAD('SURFINSPLUIE    ',-1)
  YFA_XLSG =YSUFAD('SURFINSGRAUPEL  ',-1)
ELSE
  YFA_XLSS =YSUFAD('S000NEIGE STRATI',-1)
  YFA_XLSP =YSUFAD('S000PLUIE STRATI',-1)
  YFA_XLSG =YSUFAD('S000GRAUP STRATI',-1)
ENDIF
YFA_ST     =YSUFAD('SURFTEMPERATURE',-1)
YFA_XTCC   =YSUFAD('SURFNEBUL.TOTALE',-1)
YFA_X10U   =YSUFAD('CLSVENT.ZONAL   ',-1)
YFA_X10V   =YSUFAD('CLSVENT.MERIDIEN',-1)
YFA_X10NU  =YSUFAD('CLSVENTNEUTRE.U ',-1)
YFA_X10NV  =YSUFAD('CLSVENTNEUTRE.V ',-1)
YFA_X2T    =YSUFAD('CLSTEMPERATURE  ',-1)
YFA_X2TPW  =YSUFAD('CLSTPRIM_W      ',-1)
YFA_XSIC   =YSUFAD('SEA.ICE.COVER   ',-1)   
YFA_X2SH   =YSUFAD('CLSHUMI.SPECIFIQ',-1)
YFA_X2RH   =YSUFAD('CLSHUMI.RELATIVE',-1)
YFA_XCCC   =YSUFAD('SURFNEBUL.CONVEC',-1)
YFA_XHCC   =YSUFAD('SURFNEBUL.HAUTE ',-1)
YFA_XMCC   =YSUFAD('SURFNEBUL.MOYENN',-1)
YFA_XLCC   =YSUFAD('SURFNEBUL.BASSE ',-1)
YFA_XX2T   =YSUFAD('CLSMAXI.TEMPERAT',-1)
YFA_XN2T   =YSUFAD('CLSMINI.TEMPERAT',-1)
YFA_XCVU   =YSUFAD('S000FL.U  CONVEC',-1)
YFA_XCVV   =YSUFAD('S000FL.V  CONVEC',-1)
YFA_XCVQ   =YSUFAD('S000FL.Q  CONVEC',-1)
YFA_XCVS   =YSUFAD('S000FL.CT CONVEC',-1)
YFA_XTUU   =YSUFAD('S000FL.U  TURBUL',-1)
YFA_XTUV   =YSUFAD('S000FL.V  TURBUL',-1)
YFA_XTUQ   =YSUFAD('S000FL.Q  TURBUL',-1)
YFA_XTUS   =YSUFAD('S000FL.CT TURBUL',-1)
YFA_XGDU   =YSUFAD('S000FL.U ONDG.OR',-1)
YFA_XGDV   =YSUFAD('S000FL.V ONDG.OR',-1)
YFA_XCP    =YSUFAD('S000PLUIE CONVEC',-1)
YFA_XCSF   =YSUFAD('S000NEIGE CONVEC',-1)
YFA_XCSG   =YSUFAD('S000GRAUP CONVEC',-1)
YFA_XLSH   =YSUFAD('S000GRELE STRATI',-1)
YFA_XCSH   =YSUFAD('S000GRELE CONVEC',-1)
YFA_XSSR   =YSUFAD('S000RAYT.SOLAIRE',-1)
YFA_XSTR   =YSUFAD('S000RAYT.TERREST',-1)
YFA_XTSR   =YSUFAD('SOMMRAYT.SOLAIRE',-1)
YFA_XTTR   =YSUFAD('SOMMRAYT.TERREST',-1)
YFA_X10FF  =YSUFAD('CLSWIND.VELOCITY',-1)
YFA_XCAPE  =YSUFAD('SURFCAPE.MOD.XFU',-1)
YFA_XCTOP  =YSUFAD('CLPTOPCONV.MOD.X',-1)
YFA_XMOCO  =YSUFAD('CLPMOCON.MOD.XFU',-1)
YFA_XCLPH  =YSUFAD('CLPMHAUT.MOD.XFU',-1)
YFA_XCLPHMF=YSUFAD('CLPMHAMF.MOD.XFU',-1)
YFA_XVMAXTH=YSUFAD('CLPVMAXT.MOD.XFU',-1)
YFA_XVEIN  =YSUFAD('CLPVEIND.MOD.XFU',-1)
YFA_XGUST  =YSUFAD('CLSRAFAL.MOD.XFU',-1)
YFA_XUGST  =YSUFAD('CLSU.RAF60M.XFU',-1)
YFA_XVGST  =YSUFAD('CLSV.RAF60M.XFU',-1)
YFA_XUGST2 =YSUFAD('CLSU.RAF2.MOD.XFU',-1)
YFA_XVGST2 =YSUFAD('CLSV.RAF2.MOD.XFU',-1)
YFA_XX2HU  =YSUFAD('CLSMAXI.HUMI.REL',-1)
YFA_XN2HU  =YSUFAD('CLSMINI.HUMI.REL',-1)
YFA_XTHW   =YSUFAD('THETAPWP_FLUX   ',-1)
YFA_XXDIAGH=YSUFAD('SURFDIAGHAIL    ',-1)
YFA_XMRT   =YSUFAD('CLSMEAN.RAD.TEMP',-1)
YFA_VISICLD=YSUFAD('CLSVISIN_60     ',-1)
YFA_VISIHYD=YSUFAD('CLSVISIHYDN60   ',-1)
YFA_MXCLWC =YSUFAD('CLD_WX_60M      ',-1)
YFA_VISICLD2=YSUFAD('CLSVISIN       ',-1)
YFA_VISIHYD2=YSUFAD('CLSVISIHYDN    ',-1)
YFA_MXCLWC2=YSUFAD('CLD_WX          ',-1)
YFA_XPTYPE =YSUFAD('CLSPTYPE_60M    ',-1)
YFA_XPTYPESEV=YSUFAD('CLSPTYPESEV_60M',-1)
YFA_XPTYPE2=YSUFAD('CLSPTYPE        ',-1)
YFA_XPTYPESEV2=YSUFAD('CLSPTYPESEV  ',-1)
YFA_XSNWDE =YSUFAD('SURFHAUTEUR.NEIG',-1)

! Cumulated fluxes
IF (LAROME) THEN
  YFA_CLSS =YSUFAD('SURFACCNEIGE    ',-1)
  YFA_CLSP =YSUFAD('SURFACCPLUIE    ',-1)
  YFA_CLSG =YSUFAD('SURFACCGRAUPEL  ',-1)
ELSE
  YFA_CLSS =YSUFAD('SURFPREC.NEI.GEC',-1)
  YFA_CLSP =YSUFAD('SURFPREC.EAU.GEC',-1)
  YFA_CLSG =YSUFAD('SURFPREC.GRA.GEC',-1)
ENDIF
YFA_CCP  =YSUFAD('SURFPREC.EAU.CON',-1)
YFA_CCSF =YSUFAD('SURFPREC.NEI.CON',-1)
YFA_CCSG =YSUFAD('SURFPREC.GRA.CON',-1)
YFA_CLSH =YSUFAD('SURFPREC.GRE.GEC',-1)
YFA_CCSH =YSUFAD('SURFPREC.GRE.CON',-1)
YFA_CUSS =YSUFAD('SURFTENS.TURB.ZO',-1)
YFA_CVSS =YSUFAD('SURFTENS.TURB.ME',-1)
YFA_CSSH =YSUFAD('SURFFLU.CHA.SENS',-1)
YFA_CSLH =YSUFAD('SURFCHAL LATENTE',-1)
YFA_CTSP =YSUFAD('SURFPRESSION SOL',-1)
YFA_CTCC =YSUFAD('ATMONEBUL.TOTALE',-1)
YFA_CBLD =YSUFAD('SURFDISSIP SURF ',-1)
YFA_CSSR =YSUFAD('SURFFLU.RAY.SOLA',-1)
YFA_CSTR =YSUFAD('SURFFLU.RAY.THER',-1)
YFA_CTSR =YSUFAD('SOMMFLU.RAY.SOLA',-1)
YFA_CTTR =YSUFAD('SOMMFLU.RAY.THER',-1)
YFA_CCCC =YSUFAD('ATMONEBUL.CONVEC',-1)
YFA_CHCC =YSUFAD('ATMONEBUL.HAUTE ',-1)
YFA_CMCC =YSUFAD('ATMONEBUL.MOYENN',-1)
YFA_CLCC =YSUFAD('ATMONEBUL.BASSE ',-1)
YFA_CUGW =YSUFAD('SURFTENS.DMOG.ZO',-1)
YFA_CVGW =YSUFAD('SURFTENS.DMOG.ME',-1)
YFA_CUTO =YSUFAD('SURFTENS.TOTA.ZO',-1)
YFA_CVTO =YSUFAD('SURFTENS.TOTA.ME',-1)
YFA_CE   =YSUFAD('SURFFLU.MEVAP.EA',-1)
YFA_CS   =YSUFAD('SURFFLU.MSUBL.NE',-1)
YFA_CT   =YSUFAD('SURFFLU.MTOTA.NE',-1)
YFA_CLHE =YSUFAD('SURFFLU.LAT.MEVA',-1)
YFA_CLHS =YSUFAD('SURFFLU.LAT.MSUB',-1)
YFA_CLHT =YSUFAD('SURFFLU.LAT.MTOT',-1)
YFA_CWS  =YSUFAD('SURFCONTENU EAU ',-1)
YFA_CSNS =YSUFAD('SURFRESERV NEIGE',-1)
YFA_CQTO =YSUFAD('ATMOHUMI TOTALE ',-1)
YFA_CTO3 =YSUFAD('ATMOOZONE TOTALE',-1)
YFA_CTME =YSUFAD('TOPMESO ENTH    ',-1)
YFA_CICE =YSUFAD('ATMOHUMI SOLIDE ',-1)
YFA_CLI  =YSUFAD('ATMOHUMI LIQUIDE',-1)
YFA_CCVU =YSUFAD('SURFTENS.CONV.ZO',-1)
YFA_CCVV =YSUFAD('SURFTENS.CONV.ME',-1)
YFA_CCVQ =YSUFAD('SURFCFU.Q.CONVEC',-1)
YFA_CCVS =YSUFAD('SURFCFU.CT.CONVE',-1)
YFA_CTUQ =YSUFAD('SURFCFU.Q.TURBUL',-1)
YFA_CTUS =YSUFAD('SURFCFU.CT.TURBU',-1)
YFA_CSOC =YSUFAD('SURFRAYT SOL CL ',-1)
YFA_CTHC =YSUFAD('SURFRAYT THER CL',-1)
YFA_CSOP =YSUFAD('SURFRAYT DIR SUR',-1)
YFA_CDNI =YSUFAD('SURFDIR NORM IRR',-1)
YFA_CGNI =YSUFAD('SURFGLB NORM IRR',-1)
YFA_CTOP =YSUFAD('TOPRAYT DIR SOM ',-1)
YFA_CSOD =YSUFAD('SURFRAYT SOLA DE',-1)
YFA_CTHD =YSUFAD('SURFRAYT THER DE',-1)
YFA_CFON =YSUFAD('SURFFONTE NEIGE ',-1)
YFA_CCHS =YSUFAD('SURFCHAL. DS SOL',-1)
YFA_CEAS =YSUFAD('SURFEAU DANS SOL',-1)
YFA_CSRU =YSUFAD('SURFRUISSELLEMEN',-1)
YFA_CDRU =YSUFAD('PROFRUISSELLEMEN',-1)
YFA_CIRU =YSUFAD('SURFRUISS. INTER',-1)
YFA_CETP =YSUFAD('SURFEVAPOTRANSPI',-1)
YFA_CTP  =YSUFAD('SURFTRANSPIRATIO',-1)
YFA_CSMR =YSUFAD('SURFRAYT.LUNE.DE',-1)
YFA_CTSOC=YSUFAD('SOMMRAYT SOL CL ',-1)
YFA_CTTHC=YSUFAD('SOMMRAYT THER CL',-1)
YFA_CDUTP=YSUFAD('SURFTIME.PREC.TO',-1)
YFA_CFLASH=YSUFAD('SURFDIAG.FLASH ',-1)
YFA_CWLS=YSUFAD('SURFLOADSNOW',-1)
YFA_CWLI=YSUFAD('SURFLOADICE',-1)
YFA_CWDS=YSUFAD('SURFDIAMACCR',-1)
YFA_CWPS=YSUFAD('SURFPCPWSNOW',-1)
YFA_CWPI=YSUFAD('SURFPCPICE',-1)

! Miscellaneous
YFA_CAPE   =YSUFAD('SURFCAPE.POS.F00',-1)
YFA_CIEN   =YSUFAD('SURFCIEN.POS.F00',-1)
YFA_MUMLCAPE =YSUFAD('ATMOMUMLCAPE.POS',-1)
YFA_MLCAPE   =YSUFAD('ATMOMLCAPE.POS  ',-1)
YFA_TCVS   =YSUFAD('SURFTCVS.POS.F00',-1)
YFA_ASMC   =YSUFAD('SURFANAMOCON.POS',-1)
YFA_VSMC   =YSUFAD('VARPACKSURFMOCON',-1)
YFA_ACCGREL=YSUFAD('SURFACCGRELE    ',-1)

NVERBOSE=0

CMODEL   = ''
NIDCEN   = 85
LEXTERN  = .FALSE.
LSUPPDATE=.FALSE. ! And if somebody complains about that, please come to me. REK

!     ------------------------------------------------------------------

!*       2. READ NAMELIST
!           -------------

CALL POSNAM(NULNAM,'NAMFA')
READ(NULNAM,NAMFA)
WRITE(UNIT=NULOUT,FMT='(/,'' NAMELIST NAMFA'')')
WRITE(NULOUT,'(''   NVGRIB ='',I3,''   NBITPG ='',I3,''   NBITCS ='',I3, &
 & ''   NSTRON ='',I4,''   NPULAP ='',I2, ''  NVERBOSE ='', I2,'' LSUPPDATE = '',L2,&
 & '' CMODEL = '',A,'' LEXTERN = '',L2,'' NIDCEN = '',I3)') &
 & NVGRIB, NBITPG, NBITCS, NSTRON, NPULAP, NVERBOSE, LSUPPDATE, CMODEL, LEXTERN, NIDCEN

!     ------------------------------------------------------------------

!*       3. Control and set up of GRIB packing parameters for files ARPEGE/ALADIN
!           ---------------------------------------------------------------------

IF (NGRIBFILE==0.OR.LARPEGEF) THEN

  CALL FANMSG(NVERBOSE,NULOUT)
  CALL FAGIOT ( NVGRIB, NBITPG, NBITCS, NSTRON, NPULAP, IDMOPL )
  CALL FAREGI ('IDCEN', NIDCEN, 1_JPIM)
  
  IF (YFAL%NBITS     < 0) YFAL%NBITS=NBITPG
  IF (YFAI%NBITS     < 0) YFAI%NBITS=NBITPG
  IF (YFALCONV%NBITS < 0) YFALCONV%NBITS=NBITPG
  IF (YFAICONV%NBITS < 0) YFAICONV%NBITS=NBITPG
  IF (YFARCONV%NBITS < 0) YFARCONV%NBITS=NBITPG
  IF (YFASCONV%NBITS < 0) YFASCONV%NBITS=NBITPG
  IF (YFAUAL%NBITS   < 0) YFAUAL%NBITS=NBITPG
  IF (YFAUOM%NBITS   < 0) YFAUOM%NBITS=NBITPG
  IF (YFADAL%NBITS   < 0) YFADAL%NBITS=NBITPG
  IF (YFADOM%NBITS   < 0) YFADOM%NBITS=NBITPG
  IF (YFALRAD%NBITS  < 0) YFALRAD%NBITS=NBITPG
  IF (YFAIRAD%NBITS  < 0) YFAIRAD%NBITS=NBITPG
  IF (YFACLF%NBITS   < 0) YFACLF%NBITS=NBITPG
  IF (YFAS%NBITS     < 0) YFAS%NBITS=NBITPG
  IF (YFAR%NBITS     < 0) YFAR%NBITS=NBITPG
  IF (YFAG%NBITS     < 0) YFAG%NBITS=NBITPG
  IF (YFAH%NBITS     < 0) YFAH%NBITS=NBITPG
  IF (YFATKE%NBITS   < 0) YFATKE%NBITS=NBITPG
  IF (YFAEFB1%NBITS  < 0) YFAEFB1%NBITS=NBITPG
  IF (YFAEFB2%NBITS  < 0) YFAEFB2%NBITS=NBITPG
  IF (YFAEFB3%NBITS  < 0) YFAEFB3%NBITS=NBITPG
  IF (YFAO3%NBITS    < 0) YFAO3%NBITS=NBITPG
  IF (YFACPF%NBITS   < 0) YFACPF%NBITS=NBITPG
  IF (YFASPF%NBITS   < 0) YFASPF%NBITS=NBITPG
  
! Find out which values are used by creating a new file environement
  INBARI=0
  CALL FANOUV(IREP,NSCRTCH,.FALSE.,CLSCRTCH,'NEW',.TRUE.,.TRUE.,1,1,INBARI,CNMCA)  
  CALL FAVEUR(IREP,NSCRTCH,NVGRIB,NBITPG,NBITCS,NSTRON,NPULAP,IDMOPL)
  CALL FAIRNO(IREP,NSCRTCH,'DELETE')

ENDIF

WRITE(UNIT=NULOUT,FMT='(/,'' MODULE YOMFA'')')
WRITE(UNIT=NULOUT,FMT=&
 & '(''   NVGRIB ='',I3,''   NBITPG ='',I3,''   NBITCS ='',I3,&
 & ''   NSTRON ='',I4,''   NPULAP ='',I2,/)')&
 & NVGRIB,NBITPG, NBITCS, NSTRON, NPULAP  
WRITE(UNIT=NULOUT,FMT='(3(''( '',A16,1X,I3,'') ''))') &
 & YFAOROG  ,YFASP    ,YFAPSI   ,YFAKHI   ,YFAUGEO  ,YFAVGEO  , &
 & YFAT     ,YFAPD    ,YFAVD    ,YFAQ     ,YFAL     ,YFAI     , &
 & YFALRAD  ,YFAIRAD  ,YFALCONV ,YFAICONV ,YFARCONV ,YFASCONV , &
 & YFAUAL   ,YFAUOM   ,YFADAL   ,YFADOM   , &
 & YFAR     ,YFAS     ,YFAG     ,YFAH     ,YFATKE   ,YFAEFB1   , &
 & YFAEFB2  ,YFAEFB3  ,YFASRC   , & 
 & YFAO3    ,YFACLF   ,YFACPF   ,YFASPF   ,YFACVGQ  , &
 & YFASDSAT ,YFACVV   ,YFAQVA   , &
 & YFAUOM   ,YFAUAL   ,YFADOM   ,YFADAL   ,YFAUEN   ,YFAUNEBH , &
 & YFARKTH  ,YFARKTQV ,YFARKTQC, &
 & YFA_MSAT7C1, YFA_MSAT7C2, YFA_MSAT8C1, YFA_MSAT8C2, YFA_MSAT8C3, YFA_MSAT8C4, &
 & YFA_MSAT8C5, YFA_MSAT8C6, YFA_MSAT8C7, YFA_MSAT8C8, YFA_MSAT9C1, YFA_MSAT9C2, &
 & YFA_MSAT9C3, YFA_MSAT9C4, YFA_MSAT9C5, YFA_MSAT9C6, YFA_MSAT9C7, YFA_MSAT9C8, &
 & YFA_MSAT10C1, YFA_MSAT10C2, YFA_MSAT10C3, YFA_MSAT10C4, YFA_MSAT10C5, YFA_MSAT10C6, &
 & YFA_MSAT10C7, YFA_MSAT10C8, &
 & YFA_MSAT11C1, YFA_MSAT11C2, YFA_MSAT11C3, YFA_MSAT11C4, YFA_MSAT11C5, YFA_MSAT11C6, &
 & YFA_MSAT11C7, YFA_MSAT11C8, &
 & YFA_GOES11C1,YFA_GOES11C2,YFA_GOES11C3,YFA_GOES11C4,YFA_GOES12C1,YFA_GOES12C2,&
 & YFA_GOES12C3,YFA_GOES12C4,YFA_GOES15C1,YFA_GOES15C2,YFA_GOES15C3,YFA_GOES15C4, &
 & YFA_GOES16C1,YFA_GOES16C2,YFA_GOES16C3,YFA_GOES16C4,YFA_GOES16C5,YFA_GOES16C6, &
 & YFA_GOES16C7,YFA_GOES16C8,YFA_GOES16C9,YFA_GOES16C10,YFA_GOES17C1,YFA_GOES17C2, &
 & YFA_GOES17C3,YFA_GOES17C4,YFA_GOES17C5,YFA_GOES17C6,YFA_GOES17C7,YFA_GOES17C8, &
 & YFA_GOES17C9,YFA_GOES17C10,YFA_MTSAT1C1,YFA_MTSAT1C2,YFA_MTSAT1C3,YFA_MTSAT1C4,&
 & YFA_HIMA8C1,YFA_HIMA8C2,YFA_HIMA8C3,YFA_HIMA8C4,YFA_HIMA8C5,YFA_HIMA8C6, &
 & YFA_HIMA8C7,YFA_HIMA8C8,YFA_HIMA8C9,YFA_HIMA8C10, &
 & YFA_XTCC,  YFA_X10U,  YFA_X10V,  YFA_X10NU, YFA_X10NV, &
 & YFA_X2T ,  YFA_X2SH,  YFA_X2RH,  YFA_XCCC,  YFA_XHCC, YFA_XSIC, YFA_XSNWDE, &
 & YFA_XMCC,  YFA_XLCC,  YFA_XX2T,  YFA_XN2T,  YFA_XCVU,  YFA_XCVV,  YFA_XCVQ,  YFA_XCVS,  &
 & YFA_XTUU,  YFA_XTUV,  YFA_XTUQ,  YFA_XTUS,  YFA_XGDU,  YFA_XGDV,  YFA_XLSP,  YFA_XCP,   &
 & YFA_XLSS,  YFA_XCSF,  YFA_XLSG,  YFA_XCSG,  YFA_XLSH,  YFA_XCSH,  YFA_XSSR,  YFA_XSTR,  &
 & YFA_XTSR,  YFA_XTTR,  YFA_X10FF, YFA_XCAPE, YFA_XCTOP, YFA_XMOCO, YFA_XCLPH, YFA_XVEIN, YFA_XGUST, &
 & YFA_XCLPHMF,  YFA_XVMAXTH, &
 & YFA_XUGST, YFA_XVGST,YFA_XUGST2, YFA_XVGST2,YFA_XX2HU, YFA_XN2HU, YFA_XTHW,  YFA_XXDIAGH, YFA_XMRT, &
 & YFA_VISICLD, YFA_VISIHYD, YFA_MXCLWC, YFA_VISICLD2, YFA_VISIHYD2, YFA_MXCLWC2, YFA_XPTYPE, &
 & YFA_XPTYPESEV, YFA_XPTYPE2, YFA_XPTYPESEV2, YFA_X2TPW, &
 & YFA_CLSP , YFA_CCP  , YFA_CLSS , YFA_CCSF , YFA_CLSG , YFA_CCSG , YFA_CLSH , YFA_CCSH , &
 & YFA_CUSS , YFA_CVSS , YFA_CSSH , YFA_CSLH , YFA_CTSP , YFA_CTCC , YFA_CBLD , YFA_CSSR , &
 & YFA_CSTR , YFA_CTSR , YFA_CTTR , YFA_CCCC , YFA_CHCC , YFA_CMCC , YFA_CLCC , YFA_CUGW , &
 & YFA_CVGW , YFA_CUTO , YFA_CVTO , YFA_CE   , YFA_CS   , YFA_CT   , YFA_CLHE , YFA_CLHS , YFA_CLHT , &
 & YFA_CWS  , YFA_CSNS , YFA_CQTO , YFA_CTO3 , YFA_CTME , YFA_CICE , YFA_CLI  , YFA_CCVU , YFA_CCVV , &
 & YFA_CCVQ , YFA_CCVS , YFA_CTUQ , YFA_CTUS , YFA_CSOC , YFA_CTHC , YFA_CSOP , YFA_CDNI , YFA_CGNI , YFA_CTOP , &
 & YFA_CSOD , YFA_CTHD , YFA_CFON , YFA_CCHS , YFA_CEAS , YFA_CSRU , YFA_CDRU , YFA_CIRU , YFA_CETP , &
 & YFA_CTP  , YFA_CSMR , YFA_CTSOC, YFA_CTTHC, YFA_CDUTP, &
 & YFA_CWLS , YFA_CWLI , YFA_CWDS , YFA_CWPS , YFA_CWPI , &
 & YFA_CAPE , YFA_CIEN , YFA_MUMLCAPE, YFA_MLCAPE, YFA_TCVS , YFA_ASMC , YFA_VSMC , YFA_ACCGREL

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('SUFA',1,ZHOOK_HANDLE)
END SUBROUTINE SUFA
