MODULE GETDATA_LIMA_MOD

USE OMP_LIB
USE ARRAYS_MANIP, ONLY: SETUP, REPLICATE, NPROMIZE, INTERPOLATE, SET
USE PARKIND1, ONLY: JPRD

CONTAINS

SUBROUTINE GETDATA_LIMA (NPROMA, NGPBLKS, NFLEVG, KRR, KSV, NMOD_CCN, NMOD_IFN, NMOD_IMM, NSP, NCARB, NSOA, &
                        &ZTHVREFZIKB, PRHODREF_B, PEXNREF_B, PDZZ_B, PRHODJ_B, PPABSM_B, PDTHRAD_B, PTHT_B, &
                        &PRT_B, PSVT_B, PW_NU_B, PTHS_B, PRS_B, PSVS_B, PCLDFR_B, PICEFR_B, PPRCFR_B, PFPR_B, &
                        &PTHS_OUT_B, PRS_OUT_B, PSVS_OUT_B, ZINPRC_OUT_B, ZINDEP_OUT_B, PINPRR_OUT_B, ZINPRI_OUT_B, &
                        &PINPRS_OUT_B, PINPRG_OUT_B, PINPRH_OUT_B, PEVAP_OUT_B, PCLDFR_OUT_B, PICEFR_OUT_B, &
                        &PPRCFR_OUT_B, PFPR_OUT_B, &
                        &ZINPRC_B, ZINDEP_B, PINPRR_B, ZINPRI_B, PINPRS_B, PINPRG_B, PINPRH_B, PEVAP_B, &
                        &PAERO_B, PSOLORG_B, PMI_B, &
                        &PHLC_HRC_B, PHLC_HCF_B, PHLI_HRI_B, PHLI_HCF_B, &
                        &LDVERBOSE)
IMPLICIT NONE

INTEGER, PARAMETER :: IFILE = 77

INTEGER      :: KLON 
INTEGER      :: KIDIA  
INTEGER      :: KFDIA  
INTEGER      :: KLEV  
INTEGER, INTENT(OUT) :: KRR, KSV, NMOD_CCN, NMOD_IFN, NMOD_IMM
REAL, INTENT(OUT) :: ZTHVREFZIKB
INTEGER      :: KDUM
REAL              :: PTSTEP

LOGICAL, INTENT(IN) :: LDVERBOSE

REAL, INTENT(OUT), ALLOCATABLE   :: PRHODREF_B   (:,:,:) 
REAL, INTENT(OUT), ALLOCATABLE   :: PEXNREF_B    (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PDZZ_B       (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PRHODJ_B     (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PPABSM_B     (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PDTHRAD_B    (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PTHT_B       (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PRT_B        (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PSVT_B       (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PW_NU_B      (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PTHS_B       (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PRS_B        (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PSVS_B       (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PCLDFR_B     (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PICEFR_B     (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PPRCFR_B     (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PFPR_B       (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PTHS_OUT_B   (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PRS_OUT_B    (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PSVS_OUT_B   (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: ZINPRC_OUT_B (:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: ZINDEP_OUT_B (:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PINPRR_OUT_B (:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: ZINPRI_OUT_B (:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PINPRS_OUT_B (:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PINPRG_OUT_B (:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PINPRH_OUT_B (:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PEVAP_OUT_B  (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PCLDFR_OUT_B (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PICEFR_OUT_B (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PPRCFR_OUT_B (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PFPR_OUT_B   (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: ZINPRC_B     (:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: ZINDEP_B     (:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PINPRR_B     (:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: ZINPRI_B     (:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PINPRS_B     (:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PINPRG_B     (:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PINPRH_B     (:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PEVAP_B      (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PAERO_B      (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PSOLORG_B    (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PMI_B        (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PHLC_HRC_B     (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PHLC_HCF_B     (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PHLI_HRI_B     (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PHLI_HCF_B     (:,:,:)

REAL(KIND=JPRD), ALLOCATABLE   :: PRHODREF     (:,:,:) 
REAL(KIND=JPRD), ALLOCATABLE   :: PEXNREF      (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PDZZ         (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PRHODJ       (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PPABSM       (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PDTHRAD      (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PTHT         (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PRT          (:,:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PSVT         (:,:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PW_NU        (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PTHS         (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PRS          (:,:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PSVS         (:,:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PCLDFR       (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PICEFR       (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PPRCFR       (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PFPR         (:,:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PTHS_OUT     (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PRS_OUT      (:,:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PSVS_OUT     (:,:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: ZINPRC_OUT   (:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: ZINDEP_OUT   (:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PINPRR_OUT   (:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: ZINPRI_OUT   (:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PINPRS_OUT   (:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PINPRG_OUT   (:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PINPRH_OUT   (:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PEVAP_OUT    (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PCLDFR_OUT   (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PICEFR_OUT   (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PPRCFR_OUT   (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PFPR_OUT     (:,:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PHLC_HRC       (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PHLC_HCF       (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PHLI_HRI       (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PHLI_HCF       (:,:,:)

INTEGER, INTENT(IN) :: NPROMA, NGPBLKS
INTEGER, INTENT(OUT) :: NSP, NCARB, NSOA
INTEGER :: NGPTOT
INTEGER, INTENT(INOUT) :: NFLEVG
INTEGER :: IOFF, IBL
LOGICAL :: LLEXIST
CHARACTER(LEN=32) :: CLFILE

CALL SETUP()

NGPTOT = NPROMA * NGPBLKS

IBL = 1
NSP=1
NCARB=1
NSOA=1
WRITE (CLFILE, '("data/",I8.8,".dat")') IBL
OPEN (IFILE, FILE=TRIM (CLFILE), FORM='UNFORMATTED') 
READ (IFILE) KLON, KDUM, KLEV
READ (IFILE) KRR, KSV
CLOSE (IFILE)

IF (NFLEVG < 0) NFLEVG = KLEV

ALLOCATE (PRHODREF_B   (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PEXNREF_B    (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PDZZ_B       (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PRHODJ_B     (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PPABSM_B     (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PDTHRAD_B    (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PTHT_B       (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PRT_B        (NPROMA,NFLEVG,KRR,NGPBLKS))
ALLOCATE (PSVT_B       (NPROMA,NFLEVG,KSV,NGPBLKS))
ALLOCATE (PW_NU_B      (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PTHS_B       (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PRS_B        (NPROMA,NFLEVG,KRR,NGPBLKS))
ALLOCATE (PSVS_B       (NPROMA,NFLEVG,KSV,NGPBLKS))
ALLOCATE (PCLDFR_B     (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PICEFR_B     (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PPRCFR_B     (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PFPR_B       (NPROMA,NFLEVG,KRR,NGPBLKS))
ALLOCATE (PTHS_OUT_B   (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PRS_OUT_B    (NPROMA,NFLEVG,KRR,NGPBLKS))
ALLOCATE (PSVS_OUT_B   (NPROMA,NFLEVG,KSV,NGPBLKS))
ALLOCATE (ZINPRC_OUT_B (NPROMA,NGPBLKS))
ALLOCATE (ZINDEP_OUT_B (NPROMA,NGPBLKS))
ALLOCATE (PINPRR_OUT_B (NPROMA,NGPBLKS))
ALLOCATE (ZINPRI_OUT_B (NPROMA,NGPBLKS))
ALLOCATE (PINPRS_OUT_B (NPROMA,NGPBLKS))
ALLOCATE (PINPRG_OUT_B (NPROMA,NGPBLKS))
ALLOCATE (PINPRH_OUT_B (NPROMA,NGPBLKS))
ALLOCATE (PEVAP_OUT_B  (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PCLDFR_OUT_B (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PICEFR_OUT_B (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PPRCFR_OUT_B (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PFPR_OUT_B   (NPROMA,NFLEVG,KRR,NGPBLKS))
ALLOCATE (ZINPRC_B     (NPROMA,NGPBLKS))
ALLOCATE (ZINDEP_B     (NPROMA,NGPBLKS))
ALLOCATE (PINPRR_B     (NPROMA,NGPBLKS))
ALLOCATE (ZINPRI_B     (NPROMA,NGPBLKS))
ALLOCATE (PINPRS_B     (NPROMA,NGPBLKS))
ALLOCATE (PINPRG_B     (NPROMA,NGPBLKS))
ALLOCATE (PINPRH_B     (NPROMA,NGPBLKS))
ALLOCATE (PEVAP_B      (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PAERO_B      (NPROMA,NFLEVG,KSV,NGPBLKS))
ALLOCATE (PSOLORG_B    (NPROMA,NFLEVG,10,NGPBLKS))
ALLOCATE (PMI_B        (NPROMA,NFLEVG,NSP+NCARB+NSOA,NGPBLKS))
ALLOCATE (PHLC_HRC_B   (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PHLC_HCF_B   (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PHLI_HRI_B   (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PHLI_HCF_B   (NPROMA,NFLEVG,NGPBLKS))

CALL SET (PRHODREF_B   )
CALL SET (PEXNREF_B    )
CALL SET (PDZZ_B       )
CALL SET (PRHODJ_B     )
CALL SET (PPABSM_B     )
CALL SET (PDTHRAD_B    )
CALL SET (PTHT_B       )
CALL SET (PRT_B        )
CALL SET (PSVT_B       )
CALL SET (PW_NU_B      )
CALL SET (PTHS_B       )
CALL SET (PRS_B        )
CALL SET (PSVS_B       )
CALL SET (PCLDFR_B     )
CALL SET (PICEFR_B     )
CALL SET (PPRCFR_B     )
CALL SET (PFPR_B       )
CALL SET (PTHS_OUT_B   )
CALL SET (PRS_OUT_B    )
CALL SET (PSVS_OUT_B   )
CALL SET (ZINPRC_OUT_B )
CALL SET (ZINDEP_OUT_B )
CALL SET (PINPRR_OUT_B )
CALL SET (ZINPRI_OUT_B )
CALL SET (PINPRS_OUT_B )
CALL SET (PINPRG_OUT_B )
CALL SET (PINPRH_OUT_B )
CALL SET (PEVAP_OUT_B  )
CALL SET (PCLDFR_OUT_B )
CALL SET (PICEFR_OUT_B )
CALL SET (PPRCFR_OUT_B )
CALL SET (PFPR_OUT_B   )
CALL SET (PHLC_HRC_B    )
CALL SET (PHLC_HCF_B    )
CALL SET (PHLI_HRI_B    )
CALL SET (PHLI_HCF_B    )

IOFF = 0
IBL = 0
LLEXIST = .TRUE.

DO WHILE(LLEXIST)
  IBL = IBL + 1
  WRITE (CLFILE, '("data/",I8.8,".dat")') IBL

  INQUIRE (FILE=TRIM (CLFILE), EXIST=LLEXIST)

  IF (LDVERBOSE) PRINT *, TRIM (CLFILE)

  IF (.NOT. LLEXIST) EXIT

  OPEN (IFILE, FILE=TRIM (CLFILE), FORM='UNFORMATTED') 
  
  READ (IFILE) KLON, KDUM, KLEV
  READ (IFILE) KRR, KSV
  READ (IFILE) PTSTEP, NMOD_CCN, NMOD_IFN, NMOD_IMM

  IF (IBL == 1) THEN
    ALLOCATE (PRHODREF     (NGPTOT,KLEV,1))
    ALLOCATE (PEXNREF      (NGPTOT,KLEV,1))
    ALLOCATE (PDZZ         (NGPTOT,KLEV,1))
    ALLOCATE (PRHODJ       (NGPTOT,KLEV,1))
    ALLOCATE (PPABSM       (NGPTOT,KLEV,1))
    ALLOCATE (PDTHRAD      (NGPTOT,KLEV,1))
    ALLOCATE (PTHT         (NGPTOT,KLEV,1))
    ALLOCATE (PRT          (NGPTOT,KLEV,KRR,1))
    ALLOCATE (PSVT         (NGPTOT,KLEV,KSV,1))
    ALLOCATE (PW_NU        (NGPTOT,KLEV,1))
    ALLOCATE (PTHS         (NGPTOT,KLEV,1))
    ALLOCATE (PRS          (NGPTOT,KLEV,KRR,1))
    ALLOCATE (PSVS         (NGPTOT,KLEV,KSV,1))
    ALLOCATE (PCLDFR       (NGPTOT,KLEV,1))
    ALLOCATE (PICEFR       (NGPTOT,KLEV,1))
    ALLOCATE (PPRCFR       (NGPTOT,KLEV,1))
    ALLOCATE (PFPR         (NGPTOT,KLEV,KRR,1))
    ALLOCATE (PTHS_OUT     (NGPTOT,KLEV,1))
    ALLOCATE (PRS_OUT      (NGPTOT,KLEV,KRR,1))
    ALLOCATE (PSVS_OUT     (NGPTOT,KLEV,KSV,1))
    ALLOCATE (ZINPRC_OUT   (NGPTOT,1))
    ALLOCATE (ZINDEP_OUT   (NGPTOT,1))
    ALLOCATE (PINPRR_OUT   (NGPTOT,1))
    ALLOCATE (ZINPRI_OUT   (NGPTOT,1))
    ALLOCATE (PINPRS_OUT   (NGPTOT,1))
    ALLOCATE (PINPRG_OUT   (NGPTOT,1))
    ALLOCATE (PINPRH_OUT   (NGPTOT,1))
    ALLOCATE (PEVAP_OUT    (NGPTOT,KLEV,1))
    ALLOCATE (PCLDFR_OUT   (NGPTOT,KLEV,1))
    ALLOCATE (PICEFR_OUT   (NGPTOT,KLEV,1))
    ALLOCATE (PPRCFR_OUT   (NGPTOT,KLEV,1))
    ALLOCATE (PFPR_OUT     (NGPTOT,KLEV,KRR,1))
    ALLOCATE (PHLC_HRC     (NGPTOT,KLEV,1))
    ALLOCATE (PHLC_HCF     (NGPTOT,KLEV,1))
    ALLOCATE (PHLI_HRI     (NGPTOT,KLEV,1))
    ALLOCATE (PHLI_HCF     (NGPTOT,KLEV,1))
  ENDIF

  IF (IOFF+KLON > NGPTOT) THEN
    EXIT
  ENDIF

  READ (IFILE) PRHODREF     (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PEXNREF      (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PDZZ         (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) ZTHVREFZIKB
  READ (IFILE) PRHODJ       (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PPABSM       (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PDTHRAD      (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PTHT         (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PRT          (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) PSVT         (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) PW_NU        (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PTHS         (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PRS          (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) PSVS         (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) PCLDFR       (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PICEFR       (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PPRCFR       (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PFPR         (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) PTHS_OUT     (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PRS_OUT      (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) PSVS_OUT     (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) ZINPRC_OUT   (IOFF+1:IOFF+KLON,1)
  READ (IFILE) ZINDEP_OUT   (IOFF+1:IOFF+KLON,1)
  READ (IFILE) PINPRR_OUT   (IOFF+1:IOFF+KLON,1)
  READ (IFILE) ZINPRI_OUT   (IOFF+1:IOFF+KLON,1)
  READ (IFILE) PINPRS_OUT   (IOFF+1:IOFF+KLON,1)
  READ (IFILE) PINPRG_OUT   (IOFF+1:IOFF+KLON,1)
  READ (IFILE) PINPRH_OUT   (IOFF+1:IOFF+KLON,1)
  READ (IFILE) PEVAP_OUT    (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PCLDFR_OUT   (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PICEFR_OUT   (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PPRCFR_OUT   (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PFPR_OUT     (IOFF+1:IOFF+KLON,:,:,1)
!  READ (IFILE) PHLC_HRC     (IOFF+1:IOFF+KLON,:,1)
!  READ (IFILE) PHLC_HCF     (IOFF+1:IOFF+KLON,:,1)
!  READ (IFILE) PHLI_HRI     (IOFF+1:IOFF+KLON,:,1)
!  READ (IFILE) PHLI_HCF     (IOFF+1:IOFF+KLON,:,1)

  CLOSE (IFILE)

  IOFF = IOFF + KLON

ENDDO

IF (NFLEVG /= KLEV) THEN
  CALL INTERPOLATE (NFLEVG, IOFF,  PRHODREF     )
  CALL INTERPOLATE (NFLEVG, IOFF,  PEXNREF      )
  CALL INTERPOLATE (NFLEVG, IOFF,  PDZZ         )
  CALL INTERPOLATE (NFLEVG, IOFF,  PRHODJ       )
  CALL INTERPOLATE (NFLEVG, IOFF,  PPABSM       )
  CALL INTERPOLATE (NFLEVG, IOFF,  PDTHRAD      )
  CALL INTERPOLATE (NFLEVG, IOFF,  PTHT         )
  CALL INTERPOLATE (NFLEVG, IOFF,  PRT          )
  CALL INTERPOLATE (NFLEVG, IOFF,  PSVT         )
  CALL INTERPOLATE (NFLEVG, IOFF,  PW_NU        )
  CALL INTERPOLATE (NFLEVG, IOFF,  PTHS         )
  CALL INTERPOLATE (NFLEVG, IOFF,  PRS          )
  CALL INTERPOLATE (NFLEVG, IOFF,  PSVS         )
  CALL INTERPOLATE (NFLEVG, IOFF,  PCLDFR       )
  CALL INTERPOLATE (NFLEVG, IOFF,  PICEFR       )
  CALL INTERPOLATE (NFLEVG, IOFF,  PPRCFR       )
  CALL INTERPOLATE (NFLEVG, IOFF,  PFPR         )
  CALL INTERPOLATE (NFLEVG, IOFF,  PTHS_OUT     )
  CALL INTERPOLATE (NFLEVG, IOFF,  PRS_OUT      )
  CALL INTERPOLATE (NFLEVG, IOFF,  PSVS_OUT     )
  CALL INTERPOLATE (NFLEVG, IOFF,  PEVAP_OUT    )
  CALL INTERPOLATE (NFLEVG, IOFF,  PCLDFR_OUT   )
  CALL INTERPOLATE (NFLEVG, IOFF,  PICEFR_OUT   )
  CALL INTERPOLATE (NFLEVG, IOFF,  PPRCFR_OUT   )
  CALL INTERPOLATE (NFLEVG, IOFF,  PFPR_OUT     )
!  CALL INTERPOLATE (NFLEVG, IOFF, PHLC_HRC    )
!  CALL INTERPOLATE (NFLEVG, IOFF, PHLC_HCF    )
!  CALL INTERPOLATE (NFLEVG, IOFF, PHLI_HRI    )
!  CALL INTERPOLATE (NFLEVG, IOFF, PHLI_HCF    )
ENDIF

CALL REPLICATE (IOFF, PRHODREF     (:,:,1))
CALL REPLICATE (IOFF, PEXNREF      (:,:,1))
CALL REPLICATE (IOFF, PDZZ         (:,:,1))
CALL REPLICATE (IOFF, PRHODJ       (:,:,1))
CALL REPLICATE (IOFF, PPABSM       (:,:,1))
CALL REPLICATE (IOFF, PDTHRAD      (:,:,1))
CALL REPLICATE (IOFF, PTHT         (:,:,1))
CALL REPLICATE (IOFF, PRT          (:,:,:,1))
CALL REPLICATE (IOFF, PSVT         (:,:,:,1))
CALL REPLICATE (IOFF, PW_NU        (:,:,1))
CALL REPLICATE (IOFF, PTHS         (:,:,1))
CALL REPLICATE (IOFF, PRS          (:,:,:,1))
CALL REPLICATE (IOFF, PSVS         (:,:,:,1))
CALL REPLICATE (IOFF, PCLDFR       (:,:,1))
CALL REPLICATE (IOFF, PICEFR       (:,:,1))
CALL REPLICATE (IOFF, PPRCFR       (:,:,1))
CALL REPLICATE (IOFF, PFPR         (:,:,:,1))
CALL REPLICATE (IOFF, PTHS_OUT     (:,:,1))
CALL REPLICATE (IOFF, PRS_OUT      (:,:,:,1))
CALL REPLICATE (IOFF, PSVS_OUT     (:,:,:,1))
CALL REPLICATE (IOFF, ZINPRC_OUT   (:,1))
CALL REPLICATE (IOFF, ZINDEP_OUT   (:,1))
CALL REPLICATE (IOFF, PINPRR_OUT   (:,1))
CALL REPLICATE (IOFF, ZINPRI_OUT   (:,1))
CALL REPLICATE (IOFF, PINPRS_OUT   (:,1))
CALL REPLICATE (IOFF, PINPRG_OUT   (:,1))
CALL REPLICATE (IOFF, PINPRH_OUT   (:,1))
CALL REPLICATE (IOFF, PEVAP_OUT    (:,:,1))
CALL REPLICATE (IOFF, PCLDFR_OUT   (:,:,1))
CALL REPLICATE (IOFF, PICEFR_OUT   (:,:,1))
CALL REPLICATE (IOFF, PPRCFR_OUT   (:,:,1))
CALL REPLICATE (IOFF, PFPR_OUT     (:,:,:,1))
!CALL REPLICATE (IOFF, PHLC_HRC     (:, :, 1))
!CALL REPLICATE (IOFF, PHLC_HCF     (:, :, 1))
!CALL REPLICATE (IOFF, PHLI_HRI     (:, :, 1))
!CALL REPLICATE (IOFF, PHLI_HCF     (:, :, 1))

CALL NPROMIZE (NPROMA, PRHODREF     , PRHODREF_B    )
CALL NPROMIZE (NPROMA, PEXNREF      , PEXNREF_B     )
CALL NPROMIZE (NPROMA, PDZZ         , PDZZ_B        )
CALL NPROMIZE (NPROMA, PRHODJ       , PRHODJ_B      )
CALL NPROMIZE (NPROMA, PPABSM       , PPABSM_B      )
CALL NPROMIZE (NPROMA, PDTHRAD      , PDTHRAD_B     )
CALL NPROMIZE (NPROMA, PTHT         , PTHT_B        )
CALL NPROMIZE (NPROMA, PRT          , PRT_B         )
CALL NPROMIZE (NPROMA, PSVT         , PSVT_B        )
CALL NPROMIZE (NPROMA, PW_NU        , PW_NU_B       )
CALL NPROMIZE (NPROMA, PTHS         , PTHS_B        )
CALL NPROMIZE (NPROMA, PRS          , PRS_B         )
CALL NPROMIZE (NPROMA, PSVS         , PSVS_B        )
CALL NPROMIZE (NPROMA, PCLDFR       , PCLDFR_B      )
CALL NPROMIZE (NPROMA, PICEFR       , PICEFR_B      )
CALL NPROMIZE (NPROMA, PPRCFR       , PPRCFR_B      )
CALL NPROMIZE (NPROMA, PFPR         , PFPR_B        )
CALL NPROMIZE (NPROMA, PTHS_OUT     , PTHS_OUT_B    )
CALL NPROMIZE (NPROMA, PRS_OUT      , PRS_OUT_B     )
CALL NPROMIZE (NPROMA, PSVS_OUT     , PSVS_OUT_B    )
CALL NPROMIZE (NPROMA, ZINPRC_OUT   , ZINPRC_OUT_B  )
CALL NPROMIZE (NPROMA, ZINDEP_OUT   , ZINDEP_OUT_B  )
CALL NPROMIZE (NPROMA, PINPRR_OUT   , PINPRR_OUT_B  )
CALL NPROMIZE (NPROMA, ZINPRI_OUT   , ZINPRI_OUT_B  )
CALL NPROMIZE (NPROMA, PINPRS_OUT   , PINPRS_OUT_B  )
CALL NPROMIZE (NPROMA, PINPRG_OUT   , PINPRG_OUT_B  )
CALL NPROMIZE (NPROMA, PINPRH_OUT   , PINPRH_OUT_B  )
CALL NPROMIZE (NPROMA, PEVAP_OUT    , PEVAP_OUT_B   )
CALL NPROMIZE (NPROMA, PCLDFR_OUT   , PCLDFR_OUT_B  )
CALL NPROMIZE (NPROMA, PICEFR_OUT   , PICEFR_OUT_B  )
CALL NPROMIZE (NPROMA, PPRCFR_OUT   , PPRCFR_OUT_B  )
CALL NPROMIZE (NPROMA, PFPR_OUT     , PFPR_OUT_B    )
!CALL NPROMIZE (NPROMA, PHLC_HRC    ,  PHLC_HRC_B      )
!CALL NPROMIZE (NPROMA, PHLC_HCF    ,  PHLC_HCF_B      )
!CALL NPROMIZE (NPROMA, PHLI_HRI    ,  PHLI_HRI_B      )
!CALL NPROMIZE (NPROMA, PHLI_HCF    ,  PHLI_HCF_B      )

END SUBROUTINE 

END  MODULE
