MODULE GETDATA_LIMA_ADJUST_MOD

USE OMP_LIB
USE ARRAYS_MANIP, ONLY: SETUP, REPLICATE, NPROMIZE, INTERPOLATE, SET
USE PARKIND1, ONLY: JPRD

CONTAINS

SUBROUTINE GETDATA_LIMA_ADJUST (NPROMA, NGPBLKS, NFLEVG, KRR, KSV, NSP, NCARB, NSOA, &
                               &PRHODREF_B, PRHODJ_B, PEXNREF_B, ZSIGQSAT_B, PSIGS_B, PMFCONV_B, PPABSM_B, ZZZ_B, &
                               &PDTHRAD_B, PW_NU_B, PRT_B, PRS_B, PSVT_B, PSVS_B, PTHS_B, &
                               &PRC_MF_B, PRI_MF_B, PCF_MF_B, PRS_OUT_B, PSVS_OUT_B, PTHS_OUT_B, &
                               &PSRCS_B, PCLDFR_B, PICEFR_B, &
                               &PSRCS_OUT_B, PCLDFR_OUT_B, PICEFR_OUT_B, &
                               &PAERO_B, PSOLORG_B, PMI_B, &
                               &LDVERBOSE)

IMPLICIT NONE

INTEGER, PARAMETER :: IFILE = 77

INTEGER      :: KLON 
INTEGER      :: KIDIA  
INTEGER      :: KFDIA  
INTEGER      :: KLEV  
INTEGER, INTENT(OUT) :: KRR, KSV
INTEGER      :: KDUM
CHARACTER(LEN=80) :: CCONDENS
CHARACTER(LEN=4)  :: CLAMBDA3
LOGICAL           :: OSUBG_COND, OSIGMAS
REAL              :: PTSTEP, PSIGQSAT

LOGICAL, INTENT(IN) :: LDVERBOSE

REAL, INTENT(OUT), ALLOCATABLE   :: PRHODREF_B     (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PRHODJ_B       (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PEXNREF_B      (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: ZSIGQSAT_B     (:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PSIGS_B        (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PMFCONV_B      (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PPABSM_B       (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: ZZZ_B          (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PDTHRAD_B      (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PW_NU_B        (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PRT_B          (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PRS_B          (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PSVT_B         (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PSVS_B         (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PTHS_B         (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PRC_MF_B       (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PRI_MF_B       (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PCF_MF_B       (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PRS_OUT_B      (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PSVS_OUT_B     (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PTHS_OUT_B     (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PSRCS_B        (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PCLDFR_B       (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PICEFR_B       (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PSRCS_OUT_B    (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PCLDFR_OUT_B   (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PICEFR_OUT_B   (:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PAERO_B      (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PSOLORG_B    (:,:,:,:)
REAL, INTENT(OUT), ALLOCATABLE   :: PMI_B        (:,:,:,:)

REAL(KIND=JPRD), ALLOCATABLE   :: PRHODREF       (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PRHODJ         (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PEXNREF        (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PSIGS          (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PMFCONV        (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PPABSM         (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: ZZZ            (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PDTHRAD        (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PW_NU          (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PRT            (:,:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PRS            (:,:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PSVT           (:,:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PSVS           (:,:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PTHS           (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PRC_MF         (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PRI_MF         (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PCF_MF         (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PRS_OUT        (:,:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PSVS_OUT       (:,:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PTHS_OUT       (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PSRCS_OUT      (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PCLDFR_OUT     (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE   :: PICEFR_OUT     (:,:,:)

INTEGER, INTENT(IN) :: NPROMA, NGPBLKS
INTEGER, INTENT(OUT) :: NSP, NCARB, NSOA
INTEGER :: NGPTOT
INTEGER, INTENT(INOUT) :: NFLEVG
INTEGER :: IOFF, IBL
LOGICAL :: LLEXIST
CHARACTER(LEN=32) :: CLFILE

CALL SETUP()

NGPTOT = NPROMA * NGPBLKS

IBL = 1
NSP=1
NCARB=1
NSOA=1
WRITE (CLFILE, '("data/",I8.8,".dat")') IBL
OPEN (IFILE, FILE=TRIM (CLFILE), FORM='UNFORMATTED') 
READ (IFILE) KLON, KDUM, KLEV
READ (IFILE) KRR, KSV
CLOSE (IFILE)

IF (NFLEVG < 0) NFLEVG = KLEV

ALLOCATE (ZSIGQSAT_B     (NPROMA,NGPBLKS))
ALLOCATE (PRHODREF_B     (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PRHODJ_B       (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PEXNREF_B      (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PSIGS_B        (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PMFCONV_B      (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PPABSM_B       (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (ZZZ_B          (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PDTHRAD_B      (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PW_NU_B        (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PRT_B          (NPROMA,NFLEVG,KRR,NGPBLKS))
ALLOCATE (PRS_B          (NPROMA,NFLEVG,KRR,NGPBLKS))
ALLOCATE (PSVT_B         (NPROMA,NFLEVG,KSV,NGPBLKS))
ALLOCATE (PSVS_B         (NPROMA,NFLEVG,KSV,NGPBLKS))
ALLOCATE (PTHS_B         (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PRC_MF_B       (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PRI_MF_B       (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PCF_MF_B       (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PRS_OUT_B      (NPROMA,NFLEVG,KRR,NGPBLKS))
ALLOCATE (PSVS_OUT_B     (NPROMA,NFLEVG,KSV,NGPBLKS))
ALLOCATE (PTHS_OUT_B     (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PSRCS_B        (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PCLDFR_B       (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PICEFR_B       (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PSRCS_OUT_B    (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PCLDFR_OUT_B   (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PICEFR_OUT_B   (NPROMA,NFLEVG,NGPBLKS))
ALLOCATE (PAERO_B      (NPROMA,NFLEVG,KSV,NGPBLKS))
ALLOCATE (PSOLORG_B    (NPROMA,NFLEVG,10,NGPBLKS))
ALLOCATE (PMI_B        (NPROMA,NFLEVG,NSP+NCARB+NSOA,NGPBLKS))

CALL SET (ZSIGQSAT_B     )
CALL SET (PRHODREF_B     )
CALL SET (PRHODJ_B       )
CALL SET (PEXNREF_B      )
CALL SET (PSIGS_B        )
CALL SET (PMFCONV_B      )
CALL SET (PPABSM_B       )
CALL SET (ZZZ_B          )
CALL SET (PDTHRAD_B      )
CALL SET (PW_NU_B        )
CALL SET (PRT_B          )
CALL SET (PRS_B          )
CALL SET (PSVT_B         )
CALL SET (PSVS_B         )
CALL SET (PTHS_B         )
CALL SET (PRC_MF_B       )
CALL SET (PRI_MF_B       )
CALL SET (PCF_MF_B       )
CALL SET (PRS_OUT_B      )
CALL SET (PSVS_OUT_B     )
CALL SET (PTHS_OUT_B     )
CALL SET (PSRCS_B        )
CALL SET (PCLDFR_B       )
CALL SET (PICEFR_B       )
CALL SET (PSRCS_OUT_B    )
CALL SET (PCLDFR_OUT_B   )
CALL SET (PICEFR_OUT_B   )

ZSIGQSAT_B     = PSIGQSAT

IOFF = 0
IBL = 0
LLEXIST = .TRUE.

DO WHILE(LLEXIST)
  IBL = IBL + 1
  WRITE (CLFILE, '("data/",I8.8,".dat")') IBL

  INQUIRE (FILE=TRIM (CLFILE), EXIST=LLEXIST)

  IF (LDVERBOSE) PRINT *, TRIM (CLFILE)

  IF (.NOT. LLEXIST) EXIT

  OPEN (IFILE, FILE=TRIM (CLFILE), FORM='UNFORMATTED') 
  
  READ (IFILE) KLON, KDUM, KLEV
  READ (IFILE) KRR, KSV
  READ (IFILE) CCONDENS, CLAMBDA3
  READ (IFILE) OSUBG_COND, OSIGMAS, PTSTEP, PSIGQSAT

  IF (IBL == 1) THEN
    ALLOCATE (PRHODREF       (NGPTOT,KLEV,1))
    ALLOCATE (PRHODJ         (NGPTOT,KLEV,1))
    ALLOCATE (PEXNREF        (NGPTOT,KLEV,1))
    ALLOCATE (PSIGS          (NGPTOT,KLEV,1))
    ALLOCATE (PMFCONV        (NGPTOT,KLEV,1))
    ALLOCATE (PPABSM         (NGPTOT,KLEV,1))
    ALLOCATE (ZZZ            (NGPTOT,KLEV,1))
    ALLOCATE (PDTHRAD        (NGPTOT,KLEV,1))
    ALLOCATE (PW_NU          (NGPTOT,KLEV,1))
    ALLOCATE (PRT            (NGPTOT,KLEV,KRR,1))
    ALLOCATE (PRS            (NGPTOT,KLEV,KRR,1))
    ALLOCATE (PSVT           (NGPTOT,KLEV,KSV,1))
    ALLOCATE (PSVS           (NGPTOT,KLEV,KSV,1))
    ALLOCATE (PTHS           (NGPTOT,KLEV,1))
    ALLOCATE (PRC_MF         (NGPTOT,KLEV,1))
    ALLOCATE (PRI_MF         (NGPTOT,KLEV,1))
    ALLOCATE (PCF_MF         (NGPTOT,KLEV,1))
    ALLOCATE (PRS_OUT        (NGPTOT,KLEV,KRR,1))
    ALLOCATE (PSVS_OUT       (NGPTOT,KLEV,KSV,1))
    ALLOCATE (PTHS_OUT       (NGPTOT,KLEV,1))
    ALLOCATE (PSRCS_OUT      (NGPTOT,KLEV,1))
    ALLOCATE (PCLDFR_OUT     (NGPTOT,KLEV,1))
    ALLOCATE (PICEFR_OUT     (NGPTOT,KLEV,1))
  ENDIF

  IF (IOFF+KLON > NGPTOT) THEN
    EXIT
  ENDIF

  READ (IFILE) PRHODREF       (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PRHODJ         (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PEXNREF        (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PSIGS          (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PMFCONV        (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PPABSM         (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) ZZZ            (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PDTHRAD        (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PW_NU          (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PRT            (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) PRS            (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) PSVT           (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) PSVS           (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) PTHS           (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PRC_MF         (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PRI_MF         (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PCF_MF         (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PRS_OUT        (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) PSVS_OUT       (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) PTHS_OUT       (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PSRCS_OUT      (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PCLDFR_OUT     (IOFF+1:IOFF+KLON,:,1)
  READ (IFILE) PICEFR_OUT     (IOFF+1:IOFF+KLON,:,1)
  
  CLOSE (IFILE)

  IOFF = IOFF + KLON

ENDDO

IF (NFLEVG /= KLEV) THEN
  CALL INTERPOLATE (NFLEVG, IOFF, PRHODREF   )
  CALL INTERPOLATE (NFLEVG, IOFF, PRHODJ     )
  CALL INTERPOLATE (NFLEVG, IOFF, PEXNREF    )
  CALL INTERPOLATE (NFLEVG, IOFF, PSIGS      )
  CALL INTERPOLATE (NFLEVG, IOFF, PMFCONV    )
  CALL INTERPOLATE (NFLEVG, IOFF, PPABSM     )
  CALL INTERPOLATE (NFLEVG, IOFF, ZZZ        )
  CALL INTERPOLATE (NFLEVG, IOFF, PDTHRAD    )
  CALL INTERPOLATE (NFLEVG, IOFF, PW_NU      )
  CALL INTERPOLATE (NFLEVG, IOFF, PRT        )
  CALL INTERPOLATE (NFLEVG, IOFF, PRS        )
  CALL INTERPOLATE (NFLEVG, IOFF, PSVT       )
  CALL INTERPOLATE (NFLEVG, IOFF, PSVS       )
  CALL INTERPOLATE (NFLEVG, IOFF, PTHS       )
  CALL INTERPOLATE (NFLEVG, IOFF, PRC_MF     )
  CALL INTERPOLATE (NFLEVG, IOFF, PRI_MF     )
  CALL INTERPOLATE (NFLEVG, IOFF, PCF_MF     )
  CALL INTERPOLATE (NFLEVG, IOFF, PRS_OUT    )
  CALL INTERPOLATE (NFLEVG, IOFF, PSVS_OUT   )
  CALL INTERPOLATE (NFLEVG, IOFF, PTHS_OUT   )
  CALL INTERPOLATE (NFLEVG, IOFF, PSRCS_OUT  )
  CALL INTERPOLATE (NFLEVG, IOFF, PCLDFR_OUT )
  CALL INTERPOLATE (NFLEVG, IOFF, PICEFR_OUT )
ENDIF

CALL REPLICATE (IOFF, PRHODREF       (:,:,1))
CALL REPLICATE (IOFF, PRHODJ         (:,:,1))
CALL REPLICATE (IOFF, PEXNREF        (:,:,1))
CALL REPLICATE (IOFF, PSIGS          (:,:,1))
CALL REPLICATE (IOFF, PMFCONV        (:,:,1))
CALL REPLICATE (IOFF, PPABSM         (:,:,1))
CALL REPLICATE (IOFF, ZZZ            (:,:,1))
CALL REPLICATE (IOFF, PDTHRAD        (:,:,1))
CALL REPLICATE (IOFF, PW_NU          (:,:,1))
CALL REPLICATE (IOFF, PRT            (:,:,:,1))
CALL REPLICATE (IOFF, PRS            (:,:,:,1))
CALL REPLICATE (IOFF, PSVT           (:,:,:,1))
CALL REPLICATE (IOFF, PSVS           (:,:,:,1))
CALL REPLICATE (IOFF, PTHS           (:,:,1))
CALL REPLICATE (IOFF, PRC_MF         (:,:,1))
CALL REPLICATE (IOFF, PRI_MF         (:,:,1))
CALL REPLICATE (IOFF, PCF_MF         (:,:,1))
CALL REPLICATE (IOFF, PRS_OUT        (:,:,:,1))
CALL REPLICATE (IOFF, PSVS_OUT       (:,:,:,1))
CALL REPLICATE (IOFF, PTHS_OUT       (:,:,1))
CALL REPLICATE (IOFF, PSRCS_OUT      (:,:,1))
CALL REPLICATE (IOFF, PCLDFR_OUT     (:,:,1))
CALL REPLICATE (IOFF, PICEFR_OUT     (:,:,1))

CALL NPROMIZE (NPROMA, PRHODREF       , PRHODREF_B       )
CALL NPROMIZE (NPROMA, PRHODJ         , PRHODJ_B         )
CALL NPROMIZE (NPROMA, PEXNREF        , PEXNREF_B        )
CALL NPROMIZE (NPROMA, PSIGS          , PSIGS_B          )
CALL NPROMIZE (NPROMA, PMFCONV        , PMFCONV_B        )
CALL NPROMIZE (NPROMA, PPABSM         , PPABSM_B         )
CALL NPROMIZE (NPROMA, ZZZ            , ZZZ_B            )
CALL NPROMIZE (NPROMA, PDTHRAD        , PDTHRAD_B        )
CALL NPROMIZE (NPROMA, PW_NU          , PW_NU_B          )
CALL NPROMIZE (NPROMA, PRT            , PRT_B            )
CALL NPROMIZE (NPROMA, PRS            , PRS_B            )
CALL NPROMIZE (NPROMA, PSVT           , PSVT_B           )
CALL NPROMIZE (NPROMA, PSVS           , PSVS_B           )
CALL NPROMIZE (NPROMA, PTHS           , PTHS_B           )
CALL NPROMIZE (NPROMA, PRC_MF         , PRC_MF_B         )
CALL NPROMIZE (NPROMA, PRI_MF         , PRI_MF_B         )
CALL NPROMIZE (NPROMA, PCF_MF         , PCF_MF_B         )
CALL NPROMIZE (NPROMA, PRS_OUT        , PRS_OUT_B        )
CALL NPROMIZE (NPROMA, PSVS_OUT       , PSVS_OUT_B       )
CALL NPROMIZE (NPROMA, PTHS_OUT       , PTHS_OUT_B       )
CALL NPROMIZE (NPROMA, PSRCS_OUT      , PSRCS_OUT_B      )
CALL NPROMIZE (NPROMA, PCLDFR_OUT     , PCLDFR_OUT_B     )
CALL NPROMIZE (NPROMA, PICEFR_OUT     , PICEFR_OUT_B     )

END SUBROUTINE 

END  MODULE
