!     ######spl
      MODULE MODD_SUB_CH_MONITOR_n
      USE PARKIND1, ONLY : JPRB
      USE YOMHOOK , ONLY : LHOOK, DR_HOOK
!!    ########################
!!
!
USE MODD_PARAMETERS, ONLY: JPMODELMAX
IMPLICIT NONE

TYPE SUB_CH_MONITOR_t
!!
  INTEGER :: ISVECNMASK,ISVECNPT
  INTEGER, DIMENSION(:,:), POINTER :: ISVECMASK=>NULL()
  INTEGER          :: ISTCOUNT = 0  ! counter for JVALUE update
END TYPE SUB_CH_MONITOR_t

TYPE(SUB_CH_MONITOR_t), DIMENSION(JPMODELMAX), TARGET, SAVE :: SUB_CH_MONITOR_MODEL

INTEGER, POINTER :: ISVECNMASK=>NULL(),ISVECNPT=>NULL()
INTEGER, DIMENSION(:,:), POINTER :: ISVECMASK=>NULL()
INTEGER, POINTER :: ISTCOUNT=>NULL()

CONTAINS

SUBROUTINE SUB_CH_MONITOR_GOTO_MODEL(KFROM, KTO)
INTEGER, INTENT(IN) :: KFROM, KTO
!
! Save current state for allocated arrays
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('MODD_SUB_CH_MONITOR_N:SUB_CH_MONITOR_GOTO_MODEL',0,ZHOOK_HANDLE)
SUB_CH_MONITOR_MODEL(KFROM)%ISVECMASK=>ISVECMASK
!
! Current model is set to model KTO
ISVECNMASK=>SUB_CH_MONITOR_MODEL(KTO)%ISVECNMASK
ISVECNPT=>SUB_CH_MONITOR_MODEL(KTO)%ISVECNPT
ISVECMASK=>SUB_CH_MONITOR_MODEL(KTO)%ISVECMASK
ISTCOUNT=>SUB_CH_MONITOR_MODEL(KTO)%ISTCOUNT

IF (LHOOK) CALL DR_HOOK('MODD_SUB_CH_MONITOR_N:SUB_CH_MONITOR_GOTO_MODEL',1,ZHOOK_HANDLE)
END SUBROUTINE SUB_CH_MONITOR_GOTO_MODEL

END MODULE MODD_SUB_CH_MONITOR_n
