!     ######spl
MODULE MODE_MODELN_HANDLER
USE PARKIND1, ONLY : JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK
IMPLICIT NONE 

INTEGER, SAVE, PRIVATE     :: ICURRENT_MODEL = -1

CONTAINS 

FUNCTION GET_CURRENT_MODEL_INDEX()
INTEGER :: GET_CURRENT_MODEL_INDEX
!!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('MODE_MODELN_HANDLER:GET_CURRENT_MODEL_INDEX',0,ZHOOK_HANDLE)
GET_CURRENT_MODEL_INDEX = ICURRENT_MODEL
!!
IF (LHOOK) CALL DR_HOOK('MODE_MODELN_HANDLER:GET_CURRENT_MODEL_INDEX',1,ZHOOK_HANDLE)
END FUNCTION GET_CURRENT_MODEL_INDEX

SUBROUTINE GOTO_MODEL(KMI)
INTEGER, INTENT(IN) :: KMI
!!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('MODE_MODELN_HANDLER:GOTO_MODEL',0,ZHOOK_HANDLE)
IF (ICURRENT_MODEL == -1) THEN
  ICURRENT_MODEL = 1 ! Default model index
!***AROME***
!  CALL GOTO_MODEL_WRAPPER(ICURRENT_MODEL, KMI)
  ICURRENT_MODEL = KMI
ELSE
  IF (ICURRENT_MODEL /= KMI) THEN
!   Switch to model KMI, only if necessary
!    CALL GOTO_MODEL_WRAPPER(ICURRENT_MODEL, KMI)
    ICURRENT_MODEL = KMI 
  END IF
END IF
!!
IF (LHOOK) CALL DR_HOOK('MODE_MODELN_HANDLER:GOTO_MODEL',1,ZHOOK_HANDLE)
END SUBROUTINE GOTO_MODEL

END MODULE MODE_MODELN_HANDLER
