!     ######spl
     MODULE MODI_CH_AER_TRANS
!!   ########################
!!
INTERFACE
!!
SUBROUTINE CH_AER_TRANS(KDIR, PM, PSIG0, PRG0, PN0, PRHOP0, PAERO,&
                  PCONC, PCTOTG, PCTOTA, PCCTOT,PFRAC,PMI,PMASK,GSCHEME)


IMPLICIT NONE
INTEGER,                  INTENT(IN)    :: KDIR    ! KDIR = 0 gas -> aero
                                                   ! KDIR = 1 aero -> gas
REAL,   DIMENSION(:,:),   INTENT(INOUT) :: PM      ! moments
REAL,   DIMENSION(:,:),   INTENT(INOUT) :: PSIG0, PRG0, PN0, PRHOP0, PCTOTG
REAL,   DIMENSION(:,:,:), INTENT(INOUT) :: PCTOTA, PCCTOT
REAL,   DIMENSION(:,:),   INTENT(INOUT) :: PCONC
REAL,   DIMENSION(:,:),   INTENT(INOUT) :: PAERO
REAL,   DIMENSION(:,:),   INTENT(INOUT) :: PFRAC
REAL,   DIMENSION(:,:),   INTENT(INOUT) :: PMI
REAL,   DIMENSION(:,:),   INTENT(INOUT) :: PMASK
CHARACTER(LEN=10),        INTENT(IN)    :: GSCHEME

END SUBROUTINE CH_AER_TRANS
!!
END INTERFACE
!!
END MODULE MODI_CH_AER_TRANS
