!     ######spl
MODULE MODI_CH_BOUNDARIES
!########################
!
INTERFACE
!
      SUBROUTINE CH_BOUNDARIES (HLBCX,HLBCY,                 &
                                PSVBM,PUT,PVT,PSVBT          )
!
CHARACTER(LEN=4), DIMENSION(2), INTENT(IN)  :: HLBCX,HLBCY  
REAL, DIMENSION(:,:,:),       INTENT(INOUT) :: PSVBT,PSVBM
REAL, DIMENSION(:,:,:),         INTENT(IN) :: PUT,PVT
!
END SUBROUTINE CH_BOUNDARIES
!
END INTERFACE
!
END MODULE MODI_CH_BOUNDARIES
