!     ######spl
MODULE MODI_CH_AER_INTERMIN
!!    ###########################
!!
INTERFACE
!!
  SUBROUTINE CH_AER_INTERMIN(v, w, x, y, z,zout,KVECNPT)
  USE MODD_CH_AEROSOL
  IMPLICIT NONE
  INTEGER :: KVECNPT
  REAL, DIMENSION(:) :: v
  DOUBLE PRECISION, DIMENSION(:) :: w, x, y, z
  DOUBLE PRECISION, DIMENSION(:,:) :: zout
  END SUBROUTINE CH_AER_INTERMIN
!!
END INTERFACE
!!
END MODULE MODI_CH_AER_INTERMIN
