!     ######spl
      MODULE MODI_CH_NONZEROTERMS
!!    ###########################
INTERFACE
SUBROUTINE CH_NONZEROTERMS(KINDEX, KINDEXDIM)
IMPLICIT NONE
INTEGER, INTENT(IN)                          :: KINDEXDIM
INTEGER, INTENT(OUT), DIMENSION(2,KINDEXDIM) :: KINDEX
END SUBROUTINE CH_NONZEROTERMS
END INTERFACE
END MODULE MODI_CH_NONZEROTERMS
