!     ######spl
      MODULE MODI_CH_WRITE_CHEM
!!    ######################### 
!!
!
INTERFACE
SUBROUTINE CH_WRITE_CHEM(PCONC, PAERO, PRHODREF, HFILE)
IMPLICIT NONE
!REAL, DIMENSION(NEQ), INTENT(IN) :: PCONC ! PCONC: concentration vector 
REAL, DIMENSION(:), INTENT(IN) :: PCONC ! PCONC: concentration vector 
REAL, DIMENSION(:), INTENT(IN) :: PAERO ! PCONC: concentration vector 
REAL, DIMENSION(:), INTENT(IN) :: PRHODREF ! air density
CHARACTER(LEN=*), INTENT(IN)     :: HFILE ! HFILE: name of the file for write
END SUBROUTINE CH_WRITE_CHEM
END INTERFACE
END MODULE MODI_CH_WRITE_CHEM
