!     ######spl
      MODULE MODI_CH_INIT_JVALUES
!     ############################
!
INTERFACE
!
      SUBROUTINE CH_INIT_JVALUES(KDAY, KMONTH, KYEAR, KLUOUT)
!
INTEGER, INTENT(IN)    :: KLUOUT
INTEGER, INTENT(IN)    :: KYEAR       ! Current Year
INTEGER, INTENT(IN)    :: KMONTH      ! Current Month
INTEGER, INTENT(IN)    :: KDAY        ! Current Day

!
!
END SUBROUTINE CH_INIT_JVALUES
!
END INTERFACE
!
END MODULE MODI_CH_INIT_JVALUES
