!     ######spl
      MODULE MODI_CH_SPARSE
!!    #####################
INTERFACE
SUBROUTINE CH_SPARSE(KSPARSE, KSPARSEDIM)
IMPLICIT NONE
INTEGER, INTENT(INOUT)                        :: KSPARSEDIM
INTEGER, INTENT(OUT), DIMENSION(2,KSPARSEDIM) :: KSPARSE
END SUBROUTINE CH_SPARSE
END INTERFACE
END MODULE MODI_CH_SPARSE
