!     ######spl
       MODULE MODI_TROE
 !     ################
 INTERFACE
 FUNCTION TROE(PCOEF,PKO, PNEXP, PKINF, PMEXP, PM, PT, KVECNPT)
 IMPLICIT NONE
 INTEGER,                  INTENT(IN) :: KVECNPT ! no. of points in vector mask
 REAL, DIMENSION(KVECNPT)             :: TROE 
 REAL,                     INTENT(IN) :: PCOEF,PKO, PNEXP, PKINF, PMEXP
 REAL, DIMENSION(KVECNPT), INTENT(IN) :: PM, PT
 END FUNCTION TROE
 END INTERFACE
 END MODULE MODI_TROE
