!     ######spl
     MODULE MODI_CH_INI_ORILAM
!!   ###########################
!!
INTERFACE
     SUBROUTINE CH_INI_ORILAM(PM, PSIG0, PRG0, PN0,PCTOTG, PCTOTA, PCCTOT, &
                              PSEDA, POM, PRHOP0, PAERO,PCHEM,PRV, PDENAIR,&
                              PPRESSURE, PTEMP, PRC, PFRAC, PMI, GSCHEME)
IMPLICIT NONE
REAL, DIMENSION(:,:),   INTENT(INOUT) :: PM, POM
REAL, DIMENSION(:,:),   INTENT(INOUT) :: PSEDA
REAL, DIMENSION(:,:),   INTENT(INOUT) :: PSIG0, PRG0, PN0
REAL, DIMENSION(:,:),   INTENT(INOUT) :: PCTOTG
REAL, DIMENSION(:,:,:), INTENT(INOUT) :: PCTOTA, PCCTOT
REAL, DIMENSION(:,:),   INTENT(INOUT) :: PRHOP0
REAL, DIMENSION(:,:),   INTENT(INOUT) :: PCHEM, PAERO
REAL, DIMENSION(:,:),   INTENT(INOUT) :: PFRAC
REAL, DIMENSION(:,:),   INTENT(INOUT) :: PMI
REAL, DIMENSION(:),     INTENT(IN)    :: PRV, PDENAIR, PPRESSURE, PTEMP, PRC
CHARACTER(LEN=10),      INTENT(IN)    :: GSCHEME



END SUBROUTINE CH_INI_ORILAM
END INTERFACE
!!
END MODULE MODI_CH_INI_ORILAM
