!     ######spl
      MODULE MODI_DUSTLFI_n
!     ########################
!
INTERFACE
!
SUBROUTINE DUSTLFI_n(PSV, PRHODREF)
IMPLICIT NONE
REAL,       DIMENSION(:,:,:,:),  INTENT(INOUT) :: PSV
REAL,       DIMENSION(:,:,:),  INTENT(IN) :: PRHODREF
END SUBROUTINE DUSTLFI_n
!
END INTERFACE
!
END MODULE MODI_DUSTLFI_n
