!     ######spl
     MODULE MODI_CH_AER_EQM_INIT0d
!!   ########################
!!
INTERFACE
!!
SUBROUTINE CH_AER_EQM_INIT0d(PMI, PAERO, PM3D, PRHOP3D, PSIG3D, PRG3D, &
                             PN3D, PCTOTA)
IMPLICIT NONE
REAL,       DIMENSION(:,:),  INTENT(INOUT)   :: PAERO, PMI
REAL,       DIMENSION(:,:),  INTENT(INOUT)   :: PM3D, PRHOP3D, PSIG3D, PRG3D, PN3D
REAL,       DIMENSION(:,:,:),INTENT(INOUT)   :: PCTOTA
END SUBROUTINE CH_AER_EQM_INIT0d
!!
END INTERFACE
!!
END MODULE MODI_CH_AER_EQM_INIT0d
