!     ######spl
MODULE MODI_CH_AER_THERMO
!!    ################### 
!!
INTERFACE
!!
SUBROUTINE CH_AER_THERMO(PAER,PRH, PDENAIR, PPRESSURE, PTEMP, PRC)
!
!
IMPLICIT NONE
!
REAL, DIMENSION(:,:), INTENT(INOUT) :: PAER
REAL, DIMENSION(:),   INTENT(IN)    :: PRH, PDENAIR, PPRESSURE, PTEMP, PRC
!
END SUBROUTINE CH_AER_THERMO
!!
END INTERFACE
!!
END MODULE MODI_CH_AER_THERMO
