!     ######spl
       MODULE MODI_CH_JVALUES_CLOUDS
!      #############################
        INTERFACE
         SUBROUTINE CH_JVALUES_CLOUDS(PZENITH, KPJVMAX, KJVLEVEL, PAZ, PLWC, PFCLD)
          IMPLICIT NONE
          INTEGER, INTENT(IN)                   :: KPJVMAX, KJVLEVEL
          REAL, DIMENSION(:,:),     INTENT(IN)  :: PZENITH
          REAL, DIMENSION(:,:,:),   INTENT(IN)  :: PLWC, PAZ
          REAL, DIMENSION(:,:,:,:), INTENT(OUT) :: PFCLD
         END SUBROUTINE CH_JVALUES_CLOUDS
        END INTERFACE
       END MODULE MODI_CH_JVALUES_CLOUDS
