!     ######spl
     MODULE MODI_CH_AER_EQM_CORMASS
!!   ########################
!!
INTERFACE
!!
SUBROUTINE CH_AER_EQM_CORMASS(PSVT)
IMPLICIT NONE
REAL,       DIMENSION(:,:,:,:),  INTENT(INOUT)   :: PSVT
END SUBROUTINE CH_AER_EQM_CORMASS
!!
END INTERFACE
!!
END MODULE MODI_CH_AER_EQM_CORMASS
