!     ######spl
      MODULE MODI_CH_OUTPUT
!!    ##################### 
!
INTERFACE
SUBROUTINE CH_OUTPUT(PCONC, PAERO, PMI, TPM, KMI, KVECNPT)
USE MODD_CH_M9,              ONLY: METEOTRANSTYPE   
IMPLICIT NONE
INTEGER, INTENT(IN)              :: KVECNPT
!REAL, DIMENSION(KVECNPT,NEQ), INTENT(IN) :: PCONC ! the chem species
REAL, DIMENSION(:,:), INTENT(IN) :: PCONC ! the chem species
REAL, DIMENSION(:,:), INTENT(IN) :: PAERO ! the chem species
REAL, DIMENSION(:,:), INTENT(IN) :: PMI   ! the molecular mass
TYPE(METEOTRANSTYPE), DIMENSION(KVECNPT), INTENT(IN) :: TPM   ! the meteo variables
INTEGER, INTENT(IN)              :: KMI
!
END SUBROUTINE CH_OUTPUT
END INTERFACE
END MODULE MODI_CH_OUTPUT
