!     ######spl
       MODULE MODI_TROE_EQUIL
 !     ######################
 INTERFACE
 FUNCTION TROE_EQUIL(PKO, PNEXP, PKINF, PMEXP, PAFACT, PB, PM, PT, KVECNPT)
 IMPLICIT NONE
 INTEGER,                  INTENT(IN) :: KVECNPT ! no. of points in vector mask
 REAL,DIMENSION(KVECNPT)              :: TROE_EQUIL 
 REAL,                     INTENT(IN) :: PKO, PNEXP, PKINF, PMEXP, PAFACT, PB
 REAL, DIMENSION(KVECNPT), INTENT(IN) :: PM, PT
 END FUNCTION TROE_EQUIL
 END INTERFACE
 END MODULE MODI_TROE_EQUIL
