!     ######spl
      MODULE MODI_CH_SOLVER_n
!!    #####################
!!
!
INTERFACE
SUBROUTINE CH_SOLVER_n(PTSIMUL, PDTACT, PCONC, PNEWCONC, KEQ, KVECNPT, KMI)
IMPLICIT NONE
REAL,    INTENT(IN) :: PTSIMUL  ! time of simulation
REAL,    INTENT(IN) :: PDTACT   ! actual time-step
INTEGER, INTENT(IN) :: KEQ      ! dimension of the problem to solve
INTEGER, INTENT(IN) :: KVECNPT
INTEGER, INTENT(IN) :: KMI      ! model number
REAL, INTENT(IN),  DIMENSION(KVECNPT,KEQ) :: PCONC    ! concentration vector at PTSIMUL
REAL, INTENT(OUT), DIMENSION(KVECNPT,KEQ) :: PNEWCONC ! solution at PTSIMUL + PDTACT
END SUBROUTINE CH_SOLVER_n
END INTERFACE
!!
END MODULE MODI_CH_SOLVER_n
