!     ######spl
      MODULE MODI_CH_INIT_SCHEME
!     ############################
!
INTERFACE
!
      SUBROUTINE CH_INIT_SCHEME(KLUOUT)
!
INTEGER, INTENT(IN) :: KLUOUT
!
!
END SUBROUTINE CH_INIT_SCHEME
!
END INTERFACE
!
END MODULE MODI_CH_INIT_SCHEME
