!     ######spl
     MODULE MODI_CH_AER_GROWTH
!!   #########################
!!
INTERFACE
!!
SUBROUTINE CH_AER_GROWTH(PM,PSIG0, PRG0, PDMCOND,PDENAIR,PGASMW,PPGAS,PTGAS,PRH, POM,&
                           PSO4RAT, PDT)
IMPLICIT NONE
REAL, DIMENSION(:,:), INTENT(INOUT) :: PM
REAL, DIMENSION(:,:), INTENT(INOUT) :: PDMCOND, POM
REAL, DIMENSION(:),   INTENT(IN)    :: PDENAIR,PPGAS,PTGAS
REAL, DIMENSION(:),   INTENT(INOUT) :: PRH, PSO4RAT
REAL, DIMENSION(:,:), INTENT(INOUT) :: PSIG0, PRG0
REAL, INTENT(INOUT) :: PGASMW
REAL, INTENT(IN)    :: PDT
END SUBROUTINE CH_AER_GROWTH
!!
END INTERFACE
!!
END MODULE MODI_CH_AER_GROWTH
