!     ######spl
     MODULE MODI_CH_AER_EQSAM
!!   ########################
!!
INTERFACE
!!
SUBROUTINE CH_AER_EQSAM(PAER,PRH, PPRESSURE, PTEMP)
IMPLICIT NONE
REAL, DIMENSION(:,:), INTENT(INOUT) :: PAER
REAL, DIMENSION(:),   INTENT(IN)    :: PRH, PPRESSURE, PTEMP
END SUBROUTINE CH_AER_EQSAM
!!
END INTERFACE
!!
END MODULE MODI_CH_AER_EQSAM
