!     ######spl
     MODULE MODI_CH_AER_ORGANIC
!!   #######################
!!
INTERFACE
!!
SUBROUTINE CH_AER_ORGANIC(PCTOTG, PCTOTA, PRV, PDENAIR, PPRESSURE, PTEMP, PRC, POM,&
                          PCCTOT,PSIG0, PRG0, PDT, PSOLORG)
IMPLICIT NONE
REAL, DIMENSION(:,:),   INTENT(INOUT) :: PCTOTG, POM
REAL, DIMENSION(:,:,:), INTENT(INOUT) :: PCTOTA, PCCTOT
REAL, DIMENSION(:),     INTENT(IN)    :: PRV, PDENAIR, PPRESSURE, PTEMP, PRC
REAL, DIMENSION(:,:),   INTENT(IN)    :: PSIG0, PRG0
REAL,                   INTENT(IN)    :: PDT
REAL, DIMENSION(:,:),   INTENT(INOUT) :: PSOLORG




END SUBROUTINE CH_AER_ORGANIC
!!
END INTERFACE
!!
END MODULE MODI_CH_AER_ORGANIC
