!     ######spl
     MODULE MODI_DUST_VELGRAV
!!   ##############################
!!
INTERFACE
!!
SUBROUTINE DUST_VELGRAV(PSIG, PRG, PTHT, PABST,PRHODREF, PRHOP, PMU, PVGK,PDPK, PVGG)
IMPLICIT NONE
REAL,                     INTENT(IN) :: PRHOP
REAL, DIMENSION(:,:,:,:), INTENT(IN) :: PSIG, PRG
REAL, DIMENSION(:,:,:),   INTENT(IN) :: PTHT, PABST, PRHODREF
REAL, DIMENSION(:,:,:,:), INTENT(OUT) :: PVGK,PDPK
REAL, DIMENSION(:,:,:),   INTENT(OUT) :: PMU
REAL, DIMENSION(:,:,:,:), INTENT(OUT) :: PVGG
END SUBROUTINE DUST_VELGRAV
!!
END INTERFACE
!!
END MODULE MODI_DUST_VELGRAV
