!     ######spl
     MODULE MODI_DUST_FILTER
!!   ##############################
!!
INTERFACE
!
SUBROUTINE DUST_FILTER(PSV, PRHODREF)

IMPLICIT NONE

REAL,  DIMENSION(:,:,:,:),  INTENT(INOUT) :: PSV
REAL,  DIMENSION(:,:,:),    INTENT(IN)    :: PRHODREF

END SUBROUTINE DUST_FILTER
!!
END INTERFACE
!!
END MODULE MODI_DUST_FILTER
