!     ######spl
     MODULE MODI_CH_AER_COAG
!!   ########################
!!
INTERFACE
!!
SUBROUTINE CH_AER_COAG(PM, PSIG0, PRG0, PN0,PDMINTRA,PDMINTER,PTGAS,PMU,&
                         PLAMBDA,PRHOP0)
IMPLICIT NONE
REAL, DIMENSION(:,:), INTENT(INOUT) :: PM,PRHOP0 
REAL, DIMENSION(:),   INTENT(INOUT) :: PLAMBDA, PMU
REAL, DIMENSION(:,:), INTENT(INOUT) :: PDMINTRA
REAL, DIMENSION(:,:), INTENT(INOUT) :: PDMINTER
REAL, DIMENSION(:),INTENT(IN) :: PTGAS
REAL,   DIMENSION(:,:), INTENT(IN) :: PSIG0, PRG0, PN0
END SUBROUTINE CH_AER_COAG
!!
END INTERFACE
!!
END MODULE MODI_CH_AER_COAG
