!     ######spl
      MODULE MODI_SALTLFI_n
!     ########################
!
INTERFACE
!
SUBROUTINE SALTLFI_n(PSV, PRHODREF)
IMPLICIT NONE
REAL,       DIMENSION(:,:,:,:),  INTENT(INOUT) :: PSV
REAL,       DIMENSION(:,:,:),  INTENT(IN) :: PRHODREF
END SUBROUTINE SALTLFI_n
!
END INTERFACE
!
END MODULE MODI_SALTLFI_n
