!     ######spl
      MODULE MODI_CH_READ_METEO
!!    ######################### 
!
INTERFACE
SUBROUTINE CH_READ_METEO(TPM)
USE MODD_CH_M9,      ONLY: METEOTRANSTYPE
IMPLICIT NONE
TYPE(METEOTRANSTYPE), INTENT(INOUT) :: TPM
END SUBROUTINE CH_READ_METEO
END INTERFACE
END MODULE MODI_CH_READ_METEO
