!     ######spl
      MODULE MODI_CH_LINSSA
!!    ##################### 
!!
!
INTERFACE
!!
SUBROUTINE CH_LINSSA(PTSIMUL, PDTACT, PCONC, PNEWCONC, KEQ, KVECNPT, KMI, &
                     KSSA, KSSAINDEX)
IMPLICIT NONE
REAL,    INTENT(IN) :: PTSIMUL  ! time of simulation
REAL,    INTENT(IN) :: PDTACT   ! actual time-step
INTEGER, INTENT(IN) :: KEQ      ! dimension of the problem to solve
INTEGER, INTENT(IN) :: KVECNPT
REAL, INTENT(IN),  DIMENSION(KVECNPT,KEQ) :: PCONC    ! concentration vector at PTSIMUL
REAL, INTENT(OUT), DIMENSION(KVECNPT,KEQ) :: PNEWCONC ! solution at PTSIMUL + PDTACT
INTEGER, INTENT(IN) :: KMI      ! model number
INTEGER, INTENT(IN) :: KSSA
INTEGER, DIMENSION(1000)  ::  KSSAINDEX
!
END SUBROUTINE CH_LINSSA
!!
END INTERFACE
!!
END MODULE MODI_CH_LINSSA
