!     ######spl
      MODULE MODI_CH_INIT_MODEL0D
!!    ###########################
!!
INTERFACE
SUBROUTINE CH_INIT_MODEL0D(HNAMELISTFILE)
IMPLICIT NONE
CHARACTER*(*), INTENT(IN) :: HNAMELISTFILE
END SUBROUTINE CH_INIT_MODEL0D
END INTERFACE
END MODULE MODI_CH_INIT_MODEL0D
