!     ######spl
      MODULE MODI_CH_UPDATE_METEO
!!    ########################### 
!
INTERFACE
SUBROUTINE CH_UPDATE_METEO(TPM,PTIME)
USE MODD_CH_M9, ONLY: METEOTRANSTYPE
IMPLICIT NONE
TYPE(METEOTRANSTYPE), INTENT(INOUT) :: TPM
REAL,                 INTENT(IN)    :: PTIME ! current simulation time
END SUBROUTINE CH_UPDATE_METEO
END INTERFACE
END MODULE MODI_CH_UPDATE_METEO
