!     ######spl
     MODULE MODI_CH_AER_MINERAL
!!   #######################
!!
INTERFACE
!
SUBROUTINE CH_AER_MINERAL(PCTOTG, PCTOTA, PRV, PDENAIR, PPRESSURE, PTEMP, PRC, POM,&
                           PCCTOT,PSIG0, PRG0, PDT)
IMPLICIT NONE
REAL, DIMENSION(:,:),   INTENT(INOUT) :: PCTOTG, POM
REAL, DIMENSION(:,:,:), INTENT(INOUT) :: PCTOTA, PCCTOT 
REAL, DIMENSION(:),     INTENT(IN)    :: PRV, PDENAIR, PPRESSURE, PTEMP, PRC
REAL, DIMENSION(:,:),   INTENT(INOUT) :: PSIG0, PRG0
REAL,                   INTENT(IN)    :: PDT
!
END SUBROUTINE CH_AER_MINERAL
!
END INTERFACE
!
END MODULE MODI_CH_AER_MINERAL
