!     ######spl
     MODULE MODI_INIT_DUST
!!   ##############################
!!
INTERFACE
!
SUBROUTINE INIT_DUST(PSV, PRHODREF)

IMPLICIT NONE

REAL,  DIMENSION(:,:,:,:),  INTENT(INOUT) :: PSV
REAL,  DIMENSION(:,:,:),    INTENT(IN)    :: PRHODREF


END SUBROUTINE INIT_DUST
!!
END INTERFACE
!!
END MODULE MODI_INIT_DUST
