!     ######spl
     MODULE MODI_CH_NNARES
!!   #####################
!!
INTERFACE
!!
SUBROUTINE CH_NNARES (PAER,PRH, PDENAIR, PPRESSURE, PTEMP, PRC)
USE MODD_CH_M9
IMPLICIT NONE
REAL, DIMENSION(:,:), INTENT(INOUT) :: PAER
REAL, DIMENSION(:),   INTENT(IN)    :: PRH, PDENAIR, PPRESSURE, PTEMP, PRC

END SUBROUTINE CH_NNARES
!!
END INTERFACE
!!
END MODULE MODI_CH_NNARES
