!     ######spl
      MODULE MODI_CH_INIT_OUTPUT
!!    ##########################
!!
!
INTERFACE
SUBROUTINE CH_INIT_OUTPUT(TPM)
USE MODD_CH_M9, ONLY: METEOTRANSTYPE
IMPLICIT NONE
TYPE(METEOTRANSTYPE), INTENT(IN) :: TPM
END SUBROUTINE CH_INIT_OUTPUT
END INTERFACE
END MODULE MODI_CH_INIT_OUTPUT
