!     ######spl
      MODULE MODI_CH_QSSA
!!    ################### 
!!
!
INTERFACE
!!
SUBROUTINE CH_QSSA(PTSIMUL, PDTACT, PCONC, PNEWCONC, KEQ, KVECNPT, KMI, &
                   PSLOW, PFAST, KQSSAITER)
IMPLICIT NONE
REAL,    INTENT(IN) :: PTSIMUL  ! time of simulation
REAL,    INTENT(IN) :: PDTACT   ! actual time-step
INTEGER, INTENT(IN) :: KEQ      ! dimension of the problem to solve
INTEGER, INTENT(IN) :: KVECNPT
REAL, INTENT(IN),  DIMENSION(KVECNPT,KEQ) :: PCONC    ! concentration vector at PTSIMUL
REAL, INTENT(OUT), DIMENSION(KVECNPT,KEQ) :: PNEWCONC ! solution at PTSIMUL + PDTACT
INTEGER,INTENT(IN)  :: KMI      ! model number
REAL,    INTENT(IN) :: PSLOW, PFAST
INTEGER, INTENT(IN) :: KQSSAITER  
END SUBROUTINE CH_QSSA
!!
END INTERFACE
!!
END MODULE MODI_CH_QSSA
