!     ######spl
     MODULE MODI_CH_AER_EQM_INIT_n
!!   ########################
!!
INTERFACE
!!
SUBROUTINE CH_AER_EQM_INIT_n(PCHEM, PAERO, PM3D, PRHOP3D, PSIG3D, PRG3D, &
                             PN3D, PRHODREF, PCTOTA)
IMPLICIT NONE
REAL,       DIMENSION(:,:,:,:),  INTENT(INOUT)   :: PCHEM, PAERO
REAL,       DIMENSION(:,:,:,:),  INTENT(INOUT)   :: PM3D, PRHOP3D, PSIG3D, PRG3D, PN3D
REAL,       DIMENSION(:,:,:,:,:),INTENT(INOUT)   :: PCTOTA
REAL,       DIMENSION(:,:,:),    INTENT(IN)      :: PRHODREF
END SUBROUTINE CH_AER_EQM_INIT_n
!!
END INTERFACE
!!
END MODULE MODI_CH_AER_EQM_INIT_n
