!     ######spl
     MODULE MODI_CH_AER_SEDIM_n
!!   ##############################
!!
INTERFACE
!
SUBROUTINE CH_AER_SEDIM_n(PDTMONITOR,PSVT,PTHT,&
                 PRHODREF,PPABST, PVDEPAERO, PZZ, PSEDA)

IMPLICIT NONE

REAL,    INTENT(IN) :: PDTMONITOR
REAL,  DIMENSION(:,:,:,:),  INTENT(IN)    :: PSVT
REAL,  DIMENSION(:,:,:),    INTENT(IN)    :: PTHT,PRHODREF, PZZ
REAL,  DIMENSION(:,:,:),    INTENT(IN)    :: PPABST
REAL,  DIMENSION(:,:,:),    INTENT(INOUT) :: PVDEPAERO
REAL,  DIMENSION(:,:,:,:),  INTENT(INOUT) :: PSEDA


END SUBROUTINE CH_AER_SEDIM_n
!!
END INTERFACE
!!
END MODULE MODI_CH_AER_SEDIM_n
