!     ######spl
     MODULE MODI_CH_AER_REALLFI_n
!!   ########################
!!
INTERFACE
!!
SUBROUTINE CH_AER_REALLFI_n(PSV, PCO, PRHODREF)
IMPLICIT NONE
REAL,       DIMENSION(:,:,:,:),  INTENT(INOUT) :: PSV
REAL,       DIMENSION(:,:,:),    INTENT(INOUT) :: PCO
REAL,       DIMENSION(:,:,:),  INTENT(IN) :: PRHODREF
END SUBROUTINE CH_AER_REALLFI_n
!!
END INTERFACE
!!
END MODULE MODI_CH_AER_REALLFI_n
