!     ######spl
      MODULE MODI_CH_PRODLOSS
!!    #######################
INTERFACE
SUBROUTINE CH_PRODLOSS(PTIME,PCONC,PPROD,PLOSS,KMI,KVECNPT,KEQ)
IMPLICIT NONE
REAL,    INTENT(IN)                          :: PTIME
INTEGER, INTENT(IN)                          :: KVECNPT
INTEGER, INTENT(IN)                          :: KEQ
REAL,    INTENT(IN),  DIMENSION(KVECNPT,KEQ) :: PCONC
REAL,    INTENT(OUT), DIMENSION(KVECNPT,KEQ) :: PPROD, PLOSS
INTEGER, INTENT(IN)                          :: KMI
END SUBROUTINE CH_PRODLOSS
END INTERFACE
END MODULE MODI_CH_PRODLOSS
