!     ######spl
      MODULE MODI_CH_DIAGNOSTICS
!!    ########################## 
!
INTERFACE
SUBROUTINE CH_DIAGNOSTICS(PCONC, KMI, KVECNPT)
IMPLICIT NONE
INTEGER, INTENT(IN)                      :: KVECNPT
REAL, DIMENSION(:,:), INTENT(IN) :: PCONC ! the chem species
INTEGER, INTENT(IN)              :: KMI
END SUBROUTINE CH_DIAGNOSTICS
END INTERFACE
END MODULE MODI_CH_DIAGNOSTICS
