!     ######spl
      MODULE MODI_CH_TERMS
!!    ####################
INTERFACE
SUBROUTINE CH_TERMS(PTIME,PCONC,PTERMS,KMI,KVECNPT,KEQ,KREAC)
IMPLICIT NONE
REAL,    INTENT(IN)                               :: PTIME
INTEGER, INTENT(IN)                               :: KVECNPT
INTEGER, INTENT(IN)                               :: KEQ, KREAC
REAL,    INTENT(IN),  DIMENSION(KVECNPT,KEQ)      :: PCONC
REAL,    INTENT(OUT), DIMENSION(KVECNPT,KEQ,KREAC):: PTERMS
INTEGER, INTENT(IN)                               :: KMI
END SUBROUTINE CH_TERMS
END INTERFACE
END MODULE MODI_CH_TERMS
