!     ######spl
     MODULE MODI_CH_ARES
!!   #####################
!!
INTERFACE
!!
SUBROUTINE CH_ARES (PAER,PRH, PDENAIR, PPRESSURE, PTEMP, PRC)
IMPLICIT NONE
REAL, DIMENSION(:,:), INTENT(INOUT) :: PAER
REAL, DIMENSION(:),   INTENT(IN)    :: PRH, PDENAIR, PPRESSURE, PTEMP, PRC

END SUBROUTINE CH_ARES
!!
END INTERFACE
!!
END MODULE MODI_CH_ARES
