MODULE MODE_INIT_PHYEX
IMPLICIT NONE
CONTAINS
SUBROUTINE FILL_DIMPHYEX(KLON, KLEV, D)
USE MODD_DIMPHYEX,   ONLY: DIMPHYEX_t
USE MODD_PARAMETERS, ONLY: JPVEXT_TURB
IMPLICIT NONE
INTEGER, INTENT(IN) :: KLON
INTEGER, INTENT(IN) :: KLEV
TYPE(DIMPHYEX_t), INTENT(OUT) :: D
D%NIT  = KLON
D%NIB  = 1
D%NIE  = KLON
D%NJT  = 1
D%NJB  = 1
D%NJE  = 1
D%NIJT = D%NIT * D%NJT
D%NIJB = 1
D%NIJE = 1
D%NKL  = 1
D%NKT  = KLEV+2
D%NKA  = 1
D%NKU  = KLEV+2
D%NKB  = 1+JPVEXT_TURB
D%NKE  = D%NKT - JPVEXT_TURB
D%NKTB = 1+JPVEXT_TURB
D%NKTE = D%NKT - JPVEXT_TURB
D%NIBC = 1
D%NJBC = 1
D%NIEC = D%NIE
D%NJEC = D%NJT
END SUBROUTINE FILL_DIMPHYEX
!
SUBROUTINE INIT_PHYEX(PTSTEP, PDZMIN, PHYEX)
!
USE MODD_PHYEX,      ONLY: PHYEX_t
USE MODI_INI_PHYEX,  ONLY: INI_PHYEX
!
IMPLICIT NONE
!
REAL, INTENT(IN)              :: PTSTEP
REAL, INTENT(IN)              :: PDZMIN
TYPE(PHYEX_t), INTENT(OUT) :: PHYEX
!
CHARACTER(LEN=6) :: CPROGRAM
CHARACTER(LEN=4) :: CMICRO
CHARACTER(LEN=4) :: CSCONV
CHARACTER(LEN=4) :: CTURB
INTEGER :: K
!
!General configuration, cannot be modified by namelist
CPROGRAM='AROME '
CMICRO='ICE3'
CSCONV='EDKF'
CTURB='TKEL'
!
! Initialize PHYEX
CALL INI_PHYEX(HPROGRAM=CPROGRAM, KUNITNML=0, LDNEEDNAM=.TRUE., &
              &KLUOUT=20, KFROM=0, KTO=1, &
              &PTSTEP=PTSTEP, PDZMIN=PDZMIN, &
              &CMICRO=CMICRO, CSCONV=CSCONV, CTURB=CTURB, &
              &LDDEFAULTVAL=.TRUE., LDREADNAM=.FALSE., LDCHECK=.TRUE., &
              &KPRINT=2, LDINIT=.TRUE., &
              &PHYEX_OUT=PHYEX)
!
PHYEX%MISC%CPROGRAM=CPROGRAM
PHYEX%MISC%ZTFILE%LOPENED=.FALSE.
PHYEX%MISC%TLES%LLES=.FALSE.
PHYEX%MISC%CMICRO=CMICRO
PHYEX%MISC%CSCONV=CSCONV
PHYEX%MISC%CTURB=CTURB
!
! Budgets
DO K=1, PHYEX%MISC%NBUDGET
  PHYEX%MISC%YLBUDGET(K)%NBUDGET=K
ENDDO
PHYEX%MISC%TBUCONF%LBU_ENABLE=.FALSE.
PHYEX%MISC%TBUCONF%LBUDGET_U=.FALSE.
PHYEX%MISC%TBUCONF%LBUDGET_V=.FALSE.
PHYEX%MISC%TBUCONF%LBUDGET_W=.FALSE.
PHYEX%MISC%TBUCONF%LBUDGET_TH=.FALSE.
PHYEX%MISC%TBUCONF%LBUDGET_TKE=.FALSE.
PHYEX%MISC%TBUCONF%LBUDGET_RV=.FALSE.
PHYEX%MISC%TBUCONF%LBUDGET_RC=.FALSE.
PHYEX%MISC%TBUCONF%LBUDGET_RR=.FALSE.
PHYEX%MISC%TBUCONF%LBUDGET_RI=.FALSE.
PHYEX%MISC%TBUCONF%LBUDGET_RS=.FALSE.
PHYEX%MISC%TBUCONF%LBUDGET_RG=.FALSE.
PHYEX%MISC%TBUCONF%LBUDGET_RH=.FALSE.
PHYEX%MISC%TBUCONF%LBUDGET_SV=.FALSE.
!
END SUBROUTINE INIT_PHYEX
END MODULE MODE_INIT_PHYEX
