MODULE NAMELIST_MOD
IMPLICIT NONE
PRIVATE
PUBLIC :: POSNAME
CONTAINS
SUBROUTINE POSNAME(KULNAM, CDNAML, KSTAT, LDNOREWIND)

!To position namelist file at correct place for reading namelists
!Code adapted from different sources (ECMWF, ARPIFS, MESO-NH)
!Interface is compatible with the fiat implementation

USE MODE_MSG, ONLY: NVERB_FATAL, NVERB_WARNING, PRINT_MSG

IMPLICIT NONE

INTEGER,           INTENT(IN)    :: KULNAM     !< Namelist logical unit
CHARACTER(LEN=*),  INTENT(IN)    :: CDNAML     !< Namelist name
INTEGER,           INTENT(OUT)   :: KSTAT      !< 0 if namelist found
LOGICAL, OPTIONAL, INTENT(IN)    :: LDNOREWIND !< True if namelist has been found

INTEGER :: ILEN, ISTATUS, ISCAN, IND
CHARACTER(LEN=120) :: CLINE
CHARACTER(LEN=1)   ::  CLTEST
CHARACTER(LEN=100) :: CTEMP

IF (.NOT. PRESENT(LDNOREWIND)) THEN
  REWIND(KULNAM)
ELSEIF (.NOT. LDNOREWIND) THEN
  REWIND(KULNAM)
ENDIF
ILEN=LEN(CDNAML)
KSTAT=0
ISTATUS=0
ISCAN=0
CLINE=' '
DO WHILE(ISTATUS==0 .AND. ISCAN==0)
  READ(KULNAM,'(A)',IOSTAT=ISTATUS) CLINE
  IF(ISTATUS<=-1) THEN
    !End of file
    KSTAT=1
    CTEMP='CANNOT LOCATE '//CDNAML
    CALL PRINT_MSG(NVERB_WARNING, 'GEN', 'POSNAM_PHY', CTEMP)
  ELSEIF(ISTATUS>=1) THEN
    !Error
    CALL PRINT_MSG(NVERB_FATAL, 'GEN', 'POSNAM_PHY', 'AN ERROR HAPPENED WHILE READING THE NAMELIST')
  ELSE !ISTATUS==0
    !Normal line
    IND=INDEX(TO_UPPER(CLINE), '&'//TO_UPPER(CDNAML))
    IF(IND/=0) THEN
      CLTEST=CLINE(IND+ILEN+1:IND+ILEN+1)
      IF (.NOT. ((LGE(CLTEST,'0').AND.LLE(CLTEST,'9')) .OR. &
                &(LGE(CLTEST,'A').AND.LLE(CLTEST,'Z')))) THEN
        ISCAN=1
      ENDIF
    ENDIF
  ENDIF
ENDDO
BACKSPACE(KULNAM)

END SUBROUTINE POSNAME

PURE FUNCTION TO_UPPER(CSTRING) RESULT(CUPPER_STRING)
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CSTRING       !< Input string to be put in upper case
  CHARACTER(LEN=LEN(CSTRING))  :: CUPPER_STRING !< Resulting string
  CHARACTER(LEN=26), PARAMETER :: UPPER_CHAR = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
  CHARACTER(LEN=26), PARAMETER :: LOWER_CHAR = 'abcdefghijklmnopqrstuvwxyz'
  INTEGER :: II, IX
  CUPPER_STRING=CSTRING
  DO II=1, LEN(CUPPER_STRING)
     IX=INDEX(LOWER_CHAR, CUPPER_STRING(II:II))
     IF(IX/= 0) CUPPER_STRING(II:II)=UPPER_CHAR(IX:IX)
  END DO    
END FUNCTION TO_UPPER
END MODULE NAMELIST_MOD
