name: Build the AROME branch from commits

on:
  push:
    branches:
      - master

jobs:
  process:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Make the arome branch available
      run: git branch --track arome origin/arome || { echo "AROME branch does not exist. Stopping the job."; exit; }

    - name: Process commits
      run: |
        if git show-ref --verify --quiet refs/heads/arome; then
          # Python environment and dependencies
          python3 -m venv phyex.env
          . phyex.env/bin/activate
          pip install --prefer-binary -e ${{ github.workspace }}/tools/
          # Loop on all new commits from the oldest to the newest, restricted to the immediate family
          for commit in $(git rev-list --reverse --topo-order --ancestry-path ${{ github.event.before}}..${{ github.sha}}); do
            # Get the arome branch in a new repo
            temp_dir=$(mktemp -d)
            cd $temp_dir
            git init --initial-branch=master
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git remote add origin ${{ github.workspace }}/.git
            git fetch origin
            git checkout -b arome origin/arome
            # Merge (only for history) the new commit and erase the content
            git merge --no-commit --no-ff $commit || true
            find . -not -path './.git/*' -not -path './.git' -delete
            # Copy the new commit src directory and transform it using prep_code
            cp -r ${{ github.workspace }}/src .
            phyex-prep_code -s gmkpack_ignored_files -s turb -s micro -s aux -s conv -s ial_version.json -s CMakeLists.txt -s cmake -m arome $temp_dir -- --shumanFUNCtoCALL --removeACC --mnhExpand
            # Commit and push to the main repo
            git add .
            git commit -m "AROME version of commit $commit" -m "$cmd"
            git push origin arome
            cd ..
            rm -rf $temp_dir
          done
          # Push the new commits on the arome branch
          cd ${{ github.workspace }}
          git push -u origin arome
        fi
