!MNH_LIC Copyright 1994-2021 CNRS, Meteo-France and Universite Paul Sabatier
!MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
!MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt
!MNH_LIC for details. version 1.
!-----------------------------------------------------------------
! Modifications
!  P. Wautelet 28/01/2020: new SUBROUTINEs: Budget_store_init, Budget_store_end and Budget_source_id_find in new module mode_budget
!  P. Wautelet 17/08/2020: treat LES budgets correctly
!  P. Wautelet 05/03/2021: measure cpu_time for budgets
!-----------------------------------------------------------------

!#################
MODULE MODE_BUDGET_PHY
!#################

USE MODD_BUDGET, ONLY: TBUDGETDATA, TBUDGETDATA_ABS
USE MODD_DIMPHYEX, ONLY: DIMPHYEX_t

IMPLICIT NONE
!
TYPE, EXTENDS(TBUDGETDATA_ABS) :: TBUDGETDATA_MNH
  TYPE(TBUDGETDATA), POINTER :: TBUDGET
  CONTAINS
  PROCEDURE :: INIT_PHY => BUDGET_INIT
  PROCEDURE :: END_PHY => BUDGET_END
  PROCEDURE :: ADD_PHY => BUDGET_ADD
ENDTYPE TBUDGETDATA_MNH
!
TYPE(TBUDGETDATA_MNH), DIMENSION(:), ALLOCATABLE, SAVE, TARGET :: TBUDGETS_MNH
!
PRIVATE
PUBLIC :: TBUDGETS_MNH

CONTAINS

SUBROUTINE BUDGET_INIT(SELF, D, HSOURCE, PVARS)
  USE MODE_BUDGET, ONLY: BUDGET_STORE_INIT
  CLASS(TBUDGETDATA_MNH), INTENT(INOUT) :: SELF
  TYPE(DIMPHYEX_T),       INTENT(IN)    :: D
  CHARACTER(LEN=*),       INTENT(IN)    :: HSOURCE  ! NAME OF THE SOURCE TERM
  REAL, DIMENSION(D%NIT,D%NJT,D%NKT), INTENT(IN)    :: PVARS    ! CURRENT VALUE TO BE STORED
  !
  CALL BUDGET_STORE_INIT(SELF%TBUDGET, HSOURCE, PVARS)
  !
END SUBROUTINE BUDGET_INIT
!
SUBROUTINE BUDGET_END(SELF, D, HSOURCE, PVARS)
  USE MODE_BUDGET, ONLY: BUDGET_STORE_END
  CLASS(TBUDGETDATA_MNH), INTENT(INOUT) :: SELF
  TYPE(DIMPHYEX_T),       INTENT(IN)    :: D
  CHARACTER(LEN=*),       INTENT(IN)    :: HSOURCE  ! NAME OF THE SOURCE TERM
  REAL, DIMENSION(D%NIT,D%NJT,D%NKT), INTENT(IN)    :: PVARS    ! CURRENT VALUE TO BE STORED
  !
  CALL BUDGET_STORE_END(SELF%TBUDGET, HSOURCE, PVARS)
  !
END SUBROUTINE BUDGET_END
!
SUBROUTINE BUDGET_ADD(SELF, D, HSOURCE, PVARS)
  USE MODE_BUDGET,   ONLY: BUDGET_STORE_ADD
  CLASS(TBUDGETDATA_MNH), INTENT(INOUT) :: SELF
  TYPE(DIMPHYEX_T),       INTENT(IN)    :: D
  CHARACTER(LEN=*),       INTENT(IN)    :: HSOURCE  ! NAME OF THE SOURCE TERM
  REAL, DIMENSION(D%NIT,D%NJT,D%NKT), INTENT(IN)    :: PVARS    ! CURRENT VALUE TO BE STORED
  !
  CALL BUDGET_STORE_ADD(SELF%TBUDGET, HSOURCE, PVARS)
  !
END SUBROUTINE BUDGET_ADD
!
END MODULE MODE_BUDGET_PHY
